### ISSUE TITLE
[Bug]: MO crash with alter table drop primary key

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10355]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b0ae95cb9e7ce6310c872ce355bc679309e1e5ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
CREATE TABLE `t2` (
`a` INT DEFAULT NULL
) COMMENT='New table comment';

alter table t2 drop primary key;

CREATE TABLE `t3` (
`a` INT NOT NULL,
PRIMARY KEY (`a`)
);
alter table t3 drop primary key;
```

MO Crashed:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x150 pc=0x22cf9b2]

goroutine 363 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).EvaluateTxnRequest(_, {_, _}, {{0xc014a46320, 0x10, 0x10}, 0x0, {0x176df1c625f2228d, 0x1, 0x0, ...}, ...})
        /data/mo/202306271211/matrixone/pkg/vm/engine/tae/rpc/handle.go:505 +0xb2
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandlePreCommitWrite(_, {_, _}, {{0xc014a46320, 0x10, 0x10}, 0x0, {0x176df1c625f2228d, 0x1, 0x0, ...}, ...}, ...)
        /data/mo/202306271211/matrixone/pkg/vm/engine/tae/rpc/handle.go:692 +0x47e
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.handleWrite[...]({_, _}, _, {{0xc014a46320, 0x10, 0x10}, 0x0, {0x176df1c625f2228d, 0x1, 0x0, ...}, ...}, ...)
        /data/mo/202306271211/matrixone/pkg/txn/storage/tae/write.go:90 +0x193
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Write(_, {_, _}, {{0xc014a46320, 0x10, 0x10}, 0x0, {0x176df1c625f2228d, 0x1, 0x0, ...}, ...}, ...)
        /data/mo/202306271211/matrixone/pkg/txn/storage/tae/write.go:38 +0xcd
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Write(0xc0043de5a0, {0x2eab6d8, 0xc014a3f830}, 0xc0127f51e0, 0xc00d8bd780)
        /data/mo/202306271211/matrixone/pkg/txn/service/service_cn_handler.go:158 +0x9eb
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).doWrite(0x1?, {0x2eab6d8, 0xc014a3f830}, 0xc0127f51e0, 0xc00d8bd780)
        /data/mo/202306271211/matrixone/pkg/dnservice/store_rpc_handler.go:87 +0x96
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWithRetry(0xc00f4ec210?, {0x2eab6d8, 0xc014a3f830}, 0xc000155180?, 0xc00d8bd780, 0xc0145d5ca8)
        /data/mo/202306271211/matrixone/pkg/dnservice/store_rpc_handler.go:184 +0xba
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWrite(...)
        /data/mo/202306271211/matrixone/pkg/dnservice/store_rpc_handler.go:62
github.com/matrixorigin/matrixone/pkg/txn/rpc.executor.exec({{0xc1205c492853446a, 0x9febb63e8, 0x4470340}, {0x2eab6d8, 0xc014a3f830}, 0xc014a12e20, 0xc0127f51e0, {0x2eb9f18, 0xc00dc8fd90}, 0xc0041c1b70, ...})
        /data/mo/202306271211/matrixone/pkg/txn/rpc/server.go:275 +0x10d
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).handleTxnRequest(0xc000155130, {0x2eab6d8, 0xc0044a4b70})
        /data/mo/202306271211/matrixone/pkg/txn/rpc/server.go:250 +0x125
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /data/mo/202306271211/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /data/mo/202306271211/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

**Comment by dengn** [comment]
same crash for `mysql> alter table t2 AUTO_INCREMENT=10;`

**Comment by dengn** [comment]
This fix is not very solid. It looks like it only blocks the two examples I showed here. 

There are tons of ALTER TABLE cases that users might try. The following statements still crash MO.

ALTER TABLE t2 CHARACTER SET = utf8mb4;
ALTER TABLE t2 ROW_FORMAT = COMPRESSED;
ALTER TABLE t2 ENGINE = InnoDB;

I'm referring from this page. https://dev.mysql.com/doc/refman/8.0/en/alter-table.html 
I believe there must be a better fix for preventing this crash.
