### ISSUE TITLE
[Bug]: HAKeeper illegal state causing CN system init timeout panic

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#10422]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 218775ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN panic after restart:

```bash
{"level":"INFO","time":"2023/07/05 05:48:46.522633 +0000","name":"cn-service","caller":"logutil/action.go:52","msg":"async task exited","uuid":"39303339-3464-6532-6537-326164396438","action":"run-async-task","async-task":"cnservice/wait-system-init-task","cost":"5m0.192036462s"}
panic: wait system init timeout

goroutine 225 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).waitSystemInitCompleted(0xc001a20000, {0x2eb3478, 0xc038f5b050})
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_task.go:213 +0x551
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

The reason might be HAKeeper illegal state causing the CN cannot get taskservice.

logservice log:

```
{"level":"INFO","time":"2023/07/04 11:03:33.938654 +0000","name":"rsm","caller":"rsm/statemachine.go:281","msg":"[00000:31073] no snapshot available during launch"}
{"level":"INFO","time":"2023/07/04 11:03:34.357422 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:501","msg":"initial cluster set, HAKeeper is in BOOTSTRAPPING state"}
{"level":"INFO","time":"2023/07/04 11:03:34.357680 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:374","msg":"HAKeeper is in HAKeeperBootstrapCommandsReceived state"}
{"level":"INFO","time":"2023/07/04 11:03:34.357730 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:374","msg":"HAKeeper is in HAKeeperBootstrapCommandsReceived state"}
{"level":"INFO","time":"2023/07/04 11:03:34.357783 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:374","msg":"HAKeeper is in HAKeeperBootstrapCommandsReceived state"}
{"level":"INFO","time":"2023/07/04 11:03:34.357935 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:374","msg":"HAKeeper is in HAKeeperRunning state"}
{"level":"INFO","time":"2023/07/04 11:03:34.358010 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:442","msg":"task table user set, TaskSchedulerState in TaskSchedulerRunning state"}
{"level":"ERROR","time":"2023/07/04 11:03:35.176630 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:514","msg":"read from backend failed","remote":"default-log-discovery.freetier-02.svc:32001","backend-id":"b64db358-568f-46e8-9ca5-287a77392572","error":"illegal state"}
{"level":"ERROR","time":"2023/07/04 11:03:35.363570 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:514","msg":"read from backend failed","remote":"default-log-discovery.freetier-02.svc:32001","backend-id":"e99ed463-bbc6-402d-bcdd-7f8920cf6fbb","error":"illegal state"}
```

### Expected Behavior

CN should not panic

### Steps to Reproduce

```Markdown
1. start a distributed cluster
2. restart a logservice
```

### Additional information

CN log:  [cn-log.txt](https://github.com/matrixorigin/matrixone/files/11954538/cn-log.txt)
log of log-1: 
[log-1.txt](https://github.com/matrixorigin/matrixone/files/11954542/log-1.txt)

**Comment by aylei** [comment]
@volgariver6 PTAL

**Comment by gouhongshen** [comment]
I notice that when cn-service was created at `2023/07/05 05:43:44.664207` the HAKeeper already shut down all log-service and dn-service, so the cn-service `QueryTask` timeout may caused by the dn-service shutdown.

another problem is what the behavior should be when HAKeeper shutdown the log-store and dn-store?

when log and dn received the `shutdown` cmd, they then called `s.Close()`, and then `stopper.Stop()`.

in `stopper.Stop()`, it waits for all tasks done, however, the heartbeat also needs to wait for`s.Close()` to return and can detect the ctx has been canceled. deadlock occurred. 
```golang
for {
		select {
		case <-timer.C:
			tasks := s.runningTasks()
			continuous := time.Since(stopAt)
			s.opts.logger.Warn("tasks still running in stopper",
				zap.String("stopper", s.name),
				zap.Duration("continuous", continuous),
				zap.String("tasks", strings.Join(tasks, ",")))
			if s.opts.timeoutTaskHandler != nil {
				s.opts.timeoutTaskHandler(tasks, continuous)
			}
			timer.Reset(s.opts.stopTimeout)
		default:
			if s.GetTaskCount() == 0 {
				return
			}
		}

		// Such 5ms delay can be a problem if we need to repeatedly create different stoppers,
		// e.g. one stopper for each incoming request.
		time.Sleep(time.Millisecond * 5)
	}
```

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by aylei** [comment]
close #10888 , track in this issue

cc @volgariver6

**Comment by volgariver6** [comment]
fixed by #10658

**Comment by aylei** [comment]
Not reproduced in last week, observe for longer time

**Comment by aylei** [comment]
closing as no longer reproduced
