### ISSUE TITLE
[Bug]: golang demo 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10589]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.8.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Followed by https://github.com/matrixorigin/matrixorigin.io.cn/issues/507, I've setup a MO 0.8.0 by docker and got this issue by running a golang demo

mysql -h 175.27.194.201 -P6001 -uroot -p111

[go_crud_mo.go.txt](https://github.com/matrixorigin/matrixone/files/12014855/go_crud_mo.go.txt)

run this golang file: 
```
go run golang_crud_matrixone.go
```

And I got the same error:
```
nandeng-macbookpro:go_crud nandeng$ go run go_crud_mo.go 
Successfully Created
panic: Error 20101 (HY000): internal error: panic unsupported type DATE: 
github.com/matrixorigin/matrixone/pkg/sql/util.SetBytesToAnyVector
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/util/eval_expr_util.go:189
github.com/matrixorigin/matrixone/pkg/sql/compile.constructValueScanBatch
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:678
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:698
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:727
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:727
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:912
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1031
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1095
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:606
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:388
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:194
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/computation_wrapper.go:341
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2951
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3389
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3614
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:207
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:427
github.com/fagongzi/goetty/v2.(*server).doConnection
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:344
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

goroutine 1 [running]:
main.checkErr(...)
        /Users/nandeng/Test/go_crud/go_crud_mo.go:72
main.main()
        /Users/nandeng/Test/go_crud/go_crud_mo.go:26 +0x6e4
exit status 2
```

**Comment by daviszhen** [comment]
但是在 version a45f3093fd147a1e01a139b121e30eaa307057e4 上
直接执行 create语句是成功的。

```sql
CREATE TABLE `userinfo` (`uid` INT(10) NOT NULL AUTO_INCREMENT,`username` VARCHAR(64) NULL DEFAULT NULL,`department` VARCHAR(64) NULL DEFAULT NULL,`created` DATE NULL DEFAULT NULL, PRIMARY KEY (`uid`));
```

**Comment by dengn** [comment]
@ouyuanning what's the reason for this bug? As this is already a 0.8 release package, I may need to modify the code to avoid it.

**Comment by ouyuanning** [comment]
是之前prepare优化的时候，有个地方遗漏了对date类型的处理。
如果prepare中的?有date类型，就会有问题。不好避开，需要的话，可能要打patch到0.8

**Comment by dengn** [comment]
fixed.
