### ISSUE TITLE
[Bug]: cn crash because of "index out of range"

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#10656]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-8911e24d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"INFO","time":"2023/07/14 02:42:04.447129 +0000","caller":"frontend/util.go:530","msg":"time of Exec.Build : 1.87515143s connectionId 6511302|172.25.171.166:45388|{account fcfbcd43_db90_4079_a6cd_db64365f5ff5:admin:accountadmin -- 57200001:2:2}|goRoutineId 29445|01f4f529-21f0-11ee-8d04-f62e6021550d"}
panic: runtime error: index out of range [1] with length 1

goroutine 67069 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.newParallelScope(0xc00bcad6c0, {0xc003dbb3a0, 0x4, 0x4})
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:642 +0xec7
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).JoinRun(0xc00bcad6c0, 0xc00836ad80)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:445 +0x345
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc00bcad6c0, 0xc00836ad80, 0x1)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:213 +0x9b5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00bcad6c0, 0xc00836ad80)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:188 +0xa5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0xc02154e6c0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:122 +0x2f
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:121 +0x1f8
```

### Steps to Reproduce

```Markdown
not sure
```

### Additional information

full cn log:
[normal-cn-0.log](https://github.com/matrixorigin/matrixone/files/12045919/normal-cn-0.log)

full dn log:
[dn.log](https://github.com/matrixorigin/matrixone/files/12045991/dn.log)

**Comment by Morranto** [comment]
try to reproduce

**Comment by Morranto** [comment]
very hard to reproduce .I am trying to review the related code .

**Comment by Morranto** [comment]
very hard to reproduce .I am trying to review the related code .

**Comment by tianyahui-python** [comment]
It can be reproduced in Alibaba Cloud environment, if necessary, please contact me. @Morranto

**Comment by Morranto** [comment]
working on it

**Comment by m-schen** [comment]
占个坑
---

nightly-8911e24d 对应于 7月10的main分支。

**Comment by Morranto** [comment]
以上分析还不太特别明确，需要等待田亚辉请假回来之后帮忙复现，看看算子具体情况

**Comment by Morranto** [comment]
waiting for Alibaba Cloud environment( no-share CN set)

**Comment by Morranto** [comment]
very very hard to reproduced，may be degraded，and add some log

**Comment by Morranto** [comment]
跟 @nnsgmsone  ， @tianyahui-python  讨论过后，测试也暂时复现不出来，降级至s1，考虑加点log，然后加点处理越界的代码，以保证以后不会crash掉

**Comment by m-schen** [comment]
不好意思上面的分析错了。

-> join -> connect / dispatch
这样的一个pipeline被发送到远端执行了，

因为发送前这个 connect / dispatch会被删掉，
所以远端收到的这个pipeline，
它的instructions只有 -> join 这样一个算子。

远端收到pipeline后会尝试对其进行rewrite，调用newMergeScope将其变成
[-> join -> connector -> ] -> [merge -> send back] 的pipeline，由于图示代码
<img width="1056" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/033b7cd9-0b9e-41bf-823e-c2c40c0dc459">
的IsEnd判断（我不知道这个是什么，似乎是统计信息的一个东西），会导致无法加上connector。

因此在JoinRun时导致该instruction只有一个算子而下标越界。

对于该bug的修改，应该在remote run的接收端保证必须可以构建出如下Pipeline
[-> 原来的算子列表 -> connector -> ] -> [merge -> send back] 
最简单的修改是强制将收到的pipeline的最后一个算子设置成IsEnd, 或者这里不调用newMergeScope，而是自己写一个。

接收端部分代码位于：
https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/compile/scopeRemoteRun.go#L169

发送端代码位于：
https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/compile/scopeRemoteRun.go#L284

@Morranto 望参考。
