### ISSUE TITLE
[Bug]: logsevice cannot startup because of bad S3 config 

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#10666]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-64cda013
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
/mo-service -cfg /tmp/tmp.rCFOtIWlZN -debug-http=:6060
{"level":"INFO","time":"2023/07/14 09:06:06.348672 +0000","caller":"logutil/internal.go:37","msg":"MO logger init, level=, log file=, stackLevel=panic"}
{"level":"INFO","time":"2023/07/14 09:06:06.348835 +0000","caller":"fileservice/local_fs.go:133","msg":"fileservice: memory cache initialized","fs-name":"LOCAL","config":{"MemoryCapacity":536870912,"DiskPath":null,"DiskCapacity":8589934592,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
panic: internal error: bad s3 config: operation error S3: HeadBucket, https response error StatusCode: 403, RequestID: 64B10FFFB94B7E34373DE7EF, HostID: , api error Forbidden: Forbidden

goroutine 1 [running]:
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:99 +0x410

```

### Steps to Reproduce

```Markdown
just start a mo cluster in Aliyun cloud
```

**Comment by reusee** [comment]
aliyun sdk credentials provider is disabled in https://github.com/matrixorigin/matrixone/commit/6f38ea3d1768ccefbe049adf85b06d37e0d96b80
