### ISSUE TITLE
[Bug]: tae panic during bvt test

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10776]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):226e08ea4ab98f24a8db5eca0ac720234555a3ce
- Hardware parameters:amd
- OS type:ubuntu
- Others:
```

### Actual Behavior

```
pengzhen@pengzhen:~/Documents/matrixone$ ./mo-service -debug-http 127.0.0.1:8123 -launch etc/launch-tae-CN-tae-DN/launch.toml > log.txt 
panic: runtime error: index out of range [5] with length 5

goroutine 1448 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*memoryNode).Foreach(...)
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/tables/mnode.go:126
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseBlock).Foreach(0xc016d150e0, {0x2ebe938, 0xc005f7a9f0}, 0x5, 0x2777440?, 0xc008e6bb01?)
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/tables/base.go:113 +0x297
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*TxnLogtailRespBuilder).visitDelete(0xc01761c900, {0x2ebe938, 0xc005f7a9f0}, {0x2f07f00?, 0xc01762f280})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/logtail/txn_handle.go:208 +0x56e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).ObserveTxn(0xc01706f4a0, 0xc017636070, 0xc017636080, 0xc017636090, 0xc0176360a0, 0xc0176360b0, 0xc0176360c0, 0xc0176360d0)
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:388 +0x384
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*TxnLogtailRespBuilder).CollectLogtail(0xc01761c900, {0x2f25b80?, 0xc017138ee0?})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/logtail/txn_handle.go:86 +0x283
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*Manager).onCollectTxnLogtails(0xc007810770, {0xc0066fe300?, 0x1, 0x0?})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/logtail/mgr.go:115 +0x21c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:79 +0x1ec
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:58 +0xea



```

### Expected Behavior

no panic

### Steps to Reproduce

I am not sure that it can be reproduced again.

```Markdown
the code is on the branch https://github.com/daviszhen/matrixone/tree/0719-debug-10549 modified based on the branch 0.8.0.

1. remove mo-data
2. `./mo-service -debug-http 127.0.0.1:8123 -launch etc/launch-tae-CN-tae-DN/launch.toml > log.txt `
3. run bvt. `./run.sh  -p /home/pengzhen/Documents/matrixone/test/distributed/cases`
```

**Comment by daviszhen** [comment]
mo log

[log.txt](https://github.com/matrixorigin/matrixone/files/12101434/log.txt)

**Comment by daviszhen** [comment]
I reproduce it again.

**Comment by daviszhen** [comment]
i reproduce it again. Jesus! I can not run bvt on my pc

**Comment by daviszhen** [comment]
感觉是run bvt 时，没带参数-g

**Comment by aptend** [comment]
暂时没看

**Comment by aptend** [comment]
之前的一个 pr #10788 应该对这个panic 有修复
