### ISSUE TITLE
[Bug]: panic happened in the bvt during the pr to the 0.8.0

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10807]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c54497aa2930c650ee6ba595844a47523a816f57 on branch : https://github.com/daviszhen/matrixone/tree/0721-update-bvt-cases
- Hardware parameters:
- OS type:
- Others:ci
```

### Actual Behavior

failed ci.

https://github.com/matrixorigin/matrixone/actions/runs/5620262215/job/15228858738?pr=10802

```
2023/07/21 08:31:46.519867 +0000 INFO rpc/handle.go:778 [precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 273971-insert_with_function:273975-test1 txn: ctx[576100F8DD6E456392B8CB81884CC44E][1689928306517423381-1->9223372036854775807-4294967295][Active]: <nil>
2023/07/21 08:31:46.537075 +0000 INFO dn-service.logtail-push-service service/server.go:389 handle subscription asynchronously {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "server-id": "526ed7d4-a411-4425-bf68-5872ba603235", "table": "db_id:273971 tb_id:273975 "}
2023/07/21 08:31:46.537274 +0000 INFO dn-service.logtail-push-service service/session.go:425 send subscription response {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "server-id": "526ed7d4-a411-4425-bf68-5872ba603235", "stream-id": 1, "remote": "127.0.0.1:44302", "table": "db_id:273971 tb_id:273975 ", "To": "PhysicalTime:1689928306536408518 "}
panic: runtime error: slice bounds out of range [8193:8192]

goroutine 11486 [running]:
github.com/matrixorigin/matrixone/pkg/proxy.(*msgBuf).preRecv(0xc00fb05570)
	/home/runner/work/matrixone/matrixone/head/pkg/proxy/mysql_conn_buf.go:160 +0x29f
github.com/matrixorigin/matrixone/pkg/proxy.(*pipe).kickoff.func3()
	/home/runner/work/matrixone/matrixone/head/pkg/proxy/tunnel.go:384 +0x6d
github.com/matrixorigin/matrixone/pkg/proxy.(*pipe).kickoff(0xc00fb682a0, {0x2ebea70, 0xc00fae37c0})
	/home/runner/work/matrixone/matrixone/head/pkg/proxy/tunnel.go:421 +0x146
github.com/matrixorigin/matrixone/pkg/proxy.(*tunnel).kickoff.func1()
	/home/runner/work/matrixone/matrixone/head/pkg/proxy/tunnel.go:160 +0x31
created by github.com/matrixorigin/matrixone/pkg/proxy.(*tunnel).kickoff
	/home/runner/work/matrixone/matrixone/head/pkg/proxy/tunnel.go:159 +0x85

```

### Expected Behavior

no panic

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/pull/10802

https://github.com/matrixorigin/matrixone/actions/runs/5620262215/job/15228858738?pr=10802
```

**Comment by daviszhen** [comment]
这个pr能解决。https://github.com/matrixorigin/matrixone/pull/10486
