### ISSUE TITLE
[Bug]: cn fail to start with log: panic: wait system init timeout

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#10888]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-cf20de26
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cn crash every 5 minutes with log:

```
{"level":"ERROR","time":"2023/07/27 08:49:01.541376 +0000","name":"cn-service.etl/db_holder","caller":"db/db_holder.go:161","msg":"sqlWriter db init failed","uuid":"38326535-3662-3336-3564-656432333037","MODiscardable":true,"error":"invalid state SQL writer's DB conn not ready"}
{"level":"ERROR","time":"2023/07/27 08:49:01.551449 +0000","name":"cn-service.etl/db_holder","caller":"db/db_holder.go:161","msg":"sqlWriter db init failed","uuid":"38326535-3662-3336-3564-656432333037","MODiscardable":true,"error":"invalid state SQL writer's DB conn not ready"}
{"level":"INFO","time":"2023/07/27 08:49:01.572137 +0000","caller":"blockio/pipeline.go:427","msg":"SelectivityStats: BLK[0/0=0.00] COL[0/0=0.00] RDF[0/0=0.00,48/60=0.80]"}
{"level":"INFO","time":"2023/07/27 08:49:04.145167 +0000","name":"cn-service","caller":"logutil/action.go:52","msg":"async task exited","uuid":"38326535-3662-3336-3564-656432333037","action":"run-async-task","async-task":"cnservice/wait-system-init-task","cost":"5m0.146716664s"}
panic: wait system init timeout

goroutine 231 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).waitSystemInitCompleted(0xc000170e00, {0x2ee3678, 0xc02005dda0})
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_task.go:212 +0x551
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

### Additional information

followoing is debug logs, dn log is too large and already sent it to liubo.

[log0.log](https://github.com/matrixorigin/matrixone/files/12181629/log0.log)

[log1.log](https://github.com/matrixorigin/matrixone/files/12181627/log1.log)

[cn-4qmvx.log](https://github.com/matrixorigin/matrixone/files/12181597/cn-4qmvx.log)

[proxy-proxy-6td9f.log](https://github.com/matrixorigin/matrixone/files/12181601/proxy-proxy-6td9f.log)
[log2.log](https://github.com/matrixorigin/matrixone/files/12181618/log2.log)
[cn-dml6h.log](https://github.com/matrixorigin/matrixone/files/12181619/cn-dml6h.log)

_No response_

**Comment by aylei** [comment]
duplicated with #10422

**Comment by aylei** [comment]
[log-0.txt](https://github.com/matrixorigin/matrixone/files/12189483/log-0.txt)

@volgariver6

**Comment by aylei** [comment]
closing, tracked in #10422

**Comment by loveRhythm1990** [comment]
closed since duplicated with https://github.com/matrixorigin/matrixone/issues/10422
