### ISSUE TITLE
[Bug]: get a panic during loading 200g tpch dataset

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8c4918429261f98f40bfd4d9080b8d017e60029f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

get following panic during loading the tpch 200g dataset.
after the panic happens ,mo-service does not quit. it can also accepts the connections from client.

```
2023/08/18 22:04:09.749995 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 50280 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/pengzhen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
panic({0x29e46c0, 0xc04d5a2be8})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/pengzhen/Documents/matrixone/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0173a0a10?, 0xc01efa8090?, 0xc004eafb30?}, 0x4eafaf0?)
	/home/pengzhen/Documents/matrixone/pkg/objectio/meta.go:68 +0x150
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x2fe5a28, 0xc000056078}, {0xc0d2f9fe90, 0x2a}, 0xc004eafce8, 0x20?, 0x0?, 0xc0a10a35a0?, {0x3006830, 0xc002d29170}, ...)
	/home/pengzhen/Documents/matrixone/pkg/objectio/funcs.go:234 +0x21f
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadTombstoneMultiBlocks(0xc00d2653b0, {0x2fe5a28, 0xc000056078}, 0x10b6d6a?, 0xc0005540a0?)
	/home/pengzhen/Documents/matrixone/pkg/objectio/reader.go:323 +0xd6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func1({0xc00cb5d678?, 0xc0005540a0?})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/blockio/pipeline.go:165 +0xb7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc009d01500)
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/tasks/job.go:122 +0xbf
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/pengzhen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/home/pengzhen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65

2023/08/18 22:04:09.750007 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 50276 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/pengzhen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
panic({0x29e46c0, 0xc00cc04270})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/pengzhen/Documents/matrixone/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0fc84c270?, 0xc01efa9bf0?, 0xc1073a2b30?}, 0x73a2af0?)
	/home/pengzhen/Documents/matrixone/pkg/objectio/meta.go:68 +0x150
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x2fe5a28, 0xc000056078}, {0xc0dd9f27e0, 0x2a}, 0xc1073a2ce8, 0x20?, 0x0?, 0xc0db9a63c0?, {0x3006830, 0xc002d29170}, ...)
	/home/pengzhen/Documents/matrixone/pkg/objectio/funcs.go:234 +0x21f
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadTombstoneMultiBlocks(0xc09af8d4f0, {0x2fe5a28, 0xc000056078}, 0xc1073a2d50?, 0x4180c5?)
	/home/pengzhen/Documents/matrixone/pkg/objectio/reader.go:323 +0xd6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func1({0xc00cb5d078?, 0xc0053b9380?})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/blockio/pipeline.go:165 +0xb7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc009d00700)
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/tae/tasks/job.go:122 +0xbf
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/pengzhen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/home/pengzhen/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65

```

### Expected Behavior

no panic

### Steps to Reproduce

```Markdown
i do not know if it can be reproduced or not.
```

### Additional information

the code is on my testing branch . https://github.com/daviszhen/matrixone/tree/0817-clean-export
but my branch focus on cleaning the code of `select...into...`. it has nothing to do with the storage.

**Comment by daviszhen** [comment]
it was fixed by @LeftHandCold
