### ISSUE TITLE
[Bug]: Panic at idle time after running bvt 50 times

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#11384]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

I started up MO and ran bvt for 50 times and didn't stop it, then MO crashed after 4 hours. The panic message is:

```
panic: logic error

goroutine 859 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).AddColumnCnt(...)
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/catalog.go:911
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*DBEntry).RemoveEntry.func1()
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/database.go:482 +0x75
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*DBEntry).RemoveEntry(0xc1b524c8c0, 0xc36889aea0)
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/database.go:516 +0x550
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).GCByTS.func2(0xc36889aea0)
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/catalog.go:154 +0xb3
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*LoopProcessor).OnTable(0xc2a77bf3e0?, 0x2fd19e0?)
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/processor.go:57 +0x1f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*DBEntry).RecurLoop(0xc5f4f3d860?, {0x2fd19e0, 0xc14175f000})
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/database.go:608 +0x63
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).RecurLoop(0x2b36717?, {0x2fd19e0, 0xc14175f000})
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/catalog.go:1137 +0xbf
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).GCByTS(0xc002d2c7d0, {0xc1cf45bd28?, 0x410705?}, {0x0, 0x0, 0x0, 0x0, 0xd8, 0x57, 0x83, ...})
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/catalog/catalog.go:178 +0x1de
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open.func6({0x2fad7f8, 0x45b1940})
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/db/open.go:225 +0x93
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/gc.(*Manager).process(0x40c51e?, {0xc0001f4640, 0x2, 0x0?})
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/gc/manager.go:94 +0x2ed
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1e5
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 159
       /home/aunjbr/codebase/work/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xe5
```

**Comment by aunjgr** [comment]
@XuPeng-SH Please have a look. Thank you!

**Comment by jiangxinmeng1** [comment]
还在定位原因

**Comment by jiangxinmeng1** [comment]
还在定位原因

**Comment by jiangxinmeng1** [comment]
还在定位原因

**Comment by jiangxinmeng1** [comment]
fixed by #11486

**Comment by aunjgr** [comment]
verifying

**Comment by aunjgr** [comment]
fixed
