### ISSUE TITLE
[Bug]: CN connection hang, no RESPONSE OK packet for select version_comment

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#11416]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 47684bd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
No.	Time	Source	Src Port	Destination	Dst Port	Protocol	Length	Info	DateTime
1	0.000000	127.0.0.1	60087	127.0.0.1	6001	TCP	68	60087 → 6001 [SYN] Seq=0 Win=65535 Len=0 MSS=16344 WS=64 TSval=410169918 TSecr=0 SACK_PERM	2023-08-23 14:19:11.125862
2	0.000042	127.0.0.1	6001	127.0.0.1	60087	TCP	68	6001 → 60087 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=16344 WS=64 TSval=1304741138 TSecr=410169918 SACK_PERM	2023-08-23 14:19:11.125904
3	0.000048	127.0.0.1	60087	127.0.0.1	6001	TCP	56	60087 → 6001 [ACK] Seq=1 Ack=1 Win=408256 Len=0 TSval=410169918 TSecr=1304741138	2023-08-23 14:19:11.125910
4	0.000053	127.0.0.1	6001	127.0.0.1	60087	TCP	56	[TCP Window Update] 6001 → 60087 [ACK] Seq=1 Ack=1 Win=408256 Len=0 TSval=1304741138 TSecr=410169918	2023-08-23 14:19:11.125915
5	0.235684	127.0.0.1	6001	127.0.0.1	60087	MySQL	151	Server Greeting  proto=10 version=8.0.30-MatrixOne-v0.8.0 	2023-08-23 14:19:11.361546
6	0.235697	127.0.0.1	60087	127.0.0.1	6001	TCP	56	60087 → 6001 [ACK] Seq=1 Ack=96 Win=408192 Len=0 TSval=410170154 TSecr=1304741374	2023-08-23 14:19:11.361559
7	0.236447	127.0.0.1	60087	127.0.0.1	6001	MySQL	260	Login Request user=dump 	2023-08-23 14:19:11.362309
8	0.236455	127.0.0.1	6001	127.0.0.1	60087	TCP	56	6001 → 60087 [ACK] Seq=96 Ack=205 Win=408064 Len=0 TSval=1304741374 TSecr=410170154	2023-08-23 14:19:11.362317
9	0.254784	127.0.0.1	6001	127.0.0.1	60087	MySQL	68	Response  OK 	2023-08-23 14:19:11.380646
10	0.254797	127.0.0.1	60087	127.0.0.1	6001	TCP	56	60087 → 6001 [ACK] Seq=205 Ack=108 Win=408192 Len=0 TSval=410170173 TSecr=1304741393	2023-08-23 14:19:11.380659
11	0.254937	127.0.0.1	60087	127.0.0.1	6001	MySQL	93	Request Query	2023-08-23 14:19:11.380799
12	0.254951	127.0.0.1	6001	127.0.0.1	60087	TCP	56	6001 → 60087 [ACK] Seq=108 Ack=242 Win=408000 Len=0 TSval=1304741393 TSecr=410170173	2023-08-23 14:19:11.380813
13	0.271638	127.0.0.1	6001	127.0.0.1	60087	MySQL	61	Response TABULAR 	2023-08-23 14:19:11.397500
14	0.271646	127.0.0.1	6001	127.0.0.1	60087	MySQL	116	Response 	2023-08-23 14:19:11.397508
15	0.271648	127.0.0.1	60087	127.0.0.1	6001	TCP	56	60087 → 6001 [ACK] Seq=242 Ack=113 Win=408128 Len=0 TSval=410170190 TSecr=1304741410	2023-08-23 14:19:11.397510
16	0.271653	127.0.0.1	60087	127.0.0.1	6001	TCP	56	60087 → 6001 [ACK] Seq=242 Ack=173 Win=408128 Len=0 TSval=410170190 TSecr=1304741410	2023-08-23 14:19:11.397515
17	15.273169	127.0.0.1	6001	127.0.0.1	60087	TCP	44	[TCP Keep-Alive] 6001 → 60087 [ACK] Seq=172 Ack=242 Win=408000 Len=0	2023-08-23 14:19:26.399031
18	15.273200	127.0.0.1	60087	127.0.0.1	6001	TCP	56	[TCP Keep-Alive ACK] 60087 → 6001 [ACK] Seq=242 Ack=173 Win=408128 Len=0 TSval=410185191 TSecr=1304741410	2023-08-23 14:19:26.399062
```

mysql-client hung after receive the result of `select @@version_comment limit 1`, the response has no `RESPONSE OK` packet followed the `RESPONSE TABULAR` packet.

### Expected Behavior

CN connection should not hang

### Additional information

client tcpdump: [client.pcap.txt](https://github.com/matrixorigin/matrixone/files/12416486/client.pcap.txt)
server tcpdump: 
[server3.pcap.txt](https://github.com/matrixorigin/matrixone/files/12416527/server3.pcap.txt)

**Comment by aylei** [comment]
@daviszhen PTAL

**Comment by daviszhen** [comment]
经过验证，卡住的发生在`compile.(*Compile).runOnce`。

其实密码验证是成功的。卡在密码验证后的一个语句`select @@version_comment limit 1;`。语句没算出结果。

完整的卡住栈。
```
goroutine 75123 [semacquire, 194 minutes]:
sync.runtime_Semacquire(0xc0000d35e0?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc00f3ea5b0?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc01697af00)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:414 +0x1b4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc01697af00, 0x2fdb878?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:347 +0x154
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt(0xc01074c1e0, {0x2fdb878, 0xc01b70a870}, 0xc016730600, {0x2fddd38, 0xc06ffbd2c0}, 0xc01607e000, {0x3009dc0?, 0xc0172a6500?}, 0x0, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3186 +0x5048
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc01074c1e0, {0x2fdb878?, 0xc01766f950}, 0xc0172a6480)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3538 +0x121a
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc01074c1e0, {0x2fdb878, 0xc01766f950}, 0x2fa3470?, 0xc02ee361c8)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3690 +0x74a
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc012866180, 0xc02ee361c8)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:218 +0x3a4
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0005d8310, {0x300b400, 0xc07d9ed100}, {0x2658820?, 0xc017fdb300}, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:464 +0xc45
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc00d256000, {0x300b400, 0xc07d9ed100})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:336 +0x485
```


验证方法：(kubeconfile 找 @aylei )
1，6001 forward出来。
```
kubectl -n freetier-01 port-forward default-cn-h9glh 6001:6001
```
2，logs forward出来。
```
kubectl -n freetier-01 logs -f default-cn-h9glh 
````
3，mysql dump登录。(密码：找 @aylei )
此时会卡住。
4，第3步登录后，到第2步的ssh上拿到。登录时的log信息，如下图。并拿到goroutineid

此例子中：goroutineid = 75123。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/9b434a22-cb0c-47a5-be9e-a49e8304f25f)

5，每几分钟、几十分钟不等，取出profile goroutine信息。保存几份输出信息。

```
curl http://127.0.0.1:6060/debug/pprof/goroutine?debug=2 -o hang.log
```
6，从输出信息中，寻找goroutineid。
本人保存了几份信息，验证了75123。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/39c0310b-c38a-4bbd-ad86-99cc5f91ccf1)

发现：goroutineid 75123。卡住7min, 22min, 25min, 26min, 194min。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/6969ef44-a66d-4132-aabe-50c631ecd224)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/4e6d4d07-3943-4698-9e69-11693807d2c0)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/6999234c-f0b8-4307-9d96-c05b378d912e)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/012f6f40-b75e-4d11-9533-629925c478e2)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/b8a705e6-0dfd-4fa8-ac31-c4dacf748460)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/9b6022a3-7b52-43e5-8662-0a5d2fafd19a)

**Comment by daviszhen** [comment]
[hang-9.log.zip](https://github.com/matrixorigin/matrixone/files/12428357/hang-9.log.zip)

**Comment by m-schen** [comment]
已下载相关协程的堆栈，下周假后分析该问题。

**Comment by m-schen** [comment]
休假中

**Comment by iamlinjunhong** [comment]
休假中

**Comment by m-schen** [comment]
休假中

**Comment by m-schen** [comment]
已经修复，原先memory table的partition上锁办法在拿到锁后查询立马结束的情况下会导致这个锁丢失，从而导致所有关于这个表的查询以及logtail的消费都卡死。等pr合并后可验证。

**Comment by m-schen** [comment]
@aylei 麻烦有空的时候用最新的main验证一些该问题，谢谢。

**Comment by aylei** [comment]
> @aylei 麻烦有空的时候用最新的main验证一些该问题，谢谢。

嗯嗯

**Comment by aylei** [comment]
还是会出现 hang 的问题，但是现象不一样，判断不是同一个 root cause.

开 https://github.com/matrixorigin/matrixone/issues/11590 来追踪 cc @daviszhen @ouyuanning @m-schen

**Comment by aylei** [comment]
Verified in cloud environment
