### ISSUE TITLE
[Bug]: Run TPCC 1 warehouse failed on MO with panic error: 2023/08/24 16:28:19.424811 [ants]: worker exits from panic: interface conversion: interface {} is []types.Rowid, not []int32

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#11443]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
mo: `f874662078c3b9f7d93782d2f09f304d2d5145fc`
mo-tpcc: `d32531aafb821af259f91f0807814c069ad61896`
- Hardware parameters: cpu: 8c, mem: 16g disk: 500g
- OS type: Debian 11
- Others: Linux test0 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
mo is running on standalone mode
```

### Actual Behavior

When loading tpcc data into mo, tpcc tool gets error `ERROR: Communications link failure`
```bash
github@test0:/data/git_action/runner/_work/mo-nightly-regression/mo-nightly-regression/mo-tpcc$ ./runLoader.sh props.mo
Starting BenchmarkSQL LoadData

props.mo
driver=com.mysql.cj.jdbc.Driver
conn=jdbc:mysql://127.0.0.1:6001/tpcc?characterSetResults=utf8&continueBatchOnError=false&useServerPrepStmts=true&alwaysSendSetIsolation=false&useLocalSessionState=true&zeroDateTimeBehavior=CONVERT_TO_NULL&failoverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false&socketTimeout=60000
user=dump
password=***********
warehouses=1
loadWorkers=10
fileLocation (not defined)
csvNullValue (not defined - using default '')

Worker 000: Loading ITEM
Worker 001: Loading Warehouse      1
java.sql.BatchUpdateException: Communications link failure

The last packet successfully received from the server was 60,005 milliseconds ago.  The last packet sent successfully to the server was 60,005 milliseconds ago.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.cj.util.Util.handleNewInstance(Util.java:191)
        at com.mysql.cj.util.Util.getInstance(Util.java:166)
        at com.mysql.cj.util.Util.getInstance(Util.java:173)
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:371)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:452)
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:814)
        at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:403)
        at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 60,005 milliseconds ago.  The last packet sent successfully to the server was 60,005 milliseconds ago.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:634)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:414)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1109)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1057)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:353)
        ... 5 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 60,005 milliseconds ago.  The last packet sent successfully to the server was 60,005 milliseconds ago.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:562)
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:732)
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:671)
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:132)
        at com.mysql.cj.NativeSession.sendCommand(NativeSession.java:321)
        at com.mysql.cj.ServerPreparedQuery.sendExecutePacket(ServerPreparedQuery.java:342)
        at com.mysql.cj.ServerPreparedQuery.serverExecute(ServerPreparedQuery.java:209)
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:632)
        ... 9 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:556)
        ... 16 more
Worker 001: ERROR: Communications link failure

The last packet successfully received from the server was 60,005 milliseconds ago.  The last packet sent successfully to the server was 60,005 milliseconds ago.
```

MO panics, but it does not exit, and it can still be connected, and seems commands like `show databases` is working normally. 
```bash
github@test0:/data/mo/20230824_144709/matrixone/logs$ cat stderr-20230824_160917.log
2023/08/24 16:28:19.424811 [ants]: worker exits from panic: interface conversion: interface {} is []types.Rowid, not []int32
goroutine 32359 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
panic({0x27c78a0, 0xc06e4aad80})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...](...)
        /data/mo/20230824_144709/matrixone/pkg/container/vector/tools.go:41
github.com/matrixorigin/matrixone/pkg/container/vector.GetUnionOneFunction.func4(0x400000016?, 0xffffffff00000020?, 0xc018d361c0?)
        /data/mo/20230824_144709/matrixone/pkg/container/vector/vector.go:1520 +0x1c9
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PartitionReader).Read(0xc07cafebe0, {0x0?, 0x2131b40?}, {0xc070761e30, 0x3, 0x3}, 0xc0c38f9560?, 0x214ccf9?, {0x2fa44d0, 0xc0c2aac840})
        /data/mo/20230824_144709/matrixone/pkg/vm/engine/disttae/partition_reader.go:140 +0x12c9
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read(0xc005722210, {0x2fb68f8, 0xc06e4aa750}, {0xc070761e30, 0x3, 0x3}, 0xc0b9c4a500?, 0x3?, {0x2fa44d0, 0xc0c2aac840})
        /data/mo/20230824_144709/matrixone/pkg/vm/engine/disttae/reader.go:571 +0x10c
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read(0xc0057221f8, {0x2fb68f8, 0xc06e4aa750}, {0xc070761e30, 0x3, 0x3}, 0xc004bac630?, 0x7ff139a7e568?, {0x2fa44d0, 0xc0c2aac840})
        /data/mo/20230824_144709/matrixone/pkg/vm/engine/disttae/reader.go:571 +0x10c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc0c38f9700, {0x2fa4200, 0xc0057221f8}, 0xc0c2aac840)
        /data/mo/20230824_144709/matrixone/pkg/vm/pipeline/pipeline.go:81 +0x366
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc09731e0d0, 0xc0075e0700?)
        /data/mo/20230824_144709/matrixone/pkg/sql/compile/scope.go:80 +0x16e
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc09731e0d0, 0xc00473d900, 0x0)
        /data/mo/20230824_144709/matrixone/pkg/sql/compile/scope.go:423 +0xbf0
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc09731e0d0?, 0xc00473d900?)
        /data/mo/20230824_144709/matrixone/pkg/sql/compile/scope.go:176 +0x85
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc00473d900, 0xc09731e0d0)
        /data/mo/20230824_144709/matrixone/pkg/sql/compile/compile.go:285 +0x1be
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
        /data/mo/20230824_144709/matrixone/pkg/sql/compile/compile.go:435 +0x33
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65
```

screenshots
<img width="1700" alt="企业微信截图_a5c0f8d1-4a3d-4d3c-87c4-f4f797a22ec2" src="https://github.com/matrixorigin/matrixone/assets/46433151/abdbd859-25d4-4b9d-a7c1-63f941f04bc5">

<img width="1692" alt="企业微信截图_15b59795-3e37-4bfa-afcc-ad70b0952410" src="https://github.com/matrixorigin/matrixone/assets/46433151/f9081a15-c346-4586-97b4-403df40f00b4">

<img width="1692" alt="企业微信截图_15b59795-3e37-4bfa-afcc-ad70b0952410" src="https://github.com/matrixorigin/matrixone/assets/46433151/f6aeeca9-929a-4bf5-b623-53c7cb071d8b">

<img width="1690" alt="企业微信截图_e0e053dd-e4cf-48fe-82a0-52279d739139" src="https://github.com/matrixorigin/matrixone/assets/46433151/a35560b2-7dbf-456f-826e-b156881805ec">

### Expected Behavior

Data should be loaded into mo normally without any panics.

### Steps to Reproduce

```Markdown
1. Deploy an MO via mo_ctl_standalone tool
https://github.com/matrixorigin/mo_ctl_standalone

mo_ctl deploy f874662078c3b9f7d93782d2f09f304d2d5145fc

2. Change mo's transaction mode to pessimistic
etc/launch/cn.toml
```toml
service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18000


[cn.txn]
mode = "pessimistic"
```

cat etc/launch/dn.toml 
```toml
service-type = "DN"
data-dir = "./mo-data"

[log]
level = "info"

[dn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 19000

[dn.txn]
mode = "pessimistic"
```
3. Start mo via `mo_ctl start`
4. Check mo status via `mo_ctl status`
5. Git clone mo-tpcc tool
https://github.com/matrixorigin/mo-tpcc
6. Follow mo-tpcc tool's instruction, and do the followings:
1) Change configuration file `props.mo`, note conf: `warehouses=1`, `loadWorkers=10`, `terminals=10`
```bash
db=mo
driver=com.mysql.cj.jdbc.Driver
conn=jdbc:mysql://127.0.0.1:6001/tpcc?characterSetResults=utf8&continueBatchOnError=false&useServerPrepStmts=true&alwaysSendSetIsolation=false&useLocalSessionState=true&zeroDateTimeBehavior=CONVERT_TO_NULL&failoverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false&socketTimeout=60000
user=dump
password=111

warehouses=1
loadWorkers=10

terminals=10
//To run specified transactions per terminal- runMins must equal zero
runTxnsPerTerminal=0
//To run for specified minutes- runTxnsPerTerminal must equal zero
runMins=1
//Number of total transactions per minute
limitTxnsPerMin=0

//Set to true to run in 4.x compatible mode. Set to false to use the
//entire configured database evenly.
terminalWarehouseFixed=false

//The following five values must add up to 100
//The default percentages of 45, 43, 4, 4 & 4 match the TPC-C spec
newOrderWeight=45
paymentWeight=43
orderStatusWeight=4
deliveryWeight=4
stockLevelWeight=4

// Directory name to create for collecting detailed result data.
// Comment this out to suppress.
resultDirectory=./report/my_result_%tY-%tm-%td_%tH%tM%tS
//osCollectorScript=./misc/os_collector_linux.py
//osCollectorInterval=1
//osCollectorSSHAddr=user@dbhost
//osCollectorDevices=net_eth0 blk_sda

//only matrixone
//duaring the test, some errors are expected
expectedErrorCodes=20619

//only for profile collection
profAddr=127.0.0.1,127.0.0.2
profPort=6060
profThink=120

```
2) Create tpcc database and table structures
```bash
./runSQL.sh props.mo tableCreates
```
3) Load tpcc data
```bash
./runLoader.sh props.mo
```

### Additional information

Attaching mo logs
[mo-20230824-1650.log.tar.gz](https://github.com/matrixorigin/matrixone/files/12427495/mo-20230824-1650.log.tar.gz)

**Comment by aronchanisme** [comment]
mo is completely gone at around 17:00
[mo-20230824-1748.log.tar.gz](https://github.com/matrixorigin/matrixone/files/12428039/mo-20230824-1748.log.tar.gz)

```bash
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x41c77b]

goroutine 85056 [running]:
runtime.throw({0x2b46145?, 0xc000b13000?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0172e1e00 sp=0xc0172e1dd0 pc=0x4455bd
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:855 +0x28a fp=0xc0172e1e60 sp=0xc0172e1e00 pc=0x45c78a
runtime.(*bmap).overflow(...)
        /usr/local/go/src/runtime/map.go:209
runtime.mapiternext(0xc0172e1f20)
        /usr/local/go/src/runtime/map.go:987 +0x7b fp=0xc0172e1ed0 sp=0xc0172e1e60 pc=0x41c77b
runtime.mapiterinit(0xc030bc42a0?, 0x2797d00?, 0x445ac78?)
        /usr/local/go/src/runtime/map.go:863 +0x236 fp=0xc0172e1ef0 sp=0xc0172e1ed0 pc=0x41c6b6
github.com/matrixorigin/matrixone/pkg/perfcounter.Update({0x2fb68f8?, 0xc00609e1b0?}, 0xc0172e2018, {0xc0042792f0, 0x2, 0x1?})
        /data/mo/20230824_144709/matrixone/pkg/perfcounter/update.go:24 +0xac fp=0xc0172e1f90 sp=0xc0172e1ef0 pc=0x9a37ec
github.com/matrixorigin/matrixone/pkg/fileservice.(*FileWithChecksum[...]).readBlock(0x2fe4280, 0xc0172e2158)
        /data/mo/20230824_144709/matrixone/pkg/fileservice/file_with_checksum.go:256 +0x206 fp=0xc0172e2040 sp=0xc0172e1f90 pc=0xcddc06
github.com/matrixorigin/matrixone/pkg/fileservice.(*FileWithChecksum[...]).WriteAt(0x2fe4280, {0xc000ad8000, 0x8000, 0x8000}, 0x3b60000)
        /data/mo/20230824_144709/matrixone/pkg/fileservice/file_with_checksum.go:144 +0x245 fp=0xc0172e21a0 sp=0xc0172e2040 pc=0xcde145
github.com/matrixorigin/matrixone/pkg/fileservice.(*FileWithChecksum[...]).Write(...)
        /data/mo/20230824_144709/matrixone/pkg/fileservice/file_with_checksum.go:191
github.com/matrixorigin/matrixone/pkg/fileservice.(*FileWithChecksum[...]).Write({0xc000ad8000?, 0xc00032c500?, 0xc007c3e000?})
        /data/mo/20230824_144709/matrixone/pkg/fileservice/file_with_checksum.go:190 +0x45 fp=0xc0172e21e0 sp=0xc0172e21a0 pc=0xceaf45
io.copyBuffer({0x2f90740, 0xc00032c500}, {0x2f907c0, 0xc00609e270}, {0xc000ad8000, 0x8000, 0x8000})
        /usr/local/go/src/io/io.go:429 +0x204 fp=0xc0172e2260 sp=0xc0172e21e0 pc=0x4ec804
```

**Comment by triump2020** [comment]
No progress

**Comment by triump2020** [comment]
After I  adding detailed logs ,   haven't reproduce yet. 

![1693235839890](https://github.com/matrixorigin/matrixone/assets/63033222/c275c7e1-2399-4314-a7b3-1269c8dac330)


![1693235875793](https://github.com/matrixorigin/matrixone/assets/63033222/e438fe75-def8-4e2a-adc6-c2e9fd5e8245)

**Comment by triump2020** [comment]
启动mysql 命令行，用load  statement 导入 ，测试没有问题； 
   用 mo-tpcc/runLoader.sh 导入 ,  @aronchanisme  发现了 这个  panic 问题, 但目前 不能复现.   

   runLoader.sh  里面是用的 prepare, execute  statement  一行一行插入的数据， **数据导入不进去，runLoader.sh 一直卡住**， 这个 @aressu1985 说  之前 就一直有问题.

**Comment by triump2020** [comment]
Root cause had been located.

**Comment by triump2020** [comment]
已经解决，等待PR 被合入

**Comment by DanielZhangQD** [comment]
A similar error:
```
MySQL [mo_cloud]> insert into cx(account,start_time,end_time,cx,type) values('bf650ecc_bb44_491c_8889_a0c3b2ce5d3b','2023-09-13 05:02:36.000','2023-09-13 05:03:36.000',10000000,'external_sql');
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is []types.Datetime, not []int64:
runtime.panicdottypeE
	/usr/local/go/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/tools.go:41
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.EvalSelectedOnFixedSizeColumnFactory[...].func1
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/util.go:996
github.com/matrixorigin/mat
```

**Comment by triump2020** [comment]
> A similar error:
> 
> ```
> MySQL [mo_cloud]> insert into cx(account,start_time,end_time,cx,type) values('bf650ecc_bb44_491c_8889_a0c3b2ce5d3b','2023-09-13 05:02:36.000','2023-09-13 05:03:36.000',10000000,'external_sql');
> ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is []types.Datetime, not []int64:
> runtime.panicdottypeE
> 	/usr/local/go/src/runtime/iface.go:262
> github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
> 	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/tools.go:41
> github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.EvalSelectedOnFixedSizeColumnFactory[...].func1
> 	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/util.go:996
> github.com/matrixorigin/mat
> ```

这个panic 是另外的问题啊, 不要放这个issue 里了.

**Comment by aronchanisme** [comment]
复测来看，
1、mo没有panic的问题了
<img width="1175" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/7b647420-b949-41ce-ba34-1394f5e987b7">

2、tpcc的mo-tpcc/runLoader.sh 脚本运行还是会卡住
<img width="809" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/62f29847-0c21-417a-b508-f633b7f20658">



版本：
```bash
root@test0:/data/mo/20230928_1039/matrixone/logs# mo_ctl get_cid
2023-09-28 11:14:07.498 UTC+0800    [INFO]    Try get mo commit id
commit 3a8fe63b46921efaea47a0e90743d4d7c558a6cb
Author: brown <1173781832@qq.com>
Date:   Wed Sep 27 22:34:55 2023 +0800

    CI: exclude optimized case in merge run (#11934)
2023-09-28 11:14:07.535 UTC+0800    [INFO]    Get commit id succeeded
```

这个issue关注panic，先关闭
