### ISSUE TITLE
[AOE]: found panic printed from AOE

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1146]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type: MacOS
- Others:
```

### Actual Behavior

```
2021/11/15 15:26:06.056163 +0800 INFO shard/manager.go:312 [AOE]: Shard-74001 SafeId-259 | Closed
panic: aoe: closed

goroutine 307 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/aoedb.(*DB).DropTable(0x140001a4e00, {0x9089, 0x197, {0x0, 0x0}, {0x140000f6580, 0x10}, 0x0})
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/engine/aoe/storage/aoedb/db.go:93 +0x8f0
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).DropTable(...)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/aoe/storage.go:119
github.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).dropTablet(0x140034b0400, {0x9089, {0x140079de570, 0xc, 0x10}, {0x140079de580, 0xc, 0x10}, {0x1, 0x0, ...}, ...}, ...)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/handler_aoe.go:75 +0x164
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).execWriteRequest(0x140079ea3c0, 0x140079f4240)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply_exec.go:487 +0x304
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).doApplyRaftCMD(0x140079ea3c0)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:531 +0x3ac
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).applyEntry(0x140079ea3c0, 0x1400a69ff80)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:443 +0x354
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).applyCommittedEntries(0x140079ea3c0, {0x1400a4f1260, 0x1, 0x1})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:411 +0x51c
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).doApplyCommittedEntries(0x140079a3900, 0x9089, 0xb4, {0x1400a4f1260, 0x1, 0x1})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:162 +0x388
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).startApplyCommittedEntriesJob.func1()
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_job.go:40 +0x50
github.com/fagongzi/util/task.(*Runner).startWorkerLocked.func1({0x1028a9cb8, 0x140034b1400})
	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:255 +0x1a0
github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked.func1(0x140034d6b40, {0x140034fce80, 0xa}, 0x1400326f4e8, {0x1028a9cb8, 0x140034b1400})
	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:454 +0xa8
created by github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked
	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:444 +0x9c
```

### Steps to Reproduce

```markdown
1. keep running below sql more than 90 times
DROP TABLE IF EXISTS t2;
CREATE TABLE t2 ( auto INT, fld1 INT(6), companynr TINYINT(2), fld3 CHAR(30), fld4 CHAR(35), fld5 CHAR(35),  fld6 CHAR(4));
mysql -h127.0.0.1 -P6001 -udump -p111 -Dtest < insert_data.sql
SELECT count(*) FROM t2;
2. Restart mo-server, then no more operations
3. execute stmt "use test;" and "select * from t2;"
4. After several minutes, found below panic:

2021/11/15 15:26:06.056163 +0800 INFO shard/manager.go:312 [AOE]: Shard-74001 SafeId-259 | Closed
panic: aoe: closed

goroutine 307 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/aoedb.(*DB).DropTable(0x140001a4e00, {0x9089, 0x197, {0x0, 0x0}, {0x140000f6580, 0x10}, 0x0})
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/engine/aoe/storage/aoedb/db.go:93 +0x8f0
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).DropTable(...)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/aoe/storage.go:119
github.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).dropTablet(0x140034b0400, {0x9089, {0x140079de570, 0xc, 0x10}, {0x140079de580, 0xc, 0x10}, {0x1, 0x0, ...}, ...}, ...)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/handler_aoe.go:75 +0x164
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).execWriteRequest(0x140079ea3c0, 0x140079f4240)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply_exec.go:487 +0x304
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).doApplyRaftCMD(0x140079ea3c0)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:531 +0x3ac
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).applyEntry(0x140079ea3c0, 0x1400a69ff80)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:443 +0x354
github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).applyCommittedEntries(0x140079ea3c0, {0x1400a4f1260, 0x1, 0x1})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:411 +0x51c
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).doApplyCommittedEntries(0x140079a3900, 0x9089, 0xb4, {0x1400a4f1260, 0x1, 0x1})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:162 +0x388
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).startApplyCommittedEntriesJob.func1()
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_job.go:40 +0x50
github.com/fagongzi/util/task.(*Runner).startWorkerLocked.func1({0x1028a9cb8, 0x140034b1400})
	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:255 +0x1a0
github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked.func1(0x140034d6b40, {0x140034fce80, 0xa}, 0x1400326f4e8, {0x1028a9cb8, 0x140034b1400})
	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:454 +0xa8
created by github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked
	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:444 +0x9c
```
```


### Additional information

_No response_

**Comment by lignay** [comment]
This issue was reproduced in testing without drop table and delete data stmts.

**Comment by LeftHandCold** [comment]
Associated  #1153

**Comment by lignay** [comment]
The issue is gone after fixing #1139.
