### ISSUE TITLE
[AOE]:  Hit panic in GetSegmentIds

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1151]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type: MacOS
- Others:
```

### Actual Behavior

Found below panic during tests:
```
time="2021-11-16T14:33:38+08:00" level=error msg="get segmentInfos for tablet \x00\x00\x00\x00\x00\x00\x00\a\x00\x00\x00\x00\x00\x00\x1e\x15 failed, exec timeout"
256644 2021/11/16 14:33:38.294470 +0800 INFO frontend/mysql_cmd_executor.go:806 time of Exec.Build : 9.955961833s
256645 2021/11/16 14:33:38.294542 +0800 INFO v1/collection.go:156 Append logindex: S-7:22024:<0+0/1>
256646 +++++++++
256647 :1 γ([sum(count(*)) -> count(*)] -> π(count(*)) -> sql output
256648 +++++++++
256649 +++0x140091a4500 begin clean
256650 2021/11/16 14:33:38.295108 +0800 INFO frontend/mysql_cmd_executor.go:867 time of Exec.Run : 242.292µs
256651 2021/11/16 14:33:38.295224 +0800 INFO frontend/routine.go:111 connection id 1003 , the time of handling the request 9.957119667s
256652 2021/11/16 14:33:38.295886 +0800 INFO frontend/mysql_cmd_executor.go:935 cmd 1
256653 2021/11/16 14:33:38.313330 +0800 INFO frontend/routine.go:111 connection id 1003 , the time of handling the request 17.426833ms
256654 2021/11/16 14:33:38.295796 +0800 INFO frontend/routine_manager.go:68 will close iosession
256655 2021/11/16 14:33:38.313642 +0800 INFO v1/collection.go:156 Append logindex: S-7:22025:<0+0/1>
256656 2021/11/16 14:33:38.331559 +0800 INFO v1/collection.go:156 Append logindex: S-7:22026:<0+0/1>
256657 2021/11/16 14:33:38.350361 +0800 INFO v1/collection.go:156 Append logindex: S-7:22027:<0+0/1>
256658 2021/11/16 14:33:38.368248 +0800 INFO shard/manager.go:312 [AOE]: Shard-7 SafeId-21706 | Closed
256659 panic: aoe: closed
256660
256661 goroutine 521 [running]:
256662 github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*DB).GetSegmentIds(0x14002fc6400, {0x101ec9074, 0x1}, {0x14009191650, 0x10})
256663     /Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/engine/aoe/storage/db/db.go:346 +0x178
256664 github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/aoedb.(*DB).GetSegmentIds(0x14002fc6400, {0x7, 0x0, {0x14009191650, 0x10}})
256665     /Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/engine/aoe/storage/aoedb/db.go:75 +0x60
256666 github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).GetSegmentIds(...)
256667     /Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/aoe/storage.go:101
256668 github.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).getSegmentIds(0x14003265300, {0x7, {0x140038a6bc0, 0xc, 0x10}, {0x140038a6bd0, 0xc, 0x10}, {0x1, 0x0, ...}, ...}, ...)
256669     /Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/handler_aoe.go:138 +0x11c
256670 github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).doExecReadCmd(0x140071ea000, {0x14006304c30, 0x1400786f560, 0x560c, 0x1aa, 0x0, 0x3f})
256671     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_replica.go:484 +0x2fc
256672 github.com/matrixorigin/matrixcube/raftstore.(*readIndexQueue).doReadLEAppliedIndex(0x140005e03c0, 0x560c, 0x140071ea000)
256673     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/batch.go:77 +0xd4
256674 github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).maybeExecRead(...)
256675     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_replica.go:469
256676 github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).doPostApply(0x140071ea000, {0x7, 0x1aa, {0x560c, {0x519c, 0x1a9, {}, {0x0, 0x0, 0x0}, ...}, ...}, ...})
256677     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_event_post_apply.go:84 +0x3fc
256678 github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).doPollApply(0x140071ea000, {0x7, 0x1aa, {0x560c, {0x519c, 0x1a9, {}, {0x0, 0x0, 0x0}, ...}, ...}, ...})
256679     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_event_post_apply.go:50 +0x44
256680 github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).handleApplyResult(0x140071ea000, {0x140074b6000, 0x400, 0x400})
256681     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_event_post_apply.go:40 +0x124
256682 github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).handleEvent(0x140071ea000)
256683     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_event_loop.go:195 +0x194
256684 github.com/matrixorigin/matrixcube/raftstore.(*store).runPRTask.func1.1({0x10220a9e0, 0x1031284d8}, {0x102496fe0, 0x140071ea000})
256685     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store.go:459 +0x68
256686 sync.(*Map).Range(0x14002e062b8, 0x14007859d78)
256687     /usr/local/go/src/sync/map.go:346 +0x304
256688 github.com/matrixorigin/matrixcube/raftstore.(*store).runPRTask.func1()
256689     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store.go:457 +0x84
256690 github.com/matrixorigin/matrixcube/raftstore.(*store).runPRTask(0x14002e061e0, {0x1024f1cb8, 0x1400727e840}, 0x1, 0x4)
256691     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store.go:479 +0x148
256692 github.com/matrixorigin/matrixcube/raftstore.(*store).startRaftWorkers.func1({0x1024f1cb8, 0x1400727e840})
256693     /Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store.go:444 +0x78
256694 github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked.func1(0x1400057f080, {0x14006330ab0, 0x16}, 0x140072598f0, {0x1024f1cb8, 0x1400727e840})
256695     /Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:454 +0xa8
256696 created by github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked
256697     /Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:444 +0x9c
256698 2021/11/16 14:33:38.399521 [info] prophet: prophet logger set
256699 2021/11/16 14:33:38.400860 +0800 INFO db-server/main.go:151 Shutdown The Server With Ctrl+C | Ctrl+\.
256700 2021/11/16 14:33:38.636926 +0800 INFO logstore/rotational.go:177 New version 0
256701 2021/11/16 14:33:38.638897 +0800 INFO v1/replayer.go:304 Total 522 entries replayed
```

### Expected Behavior

No panic found

### Steps to Reproduce

```markdown
1. Create database and table
2. Insert data and select data 
3. Restart service
Repeat steps 2 and 3
```

**Comment by LeftHandCold** [comment]
Associated  #1153

**Comment by lignay** [comment]
The issue is gone after fixing #1139.
