### ISSUE TITLE
[AOE]: Hit panic in DB Append

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1153]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type: MacOS
- Others:
```

### Actual Behavior

Found below panic in testing:
```
./mo-server-20211116140734.log-767270-2021/11/16 16:07:27.671123 +0800 INFO frontend/mysql_cmd_executor.go:806 time of Exec.Build : 9.961023917s
./mo-server-20211116140734.log-767271-+++++++++
./mo-server-20211116140734.log-767272-:1 γ([sum(count(*)) -> count(*)] -> π(count(*)) -> sql output
./mo-server-20211116140734.log-767273-+++++++++
./mo-server-20211116140734.log-767274-+++0x140091e1c00 begin clean
./mo-server-20211116140734.log-767275-2021/11/16 16:07:27.671643 +0800 INFO frontend/mysql_cmd_executor.go:867 time of Exec.Run : 269.292µs
./mo-server-20211116140734.log-767276-2021/11/16 16:07:27.671719 +0800 INFO frontend/routine.go:111 connection id 1003 , the time of handling the request 9.9798425s
./mo-server-20211116140734.log-767277-2021/11/16 16:07:27.671835 +0800 INFO frontend/mysql_cmd_executor.go:935 cmd 1
./mo-server-20211116140734.log-767278-2021/11/16 16:07:27.671870 +0800 INFO frontend/routine.go:111 connection id 1003 , the time of handling the request 36.25µs
./mo-server-20211116140734.log-767279-2021/11/16 16:07:27.671954 +0800 INFO frontend/routine_manager.go:68 will close iosession
./mo-server-20211116140734.log-767280-2021/11/16 16:07:27.689130 +0800 INFO v1/collection.go:156 Append logindex: S-7:64509:<0+0/1>
./mo-server-20211116140734.log-767281-2021/11/16 16:07:27.707252 +0800 INFO v1/collection.go:156 Append logindex: S-7:64510:<0+0/1>
./mo-server-20211116140734.log-767282-2021/11/16 16:07:27.726185 +0800 INFO v1/collection.go:156 Append logindex: S-7:64511:<0+0/1>
./mo-server-20211116140734.log-767283-2021/11/16 16:07:27.744213 +0800 INFO shard/manager.go:312 [AOE]: Shard-7 SafeId-64301 | Closed
./mo-server-20211116140734.log-767284-2021/11/16 16:07:27.744934 +0800 INFO db/flusher.go:74 driver<cnt=1>{
./mo-server-20211116140734.log-767285-ShardFlusher<7>:{ 0}
./mo-server-20211116140734.log-767286-}
./mo-server-20211116140734.log:767287:panic: aoe: closed
./mo-server-20211116140734.log-767288-
./mo-server-20211116140734.log-767289-goroutine 318 [running]:
./mo-server-20211116140734.log-767290-github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*DB).Append(0x14000220000, {0x7, 0xfc00, 0x0, 0x1, {0x105f95074, 0x1}, {0x14009095290, 0x10}, 0x140091df3b0})
./mo-server-20211116140734.log-767291-	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/engine/aoe/storage/db/db.go:164 +0x8b4
./mo-server-20211116140734.log-767292-github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/aoedb.(*DB).Append(0x14000220000, {0x7, 0xfc00, 0x0, 0x1, {0x105f95074, 0x1}, {0x14009095290, 0x10}, 0x140091df3b0})
./mo-server-20211116140734.log-767293-	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/engine/aoe/storage/aoedb/db.go:132 +0x6c
./mo-server-20211116140734.log-767294-github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).Append(0x14003514b70, {0x14009095290, 0x10}, 0x140091df3b0, 0x7, 0xfc00, 0x0, 0x1)
./mo-server-20211116140734.log-767295-	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/aoe/storage.go:77 +0x16c
./mo-server-20211116140734.log-767296-github.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).append(0x14000597840, {0x7, {0x140068a8370, 0xc, 0x10}, {0x140068a8380, 0xc, 0x10}, {0x1, 0x0, ...}, ...}, ...)
./mo-server-20211116140734.log-767297-	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/vm/driver/handler_aoe.go:108 +0x2cc
./mo-server-20211116140734.log-767298-github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).execWriteRequest(0x140077925a0, 0x140077906c0)
./mo-server-20211116140734.log-767299-	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply_exec.go:487 +0x304
./mo-server-20211116140734.log-767300-github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).doApplyRaftCMD(0x140077925a0)
./mo-server-20211116140734.log-767301-	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:531 +0x3ac
./mo-server-20211116140734.log-767302-github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).applyEntry(0x140077925a0, 0x14007a384e0)
./mo-server-20211116140734.log-767303-	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:443 +0x354
./mo-server-20211116140734.log-767304-github.com/matrixorigin/matrixcube/raftstore.(*applyDelegate).applyCommittedEntries(0x140077925a0, {0x14007c20000, 0x5eb, 0x6aa})
./mo-server-20211116140734.log-767305-	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:411 +0x51c
./mo-server-20211116140734.log-767306-github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).doApplyCommittedEntries(0x140005bcf00, 0x7, 0x1f8, {0x14007c20000, 0x5eb, 0x6aa})
./mo-server-20211116140734.log-767307-	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_apply.go:162 +0x388
./mo-server-20211116140734.log-767308-github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).startApplyCommittedEntriesJob.func1()
./mo-server-20211116140734.log-767309-	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/peer_job.go:40 +0x50
./mo-server-20211116140734.log-767310-github.com/fagongzi/util/task.(*Runner).startWorkerLocked.func1({0x1065bdcb8, 0x1400351a800})
./mo-server-20211116140734.log-767311-	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:255 +0x1a0
./mo-server-20211116140734.log-767312-github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked.func1(0x140001f34a0, {0x1400351ea50, 0xa}, 0x1400000f5d8, {0x1065bdcb8, 0x1400351a800})
./mo-server-20211116140734.log-767313-	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:454 +0xa8
./mo-server-20211116140734.log-767314-created by github.com/fagongzi/util/task.(*Runner).doRunCancelableTaskLocked
./mo-server-20211116140734.log-767315-	/Users/yangli/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210923134909-bccc37b5040d/task/task.go:444 +0x9c
./mo-server-20211116140734.log-767316-2021/11/16 16:07:27.781384 [info] prophet: prophet logger set
```

### Expected Behavior

no panic found

### Steps to Reproduce
1. Create database and table
2. Insert data and select data 
3. Restart service
Repeat steps 2 and 3

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/142131721-36cf6213-b387-4dcf-885a-7c6379ed8e86.png)

**Comment by LeftHandCold** [comment]
The test script is executed in multiple threads. When Append is being executed, other threads close the mo-server

**Comment by lignay** [comment]
This issue will be retested once #1139 is fixed, due to this issue found after hitting 1139.

**Comment by lignay** [comment]
The issue is gone after fixing #1139.

**Comment by lignay** [comment]
The issue is gone after fixing #1139.
