### ISSUE TITLE
[Bug]: drop table hung in in pessimistic mode

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#11567]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="328" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/23080c73-d1d9-4d38-b45e-d7dc932921e2">

err info：
2023/08/31 09:34:06.477193 [ants]: worker exits from panic: lock error: start[[80 61 22 255 255]] is greater than end[[80 61 20]]
goroutine 3082 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/Users/yangzhao/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0xbc
panic({0x105e15c20, 0x1400c2b2600})
	/usr/local/go/src/runtime/panic.go:890 +0x230
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRangeLockLocked(_, {{0x106355358, 0x1400c2c3080}, 0x14007d68f00, {0x1400c2c3350, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...})
	/Users/yangzhao/matrixone/pkg/lockservice/lock_table_local.go:316 +0x4e8
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock(_, {{0x106355358, 0x1400c2c3080}, 0x14007d68f00, {0x1400c2c3350, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...})
	/Users/yangzhao/matrixone/pkg/lockservice/lock_table_local.go:250 +0x24c
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock(_, {{0x106355358, 0x1400c2c3080}, 0x14007d68f00, {0x1400c2c3350, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...}, ...)
	/Users/yangzhao/matrixone/pkg/lockservice/lock_table_local.go:101 +0xf0
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock(0x140082f52b0, {0x106355358, 0x1400c2c3080}, 0x14007d68f00, {0x1400c2c3350, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...)
	/Users/yangzhao/matrixone/pkg/lockservice/lock_table_local.go:83 +0x2c8
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(_, {_, _}, _, {_, _, _}, {_, _, _}, ...)
	/Users/yangzhao/matrixone/pkg/lockservice/service.go:116 +0x668
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock({0x106355358, 0x1400c2c3080}, 0x0, {0x106381e50, 0x1400cd822e0}, 0x42866, 0x1400d4a8000, 0x0, {0x42, 0x0, ...}, ...)
	/Users/yangzhao/matrixone/pkg/sql/colexec/lockop/lock_op.go:421 +0x434
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockTable({0x106381e50, 0x1400cd822e0}, 0x1400d4a8000, 0x42866, {0x42, 0x0, 0x0, 0x0, 0x2, 0x0, ...}, ...)
	/Users/yangzhao/matrixone/pkg/sql/colexec/lockop/lock_op.go:299 +0x404
github.com/matrixorigin/matrixone/pkg/sql/compile.lockTable({0x106381e50, 0x1400cd822e0}, 0x1400d4a8000, {0x106397ee0, 0x1400a71f0e0}, 0x0)
	/Users/yangzhao/matrixone/pkg/sql/compile/ddl.go:1855 +0x194
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).DropTable(0x140082f51e0, 0x1400b670500)
	/Users/yangzhao/matrixone/pkg/sql/compile/ddl.go:1291 +0x684
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0x1400b670500, 0x140082f51e0)
	/Users/yangzhao/matrixone/pkg/sql/compile/compile.go:313 +0x434
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
	/Users/yangzhao/matrixone/pkg/sql/compile/compile.go:436 +0x44
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/Users/yangzhao/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xc8
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/Users/yangzhao/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x8c

### Steps to Reproduce

```Markdown
drop table if exists pri01;
create table pri01 (col1 enum('qy4iujd3wi4fu4h3f', '323242r34df432432', '32e3ewfdewrew') primary key);
show create table pri01;
drop table pri01;
```

**Comment by YANGGMM** [comment]
only hung when col is enum type

**Comment by YANGGMM** [comment]
<img width="892" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/eb38424a-44ea-4f79-b8b7-d4731ae697cd">
