### ISSUE TITLE
[CUBE]: signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10596f298

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1174]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
MatrixOne: b84b704
MatrixCube: v0.1.0
- Hardware parameters: M1/16GB
- OS type: MacOS
- Others:

```

### Actual Behavior

Running random instance failure and found below SIGSEGV
```
{"level":"info","ts":"2021-11-17T17:25:56.860+0800","caller":"embed/serve.go:140","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"127.0.0.1:2379"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10596f298]

goroutine 225 [running]:
github.com/matrixorigin/matrixcube/storage/pebble.(*Storage).Get(0x0, {0x106fa45f6, 0x2, 0x2})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/storage/pebble/storage.go:103 +0x38
github.com/matrixorigin/matrixcube/raftstore.(*store).mustLoadStoreMetadata(0x14002e101e0)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store_bootstrap.go:135 +0x58
github.com/matrixorigin/matrixcube/raftstore.(*store).doBootstrapCluster(0x14002e101e0)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store_bootstrap.go:58 +0x74
github.com/matrixorigin/matrixcube/raftstore.(*store).ProphetBecomeLeader.func1()
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store_bootstrap.go:31 +0x2c
sync.(*Once).doSlow(0x14002e10200, 0x14008757688)
	/usr/local/go/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/matrixorigin/matrixcube/raftstore.(*store).ProphetBecomeLeader(0x14002e101e0)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/raftstore/store_bootstrap.go:30 +0x90
github.com/matrixorigin/matrixcube/components/prophet.(*defaultProphet).enableLeader(0x140034b0690)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/components/prophet/prophet_leader.go:38 +0x240
github.com/matrixorigin/matrixcube/components/prophet/member.(*Member).enableLeader(0x1400aff81c0, {0x140072e6b40, 0x23})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/components/prophet/member/member.go:111 +0x50
github.com/matrixorigin/matrixcube/components/prophet/election.(*Leadership).campaign(0x140034ee2d0)
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/components/prophet/election/election_leadship.go:279 +0xd8c
github.com/matrixorigin/matrixcube/components/prophet/election.(*Leadership).ElectionLoop(0x140034ee2d0, {0x10639aab8, 0x14000610680})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/components/prophet/election/election_leadship.go:196 +0x910
github.com/matrixorigin/matrixcube/components/prophet/member.(*Member).ElectionLoop(0x1400aff81c0, {0x10639aab8, 0x14000610680})
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/components/prophet/member/member.go:138 +0x3c
created by github.com/matrixorigin/matrixcube/components/prophet.(*defaultProphet).startLeaderLoop
	/Users/yangli/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.1.0/components/prophet/prophet_leader.go:21 +0x50
2021/11/17 18:00:28.143516 [info] prophet: prophet logger set
```

### Steps to Reproduce

```markdown
1. Random restart service while executing stmt in parallel
2. Run testing for more than 15 hours
Also matrixone works in stand-alone mode
```

**Comment by lignay** [comment]
Entire logs has been sent to dev

**Comment by zhangxu19830126** [comment]
MetaStorage is not properly initialized when starting the Cube.

**Comment by LeftHandCold** [comment]
The reason for this issue is similar to #1153

**Comment by JinHai-CN** [comment]
#1153 is fixed, what about this issue? @LeftHandCold

**Comment by lignay** [comment]
this issue has been verified in https://github.com/matrixorigin/matrixone/issues/1139.
