### ISSUE TITLE
[Bug]: ut TestGCDropTable panic in ACTION `UT Test on Darwinx86`

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#11817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 49b70ae44
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

in `UT Test on Darwin/x86`
https://github.com/matrixorigin/matrixone/actions/runs/6220392423/job/16880330856?pr=11812

[logs_174787.zip](https://github.com/matrixorigin/matrixone/files/12646904/logs_174787.zip)

![image](https://github.com/matrixorigin/matrixone/assets/3927687/b7c91770-2369-4aa4-9848-be7d5718446d)

```
2023-09-18T09:53:01.6025830Z panic: internal error: Overlapping key range found in MemCache_LRU when inserting [759 817). The key gc/gc_0-0_1695030768328144000-0.ckp contains overlapping intervals [730 766), [766 824),
2023-09-18T09:53:01.6026540Z
2023-09-18T09:53:01.6026870Z goroutine 7443 [running]:
2023-09-18T09:53:01.6027790Z github.com/matrixorigin/matrixone/pkg/fileservice.NewLRUCache.func1({{0xc0015cd980?, 0xc001c0a990?}, 0x10007b897?, 0xc001945620?}, {0x104adeab0, 0xc0019455c0})
2023-09-18T09:53:01.6029680Z    /Users/runner/work/matrixone/matrixone/pkg/fileservice/mem_cache.go:58 +0x17b
2023-09-18T09:53:01.6030690Z github.com/matrixorigin/matrixone/pkg/fileservice/lrucache.(*LRU[...]).Set(0x104b01dc0, {0x104addcb0, 0xc00005e1b8}, {{0xc0015cd980, 0x23}, 0x2f7, 0x3a}, {0x104adeab0, 0xc0019455c0})
2023-09-18T09:53:01.6031490Z    /Users/runner/work/matrixone/matrixone/pkg/fileservice/lrucache/lru.go:108 +0xb43
2023-09-18T09:53:01.6032360Z github.com/matrixorigin/matrixone/pkg/fileservice.(*MemCache).Update(0xc001c0a9c0, {0x104addcb0, 0xc00005e1b8}, 0xc001960840, 0x0?)
2023-09-18T09:53:01.6033040Z    /Users/runner/work/matrixone/matrixone/pkg/fileservice/mem_cache.go:185 +0x346
2023-09-18T09:53:01.6033860Z github.com/matrixorigin/matrixone/pkg/fileservice.(*LocalFS).Read.func1()
2023-09-18T09:53:01.6034810Z    /Users/runner/work/matrixone/matrixone/pkg/fileservice/local_fs.go:299 +0xb7
2023-09-18T09:53:01.6035710Z github.com/matrixorigin/matrixone/pkg/fileservice.(*LocalFS).Read(0xc0017be120, {0x104addcb0, 0xc00005e1b8}, 0xc001960840)
2023-09-18T09:53:01.6037540Z    /Users/runner/work/matrixone/matrixone/pkg/fileservice/local_fs.go:317 +0x386
2023-09-18T09:53:01.6038620Z github.com/matrixorigin/matrixone/pkg/objectio.ReadOneBlockWithMeta({0x104addcb0, 0xc00005e1b8}, 0xc00153d518, {0xc0015cd980, 0x23}, 0x0, {0xc00159c908, 0x4, 0xc00153d510?}, {0x0, ...}, ...)
2023-09-18T09:53:01.6039630Z    /Users/runner/work/matrixone/matrixone/pkg/objectio/funcs.go:180 +0xbce
2023-09-18T09:53:01.6040310Z github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadOneBlock(0xc001942e10, {0x104addcb0, 0xc00005e1b8}, {0xc00159c908, 0x4, 0x4}, {0x0, 0x0, 0x0}, 0x0, ...)
2023-09-18T09:53:01.6041210Z    /Users/runner/work/matrixone/matrixone/pkg/objectio/reader.go:167 +0x1e5
2023-09-18T09:53:01.6042710Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.(*BlockReader).LoadColumns(0xc001070d50, {0x104addcb0, 0xc00005e1b8}, {0xc00159c908, 0x4, 0x4}, {0x0, 0x0, 0x0}, 0x0, ...)
2023-09-18T09:53:01.6043750Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/blockio/reader.go:130 +0x445
2023-09-18T09:53:01.6044790Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*GCTable).replayData(0x30?, {0x104addcb0, 0xc00005e1b8}, 0x0, {0x105a82d40, 0x4, 0x10005c386?}, {0x106a1eb00, 0x4, 0x4}, ...)
2023-09-18T09:53:01.6045740Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gc/table.go:296 +0x1d3
2023-09-18T09:53:01.6046580Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*GCTable).ReadTable(0xc001070d40, {0x104addcb0, 0xc00005e1b8}, {0xc0015cd980, 0x23}, 0x1029eda80?, 0xc0017ce160)
2023-09-18T09:53:01.6047500Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gc/table.go:369 +0x29d
2023-09-18T09:53:01.6048320Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*DiskCleaner).replay(0xc00057d9e0)
2023-09-18T09:53:01.6048980Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gc/diskcleaner.go:189 +0x100d
2023-09-18T09:53:01.6049950Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*DiskCleaner).process(0xc00057d9e0, {0xc0019ac000, 0x1, 0xc00165afa0?})
2023-09-18T09:53:01.6050850Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gc/diskcleaner.go:204 +0xb4
2023-09-18T09:53:01.6051640Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
2023-09-18T09:53:01.6053260Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x373
2023-09-18T09:53:01.6054180Z created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
2023-09-18T09:53:01.6055130Z    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0x19f
2023-09-18T09:53:01.6055750Z FAIL   github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/test 140.566s
```

**Comment by LeftHandCold** [comment]
这周完成gc重构

**Comment by LeftHandCold** [comment]
这周完成gc重构

**Comment by LeftHandCold** [comment]
等待完成gc重构

**Comment by LeftHandCold** [comment]
等待完成gc重构

**Comment by LeftHandCold** [comment]
等待完成gc重构

**Comment by xzxiong** [comment]
checked
