### ISSUE TITLE
[Bug]: cn continuous restart due to: panic: blk entry not existed

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#11823]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-16d88550
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="993" alt="image" src="https://github.com/matrixorigin/matrixone/assets/52204121/ae9b2aae-469c-4bd9-a071-32817486deaa">

cn panic due to following error:
```
{"level":"ERROR","time":"2023/09/18 14:14:53.848898 +0000","name":"cn-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"63373230-3561-3330-3738-346363366238","connection_id":4294967295,"statement":"select user_id,authentication_string,default_role from mo_catalog.mo_user where user_name = \"admin\"","status":"fail","error":"SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"bcf0e950-562d-11ee-a425-d69da8518a37","kind":"statement"},"session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|bcf0d4fd-562d-11ee-a425-d69da8518a37|4dd2339f-562d-11ee-a425-d69da8518a37","session_id":"bcf0d4fd-562d-11ee-a425-d69da8518a37"}
{"level":"ERROR","time":"2023/09/18 14:14:53.848956 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:2731","msg":"SQL parser error: table \"mo_user\" does not exist","uuid":"63373230-3561-3330-3738-346363366238","session_info":"connectionId 24607714|172.20.0.24:56882|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 50872|4dd2339f-562d-11ee-a425-d69da8518a37","session_id":"4dd2339f-562d-11ee-a425-d69da8518a37","statement_id":"bcf0bfc1-562d-11ee-a425-d69da8518a37"}
{"level":"ERROR","time":"2023/09/18 14:14:53.848973 +0000","name":"cn-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"63373230-3561-3330-3738-346363366238","connection_id":24607714,"statement":"alter account `b73d090f_80b1_46fb_bc0a_43fe9d49918b` admin_name 'admin' identified by '******'","status":"fail","error":"SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"bcf0bfc1-562d-11ee-a425-d69da8518a37","kind":"statement"},"session_info":"connectionId 24607714|172.20.0.24:56882|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 50872|4dd2339f-562d-11ee-a425-d69da8518a37","session_id":"4dd2339f-562d-11ee-a425-d69da8518a37","statement_id":"bcf0bfc1-562d-11ee-a425-d69da8518a37"}
{"level":"INFO","time":"2023/09/18 14:14:54.466609 +0000","caller":"disttae/logtailPushModel.go:426","msg":"[log-tail-push-client] start to unsubscribe unused table."}
{"level":"INFO","time":"2023/09/18 14:14:54.466640 +0000","caller":"disttae/logtailPushModel.go:455","msg":"[log-tail-push-client] unsubscribe unused table finished."}
{"level":"INFO","time":"2023/09/18 14:14:54.466607 +0000","caller":"disttae/logtailPushModel.go:485","msg":"GC partition_state 1695028494466603002-0"}
panic: blk entry not existed

goroutine 359 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).truncate(0xc0c9252060, {0x428e7, 0x4291e}, {0x0, 0x0, 0x0, 0x0, 0xfa, 0xd7, 0xd8, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:701 +0xa45
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*Partition).Truncate(0xc00cd06b90, {0x3c41650?, 0xc0012f4ff0?}, {0x428e7, 0x4291e}, {0x0, 0x0, 0x0, 0x0, 0xfa, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition.go:133 +0xbc
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:487 +0x491
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:461 +0xaa
```

### Additional information

full cn log:
[cn.log.918.txt](https://github.com/matrixorigin/matrixone/files/12648882/cn.log.918.txt)

**Comment by XuPeng-SH** [comment]
assign to @jiangxinmeng1

**Comment by jiangxinmeng1** [comment]
删除时有重复的blockIndex，导致同一个blk被删除两遍，第二次没有找到block。
重复的blockIndex可能是消费checkpoint的时候插入的，还在定位原因
<img width="398" alt="get blk entry failed 3" src="https://github.com/matrixorigin/matrixone/assets/51114574/0ac6a3d1-2eb1-426c-af93-11825aef3c6c">

**Comment by jiangxinmeng1** [comment]
fixed by #11882

**Comment by jiangxinmeng1** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/11882

**Comment by loveRhythm1990** [comment]
close since fixed
