### ISSUE TITLE
[Bug]: Tke regression test: tpch 1t test report error 'stream closed'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6ee7721126f7799b15252cc1714e0d6fc86b5678
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="962" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/908bec07-a03c-47a2-a649-b74fb87b7d6a">

log: http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230918%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-22ftj%5C%22%7D%20%7C%3D%20%60memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

pod status：
<img width="1487" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d906851c-0f48-41a0-b336-c4a6030c52dd">

memory: http://139.155.148.31:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=Prometheus&var-cluster=&var-namespace=mo-nightly-regression-20230918&from=now-24h&to=now
<img width="1257" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/de5247ab-e74b-45b2-9e1e-4d79a78af6c8">
根据pod状态以及内存信息，pod第一次重启时间发生在'stream closed'之前，初步判断报错与oom无关。

根据报错时间，查找日志中'stream closed'，如下，具体原因需要进一步定位：
<img width="1312" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fccdd3b2-2fff-4b35-bafb-638dc151c1ad">

**Comment by sukki37** [comment]
Panic log：
```


2023-09-19 07:13:30.479{"level":"INFO","time":"2023/09/18 23:13:30.479743 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272392:e4bbc621-0-0, 37e99662-0-0, e31ba284-20-0, 763210ed-0-0, 34e16702-0-0, e31ba284-19-0, d2484f91-0-0, 732a4dda-0-0, e31ba284-18-0, cf40c149-0-0, 1f82edc9-0-0, e31ba284-17-0"}2023-09-19 07:13:30.540{"level":"INFO","time":"2023/09/18 23:13:30.540446 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272451:e770afe9-0-0, a621fe68-0-0, e48d80a4-22-0, e46afb7f-0-0, 3a8b370c-0-0, e48d80a4-21-0, e48d80a4-20-0, d80480f7-0-4, d80480f7-0-3, d80480f7-0-2, d80480f7-0-1, d80480f7-0-0, 81c504a5-0-0, e48d80a4-19-0"}2023-09-19 07:13:30.540{"level":"INFO","time":"2023/09/18 23:13:30.540603 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272401:cf9a0441-0-0, 73772ace-0-0, e2d672b5-10-0, d9bb2fb3-0-0, cc929e1e-0-0, e2d672b5-9-0"} | 2023-09-19 07:13:30.479 | {"level":"INFO","time":"2023/09/18 23:13:30.479743 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272392:e4bbc621-0-0, 37e99662-0-0, e31ba284-20-0, 763210ed-0-0, 34e16702-0-0, e31ba284-19-0, d2484f91-0-0, 732a4dda-0-0, e31ba284-18-0, cf40c149-0-0, 1f82edc9-0-0, e31ba284-17-0"} |   |   |   | 2023-09-19 07:13:30.540 | {"level":"INFO","time":"2023/09/18 23:13:30.540446 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272451:e770afe9-0-0, a621fe68-0-0, e48d80a4-22-0, e46afb7f-0-0, 3a8b370c-0-0, e48d80a4-21-0, e48d80a4-20-0, d80480f7-0-4, d80480f7-0-3, d80480f7-0-2, d80480f7-0-1, d80480f7-0-0, 81c504a5-0-0, e48d80a4-19-0"} |   |   |   | 2023-09-19 07:13:30.540 | {"level":"INFO","time":"2023/09/18 23:13:30.540603 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272401:cf9a0441-0-0, 73772ace-0-0, e2d672b5-10-0, d9bb2fb3-0-0, cc929e1e-0-0, e2d672b5-9-0"} |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2023-09-19 07:13:30.479 | {"level":"INFO","time":"2023/09/18 23:13:30.479743 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272392:e4bbc621-0-0, 37e99662-0-0, e31ba284-20-0, 763210ed-0-0, 34e16702-0-0, e31ba284-19-0, d2484f91-0-0, 732a4dda-0-0, e31ba284-18-0, cf40c149-0-0, 1f82edc9-0-0, e31ba284-17-0"} |  
  |   | 2023-09-19 07:13:30.540 | {"level":"INFO","time":"2023/09/18 23:13:30.540446 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272451:e770afe9-0-0, a621fe68-0-0, e48d80a4-22-0, e46afb7f-0-0, 3a8b370c-0-0, e48d80a4-21-0, e48d80a4-20-0, d80480f7-0-4, d80480f7-0-3, d80480f7-0-2, d80480f7-0-1, d80480f7-0-0, 81c504a5-0-0, e48d80a4-19-0"} |  
  |   | 2023-09-19 07:13:30.540 | {"level":"INFO","time":"2023/09/18 23:13:30.540603 +0000","caller":"logtailreplay/partition_state.go:721","msg":"GC partition_state at 1695060810448194202-0 for table 272401:cf9a0441-0-0, 73772ace-0-0, e2d672b5-10-0, d9bb2fb3-0-0, cc929e1e-0-0, e2d672b5-9-0"} |  

2023-09-19 07:13:30.542panic: blk entry not existed |   |   | 2023-09-19 07:13:30.542 | panic: blk entry not existed |  
  |   | 2023-09-19 07:13:30.542 | panic: blk entry not existed |  
2023-09-19 07:13:30.5422023-09-19 07:13:30.542goroutine 1798 [running]:2023-09-19 07:13:30.542github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).truncate(0xc427e52ae0, {0x42804, 0x42805}, {0x0, 0x0, 0x0, 0x0, 0x9a, 0x4a, 0x73, ...})2023-09-19 07:13:30.542	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:701 +0xa452023-09-19 07:13:30.542github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*Partition).Truncate(0xc005d8adc0, {0x3ce9e10?, 0xc00013af00?}, {0x42804, 0x42805}, {0x0, 0x0, 0x0, 0x0, 0x9a, ...})2023-09-19 07:13:30.542	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition.go:133 +0xbc2023-09-19 07:13:30.542github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker.func1()2023-09-19 07:13:30.542	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:487 +0x4912023-09-19 07:13:30.542created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker2023-09-19 07:13:30.542	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:461 +0xaa |   |   | 2023-09-19 07:13:30.542 |   |   |   |   | 2023-09-19 07:13:30.542 | goroutine 1798 [running]: |   |   |   | 2023-09-19 07:13:30.542 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).truncate(0xc427e52ae0, {0x42804, 0x42805}, {0x0, 0x0, 0x0, 0x0, 0x9a, 0x4a, 0x73, ...}) |   |   |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:701 +0xa45 |   |   |   | 2023-09-19 07:13:30.542 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*Partition).Truncate(0xc005d8adc0, {0x3ce9e10?, 0xc00013af00?}, {0x42804, 0x42805}, {0x0, 0x0, 0x0, 0x0, 0x9a, ...}) |   |   |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition.go:133 +0xbc |   |   |   | 2023-09-19 07:13:30.542 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker.func1() |   |   |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:487 +0x491 |   |   |   | 2023-09-19 07:13:30.542 | created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker |   |   |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:461 +0xaa
  |   | 2023-09-19 07:13:30.542 |   |  
  |   | 2023-09-19 07:13:30.542 | goroutine 1798 [running]: |  
  |   | 2023-09-19 07:13:30.542 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).truncate(0xc427e52ae0, {0x42804, 0x42805}, {0x0, 0x0, 0x0, 0x0, 0x9a, 0x4a, 0x73, ...}) |  
  |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:701 +0xa45 |  
  |   | 2023-09-19 07:13:30.542 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*Partition).Truncate(0xc005d8adc0, {0x3ce9e10?, 0xc00013af00?}, {0x42804, 0x42805}, {0x0, 0x0, 0x0, 0x0, 0x9a, ...}) |  
  |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/partition.go:133 +0xbc |  
  |   | 2023-09-19 07:13:30.542 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker.func1() |  
  |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:487 +0x491 |  
  |   | 2023-09-19 07:13:30.542 | created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).partitionStateGCTicker |  
  |   | 2023-09-19 07:13:30.542 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:461 +0xaa


```

**Comment by XuPeng-SH** [comment]
@Ariznawlll it should be fixed by #11882

**Comment by Ariznawlll** [comment]
need to be confirmed by tke regression test.

**Comment by Ariznawlll** [comment]
Never appeared again.

**Comment by heni02** [comment]
date 10.13tke 回归又出现了这个错误，也是q18报错
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6510072880/job/17683591085
![image](https://github.com/matrixorigin/matrixone/assets/113406637/832ad841-741d-4d7c-bdfe-d0a26d110c3c)
log：
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231013%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221697221080000%22,%22to%22:%221697221139000%22%7D%7D
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7d779c58-f881-45c6-97ce-cea2b91874e2)

**Comment by DanielZhangQD** [comment]
Hit this issue with the following sql with commit `1.0-dev-a6f3e1a42`:
```
MySQL [mo_cloud]> select * from system.statement_info where statement_id = '489f1953-6bae-11ee-848e-6e52f81fce25';
ERROR 20503 (HY000): stream closed
```

**Comment by jiangxinmeng1** [comment]
日志里没有panic，不是truncate导致的

**Comment by nnsgmsone** [comment]
这个就是两个cn之间的通讯断了导致的，看日志是两个cn都在2:18:41这个时刻都感知不到对象的存在。然后连接断开，查询就报错了。。。那个如果解决我还需要想想。。。。。

**Comment by nnsgmsone** [comment]
这个就是两个cn之间的通讯断了导致的，看日志是两个cn都在2:18:41这个时刻都感知不到对象的存在。然后连接断开，查询就报错了。。。那个如果解决我还需要想想。。。。。

**Comment by aylei** [comment]
<img width="1919" alt="WeChatWorkScreenshot_30531f82-32e5-4b5a-b07d-d39bebb87e52" src="https://github.com/matrixorigin/matrixone/assets/18556593/15a4e76d-b078-4810-86f8-8b0e57b473b5">

stream closed 的原因是另一个 CN 在那个时间点重启了，重启原因缺少 k8s event 的收集目前看不到，通过内存监控推测是 OOM eviction（soft eviction）

**Comment by nnsgmsone** [comment]
目前的报错信息应该是合理的，是否需要修改行为可能需要讨论
