### ISSUE TITLE
[Bug]: newly introduced aliyun oss  sdk fails to authorize: Authorization header is invalid

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#11877]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-1008bc0e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DN pod always crash and cannot startup, reports following error:

```
{"level":"INFO","time":"2023/09/21 02:14:39.163390 +0000","caller":"db/open.go:63","msg":"open-tae","operation":"End","operand":"open","cost":"87.657908ms","err":"oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage=\"Authorization header is invalid.\", RequestId=650BA70FD469A9383290515A, Ec=0002-00000063"}
panic: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage="Authorization header is invalid.", RequestId=650BA70FD469A9383290515A, Ec=0002-00000063

goroutine 253 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x3d0b718, 0xc003196330}, {0xc0032c40f0, 0x50}, 0xc001150000?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/open.go:147 +0x25c8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0x3d0b718, 0xc003196330}, {0xc0000645a0, 0x4c}, 0x100?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:1067 +0x1a8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0x3d0b718?, 0xc003196330?}, {0xc0000645a0?, 0x360c6f3?}, 0x5?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:95 +0x49
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0x3d0b718?, 0xc003196330}, {0xc0000645a0, 0x4c}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:69 +0x24f
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).newTAEStorage(0xc00110e820, {0x3d0b718, 0xc003196330}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/tnservice/factory.go:152 +0x27f
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createTxnStorage(0xc00110e820, {0x3d0b718, 0xc003196330}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/tnservice/factory.go:73 +0x22e
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createReplica.func1({0x3d0b718?, 0xc0032a9620?})
        /go/src/github.com/matrixorigin/matrixone/pkg/tnservice/store.go:286 +0x171
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

### Expected Behavior

DN should startup successfully

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/4a59b912ac9b8ca3dc44ab1fc70f8ef46ac4509a

**Comment by loveRhythm1990** [comment]
close since fixed
