### ISSUE TITLE
[Bug]: main branch is not compatible with 0.8.0

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#11883]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others: https://github.com/matrixorigin/ci-test/actions/runs/6270902192/job/17029565642
```

### Actual Behavior

During the compatibility test, based on the existing data of version 0.8.0, the mo of the main branch could not start normally.

### Expected Behavior

During the compatibility test, based on the existing data of version 0.8.0, the mo of the main branch should be able to start normally and pass the test

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/ci-test/actions/runs/6270902192/job/17029565642
https://github.com/matrixorigin/ci-test/actions/runs/6269663485/job/17026423900
```

**Comment by sukki37** [comment]
[mo-service.log](https://github.com/matrixorigin/matrixone/files/12705763/mo-service.log)


```
panic: invalid lsn 810, current lsn 0

goroutine 577 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).checkLSN(0x401667e900, 0x17?)
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/db/replay.go:158 +0xdc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayEntry(0x401667e900, 0xb?, 0x32a, {0x4003b4e063, 0x16eff, 0x17f9d}, 0xe868?, {0xffffa6fb4a68?, 0x70?})
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/db/replay.go:111 +0xa0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).replayhandle.func1(0x2cdbea0?, 0x400453f9e0?, {0x4003b4e063?, 0x4000068a00?, 0x4001833708?}, 0xafd4?, {0x4016462b40?, 0x4016404f00?})
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/wal/driver.go:82 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).replayEntry(0x4004560210, 0x650d38b8?, 0x4004545ad0)
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/logstore/store/replay.go:81 +0x20c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).Replay.func1(0x4001833778?)
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/logstore/store/replay.go:23 +0x2c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*replayer).replayRecords(0x401389e160)
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go:146 +0x7c
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*replayer).replay
	/runner/_work/ci-test/ci-test/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go:81 +0x74

```

**Comment by jiangxinmeng1** [comment]
从日志看重启后没读到ckp文件，可能是fs的地址配置不对。
试一下用main重启的时候在cn.toml和tn.toml里加上
```
[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"
```

**Comment by XuPeng-SH** [comment]
0.8 和 现在的fileservice的默认配置变了，需要修改配置

**Comment by sukki37** [comment]
testing

**Comment by guguducken** [comment]
test pass, so close it. https://github.com/matrixorigin/ci-test/actions/runs/6446315177/job/17501821190
