### ISSUE TITLE
[Bug]:  bvt test fails at case `matrixone/test/distributed/cases/ddl/comprimary_key.sql` with error `Exception in thread "main" java.lang.NullPointerException`

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#11881]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0.0-rc1
- Hardware parameters: 8c 16g and 4c 8g
- OS type: debian 11 and kylin 10
- Others: none
```

### Actual Behavior

When running bvt test on mo in docker mode, this case always fails: 
```bash
2023-09-21 19:54:06 INFO  Executor:241 - The script file[../matrixone/test/distributed/cases/ddl/alter_table_rename_column.sql] has been executed, and cost: 11.478s, total:261, success:242, failed:0, ignored:19, abnoraml:0
2023-09-21 19:54:06 INFO  Executor:33 - Start to execute the script file[../matrixone/test/distributed/cases/ddl/comprimary_key.sql] now, and it will take a few moment,pleas wait......
2023-09-21 19:54:06 ERROR RSSet:140 - The row count does not equal with each other, one is 4, the other is 0
2023-09-21 19:54:06 ERROR Executor:159 - [../matrixone/test/distributed/cases/ddl/comprimary_key.sql][row:23][select col3,col18 from cpk_table_1;] was executed failed, con[id=0, user=dump, ***
2023-09-21 19:54:06 ERROR Executor:161 - [EXPECT RESULT]:
col3    col18
1    message
3    message
5    OPQR.STU-_+=VWXYZa
3    L/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012
2023-09-21 19:54:06 ERROR Executor:162 - [ACTUAL RESULT]:
col3    col18
Exception in thread "main" java.lang.NullPointerException
	at io.mo.result.StmtResult.regularMatch(StmtResult.java:114)
	at io.mo.cases.SqlCommand.checkResult(SqlCommand.java:202)
	at io.mo.db.Executor.run(Executor.java:146)
	at io.mo.Tester.run(Tester.java:201)
	at io.mo.Tester.run(Tester.java:210)
	at io.mo.Tester.run(Tester.java:210)
	at io.mo.Tester.main(Tester.java:148)
Error: Process completed with exit code 1.
```

### Expected Behavior

All bvt cases should pass with no errors

### Steps to Reproduce

1. Deploy an mo in docker mode
https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method3/

2. Set mo confs, 
cn.toml
```toml
service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18000


[cn.txn]
mode = "pessimistic"
```

tn.toml
```toml
service-type = "TN"
data-dir = "./mo-data"

[log]
level = "info"

[tn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 19000


[tn.txn]
mode = "pessimistic"
```

Save these 2 conf files to a folder, e.g. `/data/mo/20230921_194537/matrixone/etc/`
3. Start mo docker container
```bash
docker run -d  -v /data/mo/:/mo-data:rw -p 9876:12345 -p 6001:6001 --name mo --memory 6819m --env GOMEMLIMIT=6137MiB --hostname ecs-f749 --privileged=true -v /data/mo/20230921_194537/matrixone/etc/:/etc:rw --entrypoint /mo-service matrixorigin/matrixone:1.0.0-rc1 -launch /etc/quickstart/launch.toml
```

4. Download mo source code with bvt test cases
```bash
mkdir -p /data/bvt/
cd /data/bvt/
git clone https://ghproxy.com/github.com/matrixorigin/matrixone.git -b 1.0.0-rc1
```

5. Download mo-tester tool
```bash
mkdir -p /data/bvt/ 
git clone https://ghproxy.com/github.com/matrixorigin/mo-tester.git
```
6. Run bvt test cases
```bash
cd /data/bvt/mo-tester
./run.sh -n -g -m run -p ../matrixone/test/distributed/cases -e optimistic
/data/bvt_cases/matrixone
```

### Additional information

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6261178786/job/17000800347

**Comment by jensenojs** [comment]
类似的问题, 这个报错来看mo和mo-tester都有点问题, 合理的预期是这个case失败了mo-tester能继续往下跑
https://github.com/matrixorigin/mo-tester/issues/143

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by LiSong0214** [comment]
在原环境上复现。

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
1、在测试过程中有碰到这个问题。
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "replacement" is null
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1014)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)
        at java.base/java.lang.String.replaceAll(String.java:2939)
        at io.mo.db.Executor.run(Executor.java:126)
        at io.mo.Tester.run(Tester.java:206)
        at io.mo.Tester.run(Tester.java:215)
        at io.mo.Tester.run(Tester.java:215)
        at io.mo.Tester.run(Tester.java:215)
        at io.mo.Tester.main(Tester.java:153)

这个经确认，是要在启动项中增加  -s 来指定  resource_path
```

2、另外
```
Exception in thread "main" java.lang.NullPointerException
	at io.mo.result.StmtResult.regularMatch(StmtResult.java:114)
	at io.mo.cases.SqlCommand.checkResult(SqlCommand.java:202)
	at io.mo.db.Executor.run(Executor.java:146)
	at io.mo.Tester.run(Tester.java:201)
	at io.mo.Tester.run(Tester.java:210)
	at io.mo.Tester.run(Tester.java:210)
	at io.mo.Tester.main(Tester.java:148)
```
这个部分与https://github.com/matrixorigin/mo-tester/issues/143
这个重复了。先转苏动帮忙看看吧

**Comment by aronchanisme** [comment]
Seems to be raised by mo-tester itself and not an MO issue.
```bash
cd mo-tester

./run.sh -n -g -m run -p /data/mo/20231116_110729/test -e optimistic # not ok

./run.sh -n -g -m run -p /data/mo/20231116_110729/test/distributed/cases -e optimistic # ok
```

<img width="1729" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/70236be7-2abc-4dc4-8795-ed6ceab882f1">

**Comment by aronchanisme** [comment]
> Seems to be raised by mo-tester itself and not an MO issue.
> 
> ```shell
> cd mo-tester
> 
> ./run.sh -n -g -m run -p /data/mo/20231116_110729/test -e optimistic # not ok
> 
> ./run.sh -n -g -m run -p /data/mo/20231116_110729/test/distributed/cases -e optimistic # ok
> ```
> 
> <img alt="image" width="1729" src="https://user-images.githubusercontent.com/46433151/283311598-70236be7-2abc-4dc4-8795-ed6ceab882f1.png">

work around as stated here, closing it
