### ISSUE TITLE
[Bug]:  `panic` happens during bvt 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12017]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):46465d8abecd2635702948619e334cfb55ae5f9d
- Hardware parameters:
- OS type:
- Others:

on my branch https://github.com/daviszhen/matrixone/tree/0928-add-txn-views
```

### Actual Behavior

```
{"level":"ERROR","time":"2023/10/08 11:06:43.580635 +0000","name":"cn-log-tail-client","caller":"morpc/backend.go:221","msg":"connect to remote failed","remote":"127.0.0.1:19001","backend-id":"a380a085-a288-4cc2-b19b-0f19521960f8"}
{"level":"ERROR","time":"2023/10/08 11:06:43.580650 +0000","name":"cn-log-tail-client.rpc-client[cn-log-tail-client]","caller":"morpc/client.go:480","msg":"create backend failed","backend":"127.0.0.1:19001","error":"dial tcp4 127.0.0.1:19001: connect: connection refused"}
panic: no codec found for: IOEntry[3005,2]

goroutine 12736 [running]:
github.com/matrixorigin/matrixone/pkg/objectio.GetIOEntryCodec({0x9110?, 0x4a?})
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/codecs.go:100 +0x119
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.BuildCommandFrom({0xc00d1c5677, 0xd6, 0xd09})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnbase/command.go:544 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*ComposedCmd).UnmarshalBinary(0xc01aa79890, {0xc00d1c566f, 0xc01aa79860?, 0xd11})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnbase/command.go:466 +0x105
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.init.0.func2({0xc00d1c566f, 0xba2, 0xd11})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnbase/command.go:72 +0x98
github.com/matrixorigin/matrixone/pkg/objectio.ioEntryCodec.Decode({0x0?, 0x37927a0?}, {0xc00d1c566f?, 0xffffffffffffffff?, 0x12?})
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/codecs.go:80 +0x3a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.BuildCommandFrom({0xc00d1c566b, 0xba6, 0xd15})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnbase/command.go:545 +0x77
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnCmd).UnmarshalBinary(0xc01aa79830, {0xc00d1c5667, 0xc37, 0xd19})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnbase/command.go:374 +0xfd
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.init.0.func1({0xc00d1c5667, 0xc37, 0xd19})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnbase/command.go:60 +0x174
github.com/matrixorigin/matrixone/pkg/objectio.ioEntryCodec.Decode({0x0?, 0x3792798?}, {0xc00d1c5667?, 0x50186e?, 0x4c6e4c?})
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/codecs.go:80 +0x3a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayEntry(0xc017e80f00, 0x830bb18?, 0x4b0e, {0xc00d1c5663, 0xc3b, 0xd1d}, 0x1710?, {0x703b973decafd829?, 0x179e2f88?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/replay.go:116 +0xfb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).replayhandle.func1(0x31d8fa0?, 0xc00f015c20?, {0xc00d1c5663?, 0xc016cd3f20?, 0x499e0e?}, 0x320?, {0xc0179e2f98?, 0xc0179e2f98?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/wal/driver.go:82 +0x29
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).replayEntry(0xc0014b7290, 0xc016cd3f48?, 0xc017fdc9b0)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/logstore/store/replay.go:81 +0x283
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).Replay.func1(0xc00f8cd680?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/logstore/store/replay.go:23 +0x27
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*replayer).replayRecords(0xc0015deb00)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go:146 +0x8e
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*replayer).replay
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go:81 +0x76


```

### Expected Behavior

no panic 

### Steps to Reproduce

```Markdown
upgrade ci
```

### Additional information

https://github.com/matrixorigin/matrixone/actions/runs/6446959405?pr=11995

**Comment by daviszhen** [comment]
背景。
我的pr是增加事务视图的。尽增加了table function和view的代码。没涉及到其它修改。

**Comment by jiangxinmeng1** [comment]
分支上没包含cbc3bb16a，main上有，比main上的版本旧，没有解析这个版本的代码，合一下main再跑就可以了

**Comment by daviszhen** [comment]
应该解决了。
