### ISSUE TITLE
[Bug]: mo hang in some case when retry

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#12015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6093f845c89fc8dcc344a539433bfe5df904d920
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

session 1 run :
```
create database db1;
use db1;
drop table if exists atomic_table_12_2;
drop table if exists atomic_table_13;
create table atomic_table_12_2(c1 int primary key,c2 varchar(25));
insert into atomic_table_12_2 values (3,"a"),(4,"b"),(5,"c");
create table atomic_table_13(c1 int primary key,c2 varchar(25));
insert into atomic_table_13 values (3,"d"),(4,"e"),(5,"f");
begin;
alter table atomic_table_13 add constraint ffa foreign key f_a(c1) references atomic_table_12_2(c1);
```

then session 2 run:
```
use db1;
insert into atomic_table_13 values (8,"h");
```

then session 1 run：
```
commit;
drop table if exists atomic_table_12_4;
drop table if exists atomic_table_13;   //hang here
```

### Expected Behavior

no hang

**Comment by nnsgmsone** [comment]
还没看。。。

**Comment by nnsgmsone** [comment]
还没看。。。

**Comment by nnsgmsone** [comment]
有两个问题。。一个问题已经修复。。

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by sukki37** [comment]
cn panic with `BUG: try hold on empty lock`

http://47.97.80.230/explore?orgId=1&panes=%7B%22ebC%22:%7B%22datasource%22:%22P3C839627617F91E0%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22,%20pod%3D%5C%22default-cn-cs5gz%5C%22%7D%20%7C%3D%20%60try%20hold%20on%20empty%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3C839627617F91E0%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221697588400000%22,%22to%22:%221697590799000%22%7D%7D%7D&schemaVersion=1

**Comment by loveRhythm1990** [comment]
> cn panic with `BUG: try hold on empty lock`
> 
> http://47.97.80.230/explore?orgId=1&panes=%7B%22ebC%22:%7B%22datasource%22:%22P3C839627617F91E0%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22,%20pod%3D%5C%22default-cn-cs5gz%5C%22%7D%20%7C%3D%20%60try%20hold%20on%20empty%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3C839627617F91E0%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221697588400000%22,%22to%22:%221697590799000%22%7D%7D%7D&schemaVersion=1

panic stack of `try hold on empty lock`：
```
panic: BUG: try hold on empty lock

goroutine 253987 [running]:
github.com/matrixorigin/matrixone/pkg/lockservice.Lock.tryHold({0xa0?, 0xc08a2605a0?, {0x3604300?, 0xc08dd89180?}}, 0xc0d2d214a0)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock.go:88 +0x305
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).addRangeLockLocked(0xc1059b7520, 0xc0d2d214a0, {0xc0f8418240, 0x30, 0x30}, {0xc0f8418270, 0x30, 0x30})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:464 +0x7cd
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRangeLockLocked(0xc1059b7520, 0xc0d2d214a0)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:330 +0x176
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock(0xc1059b7520, 0xc0d2d214a0)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:270 +0xcb
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock(0xc1059b7520, 0xc0d2d214a0, 0x0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:101 +0x131
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock(0xc1059b7520, {0x35d3098?, 0xc0f1b7a7b0?}, 0xc065b9ebf0?, {0xc0f1b7a810, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:80 +0x2cf
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).handleRemoteLock(0xc001976000, {0x35d3098?, 0xc0f1b7a7b0}, 0xc065b9f9c0, 0xc051f1c000, 0xc0f3592500, {0x35e9e30?, 0xc06bc9ed10})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service_remote.go:98 +0x36e
github.com/matrixorigin/matrixone/pkg/lockservice.(*server).onMessage.func1(0xc051f1c000)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:279 +0x112
github.com/matrixorigin/matrixone/pkg/lockservice.(*server).onMessage(0xc000742300, {0x35d3098?, 0xc0f1b7a7b0?}, {{0x35d3098, 0xc0f1b7a7b0}, 0xc065b9f9c0, {0x35ebd68, 0xc051f1c000}, 0x0, 0x0, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:282 +0x9dc
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc001843220, {0x3604080, 0xc04abbed00}, {0x2db4d40?, 0xc0f1b7a8d0}, 0x4ebd1)
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:241 +0x6e3
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0018432c0, {0x3604080, 0xc04abbed00})
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:336 +0x485
```

cn log: 
[cn-panic-restart-1018.txt](https://github.com/matrixorigin/matrixone/files/12984818/cn-panic-restart-1018.txt)
