### ISSUE TITLE
[LongTermTests]: runtime error: index out of range [3] with length 3

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1205]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- MatrixOne Commit ID: d7ff30a98d8dc9aaf441b02d15f357f57b91f8f2
- MatrixCube Version: v0.1.0
- OS type: CentOS 7
- Go Version: 1.17
```

### Actual Behavior

Found connection painc with below error:
```
2021/11/23 12:38:28.500378 +0800 ERROR goetty@v1.11.1/application.go:242 connection painc {"err": "runtime error: index out of range [3] with length 3", "stack": "goroutine 197270 [running]:\ngithub.com/fagongzi/goetty.(*server).doStart.func1.1()\n\t/home/devops/go/pkg/  mod/github.com/fagongzi/goetty@v1.11.1/application.go:241 +0x7b\npanic({0x2252380, 0xc01496f9f8})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x215\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).analyseHandshakeResponse320(0xc00bdd6820,              {0xc01ccba5b8, 0x0, 0xc05f39f11dc48bc4})\n\t/home/devops/matrixone/pkg/frontend/mysql_protocol.go:763 +0x4a5\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).handleHandshake(0xc00bdd6820, {0xc01ccba5b8, 0x0, 0x3})\n\t/home/devops/matrixone/pkg/        frontend/mysql_protocol.go:519 +0x3a8\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0081056e0, {0x26225a0, 0xc024586420}, {0x203b2a0, 0xc01bd691a0}, 0xc)\n\t/home/devops/matrixone/pkg/frontend/routine_manager.go:117 +0x41e\ngithub.com/      fagongzi/goetty.(*server).doConnection(0xc00810e840, {0x26225a0, 0xc024586420})\n\t/home/devops/go/pkg/mod/github.com/fagongzi/goetty@v1.11.1/application.go:287 +0x503\ngithub.com/fagongzi/goetty.(*server).doStart.func1()\n\t/home/devops/go/pkg/mod/github.com/fagongzi/   goetty@v1.11.1/application.go:258 +0xc8\ncreated by github.com/fagongzi/goetty.(*server).doStart\n\t/home/devops/go/pkg/mod/github.com/fagongzi/goetty@v1.11.1/application.go:236 +0x192\n"}
```

### Expected Behavior

No index out of range exception

### Steps to Reproduce

```markdown
1. Start up 5 threads to random execute sql statements without service failure for long term.
2. Found below panic error from cube:

+++++++++
:3
+++++++++
2021/11/23 12:38:28.498604 +0800 INFO v1/collection.go:156 Append logindex: S-867:708:<0+0/1>
2021/11/23 12:38:28.499368 +0800 INFO goetty@v1.11.1/application.go:267 session connected {"session-id": 2396, "addr": "45.9.20.111:63054"}
2021/11/23 12:38:28.499407 +0800 INFO goetty@v1.11.1/application.go:272 session read {"session-id": 2396, "addr": "45.9.20.111:63054", "msg": {"Length":3,"SequenceID":47,"Payload":"KuAA"}}
2021/11/23 12:38:28.499420 +0800 INFO frontend/routine_manager.go:116 HANDLE HANDSHAKE
2021/11/23 12:38:28.500281 +0800 INFO frontend/routine_manager.go:68 will close iosession
2021/11/23 12:38:28.500378 +0800 ERROR goetty@v1.11.1/application.go:242 connection painc {"err": "runtime error: index out of range [3] with length 3", "stack": "goroutine 197270 [running]:\ngithub.com/fagongzi/goetty.(*server).doStart.func1.1()\n\t/home/devops/go/pkg/  mod/github.com/fagongzi/goetty@v1.11.1/application.go:241 +0x7b\npanic({0x2252380, 0xc01496f9f8})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x215\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).analyseHandshakeResponse320(0xc00bdd6820,              {0xc01ccba5b8, 0x0, 0xc05f39f11dc48bc4})\n\t/home/devops/matrixone/pkg/frontend/mysql_protocol.go:763 +0x4a5\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).handleHandshake(0xc00bdd6820, {0xc01ccba5b8, 0x0, 0x3})\n\t/home/devops/matrixone/pkg/        frontend/mysql_protocol.go:519 +0x3a8\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0081056e0, {0x26225a0, 0xc024586420}, {0x203b2a0, 0xc01bd691a0}, 0xc)\n\t/home/devops/matrixone/pkg/frontend/routine_manager.go:117 +0x41e\ngithub.com/      fagongzi/goetty.(*server).doConnection(0xc00810e840, {0x26225a0, 0xc024586420})\n\t/home/devops/go/pkg/mod/github.com/fagongzi/goetty@v1.11.1/application.go:287 +0x503\ngithub.com/fagongzi/goetty.(*server).doStart.func1()\n\t/home/devops/go/pkg/mod/github.com/fagongzi/   goetty@v1.11.1/application.go:258 +0xc8\ncreated by github.com/fagongzi/goetty.(*server).doStart\n\t/home/devops/go/pkg/mod/github.com/fagongzi/goetty@v1.11.1/application.go:236 +0x192\n"}
2021/11/23 12:38:28.501170 +0800 INFO frontend/mysql_cmd_executor.go:897 time of Exec.Run : 4.885774ms
2021/11/23 12:38:28.501218 +0800 INFO frontend/mysql_cmd_executor.go:924 time of SendResponse 23.231µs
2021/11/23 12:38:28.501240 +0800 INFO frontend/routine.go:111 connection id 3391 , the time of handling the request 6.29072ms
2021/11/23 12:38:28.501468 +0800 INFO goetty@v1.11.1/application.go:272 session read {"session-id": 2391, "addr": "127.0.0.1:54990", "msg": {"Length":78,"SequenceID":0,"Payload":                                                                                              "A0lOU0VSVCBJTlRPIHQxNDMgVkFMVUVTICg3MDIsMTk4MjAxLDM3LCdhbWVuaXRpZXMnLCdjbG9ja2VycycsJ3BpY3R1cmVzJywnQScp"}}
2021/11/23 12:38:28.501513 +0800 INFO frontend/mysql_cmd_executor.go:935 cmd 3
2021/11/23 12:38:28.501525 +0800 INFO frontend/mysql_cmd_executor.go:963 query:INSERT INTO t143 VALUES (702,198201,37,'amenities'...
2021/11/23 12:38:28.502824 +0800 INFO frontend/mysql_cmd_executor.go:806 time of Exec.Build : 1.183159ms
```

Start at: 2021/11/23 12:05:35.258148863 +0800
Found panic at: 2021/11/23 12:38:28.500378 +0800
```


### Additional information

_No response_

**Comment by lignay** [comment]
@zhangxu19830126  Please triage this issue

**Comment by zhangxu19830126** [comment]
![image](https://user-images.githubusercontent.com/2995754/142977569-de4a5d2f-b1a1-4148-bac5-482540fdb487.png)

**Comment by zhangxu19830126** [comment]
panic stack

**Comment by zhangxu19830126** [comment]
It's a bug in mysql_protocol.go

**Comment by lignay** [comment]
> It's a bug in mysql_protocol.go

Thanks.

Forward this issue to matrixone team.

**Comment by daviszhen** [comment]
This machine was accessed illegally by the sniffers detecting mysql protocol from the Europe and the Easten Europe.

       Timestamp                           IP：PORT                     Payload
2021/11/25 12:47:43.861896   89.248.165.46:56532  DuAA
2021/11/26 00:28:49.146116   89.248.165.46:38342   DuAA
2021/11/24 14:39:45.806226  89.248.165.46:33190   DuAA
2021/11/23 18:22:49.507866  195.54.167.183:64223   KuAA
2021/11/23 20:15:13.715032    45.9.20.105:63401        KuAA
2021/11/24 03:27:03.619209   89.248.165.23:60144   KuAA

After getting the complete payload from the right mysql client, the decoder decodes it correctly.
But, in this case, the decoder gets the incomplete or illegal payload, the decoder crashed in this situation.
Our mysql protocol decoder should be enhanced to process the illegal payload.

**Comment by lignay** [comment]
This fix will be retested to make sure matrixone service works well if hitting sniffers detecting on mysql protocol.

**Comment by reusee** [comment]
Decoders should pass the fuzz testing that generates random inputs to test decoders' resilience to bad inputs.
A fuzzer had been added to go in 1.18. See https://go.dev/blog/fuzz-beta for more details.

**Comment by lignay** [comment]
not found the issue, close it now. If hit again, will re-open it.
