### ISSUE TITLE
[Bug]: aliyun dev environment CN always crash because of some context deadline exceeded (with full CN log)

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#12063]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev-11d43b223
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="709" alt="image" src="https://github.com/matrixorigin/matrixone/assets/52204121/58901c7c-ea92-495a-ab0a-0b1681d69340">

```
{"level":"ERROR","time":"2023/10/11 02:10:14.182075 +0000","name":"cn-service.frontend","caller":"frontend/mysql_protocol.go:2724","msg":"failed to get extra info","uuid":"33613232-6431-3763-3834-313537303130","session_info":"connectionId 33492754|172.20.33.77:58134","session_id":"50889766-67db-11ee-9374-b6c5539867bc"}
{"level":"INFO","time":"2023/10/11 02:10:14.632350 +0000","name":"cn-service.txn","caller":"client/client.go:225","msg":"txn created txnclient.new exit","uuid":"33613232-6431-3763-3834-313537303130","options":"sql-executor"}
panic: context deadline exceeded

goroutine 330 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).bootstrap.func1({0x3593b38?, 0xc001c5a6c0?})
        /go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:701 +0x9d
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

### Expected Behavior

CN shoud not restart 

### Additional information

The environment is still there, and the full log is:
[cn.crash.1011.txt](https://github.com/matrixorigin/matrixone/files/12864169/cn.crash.1011.txt)

**Comment by daviszhen** [comment]
初步看时 错误`lz4: invalid source or destination buffer too short`，导致logtail 消费失败。
logtail订阅有问题，启动失败。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/1e547bb1-e63f-499f-9789-f63737bcefa3)

**Comment by sukki37** [comment]
seems related to #12051

**Comment by LeftHandCold** [comment]
fixed

**Comment by LeftHandCold** [comment]
Observe for a week before closing

**Comment by LeftHandCold** [comment]
fixed

**Comment by loveRhythm1990** [comment]
close since fixed
