### ISSUE TITLE
[Bug]: CN panic due to nil pointer when LoadCheckpointEntries

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12079]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2023-10-12 11:01:06 | panic: runtime error: invalid memory address or nil pointer dereference |  
-- | -- | --
  |   | 2023-10-12 11:01:06 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1cf30f0] |  
  |   | 2023-10-12 11:01:06 |   |  
  |   | 2023-10-12 11:01:06 | goroutine 40 [running]: |  
  |   | 2023-10-12 11:01:06 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.LoadCheckpointEntries({0x3593a90, 0xc001d57270}, {0xc000550380, 0x30c}, 0x1, {0xc00013ee51, 0xb}, 0x1, {0x0, 0x0}, ...) |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/handle.go:745 +0x7f0 |  
  |   | 2023-10-12 11:01:06 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeLogTailOfPushWithoutLazyLoad({0x3593a90, 0xc001d57270}, 0xb16?, 0xc0005b8000, 0x7f454c5d5ad0?, 0xc001929b08, 0x8?, 0xc000620000?, {0xc00013ee51, 0xb}) |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:1083 +0xc5 |  
  |   | 2023-10-12 11:01:06 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartitionOfPush({0x3593a90, 0xc001d57270}, 0x3?, 0xc0005b8000, 0xc001929b08, 0x0) |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:1040 +0x2c5 |  
  |   | 2023-10-12 11:01:06 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).consumeSubscribeResponse(0x412e99?, {0x3593a90?, 0xc001d57270?}, 0x0?, 0x53?) |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:999 +0xf6 |  
  |   | 2023-10-12 11:01:06 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.distributeSubscribeResponse({0x3593a90, 0xc001d57270}, 0xc0005b8000, 0x1?, {0xc001929f50, 0x4, 0x0?}) |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:782 +0x17b |  
  |   | 2023-10-12 11:01:06 | github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).receiveTableLogTailContinuously.func1() |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:294 +0x733 |  
  |   | 2023-10-12 11:01:06 | created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).receiveTableLogTailContinuously |  
  |   | 2023-10-12 11:01:06 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:263 +0x118
```

Raw log: 
[Explore-logs-2023-10-12 12_01_32.txt](https://github.com/matrixorigin/matrixone/files/12876868/Explore-logs-2023-10-12.12_01_32.txt)

**Comment by jiangxinmeng1** [comment]
下载ckp目录下的文件发现`0-0->1697065632756566408-1`的version是8，报错的CN的镜像版本是11d43b223，只更新到ver 7，没有解析的代码。可能是dn和cn的commit不同导致的。

ckp文件：
[ckpmeta.tar.gz](https://github.com/matrixorigin/matrixone/files/12893770/ckpmeta.tar.gz)

**Comment by jiangxinmeng1** [comment]
出错时，CN的版本低于DN，无法解析新DN送来的checkpoint文件。这个依赖向前兼容

**Comment by aylei** [comment]
follow up issue: https://github.com/matrixorigin/matrixone/issues/12150

**Comment by aylei** [comment]
closed as tracking in the tech request
