### ISSUE TITLE
[Bug]: CN panic: internal error: invalid txn error, code 20702, msg 20702: lock table bind changed

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12471]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN panic: `panic: internal error: invalid txn error, code 20702, msg 20702: lock table bind changed`

```
2023-11-01T13:51:41+08:00	panic: internal error: invalid txn error, code 20702, msg 20702: lock table bind changed
2023-11-01T13:51:41+08:00	
2023-11-01T13:51:41+08:00	goroutine 207 [running]:
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).checkTxnError(0xb3b?, 0xc0ab21d720, 0x100000002?)
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:903 +0x257
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).handleErrorResponse(0xc05e8ffb80, {0xb3b, 0xc06343cfc0, 0x2, 0x1, 0xc0ab21d720, 0xc02eb5eac0, 0xc161c7ef80, 0x0, 0x0, ...})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:832 +0x40a
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).handleError(0xc05e8ffb80?, 0xc0935dd1d0, {0x0?, 0x0?})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:808 +0x118
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).doWrite(0xc05e8ffb80, {0x35f0060, 0xc085d50540}, {0x0?, 0x0, 0x0}, 0x1)
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:652 +0x927
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Commit(0xc05e8ffb80, {0x35f0060, 0xc085d50540})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:468 +0x316
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*txnExecutor).commit(0x35c8d20?)
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/sql_executor.go:271 +0x92
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*sqlExecutor).ExecTxn(0x5d?, {0x35f0060?, 0xc085d50540?}, 0xc076e55260, {0x0, {0x0, 0x0}, {0x2f258e4, 0xa}, 0x0, ...})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/sql_executor.go:110 +0x145
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/incrservice.(*sqlStore).Allocate(0xc01bb65280, {0x35f0060?, 0xc085d50540}, 0x4280b, {0xc0b25aad10, 0xa}, 0x2dc6c0, {0x0, 0x0})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/store_sql.go:107 +0x50b
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).doAllocate(0xc00b502ff0, {{0x0, 0x0}, 0x0, 0x0, 0x4280b, {0xc0b25aad10, 0xa}, 0x2dc6c0, 0x0, ...})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:143 +0x108
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).run(0xc00b502ff0, {0x35f0098, 0xc00b503200})
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:130 +0x1c5
2023-11-01T13:51:41+08:00	github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
2023-11-01T13:51:41+08:00	created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
2023-11-01T13:51:41+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

rawlog:  [Explore-logs-2023-11-01 18_21_48.txt](https://github.com/matrixorigin/matrixone/files/13226613/Explore-logs-2023-11-01.18_21_48.txt)

### Expected Behavior

CN should not panic

**Comment by DanielZhangQD** [comment]
@zhangxu19830126 PTAL, thanks!

**Comment by zhangxu19830126** [comment]
fixed by 12525
