### ISSUE TITLE
[Bug]: CN report worker exits from panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12502]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): aafcfae1 (1.0-dev branch)
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN report panic:

```
2023-11-06T11:12:20+08:00	2023/11/06 03:12:20.225036 [ants]: worker exits from panic: runtime error: index out of range [0] with length 0
2023-11-06T11:12:20+08:00	goroutine 2030971 [running]:
2023-11-06T11:12:20+08:00	runtime/debug.Stack()
2023-11-06T11:12:20+08:00		/usr/local/go/src/runtime/debug/stack.go:24 +0x65
2023-11-06T11:12:20+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
2023-11-06T11:12:20+08:00	panic({0x2d73ae0, 0xc17094b3f8})
2023-11-06T11:12:20+08:00		/usr/local/go/src/runtime/panic.go:884 +0x213
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/catalog.DecodeBlockInfo(...)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/catalog/types.go:383
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).NewBlockReader(0xc001bce7e0, {0x35f0118?, 0xc1d1174d80}, 0x8, {0x1794e9e08ef74e53, 0x1, 0x0, {}, {0x0, 0x0, ...}, ...}, ...)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:445 +0xccf
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc1c75e3770, 0xc00028d900, 0x1)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:337 +0x3ab
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc1c75e3770?, 0xc00028d900?)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:188 +0x85
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:122 +0x5a
2023-11-06T11:12:20+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1()
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
2023-11-06T11:12:20+08:00	created by github.com/panjf2000/ants/v2.(*goWorker).run
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65
2023-11-06T11:12:20+08:00	
2023-11-06T11:12:20+08:00	2023/11/06 03:12:20.225245 [ants]: worker exits from panic: runtime error: index out of range [0] with length 0
2023-11-06T11:12:20+08:00	goroutine 2030969 [running]:
2023-11-06T11:12:20+08:00	runtime/debug.Stack()
2023-11-06T11:12:20+08:00		/usr/local/go/src/runtime/debug/stack.go:24 +0x65
2023-11-06T11:12:20+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
2023-11-06T11:12:20+08:00	panic({0x2d73ae0, 0xc17094b410})
2023-11-06T11:12:20+08:00		/usr/local/go/src/runtime/panic.go:884 +0x213
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/catalog.DecodeBlockInfo(...)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/catalog/types.go:383
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).NewBlockReader(0xc001bce7e0, {0x35f0118?, 0xc1d1174d80}, 0x5, {0x1794e9e08ef74e53, 0x1, 0x0, {}, {0x0, 0x0, ...}, ...}, ...)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:445 +0xccf
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc191512870, 0xc00028d900, 0x1)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:337 +0x3ab
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc191512870?, 0xc00028d900?)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:188 +0x85
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:122 +0x5a
2023-11-06T11:12:20+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1()
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
2023-11-06T11:12:20+08:00	created by github.com/panjf2000/ants/v2.(*goWorker).run
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65
2023-11-06T11:12:20+08:00	
2023-11-06T11:12:20+08:00	2023/11/06 03:12:20.225301 [ants]: worker exits from panic: runtime error: index out of range [0] with length 0
2023-11-06T11:12:20+08:00	goroutine 2030970 [running]:
2023-11-06T11:12:20+08:00	runtime/debug.Stack()
2023-11-06T11:12:20+08:00		/usr/local/go/src/runtime/debug/stack.go:24 +0x65
2023-11-06T11:12:20+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
2023-11-06T11:12:20+08:00	panic({0x2d73ae0, 0xc17094b428})
2023-11-06T11:12:20+08:00		/usr/local/go/src/runtime/panic.go:884 +0x213
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/catalog.DecodeBlockInfo(...)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/catalog/types.go:383
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).NewBlockReader(0xc001bce7e0, {0x35f0118?, 0xc1d1174d80}, 0x2, {0x1794e9e08ef74e53, 0x1, 0x0, {}, {0x0, 0x0, ...}, ...}, ...)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:445 +0xccf
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc191512a50, 0xc00028d900, 0x1)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:337 +0x3ab
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc191512a50?, 0xc00028d900?)
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:188 +0x85
2023-11-06T11:12:20+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
2023-11-06T11:12:20+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:122 +0x5a
2023-11-06T11:12:20+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1()
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
2023-11-06T11:12:20+08:00	created by github.com/panjf2000/ants/v2.(*goWorker).run
2023-11-06T11:12:20+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65
2023-11-06T11:12:20+08:00	
```

rawlog: [Explore-logs-2023-11-06 11_38_11.txt](https://github.com/matrixorigin/matrixone/files/13262215/Explore-logs-2023-11-06.11_38_11.txt)

### Expected Behavior

CN should not panic.

**Comment by triump2020** [comment]
being reproduce

**Comment by triump2020** [comment]
No reproduction

**Comment by triump2020** [comment]
@aylei  Pls close it or downgrade !

**Comment by aylei** [comment]
closing as no longer reproduced for 2 weeks

**Comment by aylei** [comment]
reopen if occurs again
