### ISSUE TITLE
[Bug]: cn restart reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12666]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-7244406e 1.0-dev
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1166" alt="企业微信截图_6301c8df-61e7-4a54-9da9-ec6fc3447d1f" src="https://github.com/matrixorigin/matrixone/assets/113406637/d3c9aa65-fb29-498d-9436-1dc938bf19de">
cn crash log:
[cncrash_moc.log](https://github.com/matrixorigin/matrixone/files/13316800/cncrash_moc.log)

{"level":"INFO","time":"2023/11/10 07:15:50.638991 +0000","caller":"motrace/syncer.go:89","msg":"Wait signal done."}
panic: found leak txn

goroutine 265 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x5?, 0x5?, {0x0?, 0x0?, 0xc0b6d9d8a0?})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc02cec7ee0, {0xc017c0af00, 0x5, 0x5})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Log(0xc0b6d9d6a0, {0x2f5533e, 0xe}, {{0x0, 0x0}, 0x5, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/log/logger.go:169 +0x44a
github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Fatal(0x2f4b123?, {0x2f5533e?, 0xc14b91b5189e716b?}, {0xc017c0af00?, 0x4d2e8e0?, 0x64?})
	/go/src/github.com/matrixorigin/matrixone/pkg/common/log/logger.go:137 +0x4e
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).getTxnClient.func1.1({0xc046fbe450, 0x10, 0xc01bf4d000?}, {0x0?, 0x0?, 0x4d2e8e0?}, {0xc046fb4300, 0xfd}, {0xc045f3a940, 0x39}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:576 +0x56b
github.com/matrixorigin/matrixone/pkg/txn/client.(*leakChecker).doCheck(0xc0005690e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/leak_checker.go:114 +0x2b2
github.com/matrixorigin/matrixone/pkg/txn/client.(*leakChecker).check(0xc0005690e0, {0x367e918, 0xc0017e18c0})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/leak_checker.go:98 +0x36
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5

**Comment by heni02** [comment]
cn crash log: 
[cncrash_moc.log](https://github.com/matrixorigin/matrixone/files/13316805/cncrash_moc.log)

**Comment by heni02** [comment]
same issue #11966  closed
