### ISSUE TITLE
[Bug]: frontend: MysqlProtocolImpl.GetRequest and handleHandshake failed in fuzz testing

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#1269]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1beb1aab164fc91b8d90f6e644bdddda88060fdd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
fuzz: elapsed: 0s, gathering baseline coverage: 0/2 completed
failure while testing seed corpus entry: FuzzMysqlProtocolGetRequest/caf81e9797b19c76c1fc4dbf537d4d81f389524539f402d13aa01f93a65ac7e9
fuzz: elapsed: 0s, gathering baseline coverage: 0/2 completed
--- FAIL: FuzzMysqlProtocolGetRequest (0.07s)
    --- FAIL: FuzzMysqlProtocolGetRequest (0.00s)
        testing.go:1320: panic: runtime error: slice bounds out of range [1:0]
            goroutine 221 [running]:
            runtime/debug.Stack()
            	/Users/reus/gotip/src/runtime/debug/stack.go:24 +0xa4
            testing.tRunner.func1()
            	/Users/reus/gotip/src/testing/testing.go:1320 +0x264
            panic({0x10504fc80, 0x140001f66f0})
            	/Users/reus/gotip/src/runtime/panic.go:838 +0x204
            github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).GetRequest(...)
            	/Users/reus/reusee/matrixone/pkg/frontend/protocol.go:169
            github.com/matrixorigin/matrixone/pkg/frontend.FuzzMysqlProtocolGetRequest.func1(0x140032ef718?, {0x105ea03f8?, 0x0?, 0x0?})
            	/Users/reus/reusee/matrixone/pkg/frontend/fuzz_test.go:8 +0x58
            reflect.Value.call({0x104e81280?, 0x105131f38?, 0x13?}, {0x104a5c6fe, 0x4}, {0x140032f22a0, 0x2, 0x2?})
            	/Users/reus/gotip/src/reflect/value.go:556 +0x5e4
            reflect.Value.Call({0x104e81280?, 0x105131f38?, 0x1400030c0d0?}, {0x140032f22a0, 0x2, 0x2})
            	/Users/reus/gotip/src/reflect/value.go:339 +0x98
            testing.(*F).Fuzz.func1.1(0x14000404b40?)
            	/Users/reus/gotip/src/testing/fuzz.go:331 +0x1b8
            testing.tRunner(0x140032d7380, 0x140001f0e10)
            	/Users/reus/gotip/src/testing/testing.go:1410 +0x110
            created by testing.(*F).Fuzz.func1
            	/Users/reus/gotip/src/testing/fuzz.go:320 +0x4cc


FAIL
exit status 1
FAIL	github.com/matrixorigin/matrixone/pkg/frontend	0.559s
```

### Expected Behavior

no crash

### Steps to Reproduce

```markdown
Add fuzz function:
fuzz_test.go

package frontend

import "testing"

func FuzzMysqlProtocolGetRequest(f *testing.F) {
	f.Fuzz(func(t *testing.T, payload []byte) {
		decoder := new(MysqlProtocolImpl)
		decoder.GetRequest(payload)
	})
}
```

Run fuzz test (requires go 1.18)

```
go test -fuzz . -run ignoretests
```
```


### Additional information

For more details about fuzz testing in go, check https://go.dev/blog/fuzz-beta

**Comment by reusee** [comment]
MysqlProtocolImpl.handleHandshake also failed in testing
```
func FuzzHandleHandshake(f *testing.F) {
	f.Fuzz(func(t *testing.T, payload []byte) {
		decoder := &MysqlProtocolImpl{
			ProtocolImpl: ProtocolImpl{
				io: NewIOPackage(true),
			},
		}
		decoder.handleHandshake(payload)
	})
}
```

```
fuzz: elapsed: 0s, gathering baseline coverage: 0/1 completed
failure while testing seed corpus entry: FuzzHandleHandshake/8727b16d337d7b8187433233f3a90099024e580a6ba319ea2bf539880c50bd7c
fuzz: elapsed: 0s, gathering baseline coverage: 0/1 completed
--- FAIL: FuzzHandleHandshake (0.07s)
    --- FAIL: FuzzHandleHandshake (0.00s)
        testing.go:1320: panic: runtime error: index out of range [2] with length 2
            goroutine 230 [running]:
            runtime/debug.Stack()
            	/Users/reus/gotip/src/runtime/debug/stack.go:24 +0xa4
            testing.tRunner.func1()
            	/Users/reus/gotip/src/testing/testing.go:1320 +0x264
            panic({0x106853c80, 0x1400021a150})
            	/Users/reus/gotip/src/runtime/panic.go:838 +0x204
            github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).analyseHandshakeResponse320(0x140032f5640, {0x14000047628, 0x2, 0x8})
            	/Users/reus/reusee/matrixone/pkg/frontend/mysql_protocol.go:763 +0x5ec
            github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).handleHandshake(0x140032f5640, {0x14000047628, 0x2, 0x8})
            	/Users/reus/reusee/matrixone/pkg/frontend/mysql_protocol.go:519 +0x33c
            github.com/matrixorigin/matrixone/pkg/frontend.FuzzHandleHandshake.func1(0x140032f5718?, {0x14000047628, 0x2, 0x8})
            	/Users/reus/reusee/matrixone/pkg/frontend/fuzz_test.go:21 +0x8c
            reflect.Value.call({0x106685280?, 0x106935f38?, 0x13?}, {0x1062606bc, 0x4}, {0x14000195cb0, 0x2, 0x2?})
            	/Users/reus/gotip/src/reflect/value.go:556 +0x5e4
            reflect.Value.Call({0x106685280?, 0x106935f38?, 0x14000185a00?}, {0x14000195cb0, 0x2, 0x2})
            	/Users/reus/gotip/src/reflect/value.go:339 +0x98
            testing.(*F).Fuzz.func1.1(0x1400018e060?)
            	/Users/reus/gotip/src/testing/fuzz.go:331 +0x1b8
            testing.tRunner(0x14000203520, 0x14000540ea0)
            	/Users/reus/gotip/src/testing/testing.go:1410 +0x110
            created by testing.(*F).Fuzz.func1
            	/Users/reus/gotip/src/testing/fuzz.go:320 +0x4cc


FAIL
exit status 1
FAIL	github.com/matrixorigin/matrixone/pkg/frontend	0.551s
```

**Comment by daviszhen** [comment]
it was done.
