### ISSUE TITLE
[Bug]: [date 11.30]standalone regression: sysbench 10w write_only test reported txn need retry in rc mode

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13152]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f8dba6beb64044147e6415497f2107a3fe347603
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7047590473/job/19182004660
<img width="1038" alt="企业微信截图_1f3aee30-e1da-42b1-8e36-041776c1805c" src="https://github.com/matrixorigin/matrixone/assets/113406637/74927793-59f0-42b9-a067-260fc9f96b58">

mo 日志：
[log.tar.gz](https://github.com/matrixorigin/matrixone/files/13520348/log.tar.gz)

**Comment by arjunsk** [comment]
Will start working on this issue after finding the root cause for panic error suppression in https://github.com/matrixorigin/MO-Cloud/issues/1881#issuecomment-1836814517

**Comment by arjunsk** [comment]
I think this issue is related to this PR:  https://github.com/matrixorigin/matrixone/pull/12926

@ouyuanning could you kindly look into this?

![image](https://github.com/matrixorigin/matrixone/assets/9638314/93191f95-0aef-4a8d-91b3-f7938b3e3be8)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/99426709-7dba-4216-a701-844811a81873)

**Comment by ouyuanning** [comment]
本地跑了一下还没复现。

**Comment by arjunsk** [comment]
Hi @ouyuanning , I think this could be due to, not having an exclusive lock on `mo_catalog.mo_indexes` during `create index ` flow.

**Comment by arjunsk** [comment]
Also, this commit is older than the latest fix for the secondary index.
https://github.com/arjunsk/matrixone/commit/6b25d558f10a3d3389cb541f1b484df4ca30643c

https://github.com/arjunsk/matrixone/commit/ff3857151c1a1d9b6f4d4c20e5f429939bbd6293


![image](https://github.com/matrixorigin/matrixone/assets/9638314/0a049ce8-e2cb-43a8-a1e0-a354815e02f6)

**Comment by arjunsk** [comment]
In my local kubernetes log service is crashing

```log
{"level":"INFO","time":"2023/12/05 23:28:41.605138 +0000","name":"raft","caller":"raft/raft.go:962","msg":"[f:1,l:537873,t:19,c:537873,a:0] [00000:31073] t19 became follower"}
{"level":"INFO","time":"2023/12/05 23:28:41.605161 +0000","name":"log-service","caller":"logservice/store_metadata.go:278","msg":"addMetadata for shardID 0 skipped, dupl shard","uuid":"00000000-0000-0000-0000-000000000001"}
{"level":"INFO","time":"2023/12/05 23:28:41.605227 +0000","name":"rsm","caller":"rsm/statemachine.go:281","msg":"[00000:31073] no snapshot available during launch"}
{"level":"INFO","time":"2023/12/05 23:28:41.605271 +0000","name":"dragonboat","caller":"v4@v4.0.0-20230426084722-d189534f8004/node.go:1552","msg":"[00000:31073] initialized using <00000:31073:0>"}
{"level":"INFO","time":"2023/12/05 23:28:41.605283 +0000","name":"dragonboat","caller":"v4@v4.0.0-20230426084722-d189534f8004/node.go:1436","msg":"[00000:31073] initial index set to 0"}
{"level":"INFO","time":"2023/12/05 23:28:41.605290 +0000","name":"log-service","caller":"logservice/store.go:223","msg":"HAKeeper ticker started","uuid":"00000000-0000-0000-0000-000000000001","process":"system-init"}
{"level":"INFO","time":"2023/12/05 23:28:41.605317 +0000","name":"log-service","caller":"logservice/store.go:782","msg":"Hakeeper interval configs","uuid":"00000000-0000-0000-0000-000000000001","HAKeeperTickInterval":100000000,"HAKeeperCheckInterval":3000000000}
{"level":"INFO","time":"2023/12/05 23:28:41.605719 +0000","name":"tan","caller":"tan/open.go:63","msg":"/var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/mo-log-1/08850055262063083118/tandb/node-1-262145 loading an existing tan db"}
{"level":"INFO","time":"2023/12/05 23:28:41.605995 +0000","name":"tan","caller":"tan/open.go:76","msg":"/var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/mo-log-1/08850055262063083118/tandb/node-1-262145 on disk files [000064.index 000079.index 000071.index 000004.log 000004.index 000051.index 000059.log 000077.log 000068.log 000070.index 000060.index 000049.log 000067.index 000068.index 000026.index 000052.log 000064.log 000051.log 000056.log 000036.log 000073.log 000050.log 000046.log 000072.log 000069.index CURRENT 000074.index 000047.index 000054.index 000079.log 000026.log 000036.index 000074.log 000065.index 000053.log 000062.index 000047.log 000057.index 000046.index 000075.index 000065.log 000054.log 000073.index 000049.index 000069.log 000053.index 000070.log 000050.index 000066.index 000061.index 000059.index 000060.log 000052.index 000044.index MANIFEST-000082 000072.index 000055.index 000066.log 000042.log 000063.index 000063.log 000081.log 000055.log 000058.log 000058.index 000061.log 000057.log 000071.log 000044.log 000056.index 000042.index 000067.log 000077.index 000075.log 000062.log]"}
{"level":"INFO","time":"2023/12/05 23:28:41.613773 +0000","name":"tan","caller":"tan/open.go:132","msg":"/var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/mo-log-1/08850055262063083118/tandb/node-1-262145 logFiles to rebuild: map[000081:{81 000081.log}]"}
{"level":"INFO","time":"2023/12/05 23:28:41.613806 +0000","name":"tan","caller":"tan/open.go:133","msg":"/var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/mo-log-1/08850055262063083118/tandb/node-1-262145 indexFiles: [{4 000004.index} {26 000026.index} {36 000036.index} {42 000042.index} {44 000044.index} {46 000046.index} {47 000047.index} {49 000049.index} {50 000050.index} {51 000051.index} {52 000052.index} {53 000053.index} {54 000054.index} {55 000055.index} {56 000056.index} {57 000057.index} {58 000058.index} {59 000059.index} {60 000060.index} {61 000061.index} {62 000062.index} {63 000063.index} {64 000064.index} {65 000065.index} {66 000066.index} {67 000067.index} {68 000068.index} {69 000069.index} {70 000070.index} {71 000071.index} {72 000072.index} {73 000073.index} {74 000074.index} {75 000075.index} {77 000077.index} {79 000079.index}]"}
{"level":"INFO","time":"2023/12/05 23:28:41.613815 +0000","name":"tan","caller":"tan/open.go:201","msg":"/var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/mo-log-1/08850055262063083118/tandb/node-1-262145 rebuildLogAndIndex, logNum 81"}
{"level":"INFO","time":"2023/12/05 23:28:41.618263 +0000","name":"dragonboat","caller":"v4@v4.0.0-20230426084722-d189534f8004/node.go:668","msg":"[00001:62145] replaying raft logs"}
{"level":"PANIC","time":"2023/12/05 23:28:41.618452 +0000","name":"dragonboat","caller":"v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:2230","msg":"[00001:62145] ReadRaftState failed: zeroed chunk\n(1) attached stack trace\n  -- stack trace:\n  | github.com/lni/dragonboat/v4.(*node).replayLog\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:683\n  | github.com/lni/dragonboat/v4.(*node).startRaft\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:368\n  | github.com/lni/dragonboat/v4.newNode\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:212\n  | github.com/lni/dragonboat/v4.(*NodeHost).startShard\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:1654\n  | github.com/lni/dragonboat/v4.(*NodeHost).StartReplica\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:508\n  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplica\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:241\n  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplicas\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:204\n  | github.com/matrixorigin/matrixone/pkg/logservice.NewService\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:125\n  | main.startLogService\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:320\n  | main.startService\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:208\n  | main.main\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109\n  | runtime.main\n  | \t/usr/local/go/src/runtime/proc.go:250\nWraps: (2) [00001:62145] ReadRaftState failed\nWraps: (3) attached stack trace\n  -- stack trace:\n  | github.com/lni/dragonboat/v4/internal/tan.(*db).readLog\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/db.go:416\n  | github.com/lni/dragonboat/v4/internal/tan.(*db).getRaftState\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/db.go:235\n  | github.com/lni/dragonboat/v4/internal/tan.(*LogDB).ReadRaftState\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/logdb.go:367\n  | github.com/lni/dragonboat/v4.(*node).replayLog\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:678\n  | github.com/lni/dragonboat/v4.(*node).startRaft\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:368\n  | github.com/lni/dragonboat/v4.newNode\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:212\n  | github.com/lni/dragonboat/v4.(*NodeHost).startShard\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:1654\n  | github.com/lni/dragonboat/v4.(*NodeHost).StartReplica\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:508\n  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplica\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:241\n  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplicas\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:204\n  | github.com/matrixorigin/matrixone/pkg/logservice.NewService\n  | \t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:125\n  | main.startLogService\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:320\n  | main.startService\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:208\n  | main.main\n  | \t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109\n  | [...repeated from below...]\nWraps: (4) attached stack trace\n  -- stack trace:\n  | github.com/lni/dragonboat/v4/internal/tan.init\n  | \t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/record.go:141\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6525\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6502\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6502\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6502\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6502\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6502\n  | runtime.main\n  | \t/usr/local/go/src/runtime/proc.go:233\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_arm64.s:1172\nWraps: (5) zeroed chunk\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *withstack.withStack (5) *errutil.leafError","stacktrace":"github.com/lni/dragonboat/v4.panicNow\n\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:2230\ngithub.com/lni/dragonboat/v4.(*NodeHost).startShard\n\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:1672\ngithub.com/lni/dragonboat/v4.(*NodeHost).StartReplica\n\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:508\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplica\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:241\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplicas\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:204\ngithub.com/matrixorigin/matrixone/pkg/logservice.NewService\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:125\nmain.startLogService\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:320\nmain.startService\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:208\nmain.main\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"INFO","time":"2023/12/05 23:28:41.621354 +0000","caller":"motrace/syncer.go:89","msg":"Wait signal done."}
panic: [00001:62145] ReadRaftState failed: zeroed chunk
(1) attached stack trace
  -- stack trace:
  | github.com/lni/dragonboat/v4.(*node).replayLog
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:683
  | github.com/lni/dragonboat/v4.(*node).startRaft
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:368
  | github.com/lni/dragonboat/v4.newNode
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:212
  | github.com/lni/dragonboat/v4.(*NodeHost).startShard
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:1654
  | github.com/lni/dragonboat/v4.(*NodeHost).StartReplica
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:508
  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplica
  |     /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:241
  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplicas
  |     /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:204
  | github.com/matrixorigin/matrixone/pkg/logservice.NewService
  |     /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:125
  | main.startLogService
  |     /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:320
  | main.startService
  |     /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:208
  | main.main
  |     /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109
  | runtime.main
  |     /usr/local/go/src/runtime/proc.go:250
Wraps: (2) [00001:62145] ReadRaftState failed
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/lni/dragonboat/v4/internal/tan.(*db).readLog
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/db.go:416
  | github.com/lni/dragonboat/v4/internal/tan.(*db).getRaftState
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/db.go:235
  | github.com/lni/dragonboat/v4/internal/tan.(*LogDB).ReadRaftState
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/logdb.go:367
  | github.com/lni/dragonboat/v4.(*node).replayLog
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:678
  | github.com/lni/dragonboat/v4.(*node).startRaft
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:368
  | github.com/lni/dragonboat/v4.newNode
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/node.go:212
  | github.com/lni/dragonboat/v4.(*NodeHost).startShard
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:1654
  | github.com/lni/dragonboat/v4.(*NodeHost).StartReplica
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:508
  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplica
  |     /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:241
  | github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplicas
  |     /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:204
  | github.com/matrixorigin/matrixone/pkg/logservice.NewService
  |     /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:125
  | main.startLogService
  |     /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:320
  | main.startService
  |     /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:208
  | main.main
  |     /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109
  | [...repeated from below...]
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/lni/dragonboat/v4/internal/tan.init
  |     /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/tan/record.go:141
  | runtime.doInit
  |     /usr/local/go/src/runtime/proc.go:6525
  | runtime.doInit
  |     /usr/local/go/src/runtime/proc.go:6502
  | runtime.doInit
  |     /usr/local/go/src/runtime/proc.go:6502
  | runtime.doInit
  |     /usr/local/go/src/runtime/proc.go:6502
  | runtime.doInit
  |     /usr/local/go/src/runtime/proc.go:6502
  | runtime.doInit
  |     /usr/local/go/src/runtime/proc.go:6502
  | runtime.main
  |     /usr/local/go/src/runtime/proc.go:233
  | runtime.goexit
  |     /usr/local/go/src/runtime/asm_arm64.s:1172
Wraps: (5) zeroed chunk
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *withstack.withStack (5) *errutil.leafError

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x40077acfa8?, 0x0?, 0x0?})
        /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x78
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x40016ae000, {0x0, 0x0, 0x0})
        /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x2bc
go.uber.org/zap.(*SugaredLogger).log(0x400012a1c0, 0x4, {0x34a0ed2?, 0x2ef3080?}, {0x4004aec9f0?, 0x3c7f4f8?, 0x4001c901e0?}, {0x0, 0x0, 0x0})
        /go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xe8
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:189
github.com/matrixorigin/matrixone/pkg/logutil.DragonboatAdaptLogger.Panicf(...)
        /go/src/github.com/matrixorigin/matrixone/pkg/logutil/dragonboat.go:65
github.com/lni/dragonboat/v4/logger.(*dragonboatLogger).Panicf(0x40001?, {0x34a0ed2, 0x3}, {0x4004aec9f0, 0x1, 0x1})
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/logger/logger.go:132 +0x54
github.com/lni/dragonboat/v4.panicNow(...)
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:2230
github.com/lni/dragonboat/v4.(*NodeHost).startShard(0x40006cbc00, 0x0, 0x0, 0x40077ad8f8?, {0x40001, 0x1, 0x1, 0x1, 0xa, 0x1, ...}, ...)
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:1672 +0x9a0
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica(0x0?, 0x0?, 0xb0?, 0x40006fa220?, {0x40001, 0x1, 0x1, 0x1, 0xa, 0x1, ...})
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/nodehost.go:508 +0xa0
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplica(0x4003cd4000, 0x1, 0x40001, 0x40016a4000?, 0x40?)
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:241 +0x13c
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startReplicas(0x4003cd4000)
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:204 +0x1d4
github.com/matrixorigin/matrixone/pkg/logservice.NewService({{0x3caeb00, 0x57de620}, 0x7ad1b65f09d8be6e, {0x4000054cc0, 0x24}, 0xc8, {0x4001928050, 0x4c}, {0x40006a4080, 0x7c}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:125 +0x460
main.startLogService(0x400174e000, 0x4000120000?, {0x3c8b780, 0x40000f00c0}, 0x3?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:320 +0x1c4
main.startService({0x3c65328, 0x4000120000}, 0x400174e000, 0x400174e000?, 0x40000846c8?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:208 +0x470
main.main()
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109 +0x2a0
➜  matrixone-operator git:(main) ✗ 


```

**Comment by ouyuanning** [comment]
等PR合并

**Comment by arjunsk** [comment]
I think we should be pushing this change to 1.0-dev and 1.1-dev.

**Comment by ouyuanning** [comment]
> We should cherry-pick this change to 1.0-dev and 1.1-dev.

Yes，I will cherry-pick it after PR is merged.

**Comment by ouyuanning** [comment]
这个依赖共享锁，1.0还没有这个功能，所以没有cherry-pick到1.0

**Comment by heni02** [comment]
confrim,closed
commit id：e89d3de2fcaf7984501e2fb3cb79d584be632c63
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7182582014
<img width="1408" alt="企业微信截图_8eb5f82b-bb39-4809-bbeb-d700d8d563ca" src="https://github.com/matrixorigin/matrixone/assets/113406637/6aae8370-a942-4dd0-96a6-3b17cc9f1acc">
