### ISSUE TITLE
[Bug]: system/system.go:74 failed to get cgroup stats

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#13170]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.1-dev
- Hardware parameters:
- OS type: running on Kubernetes (minikube)
- Others:
```

### Actual Behavior

```error
➜  matrixone-operator git:(main) ✗ kubectl -n mo logs mo-log-0 
/mo-service -cfg /tmp/tmp.PPQtAtmv8J -debug-http=:6060
2023/12/01 20:25:43.508801 +0000 ERROR system/system.go:74 failed to get cgroup stats: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19b9bfc]

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/common/system.init.0()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/system/system.go:231 +0x8c

```

### Expected Behavior

Execute without any error

### Steps to Reproduce

1. install minikube
```shell
install minikube https://minikube.sigs.k8s.io/docs/start/
minikube start
```

2. Install MatrixOne Operator 
```shell
helm repo add matrixone-operator https://matrixorigin.github.io/matrixone-operator
helm repo update
helm install mo matrixone-operator/matrixone-operator --version=1.0.0-alpha.1
```

3. Deploy MatrixOne Cluster

3.a
```shell
kubectl apply -f https://raw.githubusercontent.com/matrixorigin/matrixone-operator/main/examples/minio.yaml
NS=mo
kubectl create ns ${NS}
kubectl -n ${NS} create secret generic minio --from-literal=AWS_ACCESS_KEY_ID=minio --from-literal=AWS_SECRET_ACCESS_KEY=minio123
```

3.b Update docker image
```
curl https://raw.githubusercontent.com/matrixorigin/matrixone-operator/main/examples/mo-cluster.yaml | sed 's/#TAG/1.0.0-rc1/g' > mo.yaml

# modify the version to night builds in docker.com
# https://hub.docker.com/layers/matrixorigin/matrixone/nightly-f8dba6be/images/sha256-41b9099ec0fd3e71dfc1dc670290d18211f568a05945cf74e81736322f4093ce?context=explore

# or build docker image locally
# docker build -t arjunsk15/matrixone:local -f ./optools/images/Dockerfile .
# docker push arjunsk15/matrixone:local

kubectl -n ${NS} apply -f mo.yaml
kubectl -n mo get matrixonecluster
kubectl -n mo get pod
nohup kubectl -n mo port-forward svc/mo-tp-cn 6001:6001 &
mysql -h 127.0.0.1 -P 6001 -udump -p111

```

4. Error message
```shell
➜  matrixone-operator git:(main) ✗ kubectl -n mo get pod 
NAME       READY   STATUS    RESTARTS   AGE
mo-log-0   0/1     Error     0          11s
mo-log-1   1/1     Running   0          10s
mo-log-2   1/1     Running   0          10s

➜  matrixone-operator git:(main) ✗ kubectl -n mo logs mo-log-0
/mo-service -cfg /tmp/tmp.v8ooRsVW7P -debug-http=:6060
2023/12/01 20:36:59.244864 +0000 ERROR system/system.go:74 failed to get cgroup stats: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1912218]

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/common/system.init.0()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/system/system.go:244 +0x118

```

### Additional information

https://github.com/matrixorigin/matrixone-operator/blob/main/docs/getting_started.md

**Comment by volgariver6** [comment]
the cgroup is v2 in the container, so the v2 version should be supported by the package. I will fix it.

**Comment by volgariver6** [comment]
fixed

**Comment by arjunsk** [comment]
@volgariver6 I think this issue is there is 1.1-dev as well. Please do a cherry-pick there.

**Comment by arjunsk** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/9638314/72bc61c6-0745-43b0-875c-288d98e91553)


![image](https://github.com/matrixorigin/matrixone/assets/9638314/fb029840-dad8-4672-a2fd-01e2f7bbce50)
