### ISSUE TITLE
[Bug]:  mo hung during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13203]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b97d1318b301e231596b69e5b85c8c961eb47b00
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Account creation has not been successful for 6 hours. https://github.com/matrixorigin/matrixone/actions/runs/7084116628

[gp5s9-goroutine.log](https://github.com/matrixorigin/matrixone/files/13547869/gp5s9-goroutine.log)
[hwcr4-goroutine.log](https://github.com/matrixorigin/matrixone/files/13547874/hwcr4-goroutine.log)

Part of go stack is
```
goroutine 26659 [select, 334 minutes]:
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).Get(0xc01d448c80)
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:78 +0xe5
github.com/matrixorigin/matrixone/pkg/lockservice.(*client).Send(0xc001d499e0, {0x42158f8, 0xc028d00c00}, 0x0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:93 +0x106
github.com/matrixorigin/matrixone/pkg/lockservice.(*remoteLockTable).lock(0xc0043a8400, {0x42158f8, 0xc028d00c00}, 0xc0250e8af0, {0xc031476e88, 0x1, 0x1}, {{0x0, 0x0, 0x0, ...}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_remote.go:91 +0x41d
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(_, {_, _}, _, {_, _, _}, {0xc03db4dc10, 0x10, 0x10}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:130 +0x510
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock({0x42158f8, 0xc028d00c00}, 0x0?, {0x4249020, 0xc0049a97c0}, 0x0?, 0xc0259d6600, 0xc01bfacaa0, {0x3d, 0x0, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:426 +0x6e4
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockRows({0x4249020, 0xc0049a97c0}, 0xc0259d6600, 0x2a8a220?, 0xc031476e40?, {0x3d, 0x0, 0x0, 0x0, 0x18, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:331 +0x2e5
github.com/matrixorigin/matrixone/pkg/sql/compile.lockRows({0x4249020, 0xc0049a97c0}, 0xc0259d6600, {0x426a960?, 0xc009c6ddc0?}, 0xc01bfacaa0, 0x28d2da70?)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:2404 +0xaa
github.com/matrixorigin/matrixone/pkg/sql/compile.lockMoTable(0xc011cf4580, {0x3a5422b, 0xa}, {0xc0001e650d, 0xa}, 0x4268550?)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:2515 +0x19b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).CreateTable(0xc02800cb40, 0xc011cf4580)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:637 +0x193c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc011cf4580, 0xc02800cb40)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:354 +0x38b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:509 +0x79
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65
```

### Additional information

New connection works well.

**Comment by zhangxu19830126** [comment]
fixed by #13209

**Comment by zhangxu19830126** [comment]
It's caused by a dead loop to allocate new increment value, but failed in many hours. This only fix hung, and add max retry times for allocate, if failed return error.  Why allocate failed is another problem

**Comment by sukki37** [comment]
not repro for a few days
