### ISSUE TITLE
[Bug]: panic: failed to sync shards metadata

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#1349]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 77f928d5f686b88b5bde0144ea49d5d3ab99ddfb from https://github.com/jiangxinmeng1/matrixone-1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

saving metadata into AOE caused the following error - 

"error":"rename /Users/lni/src/matrixone/pkg/vm/driver/test/test/TestSnapshot/30366000/node-2/aoe/data/11_11_11_1-11:1:2:3:0:1:1.tblk.tmp /Users/lni/src/matrixone/pkg/vm/driver/test/test/TestSnapshot/30366000/node-2/aoe/data/11_11_11_1-11:1:2:3:0:1:1.tblk: no such file or directory",

more details - 

```
{"level":"fatal","ts":"2021-12-10 21:14:05.105","logger":"cube.store","caller":"raftstore/replica_create.go:162","msg":"failed to sync shards metadata","case":"TestSnapshot","store":"node-2","reason":"event","error":"rename /Users/lni/src/matrixone/pkg/vm/driver/test/test/TestSnapshot/30366000/node-2/aoe/data/11_11_11_1-11:1:2:3:0:1:1.tblk.tmp /Users/lni/src/matrixone/pkg/vm/driver/test/test/TestSnapshot/30366000/node-2/aoe/data/11_11_11_1-11:1:2:3:0:1:1.tblk: no such file or directory","stacktrace":"github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).maybeSaveMetadata.func1\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:162\ngithub.com/matrixorigin/matrixcube/raftstore.doWithShardsByGroupID\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:254\ngithub.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).maybeSaveMetadata\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:130\ngithub.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).create\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:93\ngithub.com/matrixorigin/matrixcube/raftstore.(*store).doDynamicallyCreate\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/store_route_handler.go:36\ngithub.com/matrixorigin/matrixcube/raftstore.(*store).startRouter.func1\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/store.go:271\ngithub.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).updateShardLocked\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/router.go:313\ngithub.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).handleEvent\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/router.go:276\ngithub.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).eventLoop\n\t/Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/router.go:249\ngithub.com/lni/goutils/syncutil.(*Stopper).runWorker.func1\n\t/Users/lni/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79"}
2021/12/10 21:14:05.105773 +0800 INFO shard/proxy.go:294 Shard-11 | pending-0, safeid-1, lastsafeid-0 | 5.25µs
panic: failed to sync shards metadata

goroutine 1408 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x1400ebf60c0, {0x14013a0fb40, 0x1, 0x1})
  /Users/lni/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x3c8
go.uber.org/zap.(*Logger).Fatal(0x1400bdf4ba0, {0x1013830d9, 0x1e}, {0x14013a0fb40, 0x1, 0x1})
  /Users/lni/go/pkg/mod/go.uber.org/zap@v1.19.1/logger.go:241 +0x68
github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).maybeSaveMetadata.func1({0x101943380, 0x140004de930}, {0x14013a9b400, 0x1, 0x1})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:162 +0x2f8
github.com/matrixorigin/matrixcube/raftstore.doWithShardsByGroupID(0x1400f76ed88, 0x1400f76ed78, {0x14013a9b300, 0x1, 0x1})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:254 +0xd4
github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).maybeSaveMetadata(0x1400f76ef50, {0x14013a9b300, 0x1, 0x1})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:130 +0x80
github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).create(0x1400f76ef50, {0x1400f76f050, 0x1, 0x1})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/replica_create.go:93 +0x94
github.com/matrixorigin/matrixcube/raftstore.(*store).doDynamicallyCreate(0x1400766a1a0, {0x42, {0x1401353f110, 0xc, 0x10}, {0x1401353f120, 0xc, 0x10}, {0x3, 0x0, ...}, ...})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/store_route_handler.go:36 +0x168
github.com/matrixorigin/matrixcube/raftstore.(*store).startRouter.func1({0x42, {0x1401353f110, 0xc, 0x10}, {0x1401353f120, 0xc, 0x10}, {0x3, 0x0, {}, ...}, ...})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/store.go:271 +0x4c
github.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).updateShardLocked(0x1400df7e850, {0x1400f9524b0, 0x48, 0x50}, 0x0, 0x0, 0x1)
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/router.go:313 +0x1d0
github.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).handleEvent(0x1400df7e850, {0x1c, 0x4, 0x0, 0x1400ebe5400, 0x0, 0x0, 0x0, {}, {0x0, ...}, ...})
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/router.go:276 +0x4b0
github.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).eventLoop(0x1400df7e850)
  /Users/lni/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211210130057-aa7ce2578f73/raftstore/router.go:249 +0x98
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1(0x14000012100, 0x1400df6f270, {0x0, 0x0}, 0x1400e7686f0)
  /Users/lni/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79 +0xc0
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
  /Users/lni/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:74 +0x88
FAIL  github.com/matrixorigin/matrixone/pkg/vm/driver/test  21.690s
FAIL
```

### Expected Behavior

No error. 

### Steps to Reproduce

```markdown
Run TestSnapshot from the SnapshotUT branch of https://github.com/jiangxinmeng1/matrixone-1.
```

### Additional information

data folder. 

[test.tar.gz](https://github.com/matrixorigin/matrixone/files/7693589/test.tar.gz)

**Comment by XuPeng-SH** [comment]
should be fixed by #1389
