### ISSUE TITLE
[Bug]: "unexpect error: EOF" in AOE

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#1371]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 017b1eb3c5e5cdfcf0e73bf1f738359051173c0d from //github.com/jiangxinmeng1/matrixone-1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Got the following error when running the test TestSnapshot using the above mentioned version. 

```
panic: unexpect error: EOF

goroutine 825 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/layout/dataio.(*BlockFile).initPointers(0x14011318510, {0x4, 0x4, 0x4, 0x0, 0x0, 0x0})
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/layout/dataio/blk.go:134 +0xecc
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/layout/dataio.NewBlockFile({0x1045fc7a0, 0x1400f2f6cb0}, {0x4, 0x4, 0x4, 0x0, 0x0, 0x0}, 0x14009a37b50)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/layout/dataio/blk.go:89 +0x320
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/layout/dataio.newVersionBlockFile(0x1, {0x1401133a0e0, 0xd}, {0x1045fc7a0, 0x1400f2f6cb0}, {0x4, 0x4, 0x4, 0x0, 0x0, ...})
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/layout/dataio/tblk.go:51 +0x8c
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/layout/dataio.(*TransientBlockFile).Sync(0x14010eced00, {0x1045e6a00, 0x14010ed15c0}, 0x14010ee9ce0)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/layout/dataio/tblk.go:282 +0x454
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/mutation.blockFlusher.flush(...)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/mutation/blk.go:32
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/mutation.(*MutableBlockNode).Flush(0x1400d65ac30)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/mutation/blk.go:102 +0x3c0
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/layout/table/v1.(*tableAppender).Flush(0x14010527450)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/layout/table/v1/appender.go:66 +0x1cc
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*DB).DoFlushTable(0x140001fa2d0, 0x14010f786c0)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/db/impl.go:81 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*DB).DoFlushDatabase(0x140001fa2d0, 0x14010243a80)
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/db/impl.go:43 +0x114
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*DB).FlushDatabase(0x140001fa2d0, {0x10406d792, 0x2})
  /Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/db/db.go:123 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).SaveShardMetadata(0x1400051e630, {0x1400ef24900, 0x1, 0x1})
  /Users/lni/src/matrixone/pkg/vm/driver/aoe/storage.go:649 +0x534
github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).maybeSaveMetadata.func1({0x1045f3780, 0x1400051e630}, {0x14010f617a0, 0x1, 0x1})
  /Users/lni/src/matrixcube/raftstore/replica_create.go:155 +0xa0
github.com/matrixorigin/matrixcube/raftstore.doWithShardsByGroupID(0x14009a38c88, 0x14009a38c78, {0x14010f61680, 0x1, 0x1})
  /Users/lni/src/matrixcube/raftstore/replica_create.go:254 +0xd4
github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).maybeSaveMetadata(0x14009a38e68, {0x14010f61680, 0x1, 0x1})
  /Users/lni/src/matrixcube/raftstore/replica_create.go:130 +0x80
github.com/matrixorigin/matrixcube/raftstore.(*replicaCreator).create(0x14009a38e68, {0x14009a38f68, 0x1, 0x1})
  /Users/lni/src/matrixcube/raftstore/replica_create.go:93 +0x94
github.com/matrixorigin/matrixcube/raftstore.(*store).doDynamicallyCreate(0x140003b8e00, {0x2e, {0x14010221b30, 0xc, 0x10}, {0x14010221b40, 0xc, 0x10}, {0x3, 0x0, ...}, ...})
  /Users/lni/src/matrixcube/raftstore/store_route_handler.go:36 +0x164
github.com/matrixorigin/matrixcube/raftstore.(*store).startRouter.func1({0x2e, {0x14010221b30, 0xc, 0x10}, {0x14010221b40, 0xc, 0x10}, {0x3, 0x0, {}, ...}, ...})
  /Users/lni/src/matrixcube/raftstore/store.go:280 +0x4c
github.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).updateShardLocked(0x140001f5ce0, {0x1400e37eb40, 0x47, 0x50}, 0x0, 0x0, 0x1)
  /Users/lni/src/matrixcube/raftstore/router.go:313 +0x1d0
github.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).handleEvent(0x140001f5ce0, {0x1d, 0x4, 0x0, 0x1400f402910, 0x0, 0x0, 0x0, {}, {0x0, ...}, ...})
  /Users/lni/src/matrixcube/raftstore/router.go:276 +0x4b0
github.com/matrixorigin/matrixcube/raftstore.(*defaultRouter).eventLoop(0x140001f5ce0)
  /Users/lni/src/matrixcube/raftstore/router.go:249 +0x98
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1(0x140003dc140, 0x14009c6e488, {0x0, 0x0}, 0x1400ad5e460)
  /Users/lni/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79 +0xc0
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
  /Users/lni/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:74 +0x88
exit status 2
FAIL  github.com/matrixorigin/matrixone/pkg/vm/driver/test  21.267s
```

### Expected Behavior

No error. 

### Steps to Reproduce

```markdown
Run TestSnapshot using the above mentioned version.
```

**Comment by JinHai-CN** [comment]
Can't reproduce and move the issue to backlog.

**Comment by XuPeng-SH** [comment]
close now. reopen if it can be reproduced again
