### ISSUE TITLE
[Bug]: panic: init db id pool failed. message:"stale command" staleCommand:<>

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#1411]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8ca0d2288dafd9e1b8e7669235cff013874f5fc6 with cube updated to 7a8cc2393f640107ae82ce166f61667760ead412 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"debug","ts":"2021-12-16 11:48:36.179","logger":"cube","caller":"server/server.go:224","msg":"error response received","request-id":"aedeb5cd9f8d42518a06a05b49705e81","error":"message:\"stale command\" staleCommand:<> "}
2021/12/16 11:48:36.179331 +0800 DEBUG driver/cube_driver.go:783 Exec of Incr cost 9748 ms
panic: init db id pool failed. message:"stale command" staleCommand:<>

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/catalog.NewCatalog({0x1041e7040, 0x14005ac9280})
	/Users/lni/src/matrixone/pkg/catalog/catalog.go:181 +0x368
main.main()
	/Users/lni/src/matrixone/cmd/db-server/main.go:265 +0x11a0
```

### Expected Behavior

No error. 

### Steps to Reproduce

```markdown
Change MO's configuration to let compaction to be checked every 1-2s, compaction threshold is set to 1. 
start MO.
load some data into MO.
ctrl+c to stop the MO.
repeat the above steps multiple times.
```

**Comment by LeftHandCold** [comment]
Fixed at #1406
