### ISSUE TITLE
[Bug]: SIGSEGV in aoe/storage/metadata/v1/base.go

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#1414]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bc3e3555ef78b263ac84b3dbd42e06bd6e0f1f3b using cube version f10b144cd98ba056e4dc454d8e577f5b8d5aa677
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"DEBUG","time":"2021/12/16 14:00:15.335064 +0800","caller":"logutil/internal.go:39","msg":"MO logger init, level=debug, log file="}
{"level":"INFO","time":"2021/12/16 14:00:15.335716 +0800","caller":"db-server/main.go:179","msg":"Shutdown The Server With Ctrl+C | Ctrl+\\."}
{"level":"INFO","time":"2021/12/16 14:00:15.471734 +0800","caller":"logstore/rotational.go:177","msg":"New version 0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1058a65e0]

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.(*BaseEntry).HasCommittedLocked(...)
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/base.go:129
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.(*BaseEntry).CommitLocked(0x0, 0xb6)
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/base.go:278 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.(*catalogReplayer).onReplayEntry(0x140036e4520, {0x106264f58, 0x1400368cf60}, {0x106226258, 0x14002f19860})
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/replayer.go:350 +0x1650
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.(*catalogReplayer).doReplay(0x140036e4520, 0x1400320ad20, {0x106226258, 0x14002f19860})
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/replayer.go:290 +0x254
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/logstore.(*Rotational).ReplayVersions(0x14002f19860, 0x140036e6270)
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/logstore/rotational.go:191 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/logstore.(*store).ReplayVersions(0x14002f077a0, 0x140036e6270)
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/logstore/types.go:141 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.(*catalogReplayer).Replay(0x140036e4520, {0x12eae2b40, 0x14002f07780})
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/replayer.go:301 +0x7c
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.(*catalogReplayer).RebuildCatalogWithDriver(0x140036e4520, 0x140000410f8, 0x140036e2990, {0x106263a60, 0x14002f07780}, {0x106260af8, 0x14002f07800})
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/replayer.go:250 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/metadata/v1.OpenCatalogWithDriver(0x140000410f8, 0x140036e2990, {0x106263a60, 0x14002f07780}, {0x106260af8, 0x14002f07800})
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/metadata/v1/catalog.go:81 +0x120
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.Open({0x140036e0360, 0xb}, 0x140030f8900)
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/db/open.go:107 +0xa00
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/aoedb/v1.Open({0x140036e0360, 0xb}, 0x140030f8900)
	/Users/lni/src/matrixone/pkg/vm/engine/aoe/storage/aoedb/v1/open.go:23 +0x38
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.NewStorageWithOptions({0x140036e0360, 0xb}, 0x140030f8900)
	/Users/lni/src/matrixone/pkg/vm/driver/aoe/storage.go:79 +0x38
main.main()
	/Users/lni/src/matrixone/cmd/db-server/main.go:218 +0xcf4
```

### Expected Behavior

No error

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/146498895-7227a5c7-1c99-43e8-b3e9-2adca9f0b90d.png)
The “cid” in Entry is illegal, but the “cid” in the Entry-header is correct。

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/146505492-5650830b-379c-479f-803c-f64f463fc1ab.png)
Entry-header is written twice, I guess mo-server is killed when loading data, the last Entry only writes the header
