### ISSUE TITLE
[Bug]: panic: internal error: duplicate vector commit_time

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#14211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.-0-dev

### Commit ID

74ec19386833029a42c0779d65d40e2881e4a298

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

local machine (macOS), standalone.
```

### Actual Behavior

```
~/MO/matrixone-debug on local-1.0-dev ⇣2⇡74 *5 !10 ?2 ❯ ./mo-service -debug-http=:6060 -launch etc/launch/launch.toml > log.log       took 13s at 02:25:25 PM
panic: internal error: duplicate vector commit_time

goroutine 752 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*Batch).AddVector(0x140574ea730, {0x104c7df91, 0xb}, {0x105ac3d20?, 0x140574d13c0})
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/containers/batch.go:81 +0x204
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*TableLogtailRespBuilder).visitBlkData(0x140549e1040, {0x105a6be20, 0x140574e6f30}, 0x10418df10?)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/handle.go:623 +0x2a4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*TableLogtailRespBuilder).VisitBlk(0x140549e1040, 0x0?)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/handle.go:637 +0x50
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*LoopProcessor).OnBlock(...)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/catalog/processor.go:85
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*BoundTableOperator).processTableData(0x1400e0cae68)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/operator.go:94 +0x294
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*BoundTableOperator).Run(0x16c586b800000001?)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/operator.go:57 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.HandleSyncLogTailReq({0x105a6be20, 0x140574e6f30}, {0x12fa70430?, 0x1400607cea0?}, 0x14006017080, 0x14000618f40, {0x140574e6f60, 0x140574e6f90, 0x140574d67c0, {}, ...}, ...)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/handle.go:181 +0x764
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*LogtailerImpl).TableLogtail(0x14016d38660, {0x105a6be20, 0x140574e6f30}, {0x4284e, 0x4284f, 0x0, {}, {0x0, 0x0, 0x0}, ...}, ...)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/logtailer.go:95 +0x1e8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).sendSubscription.func2()
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/service/server.go:436 +0xa0
runtime/trace.WithRegion({0x105a6be58?, 0x14016d39a40?}, {0x104ca193a, 0x18}, 0x1400e0cb918)
        /usr/local/go/src/runtime/trace/annotation.go:141 +0xc8
github.com/matrixorigin/matrixone/pkg/common/moprobe.WithArgAndFn({0x105a6be58, 0x14016d39a40}, 0x5, 0x0?, 0x104c749e3?, 0x1400e0cb918)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/common/moprobe/probe.go:97 +0x88
github.com/matrixorigin/matrixone/pkg/common/moprobe.WithRegion(...)
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/common/moprobe/probe.go:86
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).sendSubscription(0x1400568c180, {0x105a6be58, 0x14016d39a40}, {0x4e949145fc61, {0x140574d46e0, 0x1a}, 0x140574e6e70, 0x14000188a00})
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/service/server.go:435 +0x258
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).logtailSender(0x1400568c180, {0x105a6be58, 0x14016d39a40})
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/vm/engine/tae/logtail/service/server.go:404 +0x75c
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/common/stopper/stopper.go:259 +0x6c
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /Users/ghs-mo/MOWorkSpace/matrixone-debug/pkg/common/stopper/stopper.go:254 +0xd8
```

### Steps to Reproduce

```Markdown
create database testdb;
use testdb;

create table hhh(a int, b int);

insert into hhh select result, result from generate_series(1,2000), generate_series(1,3000)g;

insert into hhh select * from hhh where 10*(a+b) > a * b;
insert into hhh select * from hhh where 10*(a+b) > a * b;

update hhh set a = a * 2 where b mod 3 != 0;
// may need to try servals time

```

the panic err `duplicate vector commit_time` happened when MO restarted. before this restart, a panic happened when I query SQLs above to MO, refer to #14185

**Comment by XuPeng-SH** [comment]
duplicate with https://github.com/matrixorigin/MO-Cloud/issues/2299
