### ISSUE TITLE
[Bug]: cn crashed by oom panic during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14242]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

e792d6f

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2024/01/16 19:25:39.920120 +0000","name":"cn-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"30323135-6264-3333-3730-663134666439","connection_id":14577,"statement":"select c from sbtest7 where id = 47581","status":"fail","error":"error: out of memory","span":{"trace_id":"ecde2454-1966-230c-4421-6683f77bfe2e","span_id":"7e4f52b14806f28e"},"session_info":"connectionId 14577|10.10.3.0:30699|{account sysbench_test2:admin:accountadmin -- 6000003:2:2}|goRoutineId 224896|5f27b708-b48b-11ee-a35f-f6e234b2a745","session_id":"5f27b708-b48b-11ee-a35f-f6e234b2a745","statement_id":"086f70c0-b4a5-11ee-a383-f6e234b2a745"}
{"level":"ERROR","time":"2024/01/16 19:25:39.920484 +0000","caller":"mpool/mpool.go:580","msg":"error: error: out of memory"}
panic: error: out of memory

goroutine 776 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*SessionAllocator).Alloc(0x7f0d8db9da80?, 0xc2ca35ef80?)
 /go/src/github.com/matrixorigin/matrixone/pkg/frontend/types.go:237 +0x45
github.com/fagongzi/goetty/v2/buf.NewByteBuf(0xc66493e780?, {0xc404664db0, 0x2, 0x117eb41?})
 /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/buf/buf.go:102 +0xd3
github.com/fagongzi/goetty/v2.(*baseIO).initConn(0xc222cb2100)
 /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:530 +0x14e
github.com/fagongzi/goetty/v2.NewIOSession({0xc3849f8000, 0x7, 0xc70ca90900?})
 /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:238 +0x125
github.com/fagongzi/goetty/v2.(*server).doStart.func2({0x42b2b40, 0xc001b2e5b8})
 /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:336 +0x365
created by github.com/fagongzi/goetty/v2.(*server).doStart
 /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:365 +0xe5

mo-log:
http://10.222.6.1/explore?panes=%7B%22Aoi%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240116%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705415830135%22,%22to%22:%221705416712073%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run stability test on distributed mode:
1. tpch 10G longrunning in a tenant
2. tpcc 10-10 longrunning in a tenant
3. sysbench mixed cases 25 thread in a tenant
4. sysbench mixed cases 25 thread in a tenant
```

**Comment by aressu1985** [comment]
fixed
