### ISSUE TITLE
Service crashed because of index creation

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1430]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3f32c36753ec9578e17333d395635a349ada1bb7
- Hardware parameters:
- OS type: MacOS
- Others:
```

### Actual Behavior

```
{"level":"DEBUG","time":"2021/12/17 15:31:17.782155 +0800","caller":"engine/database.go:80","msg":"time cost 2 ms"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1012ada48]

goroutine 74283 [running]:
github.com/matrixorigin/matrixone/pkg/sql/plan.(*build).BuildCreateIndex(0x1400e1b1a90, 0x14014b0a8f0, 0x1401529b300)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/sql/plan/create_index.go:53 +0x98
github.com/matrixorigin/matrixone/pkg/sql/plan.(*build).BuildStatement(0x1400e1b1a90, {0x102980410, 0x14014b0a8f0})
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/sql/plan/build.go:91 +0xf4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Compile(0x1401529e780, {0x10286c5c0, 0x1400df13a00}, 0x102949618)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/sql/compile/exec.go:31 +0x80
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0x14011d386c0, {0x1400ee85ac0, 0x32})
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:816 +0x103c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x14011d386c0, 0x14018637308)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:979 +0x358
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x1400df13a00)
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/frontend/routine.go:100 +0xb8
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/Users/yangli/Documents/Origin/workspace/matrixone/pkg/frontend/routine.go:186 +0x19c
```

### Steps to Reproduce

```markdown
mysql> CREATE TABLE t1 (int_col INTEGER, string_col VARCHAR(255));
Query OK, 0 rows affected (0.35 sec)

mysql> INSERT INTO t1 (int_col, string_col) VALUES (-1, "foo"), (1, "bar");
Query OK, 2 rows affected (0.07 sec)

mysql> CREATE INDEX int_func_index ON t1 ((ABS(int_col)));
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (61)
ERROR:
Can't connect to the server
```
```


### Additional information

_No response_

**Comment by lignay** [comment]
Fixed on 311193bc3ee71034cf0ce520c121d862f39f486e
