### ISSUE TITLE
[Bug]: client hang after reconnect to CN

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#14401]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

83b8499b3

### Other Environment Information

```Markdown
MOC Dev env, connect to CN through proxy
```

### Actual Behavior

CN crashed during a query, client re-connected to MO and hung.

<img width="661" alt="WeChatWorkScreenshot_7da97deb-b82f-4eeb-8f96-c11563b67abc" src="https://github.com/matrixorigin/matrixone/assets/18556593/109366ba-e52b-4310-82bf-45255401db25">

Explore the connection ID and corresponding go-routine ID, I notice:

1. there is no request after reconnection
2. CN goroutine was waiting for client packets

```
goroutine 19236 [IO wait, 29 minutes]:
internal/poll.runtime_pollWait(0x7f40dc3e6150, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc02a165d80?, 0xc02b8cc010?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc02a165d80, {0xc02b8cc010, 0x1000, 0x1200})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc02a165d80, {0xc02b8cc010?, 0x400?, 0x0?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc01246d060, {0xc02b8cc010?, 0x4e981978046d?, 0x5eecc00?})
	/usr/local/go/src/net/net.go:183 +0x45
github.com/fagongzi/goetty/v2/buf.(*ByteBuf).ReadFrom(0xc02a16fa40, {0x42ab4e0, 0xc01246d060})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/buf/buf.go:508 +0x9d
io.copyBuffer({0x42a6600, 0xc02a16fa40}, {0x42ab4e0, 0xc01246d060}, {0xc02b595400, 0x400, 0x400})
	/usr/local/go/src/io/io.go:413 +0x14b
io.CopyBuffer({0x42a6600?, 0xc02a16fa40?}, {0x42ab4e0?, 0xc01246d060?}, {0xc02b595400?, 0xc02c97bdc0?, 0x35083c0?})
	/usr/local/go/src/io/io.go:400 +0x3c
github.com/fagongzi/goetty/v2.(*baseIO).readFromConn(0xc02b588300, 0x4e94914f0000?)
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:502 +0xd2
github.com/fagongzi/goetty/v2.(*baseIO).Read(0xc02b588300, {0x430bc40?})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:424 +0x85
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc001c82200, {0x430bc40, 0xc02b588300})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:132 +0x79
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x485
```

Ctrl-C does not work since there is no query in this session:

```
mysql> select * from processlist() as p where account='3f2b8e2a_f0b3_48d4_8c90_0b52af9ae78a';
+--------------------------------------+-----------+--------------------------------------+--------------------------------------+-------+------------------+----------+----------------------------+---------+------+--------+--------------+----------------+------------+-----------------+-------------+--------------------+--------------+
| node_id                              | conn_id   | session_id                           | account                              | user  | host             | db       | session_start              | command | info | txn_id | statement_id | statement_type | query_type | sql_source_type | query_start | client_host        | role         |
+--------------------------------------+-----------+--------------------------------------+--------------------------------------+-------+------------------+----------+----------------------------+---------+------+--------+--------------+----------------+------------+-----------------+-------------+--------------------+--------------+
| 32366636-3266-3138-3862-346135346338 | 129281058 | 018d4592-aa03-7406-bd66-b4ae1e773542 | 3f2b8e2a_f0b3_48d4_8c90_0b52af9ae78a | admin | 172.20.32.3:6001 | test_qsq | 2024-01-26 11:40:56.195497 |         |      |        |              |                |            |                 |             | 172.20.6.22:53804  | accountadmin |
| 32366636-3266-3138-3862-346135346338 | 129290908 | 018d4599-43e0-7b5d-9863-34e3d1f66d18 | 3f2b8e2a_f0b3_48d4_8c90_0b52af9ae78a | admin | 172.20.32.3:6001 |          | 2024-01-26 11:48:08.800308 |         |      |        |              |                |            |                 |             | 172.20.6.145:59062 | accountadmin |
+--------------------------------------+-----------+--------------------------------------+--------------------------------------+-------+------------------+----------+----------------------------+---------+------+--------+--------------+----------------+------------+-----------------+-------------+--------------------+--------------+
```

kill the query explicitly has no effect either:

```
mysql> kill query 129281058;
Query OK, 0 rows affected (0.36 sec)
```

### Expected Behavior

CN should not hang.

### Steps to Reproduce

```Markdown
Connect to CN, run query, crash the CN and trigger client reconnection.

Hard to reproduce
```

### Additional information

It looks like CN thought it has sent all packets to client and wait for client response, but client was still waiting for some packet from CN, thus the connection hung.

**Comment by volgariver6** [comment]
还没开始看这个问题

**Comment by volgariver6** [comment]
两个CN模拟，没有复现hang的问题，只出现了 `ERROR 20703 (HY000): lock table not found on remote lock service`，这个应该是正常的现象：
<img width="705" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/75fc04e1-bcfc-47b0-87f1-9ad5b020fd64">

**Comment by volgariver6** [comment]
跟 @aylei 讨论之后，先降级，观察是否还会出现这个问题。

**Comment by volgariver6** [comment]
问题未复现，也长时间未出现了，建议关闭
