### ISSUE TITLE
[Bug]: panic occurred when exec `select` query

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#1459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): v0.0.0-20211220135843-e652e20c08af

- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
+++++++++
:2 ∏([], []) -> splice -> limit(10) -> sql output
+++++++++
{"level":"info","ts":"2021-12-20 17:05:05.839","logger":"goetty","caller":"goetty@v1.11.3/application.go:231","msg":"session read failed","listen-address":"0.0.0.0:6003","session-id":1,"addr":"172.19.0.1:62942","error":"read tcp 172.19.0.4:6003->172.19.0.1:62942: use of closed network connection"}
2021/12/20 17:05:05.840549 +0000 INFO frontend/routine_manager.go:85 will close iosession
panic: interface conversion: interface {} is *output.Argument, not *connector.Argument

goroutine 904 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00addcb80, {0x277e6c0, 0xc00308a8a8})
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:474 +0x985
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0xc00addcb00, 0x2791648)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/exec.go:183 +0x138
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc00acf0b90, {0xc0000bb2c0, 0x25})
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:927 +0x1e2c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc00acf0b90, 0xc00adace58)
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:1046 +0x5b3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc00b0e2240)
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:99 +0x2be
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:151 +0x1e7
```

### Steps to Reproduce

```markdown
1. upgrade matrixcube to version v0.0.0-20211220135843-e652e20c08af
2. start a three-node cluster
3. create a database and table, load some data into the table
4. execute `select * from`
```

**Comment by nnsgmsone** [comment]
fixed by 1473

**Comment by sukki37** [comment]
Verified
