### ISSUE TITLE
[Bug]: [date 2.20]standalone regression: sysbench test reported fatal error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14613]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a6e7ae3b1b03946fa04ba4679bda3951cc0b830d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7975019236/job/21772225474
<img width="1438" alt="企业微信截图_8a19c08c-980a-47b5-b889-a3b2295fa95d" src="https://github.com/matrixorigin/matrixone/assets/113406637/c277ba00-3add-43ca-9ee9-6f1e6dfb40da">

log:
<img width="1419" alt="企业微信截图_6b1c0b0e-3df9-48d0-ae54-363d98caf9f6" src="https://github.com/matrixorigin/matrixone/assets/113406637/da409c5b-ae03-4753-9ea5-aa6531a16803">
{"level":"WARN","time":"2024/02/20 23:34:09.582568 +0800","name":"log-service.MOCollector","caller":"export/batch_processor.go:539","msg":"awakeBufferFactory: timeout after 3 seconds","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","MODiscardable":true}
{"level":"WARN","time":"2024/02/20 23:34:09.582587 +0800","name":"log-service.MOCollector","caller":"export/batch_processor.go:539","msg":"awakeBufferFactory: timeout after 3 seconds","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","MODiscardable":true}
{"level":"WARN","time":"2024/02/20 23:34:09.631665 +0800","name":"log-service.MOCollector","caller":"export/batch_processor.go:539","msg":"awakeBufferFactory: timeout after 3 seconds","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","MODiscardable":true}
{"level":"WARN","time":"2024/02/20 23:34:09.631784 +0800","name":"log-service.MOCollector","caller":"export/batch_processor.go:539","msg":"awakeBufferFactory: timeout after 3 seconds","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","MODiscardable":true}
fatal error: concurrent map iteration and map write

goroutine 61700 [running]:
github.com/matrixorigin/matrixone/pkg/util/status.(*LogtailStatus).fill(0xc308c9ef38, 0x457bb88?)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/status/logtail_client.go:46 +0x165
github.com/matrixorigin/matrixone/pkg/util/status.(*Status).fillCNStatus(0xc298401a38, 0xc00178f710)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/status/status.go:36 +0xff
github.com/matrixorigin/matrixone/pkg/util/status.(*Server).Dump(0xc00178f6e0)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/status/server.go:115 +0x10f
github.com/matrixorigin/matrixone/pkg/util/status.(*Server).ServeHTTP(0x4dabc0?, {0x452bc30, 0xc0877af420}, 0x91711a?)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/status/server.go:97 +0x1d
net/http.(*ServeMux).ServeHTTP(0x67f26a0?, {0x452bc30, 0xc0877af420}, 0xc806691100)
        /usr/local/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc32de649c0?}, {0x452bc30?, 0xc0877af420?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc5e089db00, {0x453dff0, 0xc00181a1b0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 180
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

### Steps to Reproduce

```Markdown
standalone regression sysbench test
```

**Comment by heni02** [comment]
date 2.21 回归问题已经解决，closed
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7990585385/job/21819885095
commit：78370d102d3d34f985a2f1fabb33e78a46a1fac0
