### ISSUE TITLE
[Bug]: memory leak detected during bvt test in backup_test.go

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#14714]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0c35ffc6a

### Other Environment Information

```Markdown
- Hardware parameters: 
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/3927687/a1da3ee8-7bb8-4d23-b26c-09a06959e9c5)

```
2024/02/27 09:41:34.636913 +0000 ERROR mpool/alloc_tracing.go:63 memory leak detected {"ptr": {}, "size": 896, "stack": "goroutine 117 [running]:
runtime/debug.Stack()
    /Users/runner/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x67
github.com/matrixorigin/matrixone/pkg/common/mpool.alloc(0x380, 0x380, 0xc00046a380)
    /Users/runner/work/matrixone/matrixone/pkg/common/mpool/alloc_tracing.go:57 +0x285
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Alloc(0xc00046a380, 0x380)
    /Users/runner/work/matrixone/matrixone/pkg/common/mpool/mpool.go:598 +0x865
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).reAlloc(0x200?, {0xc003d40490, 0x200, 0x200}, 0x380)
    /Users/runner/work/matrixone/matrixone/pkg/common/mpool/mpool.go:661 +0x85
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Grow(0xc003aec320?, {0xc003d40490, 0x200, 0x200}, 0x202)
    /Users/runner/work/matrixone/matrixone/pkg/common/mpool/mpool.go:708 +0xaa
github.com/matrixorigin/matrixone/pkg/container/vector.extend(0xc003aec320, 0x1, 0x1000501a7?)
    /Users/runner/work/matrixone/matrixone/pkg/container/vector/tools.go:160 +0xf6
github.com/matrixorigin/matrixone/pkg/container/vector.appendOneFixed[...](0xc003aec320, 0x5c7d, 0x0, 0x10007a6a9)
    /Users/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:2837 +0x5c
github.com/matrixorigin/matrixone/pkg/container/vector.AppendAny(0xc003aec320, {0x102cf8160?, 0xc003d6edfe?}, 0x0, 0xc00046a380)
    /Users/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:2694 +0x4df
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vectorWrapper).Append(0xc003978da0, {0x102cf8160, 0xc003d6edfe}, 0x0)
    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/vector.go:173 +0xcb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.MockVector({0x1a, 0x0, 0x0, 0x0, 0x2, 0x10, 0x0}, 0x12c, 0x0, {0x0, ...})
    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/mock.go:148 +0x1188
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.MockNullableBatch({0xc0001cb380, 0xd, 0xc002533158?}, 0x101f23bf9?, 0x3, 0x0)
    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/mock.go:371 +0x1fe
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.MockBatchWithAttrs(...)
    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/mock.go:361
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.MockBatch(0xc00207eb40, 0x3?)
    /Users/runner/work/matrixone/matrixone/pkg/vm/engine/tae/catalog/mock.go:283 +0x83f
github.com/matrixorigin/matrixone/pkg/backup.TestBackupData(0xc000633040)
    /Users/runner/work/matrixone/matrixone/pkg/backup/backup_test.go:62 +0x52a
testing.tRunner(0xc000633040, 0x1031e8f90)
    /Users/runner/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
    /Users/runner/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
"}
```

### Steps to Reproduce

bvt link:
https://github.com/matrixorigin/matrixone/actions/runs/8062545951/job/22022511856?pr=13801

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
tea mock 中报的错误。

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
same as https://github.com/matrixorigin/matrixone/issues/14085
