### ISSUE TITLE
[Bug]: mo panic by `panic: missing free for type...` during bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14781]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6fb2545

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8143055110

```
panic: missing free for type: *compile.Compile, &{scope:[0xc08d7657a0] pn:0xc09ef7f480 info:{Typ:1 WithGPU:false WithBigMem:false CnNumbers:1} u:0xc0759c0400 fill:0x68e1a60 affectRows:0xc057167698 addr:127.0.0.1:18000 db: tenant:sys uid:mo_logger sql:SELECT @@max_allowed_packet originSQL: anal:0xc047bb18c0 e:0xc088c484e0 ctx:0xc047bb17a0 proc:0xc08eb74c00 MessageBoard:0xc047bb1710 cnList:[{Mcpu:1 Id: Addr:127.0.0.1:18000 Header:{Type:0 Version:0} Data:[] Rel:<nil> NeedExpandRanges:false}] stmt:0xc043f397a0 counterSet:0xc0740cec00 nodeRegs:map[] stepRegs:map[] runtimeFilterReceiverMap:map[] lock:0xc061585a40 isInternal:false cnLabel:map[] buildPlanFunc:0x68b6860 startAt:{wall:13939094134039940236 ext:1184346698401 loc:0x10828900} fuzzy:<nil> createdFuzzy:[] needLockMeta:false metaTables:map[] disableRetry:false lastAllocID:0} 
 create by: <<<goroutine 43731 [running]:
runtime/debug.Stack()
	/home/runner/_work/_tool/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x105
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).got(0xe78aa20, 0xc07d836380)
	/home/runner/_work/matrixone/matrixone/head/pkg/common/reuse/checker.go:86 +0x37b
github.com/matrixorigin/matrixone/pkg/common/reuse.(*syncPoolBased[...]).Alloc(0xe74f4c0)
	/home/runner/_work/matrixone/matrixone/head/pkg/common/reuse/sync_pool_based.go:60 +0x112
github.com/matrixorigin/matrixone/pkg/common/reuse.Alloc[...]({0xe71ddc0, 0xc002694840})
	/home/runner/_work/matrixone/matrixone/head/pkg/common/reuse/factory.go:103 +0x17a
github.com/matrixorigin/matrixone/pkg/sql/compile.NewCompile({0xc004df40b1, 0xf}, {0x0, 0x0}, {0xc048d36420, 0x1b}, {0x7ca40c5, 0x3}, {0xc08871c0c7, 0x9}, ...)
	/home/runner/_work/matrixone/matrixone/head/pkg/sql/compile/compile.go:111 +0xa6
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0xc043f39800, {0xe747db0, 0xc047bb0000}, {0x7c8d220, 0xc0759c0400}, 0x7e7fe00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/computation_wrapper.go:312 +0x2df2
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt(0xc074a74780, {0xe747db0, 0xc047bb0000}, 0xc0759c0400, {0xe74fe80, 0xc043f397a0}, 0xc08eb74c00, {0xe781d80, 0xc043f39800}, 0x0, ...)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:3676 +0x7c8a
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc074a74780, {0xe747db0, 0xc047bb0000}, 0xc09ef7f240)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:4304 +0x3d7c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc074a74780, {0xe747db0, 0xc088e11e00}, 0xc0759c0400, 0xc04d4ffc68)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:4485 +0x12a2
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc0829ef900, 0xc04d4ffc68)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/routine.go:283 +0xd31
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0004a2000, {0xe793ee0, 0xc07194c000}, {0x750db40, 0xc050435080}, 0x2)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:522 +0x1c94
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc00c58c200, {0xe793ee0, 0xc07194c000})
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/server.go:145 +0x4b6
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/home/runner/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x1dc
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 1043
	/home/runner/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0xbc9
>>>


goroutine 5 [running]:
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0xe78aa20, 0xc07d836380)
	/home/runner/_work/matrixone/matrixone/head/pkg/common/reuse/checker.go:133 +0x669
github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
	/home/runner/_work/matrixone/matrixone/head/pkg/common/reuse/sync_pool_based.go:46 +0x131

```

### Steps to Reproduce

```Markdown
run bvt with race enabled
```

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8168295205

**Comment by noorall** [comment]
发现一处可能导致missing free的代码，已修复合并。再观察这几天的bvt看是否会出现这一问题。

**Comment by noorall** [comment]
@sukki37 辛苦观察一下后续的bvt是否还会出现这一问题。
