### ISSUE TITLE
[Bug]: MatirxOne启动后很快就Crash，报错panic: bad param: 176 io workers

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixone#14828]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.1(musl打包)

### Commit ID

d106f89

### Actual Behavior

**1、现象描述：**
在CentOS 7中使用musl打包的mo包一开始可以启动（https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/glibc/mo-v1.1.1-musl-x86_64.zip） ，但过了不大一会儿就挂了，日志：
```shell
panic: bad param: 176 io workers

goroutine 1323 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.newTaskScheduler(0x42ebbb8?, 0xc007dea090?, 0xc00545d880?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/scheduler.go:43 +0x8b4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x42ebbb8?, 0xc007dea090}, {0xc005c35ac0, 0x40}, 0xc0047f7f00?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/open.go:92 +0x83c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0x42ebbb8, 0xc007dea090}, {0xc005412900, 0x3c}, 0x100?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:1334 +0x1a8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0x42ebbb8?, 0xc007dea090?}, {0xc005412900?, 0xc0048800d0?}, 0xc00386bba0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:94 +0x49
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0x42ebbb8?, 0xc007dea090}, {0xc005412900, 0x3c}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:72 +0x265
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).newTAEStorage(0xc003883860, {0x42ebbb8, 0xc007dea090}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/tnservice/factory.go:158 +0x2cf
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createTxnStorage(0xc003883860, {0x42ebbb8, 0xc007dea090}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/tnservice/factory.go:73 +0x22e
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createReplica.func1({0x42ebbb8, 0xc007dea090})
	/go/src/github.com/matrixorigin/matrixone/pkg/tnservice/store.go:304 +0x111
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```
完整日志文件：
[matrixone.log](https://github.com/matrixorigin/matrixone/files/14518673/matrixone.log)

**2、CPU配置：**
```shell
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                176
On-line CPU(s) list:   0-175
Thread(s) per core:    2
Core(s) per socket:    22
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6238 CPU @ 2.10GHz
Stepping:              7
CPU MHz:               1000.012
CPU max MHz:           3700.0000
CPU min MHz:           1000.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              30976K
NUMA node0 CPU(s):     0-175
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
```

**3、操作系统：**
(物理机上安装的CentOS)：
```shell
$ uname -r
3.10.0-1160.105.1.el7.x86_64

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Steps to Reproduce

```Markdown
启动方法参考：
https://docs.matrixorigin.cn/1.1.1/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2
只是没把二进制包放在 /root/matrixone 下，换了个地方。

在这个机器上，用Docker跑也是失败。
```

**Comment by arjunsk** [comment]
The issue seems to be thrown due to bad config value for `io-workers`

![image](https://github.com/matrixorigin/matrixone/assets/9638314/bd526822-e0bf-4e0e-9c5f-c05472a47e2e)


@XuPeng-SH , could you kindly take a look at this or assign it to the appropriate person? Thank you.

**Comment by arjunsk** [comment]
io-worker is taking the number of CPU's ie 176. 

![image](https://github.com/matrixorigin/matrixone/assets/9638314/eadeec95-6d02-44dd-996c-39f8a6aafded)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/4c9c0126-c203-4892-8ff3-24008874e0c8)

But we have this condition that panic's when io_workers is more than 100.

![image](https://github.com/matrixorigin/matrixone/assets/9638314/23eab1da-bc17-46a1-bc34-04dd862973aa)

**Comment by heni02** [comment]
稳定性测试环境为128cpu之前也报了该错，看现象大于100cpu会报该错误，稳定性环境目前启动已无该问题
