### ISSUE TITLE
service is offline during BVT in cluster mode

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1515]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
matrixone-operator: 9f870e7f07b60a03b88471cb2f6af8521f28481a
matrixone:  1cfd62852d57d0cbbb560595151512c2a56d13ef
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
Query:	 select a,b,c,d from numtable;
[mysql] 2021/12/23 18:27:27 packets.go:33: unexpected EOF
[mysql] 2021/12/23 18:27:27 connection.go:261: invalid connection
[mysql] 2021/12/23 18:27:27 packets.go:33: unexpected EOF
[mysql] 2021/12/23 18:27:27 packets.go:33: unexpected EOF
=== RUN drop_database:
FATA[0002] run test [datatype] err: sql:select a,b,c,d from numtable;: run "select a,b,c,d from numtable;" at line 25 err driver: bad connection
Exit code: [1]
```

### Expected Behavior

query should be successful

### Steps to Reproduce

```markdown
1. Start three docker containers running mo-server in cluster mode
git clone https://github.com/matrixorigin/matrixone-operator
cd matrixone-operator/docker-compose
change TAG to nightly in Makefile
make up
2. run bvt test cases
```

### Additional information
service stop on node0 at 2021/12/23 10:27:27.489331
_No response_

**Comment by lignay** [comment]
Could not be reproduced on commit 311193bc3ee71034cf0ce520c121d862f39f486e

**Comment by lignay** [comment]
Hitting the issue again

**Comment by wanglei4687** [comment]
cluster slice bounds problem

```
panic: runtime error: slice bounds out of range [:262144] with capacity 154

goroutine 1167 [running]:
github.com/matrixorigin/matrixone/pkg/sql/protocol.DecodeVector({0xc00c0844d8, 0x3812448, 0x114})
	/matrixone/pkg/sql/protocol/protocol.go:2913 +0x3730
github.com/matrixorigin/matrixone/pkg/sql/protocol.DecodeBatch({0xc00c084480, 0x11a, 0x120})
	/matrixone/pkg/sql/protocol/protocol.go:883 +0xa7e
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00af35e00, {0x27cd4c0, 0xc0028dc7f8})
	/matrixone/pkg/sql/compile/scope.go:509 +0x791
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0xc0004aefb0)
	/matrixone/pkg/sql/compile/scope.go:440 +0x2a
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/matrixone/pkg/sql/compile/scope.go:439 +0x425
```

**Comment by m-schen** [comment]
steps to reproduce:
1. start at least 2 nodes cluster
2.  run
`
create table numtable(a tinyint unsigned, b smallint unsigned, c int unsigned, d bigint unsigned);
insert into numtable values(255,65535,4294967295,18446744073709551615);
select a,b,c,d from numtable;
`

due to decode for vector bug.
