### ISSUE TITLE
[Bug]: cn restart by panic runtime error: invalid memory address or nil pointer dereference during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15163]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

5071ff4178a804cb0b424674b4f9d9d01a0c69b0

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

 during stability test on distributed mode, on cn restarted by panic:
-7d2e-a131-14fe943dd9fe"}
{"level":"ERROR","time":"2024/03/26 01:57:35.474760 +0000","name":"cn-backend","caller":"v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:515","msg":"close conneciton failed","remote":"105.57:6002","backend-id":"018e7879-9aa2-776a-bc53-a58d09cb6941","session-id":0,"error":"close tcp4 10.10.5.56:33668->10.10.5.57:6002: use of closed network connection"}
{"level":"ERROR","time":"2024/03/26 01:57:35.475147 +0000","name":"cn-service.lockservice","caller":"lockservice/rpc.go:356","msg":"write response failed","uuid":"32643963-6363-3136-3762-33383865","error":"context deadline exceeded","response":""}
{"level":"ERROR","time":"2024/03/26 01:57:35.475516 +0000","name":"cn-service.lockservice","caller":"lockservice/rpc.go:356","msg":"write response failed","uuid":"32643963-6363-3136-3762-33383865","error":"context deadline exceeded","response":""}
{"level":"INFO","time":"2024/03/26 01:57:35.477442 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:3919","msg":"time of Exec.Run : 4.004761298s","uuid":"326436363-3136-3762-643633383865","session_info":"connectionId 14415|10.10.3.0:25293|{account tpcc_test:admin:accountadmin -- 3000001:2:2}|goRoutineId 7111861|018e77a1-98f8-7a58-bfd5-c7d36a6ef,"session_id":"018e77a1-98f8-7a58-bfd5-c7d36a6ef017","statement_id":"018e787a-18cd-7c88-ba88-50510ae8c5ba","txn_id":"018e7879fb20798f975e8bf57750a462/Active/S:1711418247012940372-1"}
{"level":"ERROR","time":"2024/03/26 01:57:35.478016 +0000","name":"cn-service.lockservice","caller":"lockservice/rpc.go:356","msg":"write response failed","uuid":"32643963-6363-3136-3762-33383865","error":"the connection between CN and TN has been disconnected","response":""}
{"level":"ERROR","time":"2024/03/26 01:57:35.478176 +0000","name":"cn-service.lockservice","caller":"lockservice/rpc.go:356","msg":"write response failed","uuid":"32643963-6363-3136-3762-33383865","error":"the connection between CN and TN has been disconnected","response":""}
{"level":"ERROR","time":"2024/03/26 01:57:35.478136 +0000","name":"cn-service.lockservice","caller":"lockservice/rpc.go:356","msg":"write response failed","uuid":"32643963-6363-3136-3762-33383865","error":"the connection between CN and TN has been disconnected","response":""}
{"level":"ERROR","time":"2024/03/26 01:57:35.478236 +0000","name":"cn-service.lockservice","caller":"lockservice/rpc.go:356","msg":"write response failed","uuid":"32643963-6363-3136-3762-33383865","error":"the connection between CN and TN has been disconnected","response":""}
{"level":"INFO","time":"2024/03/26 01:57:35.478261 +0000","name":"cn-service.lockservice.lock-server","caller":"v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:383","msg":"session reailed","uuid":"32643963-6363-3136-3762-643633383865","name":"lock-server","listen-addresses":"[0.0.0.0:6003]","session-id":2,"addr":"10.10.5.58:54218","error":"read tcp4 10.10.5.56:6003->0.5.58:54218: use of closed network connection"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1907ffe]

goroutine 923 [running]:
github.com/matrixorigin/matrixone/pkg/common/morpc.RPCMessage.Timeout({{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, 0x0, ...}})
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/message.go:30 +0x1e
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).startWriteLoop.func1({0x5bc72f0, 0xc005aa7620})
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:337 +0x77b
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0xd3
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0x111

mo-log:
https://shanghai-idc.1matrix.org:30088/explore?panes=%7B%220O4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-5071ff4-20240325%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711417257164%22,%22to%22:%221711419609808%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a distributed mo cluster 
2. run tpch 10G loop test
3. run tpcc 10-10 longrunning test
4. run sysbench mixed case longrunning test
```

**Comment by aressu1985** [comment]
fixed
