### ISSUE TITLE
[Bug]: JDBC connection error

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#1520]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1cfd62852d57d0cbbb560595151512c2a56d13ef
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Error log of client:
```
2021-12-24 14:35:15.703  INFO 75252 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 558 ms
2021-12-24 14:35:15.755  INFO 75252 --- [           main] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
2021-12-24 14:35:15.951 ERROR 75252 --- [           main] com.alibaba.druid.pool.DruidDataSource   : init datasource error, url: jdbc:mysql://127.0.0.1:6001/ssb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

java.sql.SQLException: Access denied for user
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:787) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:251) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1659) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:927) ~[druid-1.2.8.jar:1.2.8]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.13.jar:5.3.13]
```

error log from mo-server
```
{"level":"error","ts":"2021-12-24 04:32:13.330","logger":"goetty","caller":"goetty@v1.11.3/application.go:242","msg":"session handle failed, close this session","listen-address":"0.0.0.0:6001","session-id":46,"addr":"172.19.0.1:63684","error":"check password failed\n"}
{"level":"info","ts":"2021-12-24 04:32:13.346","logger":"goetty","caller":"goetty@v1.11.3/application.go:221","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":47,"addr":"172.19.0.1:63686"}
{"level":"error","ts":"2021-12-24 04:32:13.351","logger":"goetty","caller":"goetty@v1.11.3/application.go:242","msg":"session handle failed, close this session","listen-address":"0.0.0.0:6001","session-id":47,"addr":"172.19.0.1:63686","error":"check password failed\n"}
{"level":"info","ts":"2021-12-24 04:32:13.355","logger":"goetty","caller":"goetty@v1.11.3/application.go:221","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":48,"addr":"172.19.0.1:63688"}
{"level":"error","ts":"2021-12-24 04:32:13.361","logger":"goetty","caller":"goetty@v1.11.3/application.go:242","msg":"session handle failed, close this session","listen-address":"0.0.0.0:6001","session-id":48,"addr":"172.19.0.1:63688","error":"check password failed\n"}
{"level":"info","ts":"2021-12-24 06:28:08.805","logger":"goetty","caller":"goetty@v1.11.3/application.go:221","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":49,"addr":"172.19.0.1:64054"}
{"level":"error","ts":"2021-12-24 06:28:08.813","logger":"goetty","caller":"goetty@v1.11.3/application.go:242","msg":"session handle failed, close this session","listen-address":"0.0.0.0:6001","session-id":49,"addr":"172.19.0.1:64054","error":"check password failed\n"}
{"level":"info","ts":"2021-12-24 06:28:08.837","logger":"goetty","caller":"goetty@v1.11.3/application.go:221","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":50,"addr":"172.19.0.1:64056"}
{"level":"error","ts":"2021-12-24 06:28:08.855","logger":"goetty","caller":"goetty@v1.11.3/application.go:242","msg":"session handle failed, close this session","listen-address":"0.0.0.0:6001","session-id":50,"addr":"172.19.0.1:64056","error":"check password failed\n"}
```

**Comment by sukki37** [comment]
Validated
