### ISSUE TITLE
[Bug]: UT TestCannotHungWithUnstableNetwork failed

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#15563]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

95801d84dc017970b404c15b7e72e4c471d84339

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8714765038/job/23905543524?pr=15546

```
2024-04-17T01:37:45.7926332Z 2024/04/17 01:19:27.595764 +0000 DEBUG cn-service.lockservice unlock txn {"uuid": "", "txn": "0000001f27()", "cost": "307.825µs"}
2024-04-17T01:37:45.7926577Z panic: BUG: unlock a lock that is not held by the current txn
2024-04-17T01:37:45.7926590Z 
2024-04-17T01:37:45.7926723Z goroutine 6831 [running]:
2024-04-17T01:37:45.7927089Z go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc000a5b040, {0x0?, 0x0?, 0x0?})
2024-04-17T01:37:45.7927447Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0xa8
2024-04-17T01:37:45.7927791Z go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000a5b040, {0xc0003a6f00, 0x6, 0x6})
2024-04-17T01:37:45.7928123Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x586
2024-04-17T01:37:45.7928761Z github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Log(0xc000311e40, {0x11577b4, 0x36}, {{0x0, 0x0}, 0x5, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
2024-04-17T01:37:45.7929200Z 	/home/runner/work/matrixone/matrixone/pkg/common/log/logger.go:169 +0x565
2024-04-17T01:37:45.7929755Z github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Fatal(0xc000a17b00?, {0x11577b4, 0x36}, {0xc0003a6f00, 0x6, 0x6})
2024-04-17T01:37:45.7930092Z 	/home/runner/work/matrixone/matrixone/pkg/common/log/logger.go:137 +0xbc
2024-04-17T01:37:45.7930563Z github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock.func2({0xc000a2c84f, 0x1, 0x1})
2024-04-17T01:37:45.7930960Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:229 +0xd8e
2024-04-17T01:37:45.7931366Z github.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlice).iter(0xc0054d0480, 0xc0057a97f8)
2024-04-17T01:37:45.7931700Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/slice.go:159 +0xd7
2024-04-17T01:37:45.7932386Z github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock(0xc000360000, 0xc000a17b00, 0xc0054d02d0?, {0x0, 0x0, 0x0, {}, {0x0, 0x0, 0x0}, ...})
2024-04-17T01:37:45.7932780Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:212 +0x578
2024-04-17T01:37:45.7933120Z github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close.func1.1()
2024-04-17T01:37:45.7933445Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/txn.go:152 +0x11d
2024-04-17T01:37:45.7934226Z github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close(0xc000a17b00, {0xc000a08300, 0x15}, {0xc0056dcbe8?, 0x0?, 0xc0047c7f28?}, {0x0, 0x0, 0x0, {}, ...}, ...)
2024-04-17T01:37:45.7934557Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/txn.go:163 +0x362
2024-04-17T01:37:45.7935220Z github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Unlock(0xc000156780, {0x1f2a1e8, 0xc0054d0240}, {0xc0047c7f28, 0x5, 0x8}, {0x0, 0x0, 0x0, {}, ...})
2024-04-17T01:37:45.7935568Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service.go:180 +0x3a9
2024-04-17T01:37:45.7936165Z github.com/matrixorigin/matrixone/pkg/lockservice.TestCannotHungWithUnstableNetwork.func1.1(0xc0009beed0?, 0x0)
2024-04-17T01:37:45.7936545Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:1932 +0x3b7
2024-04-17T01:37:45.7937025Z created by github.com/matrixorigin/matrixone/pkg/lockservice.TestCannotHungWithUnstableNetwork.func1
2024-04-17T01:37:45.7937450Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:1938 +0x806
2024-04-17T01:37:45.7937716Z FAIL	github.com/matrixorigin/matrixone/pkg/lockservice	68.093s
```

### Steps to Reproduce

```Markdown
CI ut
```

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/pull/15551
[15.txt.zip](https://github.com/matrixorigin/matrixone/files/15052686/15.txt.zip)


```

2024-04-21T16:03:21.0710156Z panic: missing free for type: *lockservice.waiter, 0200000cf2-0xc003ac4c00(1) 
2024-04-21T16:03:21.0710277Z  create by: <<<>>>
2024-04-21T16:03:21.0710286Z 
2024-04-21T16:03:21.0710291Z 
2024-04-21T16:03:21.0710410Z goroutine 5 [running]:
2024-04-21T16:03:21.0710817Z github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0x11ea520, 0xc003ac4c00)
2024-04-21T16:03:21.0711187Z 	/home/runner/work/matrixone/matrixone/pkg/common/reuse/checker.go:133 +0x394
2024-04-21T16:03:21.0711608Z github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
2024-04-21T16:03:21.0711985Z 	/home/runner/work/matrixone/matrixone/pkg/common/reuse/sync_pool_based.go:46 +0xc5
2024-04-21T16:03:21.0712238Z FAIL	github.com/matrixorigin/matrixone/pkg/lockservice	72.183s
```

**Comment by zhangxu19830126** [comment]
missing free for type panic is another problem，dup with #15636. 

unlock a lock that is not held by the current txn is fixed
