### ISSUE TITLE
[Bug]:  cn panic cause by `segmentation violation`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15571]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.3

### Commit ID

14c4496c64f4639214e111baba4f8adf0d8343f0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://grafana.matrixonecloud.cn/explore?panes=%7B%22vnt%22:%7B%22datasource%22:%22fe9f0f46-57bd-4343-8755-8d67d0429b65%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22CNSet%5C%22,%20pod%3D%5C%22freetier-01-localpv-586c7f8f85-cn-bdv4v%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22fe9f0f46-57bd-4343-8755-8d67d0429b65%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713283464027%22,%22to%22:%221713283921747%22%7D%7D%7D&schemaVersion=1&orgId=1

```
2024-04-17 00:07:51.951	
panic: runtime error: invalid memory address or nil pointer dereference

2024-04-17 00:07:51.951	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2c9982d]
2024-04-17 00:07:51.951	

2024-04-17 00:07:51.951	
goroutine 101850 [running]:
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).RollbackTxn(0x0)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:391 +0xcd
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.commitAfterMigrate(0xc03c54e2c0?, {0x4348f00?, 0xc0b18b44e0?})
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2473 +0x36
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*dbMigration).Migrate.func1()
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2507 +0x35
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*dbMigration).Migrate(0x435ead0?, 0xc03c54e2c0?)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2511 +0xd2
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).Migrate(0x0?, 0xc08193ff80)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2556 +0x70
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo.func1()
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:395 +0x39
2024-04-17 00:07:51.951	
sync.(*Once).doSlow(0x36751e0?, 0xc0041e8a50?)
2024-04-17 00:07:51.951	
	/usr/local/go/src/sync/once.go:74 +0xc2
2024-04-17 00:07:51.951	
sync.(*Once).Do(...)
2024-04-17 00:07:51.951	
	/usr/local/go/src/sync/once.go:65
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo(0x0?, 0xc077e0cc40?)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:393 +0x65
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).MigrateConnectionTo(0xc000175810, 0xc08193ff80)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:625 +0x3a
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleMigrateConnTo(0xc0beac10f8?, {0x4379138?, 0xc085f0e480?}, 0xc074989450, 0xc0ace11ce0)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:351 +0x58
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x43527a0?, {0x4379138, 0xc085f0e480?}, 0x7fd165bcc0b8?, 0x7fd1cab81f18?)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:65 +0x58
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage.func1()
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:180 +0x2cc
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage(0x43cfcc0, {0x4379138, 0xc085f0e480?}, {{0x4379138, 0xc085f0e480}, 0xc10df825d0, {0x4392a08, 0xc074989450}, 0x0, 0x0, ...}, ...)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:189 +0x5aa
2024-04-17 00:07:51.951	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc000362370, {0x43ae440, 0xc082a29600}, {0x39f9f60?, 0xc086f6db30}, 0x1)
2024-04-17 00:07:51.951	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:261 +0xd53
2024-04-17 00:07:51.951	
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc000362420, {0x43ae440, 0xc082a29600})
2024-04-17 00:07:51.951	
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:393 +0x38a
2024-04-17 00:07:51.951	
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
2024-04-17 00:07:51.951	
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x90
2024-04-17 00:07:51.951	
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
2024-04-17 00:07:51.951	
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x485
```

### Steps to Reproduce

```Markdown
no idea
```

**Comment by volgariver6** [comment]
wait for the pr merged

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
