### ISSUE TITLE
[Bug]:  ut failed TestAddressManager

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15759]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8860511165/job/24331368240?pr=15744
```
2024-04-27T14:45:14.9124038Z         	Test:       	TestAddressManager
2024-04-27T14:45:14.9124189Z     address_test.go:106: 
2024-04-27T14:45:14.9124754Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:106
2024-04-27T14:45:14.9124923Z         	Error:      	Not equal: 
2024-04-27T14:45:14.9125220Z         	            	expected: "127.0.0.1:39003"
2024-04-27T14:45:14.9125516Z         	            	actual  : "127.0.0.1:39005"
2024-04-27T14:45:14.9125666Z         	            	
2024-04-27T14:45:14.9125846Z         	            	Diff:
2024-04-27T14:45:14.9126088Z         	            	--- Expected
2024-04-27T14:45:14.9126290Z         	            	+++ Actual
2024-04-27T14:45:14.9126522Z         	            	@@ -1 +1 @@
2024-04-27T14:45:14.9126785Z         	            	-127.0.0.1:39003
2024-04-27T14:45:14.9127012Z         	            	+127.0.0.1:39005
2024-04-27T14:45:14.9127203Z         	Test:       	TestAddressManager
2024-04-27T14:45:14.9127380Z --- FAIL: TestAddressManager (0.00s)
2024-04-27T14:45:14.9127716Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-04-27T14:45:14.9128133Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-04-27T14:45:14.9128410Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x66f86b]
2024-04-27T14:45:14.9128429Z 
2024-04-27T14:45:14.9128545Z goroutine 20 [running]:
2024-04-27T14:45:14.9128718Z testing.tRunner.func1.2({0x691020, 0x880c20})
2024-04-27T14:45:14.9129011Z 	/opt/hostedtoolcache/go/1.20.14/x64/src/testing/testing.go:1526 +0x372
2024-04-27T14:45:14.9129135Z testing.tRunner.func1()
2024-04-27T14:45:14.9129422Z 	/opt/hostedtoolcache/go/1.20.14/x64/src/testing/testing.go:1529 +0x650
2024-04-27T14:45:14.9129547Z panic({0x691020, 0x880c20})
2024-04-27T14:45:14.9129828Z 	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:890 +0x263
2024-04-27T14:45:14.9130172Z github.com/matrixorigin/matrixone/pkg/util/address.TestAddressManager.func1()
2024-04-27T14:45:14.9130547Z 	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:101 +0x4b
2024-04-27T14:45:14.9131000Z github.com/matrixorigin/matrixone/pkg/util/address.TestAddressManager(0xc000087520)
2024-04-27T14:45:14.9131382Z 	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:107 +0x4fb
2024-04-27T14:45:14.9131517Z testing.tRunner(0xc000087520, 0x6f1d20)
2024-04-27T14:45:14.9131814Z 	/opt/hostedtoolcache/go/1.20.14/x64/src/testing/testing.go:1576 +0x217
2024-04-27T14:45:14.9131942Z created by testing.(*T).Run
2024-04-27T14:45:14.9132222Z 	/opt/hostedtoolcache/go/1.20.14/x64/src/testing/testing.go:1629 +0x806
2024-04-27T14:45:14.9132478Z FAIL	github.com/matrixorigin/matrixone/pkg/util/address	0.048s
```

### Steps to Reproduce

```Markdown
ut
```

**Comment by volgariver6** [comment]
fixed

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9029741287/job/24817823215?pr=15965

```
2024-05-10T11:46:43.0782970Z === RUN   TestAddressManager
2024-05-10T11:46:43.0783120Z     address_test.go:99: 
2024-05-10T11:46:43.0783678Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:99
2024-05-10T11:46:43.0783918Z         	Error:      	Received unexpected error:
2024-05-10T11:46:43.0784387Z         	            	listen tcp4 0.0.0.0:39002: bind: address already in use
2024-05-10T11:46:43.0784588Z         	Test:       	TestAddressManager
2024-05-10T11:46:43.0784741Z     address_test.go:105: 
2024-05-10T11:46:43.0785295Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:105
2024-05-10T11:46:43.0785469Z         	Error:      	Not equal: 
2024-05-10T11:46:43.0785758Z         	            	expected: "0.0.0.0:39003"
2024-05-10T11:46:43.0786037Z         	            	actual  : "0.0.0.0:39002"
2024-05-10T11:46:43.0786198Z         	            	
2024-05-10T11:46:43.0786376Z         	            	Diff:
2024-05-10T11:46:43.0786629Z         	            	--- Expected
2024-05-10T11:46:43.0786829Z         	            	+++ Actual
2024-05-10T11:46:43.0787071Z         	            	@@ -1 +1 @@
2024-05-10T11:46:43.0787320Z         	            	-0.0.0.0:39003
2024-05-10T11:46:43.0787536Z         	            	+0.0.0.0:39002
2024-05-10T11:46:43.0787845Z         	Test:       	TestAddressManager
2024-05-10T11:46:43.0788006Z     address_test.go:106: 
2024-05-10T11:46:43.0788567Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:106
2024-05-10T11:46:43.0788739Z         	Error:      	Not equal: 
2024-05-10T11:46:43.0789039Z         	            	expected: "127.0.0.1:39003"
2024-05-10T11:46:43.0789330Z         	            	actual  : "127.0.0.1:39002"
2024-05-10T11:46:43.0789487Z         	            	
2024-05-10T11:46:43.0789662Z         	            	Diff:
2024-05-10T11:46:43.0789910Z         	            	--- Expected
2024-05-10T11:46:43.0790108Z         	            	+++ Actual
2024-05-10T11:46:43.0790345Z         	            	@@ -1 +1 @@
2024-05-10T11:46:43.0790605Z         	            	-127.0.0.1:39003
2024-05-10T11:46:43.0790834Z         	            	+127.0.0.1:39002
2024-05-10T11:46:43.0791027Z         	Test:       	TestAddressManager
2024-05-10T11:46:43.0791207Z --- FAIL: TestAddressManager (0.00s)
2024-05-10T11:46:43.0791538Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-05-10T11:46:43.0791831Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-05-10T11:46:43.0792108Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x66a7aa]
2024-05-10T11:46:43.0792116Z 
2024-05-10T11:46:43.0792335Z goroutine 22 [running]:
2024-05-10T11:46:43.0792510Z testing.tRunner.func1.2({0x68bf20, 0x87e1c0})
2024-05-10T11:46:43.0792823Z 	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x3f7
2024-05-10T11:46:43.0792958Z testing.tRunner.func1()
2024-05-10T11:46:43.0793252Z 	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x716
2024-05-10T11:46:43.0793393Z panic({0x68bf20?, 0x87e1c0?})
2024-05-10T11:46:43.0793670Z 	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
2024-05-10T11:46:43.0794011Z github.com/matrixorigin/matrixone/pkg/util/address.TestAddressManager.func1()
2024-05-10T11:46:43.0794383Z 	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:101 +0x4a
2024-05-10T11:46:43.0794745Z github.com/matrixorigin/matrixone/pkg/util/address.TestAddressManager(0xc000083a00)
2024-05-10T11:46:43.0795277Z 	/home/runner/work/matrixone/matrixone/pkg/util/address/address_test.go:107 +0x505
2024-05-10T11:46:43.0795426Z testing.tRunner(0xc000083a00, 0x6e77b8)
2024-05-10T11:46:43.0795776Z 	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
2024-05-10T11:46:43.0795937Z created by testing.(*T).Run in goroutine 1
2024-05-10T11:46:43.0796211Z 	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
2024-05-10T11:46:43.0796468Z FAIL	github.com/matrixorigin/matrixone/pkg/util/address	0.013s
```

**Comment by volgariver6** [comment]
fixed
