### ISSUE TITLE
[Bug]: all DML operations on a specified table hung forever.

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#15792]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v113

### Commit ID

a6e45fcd7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

table schema and mock data:
```
create database iotdemo;
use iotdemo;

CREATE TABLE `sensor_data_with_primary_key` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `device_id` INT NOT NULL,
    `timestamp` TIMESTAMP NOT NULL,
    `value` FLOAT NOT NULL,
    PRIMARY KEY (`device_id`,`id`));

INSERT INTO sensor_data_with_primary_key_2(device_id, timestamp, value) select *,NOW(),1.1 from generate_series(1,5000000)g;
INSERT INTO sensor_data_with_primary_key_2(device_id, timestamp, value) select *,NOW(),1.1 from generate_series(5000001, 10000000)g;
INSERT INTO sensor_data_with_primary_key_2(device_id, timestamp, value) select *,NOW(),1.1 from generate_series(10000001,15000000)g;
INSERT INTO sensor_data_with_primary_key_2(device_id, timestamp, value) select *,NOW(),1.1 from generate_series(15000000,20000000)g;
```

|

operations before the hung: 
go run script:
```go
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"log"
	"math/rand"
	"net/url"

	//"net/url"
	"sync"
	"time"
)

const (
	numDevices     = 1000
	dataInterval   = 3 * time.Second
	minConnections = 100
	maxConnections = 500
	logInterval    = 1 * time.Second
)

var (
	//dbUser     = "40b092bd_1079_4134_a773_75bce4e3cc3f:admin:accountadmin"
	//dbPassword = "Baidu1234"
	//dbHost     = "freetier-01.cn-hangzhou.cluster.matrixonecloud.cn"
	//dbPort     =  6001
	dbUser  = "018f27b5_0938_7abb_bcf9_d5789ce9bff3:admin:accountadmin"
	dbPwd   = "***"
	dbHost  = "freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech"
	dbPort  = 6001
	dbName  = "iotdemo"
	tblName = "sensor_data_with_primary_key_2"
	db      *sql.DB
	wg      sync.WaitGroup
)

type RR struct {
	isInsert bool
	dur      int64
}

var tpsCh chan RR

func main() {
	// 打开数据库连接
	var err error
	encodedUsername := url.QueryEscape(dbUser)
	db, err = sql.Open("mysql", fmt.Sprintf("%s:%s@tcp(%s:%d)/%s", encodedUsername, dbPwd, dbHost, dbPort, dbName))
	//db, err = sql.Open("mysql", fmt.Sprintf("dump:111@tcp(127.0.0.1:6001)/%s", dbName))
	if err != nil {
		log.Fatal("Error connecting to database:", err)
	}
	defer db.Close()
	fmt.Println("Successfully connected to database")

	// db.SetMaxIdleConns(numDevices)
	// db.SetMaxOpenConns(numDevices)

	tpsCh = make(chan RR, 10000)
	go tpsReporter()
	// 启动数据生成协程
	for i := 0; i < numDevices; i++ {
		wg.Add(1)
		go generateData(i)
	}

	// 启动并发查询协程
	ticker := time.NewTicker(logInterval)
	for range ticker.C {
		wg.Add(1)
		go runQueries()
	}

	// 等待所有协程完成
	wg.Wait()
}

var tpsCounter [2]int64
var tpsDuration [2]int64
var tpsDurMax, tpsDurMin [2]int64

func tpsReporter() {
	ticker := time.NewTicker(time.Second * 10)

	for {
		select {
		case rr := <-tpsCh:
			idx := 0
			if !rr.isInsert {
				idx = 1
			}
			tpsCounter[idx]++
			tpsDuration[idx] += rr.dur
			if tpsDurMax[idx] < rr.dur {
				tpsDurMax[idx] = rr.dur
			}
			if tpsDurMin[idx] > rr.dur {
				tpsDurMin[idx] = rr.dur
			}
		case <-ticker.C:
			fmt.Printf("Insert last 10s, tps: %d, avg lat: %f ms, max: %d ms, min: %d ms\n",
				tpsCounter[0]/10, float64(tpsDuration[0])/float64(tpsCounter[0]), tpsDurMax[0], tpsDurMin[0])
			fmt.Printf("Select last 10s, tps: %d, avg lat: %f ms, max: %d ms, min: %d ms\n",
				tpsCounter[1]/10, float64(tpsDuration[1])/float64(tpsCounter[1]), tpsDurMax[1], tpsDurMin[1])
			tpsCounter = [2]int64{0, 0}
			tpsDuration = [2]int64{0, 0}
			tpsDurMin = [2]int64{0, 0}
			tpsDurMax = [2]int64{0, 0}
		}
	}
}

// generateData 模拟传感器设备每隔一段时间上传数据
func generateData(deviceID int) {
	defer wg.Done()

	for {
		// 生成随机数据
		value := rand.Float64()

		// 插入数据到数据库
		query := fmt.Sprintf("INSERT INTO %s (device_id, timestamp, value) VALUES (%d, '%s', %f)",
			tblName, deviceID, time.Now().Format("2006-01-02 15:04:05"), value)
		now := time.Now()
		_, err := db.Exec(query)
		if err != nil {
			// 记录错误
			log.Printf("Error inserting data: %v\nQuery: %s", err, query)
			continue
		}
		dur := time.Now().Sub(now).Milliseconds()
		select {
		case tpsCh <- RR{dur: dur, isInsert: true}:
		}
		//fmt.Println("Data inserted successfully")
		// 休眠一段时间
		//time.Sleep(dataInterval)
	}
}

// runQueries 模拟并发查询
func runQueries() {
	defer wg.Done()

	// 随机生成查询类型
	queryType := rand.Intn(3)
	deviceID := rand.Intn(numDevices)
	start := time.Now().Add(-time.Hour)
	end := time.Now()
	// 生成查询语句
	var query string
	switch queryType {
	case 0:
		// 查询所有数据
		query = fmt.Sprintf("SELECT count(*) FROM %s", tblName)
	case 1:
		// 查询特定设备的数据
		//    deviceID := rand.Intn(numDevices)
		query = fmt.Sprintf("SELECT max(value) FROM %s WHERE device_id = %d", tblName, deviceID)
	case 2:
		// 查询特定时间范围内的所有数据
		//    start := time.Now().Add(-time.Hour)
		//    end := time.Now()
		query = fmt.Sprintf("SELECT avg(value) FROM %s WHERE timestamp BETWEEN '%s' AND '%s'",
			tblName, start.Format("2006-01-02 15:04:05"), end.Format("2006-01-02 15:04:05"))
	}

	now := time.Now()
	// 执行查询
	rows, err := db.Query(query)
	if err != nil {
		// 记录错误
		log.Printf("Error executing query: %v", err, query)
		return
	}
	dur := time.Now().Sub(now).Milliseconds()
	select {
	case tpsCh <- RR{dur: dur, isInsert: false}:
	}

	defer rows.Close()

	// 遍历查询结果
	for rows.Next() {
		switch queryType {
		case 0:
			// 查询所有数据
			var count int
			if err := rows.Scan(&count); err != nil {
				// 记录错误
				log.Printf("Error scanning row: %v", err, query)
				continue
			}
			//fmt.Printf("Total number of records: %d\n", count)
		case 1:
			// 查询特定设备的数据
			var maxValue float64
			if err := rows.Scan(&maxValue); err != nil {
				// 记录错误
				log.Printf("Error scanning row: %v", err, query)
				continue
			}
			//fmt.Printf("Maximum value for device %d: %f\n", deviceID, maxValue)
		case 2:
			// 查询特定时间范围内的所有数据
			var avgValue float64
			if err := rows.Scan(&avgValue); err != nil {
				// 记录错误
				log.Printf("Error scanning row: %v", err, query)
				continue
			}
			//fmt.Printf("Average value between %s and %s: %f\n", start.Format("2006-01-02 15:04:05"), end.Format("2006-01-02 15:04:05"), avgValue)
		}
	}
	if err := rows.Err(); err != nil {
		// 记录错误
		log.Printf("Error iterating over rows: %v", err)
	}
}

``` 
|

and the table can not accept any DML operations after this script stopped.
```
truncate sensor_data_with_primary_key
drop table sensor_data_with_primary_key
insert into ...
```
|

connect to this cn: 
`mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u 018f27b5_0938_7abb_bcf9_d5789ce9bff3:admin:accountadmin  -p`

|

loki: 
https://grafana.cn-dev.matrixone.tech/d/e6bd2e11-0b11-4e82-bab6-c1c928ef9dcb/txn-metrics?orgId=1&var-interval=1m&var-unit=unit-cn-hangzhou&var-ds_prom=c02d1830-4030-4ab8-abd1-763e6dc64eec&var-physicalCluster=freetier-01&var-owner=All&var-pod=freetier-01-localpv-677f8d6647-cn-prnhx&var-pod=default-dn-0&from=1714356994533&to=1714371844533

goroutine stack:

[routine_018f284f-16a3-7b3a-9e81-a95fc6cc93a1.zip](https://github.com/matrixorigin/matrixone/files/15147107/routine_018f284f-16a3-7b3a-9e81-a95fc6cc93a1.zip)

### Steps to Reproduce

```Markdown
see above
```

**Comment by gouhongshen** [comment]
https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22xP2%22:%7B%22datasource%22:%22aee71632-e6c2-4299-906a-cc73bb62fd3b%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22CNSet%5C%22,%20matrixorigin_io_owner%3D%5C%22018f27b5-0938-7abb-bcf9-d5789ce9bff3%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22aee71632-e6c2-4299-906a-cc73bb62fd3b%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714371193096%22,%22to%22:%221714380146279%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by gouhongshen** [comment]
也许是这里死锁了:

```
goroutine 73303 [semacquire, 90 minutes]:
sync.runtime_Semacquire(0xc00073c0a0?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0x0?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc0062ab080)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:588 +0x26b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc0062ab080, 0xc03846c400?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:482 +0x579
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt(0xc3b85bd920, {0x4398938, 0xc03613a210}, 0xc018e51000, {0x439ac70, 0xc03613a180}, 0xc021ad38c0, {0x43c2d20?, 0xc036139b30?}, 0x0, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3911 +0x483d
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc3b85bd920, {0x4398938, 0xc036137f80}, 0xc124f41080)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4232 +0x187e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc3b85bd920, {0x4398938, 0xc036137f80}, 0x6058eb0?, 0xc038329590)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4403 +0x848
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc058b8e870, 0xc03579c270?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:252 +0x422
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0003a0310, {0x43cdc20, 0xc30d2ea700}, {0x3510960?, 0xc025df2460}, 0x4e0d35?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:529 +0xd1a
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc000287780, {0x43cdc20, 0xc30d2ea700})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:145 +0xc5
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x485

goroutine 158336 [select, 90 minutes]:
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).wait(0xc02ca00000, {0x4398938, 0xc03615d380})
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter.go:185 +0x15c
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock(0xc0390e3860, 0xc02adb8b40, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:142 +0x125
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock(0xc0390e3860, {0x4398938, 0xc03615d380}, 0xc0905c8218?, {0xc036023d70, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:89 +0x318
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(_, {_, _}, _, {_, _, _}, {0xc09afbb4d0, 0x10, 0x10}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:155 +0x4f1
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock({0x4398938, 0xc03615d380}, 0x0?, {0x43cb900, 0xc0a5877b60}, 0x0?, 0xc021ad38c0, 0x0, {0x3d, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:442 +0x8ce
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockTable({0x43cb900, 0xc0a5877b60}, 0xc021ad38c0, 0x43cb900?, {0x3d, 0x0, 0x0, 0x0, 0x18, 0xffff, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:300 +0x2e8
github.com/matrixorigin/matrixone/pkg/sql/compile.doLockTable({0x43cb900, 0xc0a5877b60}, 0xc021ad38c0, {0x43ee8a0, 0xc02bbc8000}, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:2749 +0xc5
github.com/matrixorigin/matrixone/pkg/sql/compile.lockTable({0x4398938?, 0xc03615d350?}, {0x43cb900?, 0xc0a5877b60?}, 0x0?, {0x43ee8a0?, 0xc02bbc8000?}, {0xc0438ce575?, 0x0?}, {0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:2769 +0xef
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).DropTable(0xc0782bd200, 0xc0062ab080)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:1800 +0x51f
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc0062ab080, 0xc0782bd200)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:361 +0x49e
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:581 +0x79
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65

goroutine 177862 [syscall]:
runtime/pprof.readProfile()
	/usr/local/go/src/runtime/cpuprof.go:230 +0x4b
runtime/pprof.profileWriter({0x436cba0?, 0xc034e008c0?})
	/usr/local/go/src/runtime/pprof/pprof.go:810 +0x51
created by runtime/pprof.StartCPUProfile
	/usr/local/go/src/runtime/pprof/pprof.go:794 +0x14a

goroutine 160192 [select, 78 minutes]:
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).Get(0xc0634860a0)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:78 +0xe5
github.com/matrixorigin/matrixone/pkg/lockservice.(*client).Send(0xc0005a0960, {0x4398938?, 0xc03aff0630?}, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:97 +0xb8
github.com/matrixorigin/matrixone/pkg/lockservice.(*remoteLockTable).lock(0xc027d29100, {0x4398938, 0xc03aff0630}, 0xc05cc96120, {0xc0808949d8?, 0x1, 0x1}, {{0x0, 0x1, 0x0, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_remote.go:91 +0x418
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(_, {_, _}, _, {_, _, _}, {0xc03ef17030, 0x10, 0x10}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:155 +0x4f1
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock({0x4398938, 0xc03aff0630}, 0x0?, {0x43cb900, 0xc0aa14f840}, 0x0?, 0xc017f1c580, 0xc313974460, {0x3d, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:442 +0x8ce
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockRows({0x43cb900, 0xc0aa14f840}, 0xc017f1c580, 0x2b881e0?, 0xc0808949a8?, {0x3d, 0x0, 0x0, 0x0, 0x18, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:342 +0x2e5
github.com/matrixorigin/matrixone/pkg/sql/compile.lockRows({0x43cb900, 0xc0aa14f840}, 0xc017f1c580, {0x43ee8a0?, 0xc026b72000?}, 0xc313974460, 0x359f8c0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:2803 +0xaa
github.com/matrixorigin/matrixone/pkg/sql/compile.lockMoTable(0xc0218a3b80, {0xc03a49b740, 0x7}, {0xc03a49b748, 0x1c}, 0x4a1487?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:2914 +0x19b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).lockMetaTables(0xc0218a3b80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:744 +0x238
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc0218a3b80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:559 +0x4f
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc0218a3b80, 0xc0369d5800?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:482 +0x579
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt(0xc024d79c20, {0x4398938, 0xc03af816e0}, 0xc018e51800, {0x439af48, 0xc08e8094d0}, 0xc017f1c580, {0x43c2d20?, 0xc03af83d60?}, 0x0, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3911 +0x483d
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc024d79c20, {0x4398938, 0xc03af81440}, 0xc259369f80)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4232 +0x187e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc024d79c20, {0x4398938, 0xc03af81440}, 0x6058eb0?, 0xc0893c32d8)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4403 +0x848
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc09b40da70, 0xc0241ebd80?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:252 +0x422
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0003a0310, {0x43cdc20, 0xc029d21500}, {0x3510960?, 0xc3d6435900}, 0xc0055c8db8?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:529 +0xd1a
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc000287780, {0x43cdc20, 0xc029d21500})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:145 +0xc5
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x485

```

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
