### ISSUE TITLE
[Bug]: ut TestDeadLockWithIndirectDependsOn failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15815]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8890478826/job/24410600589?pr=15810

```
2024-04-30T07:14:50.5691971Z 2024/04/30 06:55:39.049973 +0000 DEBUG cn-service.lockservice.allocator lock service allocator client closed {"uuid": ""}
2024-04-30T07:14:50.5692306Z panic: missing free for type: *lockservice.waiter, 02-0xc000f446c0(1) 
2024-04-30T07:14:50.5692428Z  create by: <<<>>>
2024-04-30T07:14:50.5692437Z 
2024-04-30T07:14:50.5692442Z 
2024-04-30T07:14:50.5692555Z goroutine 18 [running]:
2024-04-30T07:14:50.5692962Z github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0x1203320, 0xc000f446c0)
2024-04-30T07:14:50.5693334Z 	/home/runner/work/matrixone/matrixone/pkg/common/reuse/checker.go:133 +0x394
2024-04-30T07:14:50.5693756Z github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
2024-04-30T07:14:50.5694137Z 	/home/runner/work/matrixone/matrixone/pkg/common/reuse/sync_pool_based.go:46 +0xc5
2024-04-30T07:14:50.5694403Z FAIL	github.com/matrixorigin/matrixone/pkg/lockservice	186.355s
2024-04-30T07:14:50.5695213Z 2024/04/30 06:52:36.511777 +0000 INFO malloc/malloc.go:43 malloc {"max buffer size": 2147483648, "num shards": 4, "classes": 23, "min class size": 128, "max class size": 1048576, "buffer objects per class": 44}
2024-04-30T07:14:50.5695657Z 2024/04/30 06:52:36.649355 +0000 INFO logutil/internal.go:37 MO logger init, level=debug, log file=, stackLevel=

```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by sukki37** [comment]
repro： https://github.com/matrixorigin/matrixone/actions/runs/8892338107/job/24416193396?pr=15686

TestLockSuccWithKeepBindTimeout failed with the same reason

**Comment by iamlinjunhong** [comment]
处理中

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/9014868574/job/24768397157?pr=15944

**Comment by iamlinjunhong** [comment]
死锁检测，加锁，解锁并发，导致内存泄漏，正在解决

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9222158508/job/25372758136?pr=16395

![image](https://github.com/matrixorigin/matrixone/assets/60595215/eba6f866-aad4-411e-8ed5-c4a56aed370c)

**Comment by aressu1985** [comment]
fixed
