### ISSUE TITLE
[Bug]: TN Crash during stability test caused by listen tcp4 0.0.0.0:41012: bind: address already in use

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15845]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

42d05c2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"ERROR","time":"2024/05/06 05:58:02.270484 +0000","name":"hakeeper-client-backend","caller":"v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:515","msg":"close conneciton failed","remote":"stability-regression-dis-log-0.stability-regression-dis-log-headless.mo-nightly-42d05c2-20240430.svc:32001","backend-id":"018f4c7b-06fb-7ce4-a921-9563590d4ec9","session-id":0,"error":"close tcp4 10.10.5.238:49800->10.10.6.90:32001: use of closed network connection"}
{"level":"ERROR","time":"2024/05/06 05:58:02.275638 +0000","name":"logservice-client","caller":"morpc/client.go:385","msg":"gc idle backends task stopped"}
{"level":"ERROR","time":"2024/05/06 05:58:02.275635 +0000","name":"logservice-client","caller":"morpc/client.go:408","msg":"gc inactive backends task stopped"}
{"level":"INFO","time":"2024/05/06 05:58:02.290373 +0000","name":"logservice-client","caller":"morpc/client.go:376","msg":"gc idle backends task started"}
{"level":"INFO","time":"2024/05/06 05:58:02.290944 +0000","caller":"logservice/hakeeper_client.go:632","msg":"isHAKeeper: true, err: <nil>"}
{"level":"INFO","time":"2024/05/06 05:58:02.291342 +0000","name":"tn-service.lockservice.lock-client.lock-client","caller":"morpc/client.go:376","msg":"gc idle backends task started","uuid":"00000000-0000-0000-0000-100000000000"}
{"level":"INFO","time":"2024/05/06 05:58:02.291486 +0000","name":"tn-service.lockservice.allocator","caller":"lockservice/lock_table_allocator.go:451","msg":"clean cannot commit task","uuid":"00000000-0000-0000-0000-100000000000"}
{"level":"ERROR","time":"2024/05/06 05:58:02.291662 +0000","name":"tn-service.lockservice.lock-server","caller":"morpc/server.go:134","msg":"create rpc server failed","uuid":"00000000-0000-0000-0000-100000000000","name":"lock-server","error":"listen tcp4 0.0.0.0:41012: bind: address already in use"}
panic: listen tcp4 0.0.0.0:41012: bind: address already in use

goroutine 39 [running]:
github.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableAllocator).initServer(0xc00035f4a0, {0x1, {0xdf8475800}, 0x2800, 0x1e00, 0x400, 0x400, 0x6400000, 0x4000, 0x0, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_allocator.go:654 +0x265
github.com/matrixorigin/matrixone/pkg/lockservice.NewLockTableAllocator({0xc0028fa210, 0xd}, 0x2540be400, {0x1, {0xdf8475800}, 0x2800, 0x1e00, 0x400, 0x400, 0x6400000, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_allocator.go:96 +0x658
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).initLockTableAllocator(0xc0028fda00)
        /go/src/github.com/matrixorigin/matrixone/pkg/tnservice/store.go:388 +0xdf
github.com/matrixorigin/matrixone/pkg/tnservice.NewService(0xc0005a6700, {0x6e043a0, 0xc00281a060}, {0x6e1c400, 0xc001fb6570}, 0xc000219740, {0xc0087281d0, 0x2, 0x2})
        /go/src/github.com/matrixorigin/matrixone/pkg/tnservice/store.go:191 +0xa05
main.startTNService.func1({0x6dd1dd8, 0xc008c88630})
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:296 +0x339
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:277 +0xdd
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 1
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:272 +0x118
```

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
