### ISSUE TITLE
[Bug]: ut TestRemovedCronTask panic

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16053]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9042943535/job/24850082568

```
2024-05-11T10:58:42.4739670Z === RUN   TestRemovedCronTask
2024-05-11T10:58:42.4740260Z 2024/05/11 10:45:12.706386 +0000 INFO cn-service start to fetch cron tasks {"uuid": ""}
2024-05-11T10:58:42.4741620Z 2024/05/11 10:45:13.016899 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 0, "fetch-count": 1}
2024-05-11T10:58:42.4742570Z 2024/05/11 10:45:13.017063 +0000 INFO cn-service cron task triggered {"uuid": "", "cause": "now > next", "task": "t1/0/*/1 * * * * *"}
2024-05-11T10:58:42.4743470Z 2024/05/11 10:45:13.017195 +0000 INFO cn-service cron task triggered {"uuid": "", "cause": "normal", "task": "t1/0/*/1 * * * * *"}
2024-05-11T10:58:42.4744500Z 2024/05/11 10:45:13.308940 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4745380Z 2024/05/11 10:45:13.608911 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4746240Z 2024/05/11 10:45:13.918143 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4747140Z 2024/05/11 10:45:14.001040 +0000 INFO cn-service cron task triggered {"uuid": "", "cause": "normal", "task": "t1/1/*/1 * * * * *"}
2024-05-11T10:58:42.4748010Z 2024/05/11 10:45:14.209290 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4748880Z 2024/05/11 10:45:14.507575 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4749750Z 2024/05/11 10:45:14.806912 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4750640Z 2024/05/11 10:45:15.000255 +0000 INFO cn-service cron task triggered {"uuid": "", "cause": "normal", "task": "t1/2/*/1 * * * * *"}
2024-05-11T10:58:42.4751510Z 2024/05/11 10:45:15.107429 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4752380Z 2024/05/11 10:45:15.408475 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4753250Z 2024/05/11 10:45:15.706606 +0000 DEBUG cn-service new cron tasks fetched {"uuid": "", "current-count": 1, "fetch-count": 1}
2024-05-11T10:58:42.4753820Z 2024/05/11 10:45:15.706740 +0000 INFO cn-service stop to fetch cron tasks {"uuid": ""}
2024-05-11T10:58:42.4754390Z 2024/05/11 10:45:15.713117 +0000 INFO cn-service start to fetch cron tasks {"uuid": ""}
2024-05-11T10:58:42.4755280Z 2024/05/11 10:45:16.001060 +0000 INFO cn-service cron task triggered {"uuid": "", "cause": "normal", "task": "t1/3/*/1 * * * * *"}
2024-05-11T10:58:42.4756000Z 2024/05/11 10:45:16.001165 +0000 PANIC cn-service query cron_task_id = 1, return 0 records {"uuid": ""}
2024-05-11T10:58:42.4756340Z panic: query cron_task_id = 1, return 0 records
2024-05-11T10:58:42.4756350Z 
2024-05-11T10:58:42.4756530Z goroutine 174 [running]:
2024-05-11T10:58:42.4757080Z go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc00010b5f0, {0x0?, 0x0?, 0x0?})
2024-05-11T10:58:42.4757590Z 	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x9f
2024-05-11T10:58:42.4758050Z go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00010b5f0, {0x0, 0x0, 0x0})
2024-05-11T10:58:42.4758790Z 	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x5c3
2024-05-11T10:58:42.4760140Z github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Log(0xc000234c00, {0xc000040750, 0x28}, {{0x0, 0x0}, 0x4, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
2024-05-11T10:58:42.4760890Z 	/Users/runner/work/matrixone/matrixone/pkg/common/log/logger.go:169 +0x52e
2024-05-11T10:58:42.4761960Z github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Panic(0x1b6bd5a?, {0xc000040750, 0x28}, {0x0, 0x0, 0x0})
2024-05-11T10:58:42.4762520Z 	/Users/runner/work/matrixone/matrixone/pkg/common/log/logger.go:132 +0xa8
2024-05-11T10:58:42.4763150Z github.com/matrixorigin/matrixone/pkg/taskservice.(*cronJob).doRun(0xc000135b00)
2024-05-11T10:58:42.4763840Z 	/Users/runner/work/matrixone/matrixone/pkg/taskservice/task_service_cron.go:222 +0xd6e
2024-05-11T10:58:42.4764360Z github.com/matrixorigin/matrixone/pkg/taskservice.(*cronJob).Run(0xc000135b00)
2024-05-11T10:58:42.4765170Z 	/Users/runner/work/matrixone/matrixone/pkg/taskservice/task_service_cron.go:211 +0x485
2024-05-11T10:58:42.4766160Z github.com/robfig/cron/v3.(*Cron).startJob.func1()
2024-05-11T10:58:42.4767350Z 	/Users/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0xad
2024-05-11T10:58:42.4768750Z created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 172
2024-05-11T10:58:42.4770520Z 	/Users/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x105
2024-05-11T10:58:42.4771050Z FAIL	github.com/matrixorigin/matrixone/pkg/taskservice	12.016s
```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by w-zr** [comment]
这个ut不过只在macos上有，需要查一下

**Comment by w-zr** [comment]
fixed
