### ISSUE TITLE
[Bug]: dn panic by panic: runtime error: invalid memory address or nil pointer dereference during running tpcc 100-100 test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16111]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

4c5b76c

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9075014201/job/24936542335

duaring tpcc 100-100 benchmark test, DN panic by :
{"level":"INFO","time":"2024/05/14 08:47:14.093219 +0000","caller":"txnimpl/table.go:359","msg":"[End]","txn-start-ts":"1715676434027493589-1","operation":"transfer-deletes","operand":"BLK<272535-272543-018f7648-a6aa-7b97-b11d-17b0cff81b96-0-21>","phase":"Phase_Freeze"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x26641fa]

goroutine 1598 [running]:
panic({0x3f520c0?, 0x7743350?})
        /usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc05ec7f148 sp=0xc05ec7f098 pc=0x44162c
runtime.panicmem(...)
        /usr/local/go/src/runtime/panic.go:261
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc05ec7f1a8 sp=0xc05ec7f148 pc=0x458b98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/updates.(*DeleteChain).CollectDeletesLocked.func1(0xc09821e180)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/updates/delchain.go:395 +0x29a fp=0xc05ec7f2c0 sp=0xc05ec7f1a8 pc=0x26641fa
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*MVCCChain[...]).LoopChainLocked.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/mvccchain.go:182 +0x24 fp=0xc05ec7f2d8 sp=0xc05ec7f2c0 pc=0x35bb1a4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.LoopGenericSortedDList[...](0x400?, 0xc05ec7f348?, 0x0)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common/dlnode.go:231 +0x39 fp=0xc05ec7f2f8 sp=0xc05ec7f2d8 pc=0x25cb3d9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.(*GenericSortedDList[...]).Loop(0x0?, 0x400?, 0x7f?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common/dlnode.go:149 +0x36 fp=0xc05ec7f328 sp=0xc05ec7f2f8 pc=0x25cb356
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*MVCCChain[...]).LoopChainLocked(0xb173f0c648768f01?, 0x59cf60e45eed75a9?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/mvccchain.go:180 +0x4a fp=0xc05ec7f370 sp=0xc05ec7f328 pc=0x25cad4a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/updates.(*DeleteChain).CollectDeletesLocked(0xc1299754a0, {0x7feb5a2c90a0?, 0xc10f21a8e0}, 0xc17f2f6f48)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/updates/delchain.go:376 +0x1e5 fp=0xc05ec7f420 sp=0xc05ec7f370 pc=0x2663f05
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseObject).fillInMemoryDeletesLocked(0xc0fce1d310?, {0x7feb5a2c90a0, 0xc10f21a8e0}, 0x5, 0xc1b69ad420, 0xc10f21a8e0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/base.go:218 +0x75 fp=0xc05ec7f470 sp=0xc05ec7f420 pc=0x2683f15
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseObject).ResolvePersistedColumnData(0xc0fce1d310, {0x50d4af8, 0x7929240}, {0x7feb5a2c90a0, 0xc10f21a8e0}, 0xc114af4820?, 0x2a40?, 0x11, 0x0, 0xc0005e3180)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/base.go:627 +0x265 fp=0xc05ec7f510 sp=0xc05ec7f470 pc=0x2686ce5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseObject).dedupWithLoad(0xc0fce1d310, {0x50d4af8, 0x7929240}, {0x7feb5a2c90a0?, 0xc10f21a8e0}, {0x5171a78?, 0xc19b8e7b80?}, 0xc104dd2871?, 0x0, 0x5, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/base.go:644 +0x10c fp=0xc05ec7f600 sp=0xc05ec7f510 pc=0x2686fcc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseObject).PersistedBatchDedup(0xc0fce1d310, {0x50d4af8, 0x7929240}, {0x7feb5a2c90a0, 0xc10f21a8e0}, 0x38?, {0x5171a78, 0xc19b8e7b80}, {0xc0bc691200, 0x40, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/base.go:709 +0x2e5 fp=0xc05ec7f740 sp=0xc05ec7f600 pc=0x26877c5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*object).BatchDedup(0xc2039d5e18?, {0x50d4af8, 0x7929240}, {0x5188360?, 0xc10f21a8e0}, {0x5171a78, 0xc19b8e7b80}, {0xc0bc691200, 0x40, 0x40}, ...)

dn-log:
[dn_panic.log](https://github.com/matrixorigin/matrixone/files/15306129/dn_panic.log)

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%229Tr%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-4c5b76c%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715676168975%22,%22to%22:%221715678466057%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run tpcc 100-100 benchmark test
```

**Comment by aressu1985** [comment]
fixed
