### ISSUE TITLE
[Bug]: TestGCDropTable ut failed. 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16155]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0515-free-stmt

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:


https://github.com/matrixorigin/matrixone/actions/runs/9094766370/job/24996539031?pr=16144
```

### Actual Behavior

2024-05-15T11:44:10.1142454Z 2024/05/15 11:36:15.189573 +0000 INFO checkpoint/runner.go:930 [flushtabletail] scan result: pressure 1.588091254234314e-05, totalsize 16.65KB
2024-05-15T11:44:10.1143308Z 2024/05/15 11:36:15.185226 +0000 INFO dbutils/runtime.go:113 VectorPool[trasient-vector-pool][296/512]: FixSizedVec[296/307] VarlenVec[0/205], Reset/Hit/totalStats:[0/(331,0)331/462]
2024-05-15T11:44:10.1143834Z VectorPool[small-vector-pool][0/10240]: FixSizedVec[0/6144] VarlenVec[0/4096], Reset/Hit/totalStats:[0/(64,2)66/66]
2024-05-15T11:44:10.1144495Z 2024/05/15 11:36:15.201867 +0000 INFO checkpoint/runner.go:930 [flushtabletail] scan result: pressure 1.588091254234314e-05, totalsize 16.65KB
2024-05-15T11:44:10.1148199Z 2024/05/15 11:36:15.212995 +0000 INFO jobs/flushTableTail.go:350 [End] {"operation": "[534]FT-1001-2024-05-15 11:36:15.045153648 +0000 UTC m=+23.644166300", "txn-start-ts": "1715772975079154701-0", "aobj-deletes": 0, "aobj-merge-rows": 210, "nobj-deletes": 0, "duration": "132.350765ms", "operand": {"endTs": "1715772975078113632-0", "a-objs": "6d266b3c34a5,0e330bb9dde8,6b1d39c72f92,0de2e964def6,aaa0aa4b18ce,977ef1357361,f12076cdd59c,96cf96eb8961,1bb45b808e24,b1cea216f4d9,817293b3c3ab,9cbc6fdb79bb,be52a276a75a,b03a090d9b72,265e43835ce6,2cad8ebf9110,642cfdaf4065,5055f48cfbd4,3bf949c3ac4f,9159c23d8ee0,b4e5dc79dc86,", "delete-obj-ndv": 0, "to-objs": "3e218d1e3621,"}}
2024-05-15T11:44:10.1148942Z 2024/05/15 11:36:15.220184 +0000 INFO checkpoint/runner.go:930 [flushtabletail] scan result: pressure 1.588091254234314e-05, totalsize 16.65KB
2024-05-15T11:44:10.1149870Z 2024/05/15 11:36:15.211321 +0000 INFO dbutils/runtime.go:113 VectorPool[trasient-vector-pool][296/512]: FixSizedVec[296/307] VarlenVec[0/205], Reset/Hit/totalStats:[0/(331,0)331/462]
2024-05-15T11:44:10.1150410Z VectorPool[small-vector-pool][0/10240]: FixSizedVec[0/6144] VarlenVec[0/4096], Reset/Hit/totalStats:[0/(64,2)66/66]
2024-05-15T11:44:10.1150688Z panic: runtime error: invalid memory address or nil pointer dereference
2024-05-15T11:44:10.1150963Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3510a1e]
2024-05-15T11:44:10.1150971Z 
2024-05-15T11:44:10.1151089Z goroutine 7653 [running]:
2024-05-15T11:44:10.1151588Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*MVCCSlice[...]).GetUpdateNodeLocked(...)
2024-05-15T11:44:10.1151975Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/txn/txnbase/mvccslice.go:67
2024-05-15T11:44:10.1152452Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*MVCCSlice[...]).IsCommitted(0x59cd400)
2024-05-15T11:44:10.1152887Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/txn/txnbase/mvccslice.go:250 +0x3e
2024-05-15T11:44:10.1153465Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/updates.(*AppendMVCCHandle).allAppendsCommitted(0xc00243c4e0)
2024-05-15T11:44:10.1153872Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tables/updates/mvcc.go:282 +0xdd
2024-05-15T11:44:10.1154381Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/updates.(*AppendMVCCHandle).PrepareCompact(...)
2024-05-15T11:44:10.1154757Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tables/updates/mvcc.go:271
2024-05-15T11:44:10.1155200Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*aobject).PrepareCompact(0xc0000129c0)
2024-05-15T11:44:10.1155571Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tables/aobj.go:128 +0x19c
2024-05-15T11:44:10.1156383Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).fireFlushTabletail(0xc000124000, 0xc0024ecc00, 0xc002c61200, {0x0, 0x0, 0x0, 0x0, 0xe1, 0x47, 0xfd, ...})
2024-05-15T11:44:10.1156820Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:850 +0x36f
2024-05-15T11:44:10.1157382Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).tryCompactTree(0xc000124000, 0xc0039ffa40, 0x0)
2024-05-15T11:44:10.1157822Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:992 +0x101c
2024-05-15T11:44:10.1158458Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).onDirtyEntries(0xc002791e68?, {0xc002414000, 0x1, 0xc002791f80?})
2024-05-15T11:44:10.1158889Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:1015 +0x3aa
2024-05-15T11:44:10.1159278Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
2024-05-15T11:44:10.1159675Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x396
2024-05-15T11:44:10.1160183Z created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 7432
2024-05-15T11:44:10.1160690Z    /home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0x1a5
2024-05-15T11:44:10.1161002Z FAIL       github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/test     23.995s
2024-05-15T11:44:10.1161814Z 2024/05/15 11:35:51.489497 +0000 INFO malloc/malloc.go:42 malloc {"max buffer size": 1073741824, "num shards": 16, "classes": 23, "min class size": 128, "max class size": 1048576, "buffer objects per class": 23}

### Expected Behavior

success

### Steps to Reproduce

```Markdown
ci
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed

**Comment by daviszhen** [comment]
it was fixed
