### ISSUE TITLE
[Bug]: ut TestUnlockWithBindTimeout panic

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#16314]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

f797a1b4abe1f94fad0aa1231e98ae9359790a5d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```

2024-05-22T04:11:23.4041300Z --- FAIL: TestUnlockWithBindTimeout (0.16s)
2024-05-22T04:11:23.4041810Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-05-22T04:11:23.4042350Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-05-22T04:11:23.4042780Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-05-22T04:11:23.4043200Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a7f65c]
2024-05-22T04:11:23.4043210Z 
2024-05-22T04:11:23.4043380Z goroutine 43334 [running]:
2024-05-22T04:11:23.4043620Z testing.tRunner.func1.2({0x1b8bda0, 0x23c5f20})
2024-05-22T04:11:23.4044140Z 	/Users/runner/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x3f7
2024-05-22T04:11:23.4044300Z testing.tRunner.func1()
2024-05-22T04:11:23.4044810Z 	/Users/runner/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x716
2024-05-22T04:11:23.4044970Z panic({0x1b8bda0?, 0x23c5f20?})
2024-05-22T04:11:23.4045450Z 	/Users/runner/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
2024-05-22T04:11:23.4046180Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithLevel.AfterTest.func2()
2024-05-22T04:11:23.4047190Z 	/Users/runner/go/pkg/mod/github.com/matrixorigin/goutils@v1.3.1-0.20220604063047-388d67b4dbc4/leaktest/leak.go:118 +0x405
2024-05-22T04:11:23.4047680Z panic({0x1b8bda0?, 0x23c5f20?})
2024-05-22T04:11:23.4048180Z 	/Users/runner/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
2024-05-22T04:11:23.4049480Z github.com/matrixorigin/matrixone/pkg/lockservice.TestUnlockWithBindTimeout.func1({0x1e38828, 0xc0024e2a80}, 0x1b4d8c0?, 0xc000211400, 0xc000192500, 0xc00009f0c0?)
2024-05-22T04:11:23.4050120Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_remote_test.go:365 +0x1dc
2024-05-22T04:11:23.4051170Z github.com/matrixorigin/matrixone/pkg/lockservice.runBindChangedTests.func1(0xc000218e60?, {0xc0066102a0, 0x3, 0xc000218e68?})
2024-05-22T04:11:23.4051800Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_remote_test.go:594 +0x6c4
2024-05-22T04:11:23.4052870Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithLevel.func1.1({0x1e39a70?, 0xc000218e60}, {0xc002c26360, 0x3, 0x0?})
2024-05-22T04:11:23.4053440Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:3278 +0x1d6
2024-05-22T04:11:23.4054680Z github.com/matrixorigin/matrixone/pkg/lockservice.RunLockServicesForTest(0xff?, {0xc000331e28, 0x3, 0x3?}, 0x3b9aca00?, 0xc0006f3c00, 0xc0006f3df0, {0x0, 0x0, 0x0})
2024-05-22T04:11:23.4055220Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/test_helper.go:82 +0xc4e
2024-05-22T04:11:23.4055840Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithLevel.func1()
2024-05-22T04:11:23.4056410Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:3269 +0x126
2024-05-22T04:11:23.4056920Z github.com/matrixorigin/matrixone/pkg/common/reuse.RunReuseTests(0xc000328d20)
2024-05-22T04:11:23.4057430Z 	/Users/runner/work/matrixone/matrixone/pkg/common/reuse/checker.go:145 +0x5a
2024-05-22T04:11:23.4058810Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithLevel({0x1e31a60?, 0xc0025a8d00}, 0xff, {0xc000328e28, 0x3, 0x3}, 0x3b9aca00, 0xc000328e00, 0xc000328df0, {0x0, ...})
2024-05-22T04:11:23.4059390Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:3268 +0x285
2024-05-22T04:11:23.4060040Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithAdjustConfig(...)
2024-05-22T04:11:23.4060550Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:3248
2024-05-22T04:11:23.4061270Z github.com/matrixorigin/matrixone/pkg/lockservice.runBindChangedTests(0xc0025a8d00, 0x0, 0xc000328e80)
2024-05-22T04:11:23.4061900Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_remote_test.go:559 +0x20c
2024-05-22T04:11:23.4062510Z github.com/matrixorigin/matrixone/pkg/lockservice.TestUnlockWithBindTimeout(0xc0025a8d00)
2024-05-22T04:11:23.4063130Z 	/Users/runner/work/matrixone/matrixone/pkg/lockservice/service_remote_test.go:348 +0x5b
2024-05-22T04:11:23.4063320Z testing.tRunner(0xc0025a8d00, 0x1cbede8)
2024-05-22T04:11:23.4063830Z 	/Users/runner/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
2024-05-22T04:11:23.4064040Z created by testing.(*T).Run in goroutine 1
2024-05-22T04:11:23.4064540Z 	/Users/runner/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
2024-05-22T04:11:23.4064920Z FAIL	github.com/matrixorigin/matrixone/pkg/lockservice	196.455s
2024-05-22T04:11:23.4066310Z 2024/05/22 03:49:57.136037 +0000 INFO malloc/malloc.go:42 malloc {"max buffer size": 1073741824, "num shards": 16, "classes": 23, "min class size": 128, "max class size": 1048576, "buffer objects per class": 23}
2024-05-22T04:11:23.4067020Z 2024/05/22 03:49:57.174121 +0000 INFO logutil/internal.go:37 MO logger init, level=debug, log file=, stackLevel=
2024-05-22T04:11:23.4067220Z === RUN   TestClientConfigIsValidated
```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19413
