### ISSUE TITLE
[Bug]: ut / TestGetExprValue failed in 1.2-dev

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#16441]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

8dfb81b22

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9262813285/job/25480353437?pr=16426
```
=== RUN   TestGetExprValue

 ++++> set @@x=1
✔✔2024/05/28 03:17:47.937968 +0000 DEBUG cn-service.frontend query trace(ExecStmtInSameSession) {"uuid": "", "connection_id": 4294967295, "session_info": "", "session_id": "018fbd34-3b1e-730f-92f9-dc2a39cec2a9"}
2024/05/28 03:17:47.939394 +0000 DEBUG cn-service.frontend query trace status {"uuid": "", "connection_id": 4294967295, "statement": "", "status": "success", "span": {}, "session_info": "", "session_id": "018fbd34-3b1e-730f-92f9-dc2a39cec2a9", "statement_id": "018fbd34-3b22-720c-a2a9-ae42d0231993"}
🔥


Errors:

  * /home/runner/work/matrixone/matrixone/pkg/frontend/util_test.go 
  Line 664: - internal error: no statement info in context 
  goroutine 836 [running]:
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/reporting/reports.go:150 +0x47
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/reporting/reports.go:123 +0xbc
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:253 +0xfa
  panic({0x5e52660?, 0xc003806500?})
  	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
  github.com/golang/mock/gomock.(*Controller).finish(0xc00c71c600, 0x0, {0x5e52660, 0xc003806500})
  	/home/runner/go/pkg/mod/github.com/golang/mock@v1.6.0/gomock/controller.go:288 +0x73c
  github.com/golang/mock/gomock.(*Controller).Finish(0x6f?)
  	/home/runner/go/pkg/mod/github.com/golang/mock@v1.6.0/gomock/controller.go:269 +0x39
  panic({0x5e52660?, 0xc003806500?})
  	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
  github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.EndStatement({0x8588a48, 0xc002d01ec0}, {0x0?, 0x0}, 0x0, 0x0, 0x0)
  	/home/runner/work/matrixone/matrixone/pkg/util/trace/impl/motrace/report_statement.go:586 +0x9bf
  github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus({0x8588a48, 0xc002d01ec0}, {0x8631338, 0xc003741c00}, {0xc0002b0120, 0x12}, 0x0, {0x0?, 0x0?})
  	/home/runner/work/matrixone/matrixone/pkg/frontend/util.go:513 +0xa3a
  github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus({0x8588a48, 0xc002d01ec0}, {0x8631338, 0xc003741c00}, {0x85a4d48, 0xc004a79ec0}, 0x0?, {0x0, 0x0})
  	/home/runner/work/matrixone/matrixone/pkg/frontend/util.go:496 +0x185
  github.com/matrixorigin/matrixone/pkg/frontend.respClientWhenSuccess(0xc003741c00, 0xc0048c2600)
  	/home/runner/work/matrixone/matrixone/pkg/frontend/resp_client.go:43 +0x136
  github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc003741c00, 0xc0048c2600)
  	/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:2388 +0x973
  github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc003741c00, 0xc0048c2600, 0xc0043b5ea0)
  	/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:2912 +0x2f6e
  github.com/matrixorigin/matrixone/pkg/frontend.executeStmtInSameSession({0x8588a48, 0xc00c71c030}, 0xc003741c00, 0xc0048c2600, {0x85a4d48?, 0xc004a79ec0})
  	/home/runner/work/matrixone/matrixone/pkg/frontend/back_exec.go:548 +0x6cc
  github.com/matrixorigin/matrixone/pkg/frontend.getExprValue({0x85757b8?, 0xc0043b5d60}, 0xc003741c00, 0xc0048c2400)
  	/home/runner/work/matrixone/matrixone/pkg/frontend/util.go:315 +0x775
  github.com/matrixorigin/matrixone/pkg/frontend.TestGetExprValue.func1()
  	/home/runner/work/matrixone/matrixone/pkg/frontend/util_test.go:664 +0x426a
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/discovery.go:89 +0x2f
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:279 +0x2d3
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:112 +0x1cd
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x5fd
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x39
  github.com/jtolds/gls._m(0x0, 0xc0029b6150)
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x39
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0xabd57e0?, 0xc00c71c3f0?)
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x34
  github.com/jtolds/gls.addStackTag(...)
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc00c71c3f0)
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x176
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000221a50, 0xc00c71c210, 0xc004700040)
  	/home/runner/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x285
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:107 +0x54f
  	/home/runner/go/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/doc.go:76 +0x9b
  github.com/matrixorigin/matrixone/pkg/frontend.TestGetExprValue(0xc002af21a0)
  	/home/runner/work/matrixone/matrixone/pkg/frontend/util_test.go:502 +0x19b
  testing.tRunner(0xc002af21a0, 0x6305e08)
  	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
  created by testing.(*T).Run in goroutine 1
  	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
```

直接原因: in 1.2-dev的分支下，并发执行Case，如果遇到  `motrace.GetTracerProvider().IsEnable() == true` 的情况，就会有问题。
root  cause: 跟进中
![image](https://github.com/matrixorigin/matrixone/assets/3927687/fbfa1167-d652-4b7f-9877-21624918d0c4)

### Steps to Reproduce

```Markdown
mo1.2 CI
```

**Comment by xzxiong** [comment]
注：执行 `set xxxx = ?` 会触发一个 internal 的 `select 1 from dual` 的query ，但是 context 中会有真是的 statement_info 信息
基于此，报错的case 的 ctx 确实没有 statement_info 的。这个case 不明出处
![image](https://github.com/matrixorigin/matrixone/assets/3927687/56a8e1a8-e28a-4576-8926-16681d893b29)

**Comment by xzxiong** [comment]
备注，pr https://github.com/matrixorigin/matrixone/pull/16411 合并后，这个场景就不存在了。
新代码通过 `Session.tStmt` 进行访问，不再使用 `context.Context` 判断。

**Comment by xzxiong** [comment]
root case: 
该 ut 的ctx 就是没有 StatementInfo 的，在 RecordStatement 时 `motrace.GetTracerProvider().IsEnable() ==false`.  
当执行 EndStatmenet 时，遇到 `motrace.GetTracerProvider().IsEnable() == true` 的情况

解决方式:
pr #16411  合并即可。
