### ISSUE TITLE
[Bug]: ut failed: TestReLockSuccWithReStartCN

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16484]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[job-logs.txt](https://github.com/matrixorigin/matrixone/files/15485830/job-logs.txt)

https://github.com/matrixorigin/matrixone/actions/runs/9282453807/job/25553303734
```
2024-05-29T08:59:13.9908130Z     leak.go:138: Leaked goroutine: goroutine 51894 [select]:
2024-05-29T08:59:13.9909230Z         github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).startWriteLoop.func1.1()
2024-05-29T08:59:13.9910260Z         	/Users/runner/work/matrixone/matrixone/pkg/common/morpc/server.go:299 +0x42e
2024-05-29T08:59:13.9911710Z         github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).startWriteLoop.func1({0x1e4f980, 0xc0002e2930})
2024-05-29T08:59:13.9912720Z         	/Users/runner/work/matrixone/matrixone/pkg/common/morpc/server.go:335 +0x3c2
2024-05-29T08:59:13.9913920Z         github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
2024-05-29T08:59:13.9914970Z         	/Users/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:277 +0xe8
2024-05-29T08:59:13.9916500Z         created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 51817
2024-05-29T08:59:13.9917580Z         	/Users/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:272 +0x167
2024-05-29T08:59:13.9918140Z     leak.go:138: Leaked goroutine: goroutine 51895 [select]:
2024-05-29T08:59:13.9919230Z         github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).startWriteLoop.func1.1()
2024-05-29T08:59:13.9920390Z         	/Users/runner/work/matrixone/matrixone/pkg/common/morpc/server.go:299 +0x42e
2024-05-29T08:59:13.9921910Z         github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).startWriteLoop.func1({0x1e4f980, 0xc0002ad5f0})
2024-05-29T08:59:13.9922930Z         	/Users/runner/work/matrixone/matrixone/pkg/common/morpc/server.go:335 +0x3c2
2024-05-29T08:59:13.9924130Z         github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
2024-05-29T08:59:13.9925170Z         	/Users/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:277 +0xe8
2024-05-29T08:59:13.9926690Z         created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 51826
2024-05-29T08:59:13.9927760Z         	/Users/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:272 +0x167
2024-05-29T08:59:13.9928260Z --- FAIL: TestReLockSuccWithReStartCN (13.51s)
```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19413
