### ISSUE TITLE
[Bug]: cn crashed by panic panic: the transaction 018fcd1ecd4770f4a74a54abd8366f53 has been committed or aborted

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16548]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

7d957a2

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

during statbility test on distributed mode for about 15 hours, one cn was crashed by panic:
{"level":"ERROR","time":"2024/05/31 05:28:19.580008 +0000","name":"cn-service.frontend","caller":"frontend/util.go:495","msg":"query trace status","uuid":"303937314-3835-653832356236","statement":"select mo_account.account_id, mo_account.account_name, mo_account.status, mo_account.version, mo_account.suspended_time from mo_c_account where mo_account.account_name = sysbench_test2 order by mo_account.account_id","status":"fail","error":"the transaction 018fcd1ecd4770f4a74a54abd8366f53 hommitted or aborted","txn_id":"018fcd1ecd4770f4a74a54abd8366f53","session_info":"connectionId 34617969|10.10.4.44:49698|{account sysbench_test2:admin: -- 0:0:0}|go 10931338|018fcd1e-cd44-7f15-9295-86ba157deaa1","background":true,"session_id":"018fcd1e-cd46-7794-a6c2-05e5cd26d0e4","span":{"trace_id":"b5576028-138b-6fbc-b6f1-49c","span_id":"b4afa5ece854e44b"}}
{"level":"ERROR","time":"2024/05/31 05:28:19.580110 +0000","name":"cn-service.frontend","caller":"frontend/txn.go:62","msg":"the transaction 018fcd1ecd4770f4a74a543 has been committed or aborted","uuid":"30393731-3730-3164-3835-653832356236","session_info":"connectionId 34617969|10.10.4.44:49698|{account sysbench_test2:admin0}|goRoutineId 10931338|018fcd1e-cd44-7f15-9295-86ba157deaa1","background":true,"session_id":"018fcd1e-cd46-7794-a6c2-05e5cd26d0e4","span":{"trace_id":"b5576028-136f1-41838ac2c29c","span_id":"b4afa5ece854e44b"}}
{"level":"ERROR","time":"2024/05/31 05:28:19.580179 +0000","name":"cn-service.frontend","caller":"frontend/util.go:495","msg":"query trace status","uuid":"303937314-3835-653832356236","statement":"select mo_account.account_id, mo_account.account_name, mo_account.status, mo_account.version, mo_account.suspended_time from mo_c_account where mo_account.account_name = sysbench_test2 order by mo_account.account_id","status":"fail","error":"the transaction 018fcd1ecd4770f4a74a54abd8366f53 hommitted or aborted","txn_id":"018fcd1ecd4770f4a74a54abd8366f53","session_info":"connectionId 34617969|10.10.4.44:49698|{account sysbench_test2:admin: -- 0:0:0}|go 10931338|018fcd1e-cd44-7f15-9295-86ba157deaa1","background":true,"session_id":"018fcd1e-cd46-7794-a6c2-05e5cd26d0e4","span":{"trace_id":"b5576028-138b-6fbc-b6f1-49c","span_id":"b4afa5ece854e44b"}}
panic: the transaction 018fcd1ecd4770f4a74a54abd8366f53 has been committed or aborted

goroutine 10931338 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScanDataSource(0xc4e3b31520, 0xc39611e6c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:2274 +0x165b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).initDataSource(0xc39611e6c0, 0xc4e3b31520)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:115 +0x21d
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InitAllDataSource(0xc39611e6c0, 0xc4e3b31520)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:178 +0x3d
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InitAllDataSource(0xc400a1e480, 0xc4e3b31520)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:183 +0xcc
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InitAllDataSource(0xc5ae786120, 0xc4e3b31520)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:183 +0xcc
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc4e3b31520)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:621 +0x1ed
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc4e3b31520, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:505 +0xc25
github.com/matrixorigin/matrixone/pkg/frontend.executeResultRowStmtInBack(0xc272f63500, 0xc2d9b56800)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_result_row_stmt.go:50 +0x764
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtInBack(0xc272f63500, 0xc2d9b56800)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_exec.go:401 +0xe0a
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x6e4f710, 0xc272f63500}, 0xc2d9b56800)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2570 +0x51d
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x6e4f710, 0xc272f63500}, 0xc2d9b56800, {0x6e36d30, 0xc31a532400})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2537 +0x294
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x6e4f710, 0xc272f63500}, 0xc2d9b56800)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2503 +0x825
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x6e4f710, 0xc272f63500}, 0xc2d9b5680

cn log:
[cn_panic.log](https://github.com/user-attachments/files/15510196/cn_panic.log)

mo logs link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22l2W%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-7d957a2-20240530221410%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717132798310%22,%22to%22:%221717133795233%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by sukki37** [comment]
panic loc： https://github.com/matrixorigin/matrixone/blob/6d9337f36529f948f9eb0d79c5528ecb5f79f587/pkg/frontend/routine_manager.go#L485


<img width="1379" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/544cf186-c5f2-471b-bac7-b6fb3fa758aa">

**Comment by daviszhen** [comment]
分析中

**Comment by daviszhen** [comment]
debug pr已经提了

**Comment by daviszhen** [comment]
原因未知。等再跑出来。

**Comment by daviszhen** [comment]
原因未知。等再跑出来。

**Comment by daviszhen** [comment]
原因未知。等再跑出来。

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
原因未知。等再跑出来

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by sukki37** [comment]
Closing due to inactivity. Feel free to reopen if needed.
