### ISSUE TITLE
[Tech Request]: memory leaks in memory cache

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#16971]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

detected by the newly added checked allocator in this branch: https://github.com/reusee/matrixone/tree/mallocopts

allocation call stack 
```Markdown
panic: missing free: allocated at goroutine 180475 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x5e
github.com/matrixorigin/matrixone/pkg/common/malloc.getStacktraceID(0x0)
	/home/reus/mo/mallocopts/pkg/common/malloc/stacktrace.go:51 +0x23a
github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator).Allocate(0xc002c8b380, 0xc01bf7e700?, 0xc0487a55e0?)
	/home/reus/mo/mallocopts/pkg/common/malloc/checked_allocator.go:75 +0x6f
github.com/matrixorigin/matrixone/pkg/common/malloc.(*ProfileAllocator).Allocate(0xc00335e000, 0x30026, 0x7c5b76a01000?)
	/home/reus/mo/mallocopts/pkg/common/malloc/profile_allocator.go:117 +0x2c
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.newData({0x527c100, 0xc00335e000}, 0x30026, 0xc004188660)
	/home/reus/mo/mallocopts/pkg/fileservice/memorycache/data.go:53 +0x93
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.(*Cache).Alloc(...)
	/home/reus/mo/mallocopts/pkg/fileservice/memorycache/cache.go:71
github.com/matrixorigin/matrixone/pkg/fileservice.(*MemCache).Alloc(0x2?, 0x333?)
	/home/reus/mo/mallocopts/pkg/fileservice/mem_cache.go:94 +0x25
github.com/matrixorigin/matrixone/pkg/objectio.constructorFactory.func1({0x527c080?, 0xc1117eaae0?}, {0x7c5b76a01000?, 0xc02c4bbd50?, 0x4f0fe3?}, {0x527c2c0?, 0xc004188680?})
	/home/reus/mo/mallocopts/pkg/objectio/constructors.go:46 +0x112
github.com/matrixorigin/matrixone/pkg/fileservice.(*IOEntry).setCachedData(0xc0896d7768)
	/home/reus/mo/mallocopts/pkg/fileservice/io_entry.go:43 +0x17f
github.com/matrixorigin/matrixone/pkg/fileservice.(*IOEntry).ReadFromOSFile(0xc0896d7768, 0xc0e7eec5b8)
	/home/reus/mo/mallocopts/pkg/fileservice/io_entry.go:71 +0x33c
github.com/matrixorigin/matrixone/pkg/fileservice.(*DiskCache).Read.func3(0xc0896d7768)
	/home/reus/mo/mallocopts/pkg/fileservice/disk_cache.go:230 +0x5f0
github.com/matrixorigin/matrixone/pkg/fileservice.(*DiskCache).Read(0xc00588a5c0, {0x52bc318?, 0xc1117ea6f0?}, 0xc09df57320)
	/home/reus/mo/mallocopts/pkg/fileservice/disk_cache.go:242 +0x416
github.com/matrixorigin/matrixone/pkg/fileservice.readCache({0x52bc318?, 0xc1117ea6f0?}, {0x52bc5d0, 0xc00588a5c0}, 0xc09df57320)
	/home/reus/mo/mallocopts/pkg/fileservice/cache.go:167 +0xc4
github.com/matrixorigin/matrixone/pkg/fileservice.(*S3FS).Read(0xc000578f80, {0x52bc318, 0xc00bbc0750}, 0xc09df57320)
	/home/reus/mo/mallocopts/pkg/fileservice/s3_fs.go:473 +0x8fb
github.com/matrixorigin/matrixone/pkg/objectio.ReadOneBlockWithMeta({0x52bc318, 0xc00bbc0750}, 0xc02c4bcde0, {0xc0a07122d0, 0x2a}, 0x0, {0xc0ba0fc740, 0x18, 0xc02c4bcdb8?}, {0xc0896b0200, ...}, ...)
	/home/reus/mo/mallocopts/pkg/objectio/funcs.go:193 +0x78e
github.com/matrixorigin/matrixone/pkg/objectio.ReadOneBlock(...)
	/home/reus/mo/mallocopts/pkg/objectio/funcs.go:126
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.LoadColumnsData2({0x52bc318, 0xc00bbc0750}, 0x0, {0xc0ba0fc740, 0x18, 0x20}, {0xc0896b0200, 0x18, 0x20}, {0x5316440, ...}, ...)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/blockio/funcs.go:85 +0x21b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.LoadColumns2({0x52bc318?, 0xc00bbc0750?}, {0xc0ba0fc740?, 0xc02c4bcfa8?, 0x417ec5?}, {0xc0896b0200?, 0x2d33396132303931?, 0x3262372d65636134?}, {0x5316440, 0xc000578f80}, ...)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/blockio/funcs.go:165 +0xb1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.LoadPersistedColumnDatas({0x52bc318, 0xc00bbc0750}, 0xc01d0c7b30, 0xc002c928a0, 0xc0a0712210, {0xc04c044f00, 0x18, 0xc02c4bd010?}, {0xc112fc5180, 0x4f, ...}, ...)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tables/utils.go:95 +0x3eb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseObject).ResolvePersistedColumnDatas(0xc038914f00, {0x52bc318, 0xc00bbc0750}, {0x7c5ba4e2d1e0, 0xc0ea376ea0}, 0xc01d0c7b30, 0x0, {0xc04c044f00, 0x18, 0x18}, ...)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tables/base.go:574 +0x278
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*object).GetColumnDataByIds(0xc03aa89f38, {0x52bc318, 0xc00bbc0750}, {0x53960c0, 0xc0ea376ea0}, {0x4724c80, 0xc01d0c7b30}, 0x0, {0xc04c044f00, 0x18, ...}, ...)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tables/obj.go:97 +0x17f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnObject).GetColumnDataByIds(0x4030e40?, {0x52bc318?, 0xc00bbc0750?}, 0x0?, {0xc04c044f00?, 0x53642a0?, 0xc00267ec80?}, 0xc077d23700?)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/txn/txnimpl/object.go:314 +0xad
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*mergeObjectsTask).LoadNextBatch(0xc0ec09eb40, {0x52bc318, 0xc00bbc0750}, 0xdc9348ad?)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:203 +0x217
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.(*merger[...]).loadBlk(0xc0edfd18a0, {0x52bc318?, 0xc00bbc0750}, 0x2)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/mergesort/merger.go:228 +0x50
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.(*merger[...]).merge(0x5313e20, {0x52bc318, 0xc00bbc0750})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/mergesort/merger.go:108 +0x92
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.mergeObjs({0x52bc318, 0xc00bbc0750}, {0x5353620, 0xc0ec09eb40}, 0x6)
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/mergesort/merger.go:355 +0x738
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.DoMergeAndWrite({0x52bc318, 0xc00bbc0750}, 0x6, {0x5353620, 0xc0ec09eb40})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/mergesort/task.go:145 +0x778
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*mergeObjectsTask).Execute(0xc0ec09eb40, {0x52bc318, 0xc00bbc0750})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:292 +0x47b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc076839420, {0x52bc318, 0xc00bbc0750})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0x83
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc118d5dd40, {0x52bc318, 0xc00bbc0750})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/db/task.go:64 +0x13c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc076838fc0, {0x52bc318, 0xc00bbc0750})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0x83
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc008bb2500, {0x7c5b5ddd0278, 0xc118d5dd40})
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tasks/worker/worker.go:210 +0x37
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.(*poolHandler).doHandle.func1.func2()
	/home/reus/mo/mallocopts/pkg/vm/engine/tae/tasks/poolhandler.go:60 +0x2c
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/reus/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8d
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 1843
	/home/reus/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c


goroutine 5 [running]:
github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator).Allocate.func1(0x0?)
	/home/reus/mo/mallocopts/pkg/common/malloc/checked_allocator.go:79 +0x85

```

**Comment by reusee** [comment]
can reproduce with TestFuzzingDiskS3 in the above branch.

**Comment by reusee** [comment]
false positive. there was a bug in the CheckedAllocator.
