### ISSUE TITLE
[Bug]: panic: ants worker exits from panic: deadline not set in context

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#17015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

78449880e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2024-06-19T23:55:16+08:00	2024/06/19 15:55:16.729983 [ants]: worker exits from panic: deadline not set in context
2024-06-19T23:55:16+08:00	goroutine 448583 [running]:
2024-06-19T23:55:16+08:00	runtime/debug.Stack()
2024-06-19T23:55:16+08:00		/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
2024-06-19T23:55:16+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
2024-06-19T23:55:16+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
2024-06-19T23:55:16+08:00	panic({0x3e966a0?, 0x5220f40?})
2024-06-19T23:55:16+08:00		/usr/local/go/src/runtime/panic.go:770 +0x132
2024-06-19T23:55:16+08:00	github.com/matrixorigin/matrixone/pkg/common/morpc.(*stream).Send(0xc0437d6080, {0x5272478, 0xc0b5943800}, {0x5293180, 0xc09c33cdc0})
2024-06-19T23:55:16+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:1071 +0x3b8
2024-06-19T23:55:16+08:00	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).sendNotifyMessage.func2()
2024-06-19T23:55:16+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:1211 +0x198
2024-06-19T23:55:16+08:00	github.com/panjf2000/ants/v2.(*goWorker).run.func1()
2024-06-19T23:55:16+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8d
2024-06-19T23:55:16+08:00	created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 448774
2024-06-19T23:55:16+08:00		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c
2024-06-19T23:55:16+08:00	
```

### Expected Behavior

CN should not panic

### Steps to Reproduce

```Markdown
Deploy a cluster with commit 78449880e
```

**Comment by aylei** [comment]
context deadline not set in https://github.com/matrixorigin/matrixone/blob/78449880ea31b125fdc3c172a67c7c1874ba554a/pkg/sql/compile/scope.go#L1211

@m-schen PTAL

**Comment by m-schen** [comment]
收到，昨天的pr引起的。

**Comment by m-schen** [comment]
1.2分支可进行验证，已修复。

**Comment by aylei** [comment]
closing
