### ISSUE TITLE
[Bug]: ut TestShardCanBeAllocatedToMultiCN failed 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#17011]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9580104790/job/26414047588?pr=17008

[job-logs (1).txt.zip](https://github.com/user-attachments/files/15901391/job-logs.1.txt.zip)

```
2024-06-19T10:43:12.2027888Z running tests:
2024-06-19T10:43:12.2028213Z 	TestShardCanBeAllocatedToMultiCN (29m50s)
2024-06-19T10:43:12.2028493Z 
2024-06-19T10:43:12.2028611Z goroutine 2308 [running]:
2024-06-19T10:43:12.2028925Z testing.(*M).startAlarm.func1()
2024-06-19T10:43:12.2029452Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:2366 +0x265
2024-06-19T10:43:12.2029954Z created by time.goFunc
2024-06-19T10:43:12.2030389Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/time/sleep.go:177 +0x45
2024-06-19T10:43:12.2030731Z 
2024-06-19T10:43:12.2030874Z goroutine 1 [chan receive, 29 minutes]:
2024-06-19T10:43:12.2031330Z testing.(*T).Run(0xc0004c2820, {0x25795fc, 0x20}, 0x25e23b0)
2024-06-19T10:43:12.2031928Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1750 +0x851
2024-06-19T10:43:12.2032427Z testing.runTests.func1(0xc0004c2820)
2024-06-19T10:43:12.2032935Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:2161 +0x86
2024-06-19T10:43:12.2033450Z testing.tRunner(0xc0004c2820, 0xc00005db10)
2024-06-19T10:43:12.2033980Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1689 +0x21f
2024-06-19T10:43:12.2034715Z testing.runTests(0xc00018adb0, {0x4a12040, 0x3a, 0x3a}, {0xc00005dbb8?, 0xc00005dc00?, 0x4a77ce0?})
2024-06-19T10:43:12.2035460Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:2159 +0x8bf
2024-06-19T10:43:12.2036007Z testing.(*M).Run(0xc000556500)
202
```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by LeftHandCold** [comment]
repo: https://github.com/matrixorigin/matrixone/actions/runs/10106114383/job/27947719639?pr=17735

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
fixed
