### ISSUE TITLE
[Bug]: ut TestDiskCacheFileCache fail

### ISSUE THREAD

**Issue by Wenbin1002** [matrixorigin/matrixone#17531]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9933360574/job/27435995085

```
=== RUN   TestDiskCacheFileCache
2024-07-15T03:49:16.7900489Z 2024/07/15 03:43:26.541951 +0000 INFO fileservice/disk_cache.go:153 disk cache info loaded {"all files": 1, "cache files": 0, "time": "208.658µs"}
2024-07-15T03:49:16.7901097Z panic: missing free: address 0x7fea15b62000, size 3, allocated at goroutine 146 [running]:
2024-07-15T03:49:16.7901282Z runtime/debug.Stack()
2024-07-15T03:49:16.7901797Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/debug/stack.go:24 +0x67
2024-07-15T03:49:16.7902328Z github.com/matrixorigin/matrixone/pkg/common/malloc.GetStacktraceID(0x0)
2024-07-15T03:49:16.7902965Z 	/home/runner/work/matrixone/matrixone/pkg/common/malloc/stacktrace.go:53 +0x327
2024-07-15T03:49:16.7903786Z github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator).Allocate(0xc0005bbae0, 0x3, 0x0)
2024-07-15T03:49:16.7904483Z 	/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:81 +0xdf
2024-07-15T03:49:16.7905312Z github.com/matrixorigin/matrixone/pkg/common/malloc.(*ProfileAllocator).Allocate(0xc000facba0, 0x3, 0x0)
2024-07-15T03:49:16.7906071Z 	/home/runner/work/matrixone/matrixone/pkg/common/malloc/profile_allocator.go:108 +0x6b
2024-07-15T03:49:16.7906858Z github.com/matrixorigin/matrixone/pkg/common/malloc.(*MetricsAllocator).Allocate(0xc001ea5ce0, 0x3, 0x0)
2024-07-15T03:49:16.7907543Z 	/home/runner/work/matrixone/matrixone/pkg/common/malloc/metrics_allocator.go:70 +0x73
2024-07-15T03:49:16.7908172Z github.com/matrixorigin/matrixone/pkg/fileservice.(*IOEntry).prepareData(0xc0007106e0)
2024-07-15T03:49:16.7908773Z 	/home/runner/work/matrixone/matrixone/pkg/fileservice/io_entry.go:101 +0x14f
2024-07-15T03:49:16.7909760Z github.com/matrixorigin/matrixone/pkg/fileservice.(*IOEntry).ReadFromOSFile(0xc0007106e0, {0x37eeb88, 0xc002d7fb60}, 0xc0005b4058)
2024-07-15T03:49:16.7910358Z 	/home/runner/work/matrixone/matrixone/pkg/fileservice/io_entry.go:59 +0x7a
2024-07-15T03:49:16.7910997Z github.com/matrixorigin/matrixone/pkg/fileservice.(*DiskCache).Read.func3(0xc0007106e0)
2024-07-15T03:49:16.7911616Z 	/home/runner/work/matrixone/matrixone/pkg/fileservice/disk_cache.go:275 +0x84a
2024-07-15T03:49:16.7912527Z github.com/matrixorigin/matrixone/pkg/fileservice.(*DiskCache).Read(0xc0005c8340, {0x37eeb88, 0xc002d7fb60}, 0xc00005de10)
2024-07-15T03:49:16.7913143Z 	/home/runner/work/matrixone/matrixone/pkg/fileservice/disk_cache.go:287 +0x73d
2024-07-15T03:49:16.7914083Z github.com/matrixorigin/matrixone/pkg/fileservice.TestDiskCacheWriteAgain(0xc000466000)
2024-07-15T03:49:16.7914761Z 	/home/runner/work/matrixone/matrixone/pkg/fileservice/disk_cache_test.go:199 +0xa6f
2024-07-15T03:49:16.7914992Z testing.tRunner(0xc000466000, 0x2122240)
2024-07-15T03:49:16.7915482Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1689 +0x21f
2024-07-15T03:49:16.7915735Z created by testing.(*T).Run in goroutine 1
2024-07-15T03:49:16.7916218Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1742 +0x826
2024-07-15T03:49:16.7916243Z 
2024-07-15T03:49:16.7916252Z 
2024-07-15T03:49:16.7916437Z goroutine 5 [running]:
2024-07-15T03:49:16.7917214Z github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator).Allocate.func1(0xc0005ac28c)
2024-07-15T03:49:16.7917917Z 	/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:85 +0x15f
2024-07-15T03:49:16.7918331Z FAIL	github.com/matrixorigin/matrixone/pkg/fileservice	0.258s
```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by reusee** [comment]
fixed
