### ISSUE TITLE
[Question]: mo can not launch with python

### ISSUE THREAD

**Issue by shawn0915** [matrixorigin/matrixone#17627]
### Describe your problem

this version can not launch with udf.
mo-v1.2.2-musl-x86_64.zip
[root@centos7 mo-v1.2.2-musl-x86_64]# ./mo-service --daemon --launch ./etc/launch-with-python-udf-server/launch.toml &> mo.log &
[1] 83942

panic: python server exit with error: exit status 1

goroutine 1811 [running]:
github.com/matrixorigin/matrixone/pkg/udf/pythonservice.(*service).Start.func2(0xc0107e0840)
	/home/runner/work/matrixone/matrixone/pkg/udf/pythonservice/service.go:94 +0xb9
created by github.com/matrixorigin/matrixone/pkg/udf/pythonservice.(*service).Start in goroutine 1567
	/home/runner/work/matrixone/matrixone/pkg/udf/pythonservice/service.go:89 +0x519

**Comment by fengttt** [comment]
Close due to no activity.
