### ISSUE TITLE
[Bug]: ut failed. `TestS3FS`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#17637]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0705-add-plan-test

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:


https://github.com/matrixorigin/matrixone/actions/runs/10029177674/job/27717033383?pr=17583
```

### Actual Behavior

2024-07-21T14:56:10.2089105Z === RUN   TestS3FS
2024-07-21T14:56:10.2089305Z === RUN   TestS3FS/default_policy
2024-07-21T14:56:10.2089563Z === RUN   TestS3FS/default_policy/file_service
2024-07-21T14:56:10.2089850Z === RUN   TestS3FS/default_policy/file_service/basic
2024-07-21T14:56:10.2094111Z 2024/07/21 14:48:59.977078 +0000 INFO fileservice/aws_sdk_v2.go:177 new object storage {"sdk": "aws v2", "arguments": "{\"Name\":\"fs-2024-07-21-14-48-59\",\"KeyPrefix\":\"2024-07-21.14:48:59.427361\",\"SharedConfigProfile\":\"\",\"NoDefaultCredentials\":false,\"NoBucketValidation\":false,\"Concurrency\":0,\"Bucket\":\"***\",\"Endpoint\":\"https://***\",\"IsMinio\":false,\"Region\":\"***\",\"CertFiles\":null}"}
2024-07-21T14:56:10.2094368Z === NAME  TestS3FS/default_policy/file_service
2024-07-21T14:56:10.2094806Z     s3_fs_test.go:132: 
2024-07-21T14:56:10.2095900Z            Error Trace:    /home/runner/work/matrixone/matrixone/pkg/fileservice/s3_fs_test.go:132
2024-07-21T14:56:10.2097367Z                                                    /home/runner/work/matrixone/matrixone/pkg/fileservice/file_service_test.go:53
2024-07-21T14:56:10.2101497Z            Error:          Expected nil, but got: &moerr.Error{code:0x4e85, mysqlCode:0x451, message:"internal error: bad s3 config: operation error S3: HeadBucket, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Head \"https://***.***/\": dial tcp: lookup ***.***: i/o timeout", sqlState:"HY000", detail:""}
2024-07-21T14:56:10.2101911Z            Test:           TestS3FS/default_policy/file_service
2024-07-21T14:56:10.2102169Z --- FAIL: TestS3FS (5.55s)
2024-07-21T14:56:10.2102558Z     --- FAIL: TestS3FS/default_policy (5.55s)
2024-07-21T14:56:10.2103133Z         --- FAIL: TestS3FS/default_policy/file_service (5.55s)
2024-07-21T14:56:10.2103880Z             --- FAIL: TestS3FS/default_policy/file_service/basic (5.55s)
2024-07-21T14:56:10.2104457Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-07-21T14:56:10.2104950Z    panic: runtime error: invalid memory address or nil pointer dereference
2024-07-21T14:56:10.2105406Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cf165c]
2024-07-21T14:56:10.2105418Z 
2024-07-21T14:56:10.2105606Z goroutine 2531 [running]:
2024-07-21T14:56:10.2105878Z testing.tRunner.func1.2({0x1e94d80, 0x42d3440})
2024-07-21T14:56:10.2106377Z    /opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1631 +0x3f7
2024-07-21T14:56:10.2106549Z testing.tRunner.func1()
2024-07-21T14:56:10.2106971Z    /opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1634 +0x6b6
2024-07-21T14:56:10.2107172Z panic({0x1e94d80?, 0x42d3440?})
2024-07-21T14:56:10.2107582Z    /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:770 +0x132
2024-07-21T14:56:10.2108179Z github.com/matrixorigin/matrixone/pkg/fileservice.testS3FS.func1.1({0xc000522150, 0x16})
2024-07-21T14:56:10.2108746Z    /home/runner/work/matrixone/matrixone/pkg/fileservice/s3_fs_test.go:135 +0x2dc
2024-07-21T14:56:10.2109297Z github.com/matrixorigin/matrixone/pkg/fileservice.testFileService.func1(0xc00349c680)
2024-07-21T14:56:10.2109923Z    /home/runner/work/matrixone/matrixone/pkg/fileservice/file_service_test.go:53 +0x7c
2024-07-21T14:56:10.2110168Z testing.tRunner(0xc00349c680, 0xc0028bd170)
2024-07-21T14:56:10.2110670Z    /opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1689 +0x21f
2024-07-21T14:56:10.2110937Z created by testing.(*T).Run in goroutine 2530
2024-07-21T14:56:10.2111443Z    /opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1742 +0x826
2024-07-21T14:56:10.2111872Z FAIL       github.com/matrixorigin/matrixone/pkg/fileservice       62.813s

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10029177674/job/27717033383?pr=17583
```

**Comment by ouyuanning** [comment]
锦赛找乐声了解一下这块的逻辑吧

**Comment by ouyuanning** [comment]
还是乐声先看吧，锦赛手上其他事情还没处理完。
这个UT现在不知道还会不会有问题，有点久远了

**Comment by reusee** [comment]
这个只是测试时机器的网络问题，没有预期外行为，重跑即可
