### ISSUE TITLE
[Subtask]: missing Vector.Free in tae logtail handling

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#17686]
### Parent Issue

#16965

### Detail of Subtask

boot MO in this branch: https://github.com/reusee/matrixone/tree/freevector
```
panic: missing free. allocated at goroutine 1899 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
github.com/matrixorigin/matrixone/pkg/common/malloc.GetStacktraceID(0x1)
	/home/reus/mo/freevector/pkg/common/malloc/stacktrace.go:53 +0x21a
github.com/matrixorigin/matrixone/pkg/container/vector.newFreeGuard()
	/home/reus/mo/freevector/pkg/container/vector/free_guard.go:32 +0x18
github.com/matrixorigin/matrixone/pkg/container/vector.NewVecFromReuse(...)
	/home/reus/mo/freevector/pkg/container/vector/reuse.go:49
github.com/matrixorigin/matrixone/pkg/container/vector.NewVec({0x1c, 0x0, 0x0, 0x0, 0x8, 0x0, 0x0})
	/home/reus/mo/freevector/pkg/container/vector/vector.go:303 +0x48
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.NewVector({0x1c, 0x0, 0x0, 0x0, 0x8, 0x0, 0x0}, {0xc01838ee20, 0x1, 0x1})
	/home/reus/mo/freevector/pkg/vm/engine/tae/containers/vector.go:103 +0x4a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.MakeVector(...)
	/home/reus/mo/freevector/pkg/vm/engine/tae/containers/factory.go:23
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.makeRespBatchFromSchema(0xc00076e960, 0xc000703340)
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/tools.go:102 +0x526
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.NewCatalogLogtailRespBuilder({0x55d46e0, 0xc0183903f0}, 0x2, {0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x4e, ...}, ...)
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/handle.go:233 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.HandleSyncLogTailReq({0x55d46e0, 0xc0183903f0}, {0x7fc1c9285400, 0xc00bcfc1e0}, 0xc0112a9f00, 0xc00bd157a0, {0xc0123f1e60, 0xc0123f1e90, 0xc00b9010c0, {}, ...}, ...)
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/handle.go:174 +0x7b3
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*LogtailerImpl).TableLogtail(_, {_, _}, {0x1, 0x2, 0x0, {}, {0x0, 0x0, 0x0}, ...}, ...)
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/logtailer.go:95 +0x238
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).getSubLogtailPhase.func2()
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/service/server.go:515 +0xf4
runtime/trace.WithRegion({0x55d4638?, 0xc007bfe3f0?}, {0x4aceff4, 0x19}, 0xc01838f9c0)
	/usr/lib/golang/src/runtime/trace/annotation.go:141 +0xdd
github.com/matrixorigin/matrixone/pkg/common/moprobe.WithArgAndFn({0x55d4638, 0xc007bfe3f0}, 0x5, 0x0, 0x0, 0xc01838f9c0)
	/home/reus/mo/freevector/pkg/common/moprobe/probe.go:99 +0x85
github.com/matrixorigin/matrixone/pkg/common/moprobe.WithRegion(...)
	/home/reus/mo/freevector/pkg/common/moprobe/probe.go:88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).getSubLogtailPhase(0xc0112c6d00, {0x55d4638, 0xc007bfe3f0}, {0x1bf08e95a2, {0xc00ba79da0, 0x10}, 0xc0123f1710, 0xc012384c00}, {0x17e50806ecf9114e, 0x0, ...}, ...)
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/service/server.go:514 +0x305
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).logtailSender(0xc0112c6d00, {0x55d4638, 0xc007bfe3f0})
	/home/reus/mo/freevector/pkg/vm/engine/tae/logtail/service/server.go:473 +0x565
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/home/reus/mo/freevector/pkg/common/stopper/stopper.go:277 +0x6e
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 926
	/home/reus/mo/freevector/pkg/common/stopper/stopper.go:272 +0xb0



```

**Comment by Wenbin1002** [comment]
这部分重构之后实现已经完全不一样了
