### ISSUE TITLE
[Tech Request]: frontend.PrepareStmt.params double free

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#17810]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
stack trace

panic: double free.
=== last free stack trace begin ===
goroutine 2188 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
github.com/matrixorigin/matrixone/pkg/common/malloc.GetStacktraceID(0x1)
	/home/reus/mo/doublefree/pkg/common/malloc/stacktrace.go:53 +0x21a
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc020c06fc0, {0xc025a70f18, 0xc031c3ee18?, 0x30})
	/home/reus/mo/doublefree/pkg/common/mpool/mpool.go:612 +0x5a
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc000583dc0, {0xc025a70f18, 0x445bf5?, 0x30})
	/home/reus/mo/doublefree/pkg/common/mpool/mpool.go:634 +0x233
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Free(0xc025d69280, 0xc000583dc0)
	/home/reus/mo/doublefree/pkg/container/vector/vector.go:453 +0x39
github.com/matrixorigin/matrixone/pkg/frontend.(*PrepareStmt).Close(0xc026a68820)
	/home/reus/mo/doublefree/pkg/frontend/types.go:225 +0x7a
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).RemovePrepareStmt(0xc020c3c008, {0xc035a35453, 0xe})
	/home/reus/mo/doublefree/pkg/frontend/session.go:971 +0xc5
github.com/matrixorigin/matrixone/pkg/frontend.doDeallocate(0xc020c3c008, 0x4125460?, 0x55a8a80?)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:1114 +0xbb
github.com/matrixorigin/matrixone/pkg/frontend.handleDeallocate(...)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:1124
github.com/matrixorigin/matrixone/pkg/frontend.execInFrontend(0xc020c3c008, 0xc035a92ea0)
	/home/reus/mo/doublefree/pkg/frontend/self_handle.go:135 +0xf1b
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt(0xc020c3c008, 0xc035a92ea0)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2530 +0xc96
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x56edf40, 0xc020c3c008}, 0xc035a92ea0)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2498 +0x25a
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x56edf40, 0xc020c3c008}, 0xc035a92ea0, {0x56c1de0, 0xc035af6008})
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2467 +0x331
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x56edf40, 0xc020c3c008}, 0xc035a92ea0)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2424 +0x65b
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x56edf40, 0xc020c3c008}, 0xc035a92ea0)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2315 +0x10f
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc020c3c008, 0xc035a92ea0)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2280 +0x3f6
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc020c3c008, 0xc035a92ea0, 0xc035a62780)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:2874 +0x1fc6
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest(0xc020c3c008, 0xc035a92ea0, 0xc031c439e8)
	/home/reus/mo/doublefree/pkg/frontend/mysql_cmd_executor.go:3044 +0x18bb
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc020bf8c80, 0xc031c439e8)
	/home/reus/mo/doublefree/pkg/frontend/routine.go:290 +0x5f3
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc02035eb60, 0xc020bc0a50, {0xc0363d2c84, 0x5, 0x5})
	/home/reus/mo/doublefree/pkg/frontend/routine_manager.go:379 +0x390
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest(0xc01fdbd4d0, 0xc020bc0a50)
	/home/reus/mo/doublefree/pkg/frontend/server.go:457 +0x1f6
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc01fdbd4d0, 0xc020bc0a50)
	/home/reus/mo/doublefree/pkg/frontend/server.go:430 +0x45
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0xc02035eb60?, 0xc020bc0a50?)
	/home/reus/mo/doublefree/pkg/frontend/server.go:197 +0x65
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc01fdbd4d0, {0x564c998?, 0xc020a373d8?})
	/home/reus/mo/doublefree/pkg/frontend/server.go:188 +0x4f7
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 2154
	/home/reus/mo/doublefree/pkg/frontend/server.go:153 +0xfd

--- last free stack trace end ---

goroutine 2188 [running]:
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc000583dc0, {0xc025a70f18, 0x445bf5?, 0x30})
	/home/reus/mo/doublefree/pkg/common/mpool/mpool.go:614 +0x414
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Free(0xc025d69280, 0xc000583dc0)
	/home/reus/mo/doublefree/pkg/container/vector/vector.go:453 +0x39
github.com/matrixorigin/matrixone/pkg/frontend.(*PrepareStmt).Close(0xc026a68820)
	/home/reus/mo/doublefree/pkg/frontend/types.go:225 +0x7a
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).Close(0xc020c3c008)
	/home/reus/mo/doublefree/pkg/frontend/session.go:594 +0x279
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).cleanup.func1()
	/home/reus/mo/doublefree/pkg/frontend/routine.go:449 +0x2e5
sync.(*Once).doSlow(0xc02035eb60?, 0x33f8060?)
	/usr/lib/golang/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/lib/golang/src/sync/once.go:65
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).cleanup(0xc020c3c008?)
	/home/reus/mo/doublefree/pkg/frontend/routine.go:414 +0x3c
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed(0xc02035eb60, 0xc020bc0a50)
	/home/reus/mo/doublefree/pkg/frontend/routine_manager.go:318 +0x252
github.com/matrixorigin/matrixone/pkg/frontend.(*Conn).Close(0xc020bc0a50)
	/home/reus/mo/doublefree/pkg/frontend/mysql_buffer.go:160 +0x1af
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop.func1()
	/home/reus/mo/doublefree/pkg/frontend/server.go:193 +0x25
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0xc02035eb60?, 0xc020bc0a50?)
	/home/reus/mo/doublefree/pkg/frontend/server.go:200 +0x177
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc01fdbd4d0, {0x564c998?, 0xc020a373d8?})
	/home/reus/mo/doublefree/pkg/frontend/server.go:188 +0x4f7
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 2154
	/home/reus/mo/doublefree/pkg/frontend/server.go:153 +0xfd

```

The PrepareStmt at address 0xc026a68820 was closed multiple times, causing the params field double free.

found in this PR: https://github.com/matrixorigin/matrixone/pull/17805
```


### Why is this needed ?

_No response_

### Additional information

_No response_

**Comment by CJKkkk-315** [comment]
Free Close等操作都应该做非nil判断然后置nil 好像挺多地方要改的

**Comment by reusee** [comment]
这个是 cross pool free 引起的，不是 double free，先关闭。
