### ISSUE TITLE
[Tech Request]: vector double free in mergesort.SortBlockColumns

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#17816]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
2024/07/31 11:43:22.521176 [ants]: worker exits from panic: double free.
=== last free stack trace begin ===
goroutine 12853 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
github.com/matrixorigin/matrixone/pkg/common/malloc.GetStacktraceID(0x1)
	/home/reus/mo/doublefree/pkg/common/malloc/stacktrace.go:53 +0x21a
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc000682fc0, {0xc0365b7818, 0xc0000871d8?, 0x1500})
	/home/reus/mo/doublefree/pkg/common/mpool/mpool.go:613 +0x5f
github.com/matrixorigin/matrixone/pkg/container/vector.shuffleFixed[...](0xc049bd8d00, {0xc02c883800, 0xd5, 0xd5}, 0xc000682fc0)
	/home/reus/mo/doublefree/pkg/container/vector/vector.go:3151 +0x258
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Shuffle(0xc000087200?, {0xc02c883800?, 0x0?, 0x0?}, 0x17e72f4fdb13f980?)
	/home/reus/mo/doublefree/pkg/container/vector/vector.go:875 +0x3ce
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc049d060c0, 0x4, 0x17e72f4fdb13f980?}, 0x8035240?, 0xc007c9e820)
	/home/reus/mo/doublefree/pkg/vm/engine/tae/mergesort/func.go:36 +0x11c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*flushTableTailTask).flushAObjsForSnapshot(0xc0453a2c60, {0x56004b8, 0xc007dcdad0})
	/home/reus/mo/doublefree/pkg/vm/engine/tae/tables/jobs/flushTableTail.go:667 +0x2b2
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*flushTableTailTask).Execute(0xc0453a2c60, {0x56004b8, 0xc007dcdad0})
	/home/reus/mo/doublefree/pkg/vm/engine/tae/tables/jobs/flushTableTail.go:304 +0x532
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc049aa5b20, {0x56004b8, 0xc007dcdad0})
	/home/reus/mo/doublefree/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0x83
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc03b6eb620, {0x56004b8, 0xc007dcdad0})
	/home/reus/mo/doublefree/pkg/vm/engine/tae/db/task.go:64 +0x16c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc0490ca000, {0x56004b8, 0xc007dcdad0})
	/home/reus/mo/doublefree/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0x83
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc00813f780, {0x7f921d084d58, 0xc03b6eb620})
	/home/reus/mo/doublefree/pkg/vm/engine/tae/tasks/worker/worker.go:210 +0x37
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.(*poolHandler).doHandle.func1.func2()
	/home/reus/mo/doublefree/pkg/vm/engine/tae/tasks/poolhandler.go:60 +0x2c
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/reus/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8d
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 1878
	/home/reus/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

--- last free stack trace end ---

```

found in this PR: https://github.com/matrixorigin/matrixone/pull/17805
```


### Why is this needed ?

_No response_

### Additional information

_No response_

**Comment by reusee** [comment]
Caused by cross pool free, working as expected.
