### ISSUE TITLE
部署集群时pod报错：panic: operation not supported

### ISSUE THREAD

**Issue by TZ1414** [matrixorigin/matrixone#17885]
### Describe your problem

![image](https://github.com/user-attachments/assets/2ae4ae84-3b29-4f29-9766-8f0172c5fcd4)

按照文档，使用k8s部署MatrixOne时，只有1个pod是正常的，另外2个pod一直异常，查看pod的日志，提示以下报错，有一个对象不存在返回404，然后在 HEAD 请求之后，程序尝试对同一个对象执行 PUT 请求，最后显示panic: operation not supported

以下是日志信息：
{"level":"DEBUG","time":"2024/08/05 03:50:33.417346 +0000","name":"SHARED","caller":"http/middleware_http_logging.go:71","msg":"Response\nHTTP/1.1 404 Not Found\r\nAccept-Ranges: bytes\r\nDate: Mon, 05 Aug 2024 03:50:33 GMT\r\nServer: MinIO\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nVary: Origin\r\nVary: Accept-Encoding\r\nX-Amz-Id-2: 031423072ef68e6879032cee2c46afaa185781ac4628bca4e176bb1050a24693\r\nX-Amz-Request-Id: 17E8B89B0503271F\r\nX-Content-Type-Options: nosniff\r\nX-Minio-Error-Code: NoSuchKey\r\nX-Minio-Error-Desc: \"The specified key does not exist.\"\r\nX-Xss-Protection: 1; mode=block\r\nContent-Length: 0\r\n\r\n"}
{"level":"DEBUG","time":"2024/08/05 03:50:33.417439 +0000","name":"SHARED","caller":"retry/middleware.go:60","msg":"request failed with unretryable error https response error StatusCode: 404, RequestID: 17E8B89B0503271F, HostID: 031423072ef68e6879032cee2c46afaa185781ac4628bca4e176bb1050a24693, api error NotFound: Not Found"}
{"level":"DEBUG","time":"2024/08/05 03:50:33.417846 +0000","name":"SHARED","caller":"v4/v4.go:529","msg":"Request Signature:\n---[ CANONICAL STRING  ]-----------------------------\nPUT\n/minio-mo/etl/sys/logs/2024/08/05/rawlog/1722829833_00000000-0000-0000-0000-000000000001_LOG_415036875.csv\nx-id=PutObject\naccept-encoding:identity\namz-sdk-invocation-id:44498b15-b2ae-4585-91fe-1eacc16a6fca\namz-sdk-request:attempt=1; max=1\ncontent-length:53122\ncontent-type:application/octet-stream\nhost:minio1.example.com:9000\nx-amz-content-sha256:151c5e6b68e53833ffaa4df38a4cfa451a338f5e1d760428fe285bbaf82a6fe2\nx-amz-date:20240805T035033Z\n\naccept-encoding;amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date\n151c5e6b68e53833ffaa4df38a4cfa451a338f5e1d760428fe285bbaf82a6fe2\n---[ STRING TO SIGN ]--------------------------------\nAWS4-HMAC-SHA256\n20240805T035033Z\n20240805/us-west-2/s3/aws4_request\n4c88e4ae8e01fab18fb5d7810a9a39558a4186032e45476aa96252af27efc39a\n-----------------------------------------------------"}
{"level":"DEBUG","time":"2024/08/05 03:50:33.418013 +0000","name":"SHARED","caller":"http/middleware_http_logging.go:47","msg":"Request\nPUT /minio-mo/etl/sys/logs/2024/08/05/rawlog/1722829833_00000000-0000-0000-0000-000000000001_LOG_415036875.csv?x-id=PutObject HTTP/1.1\r\nHost: minio1.example.com:9000\r\nUser-Agent: aws-sdk-go-v2/1.18.0 os/linux lang/go/1.22.3 md/GOOS/linux md/GOARCH/amd64 api/s3/1.33.1\r\nContent-Length: 53122\r\nAccept-Encoding: identity\r\nAmz-Sdk-Invocation-Id: 44498b15-b2ae-4585-91fe-1eacc16a6fca\r\nAmz-Sdk-Request: attempt=1; max=1\r\nAuthorization: AWS4-HMAC-SHA256 Credential=BwrKpDqrlSQHuCroZXzr/20240805/us-west-2/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=fd7549a5881dfd5a818ae5b2cc89a004b9c4d98e182e9471319b533a8ee4afc5\r\nContent-Type: application/octet-stream\r\nX-Amz-Content-Sha256: 151c5e6b68e53833ffaa4df38a4cfa451a338f5e1d760428fe285bbaf82a6fe2\r\nX-Amz-Date: 20240805T035033Z\r\n\r\n"}
{"level":"DEBUG","time":"2024/08/05 03:50:33.421588 +0000","name":"SHARED","caller":"http/middleware_http_logging.go:71","msg":"Response\nHTTP/1.1 200 OK\r\nContent-Length: 0\r\nAccept-Ranges: bytes\r\nDate: Mon, 05 Aug 2024 03:50:33 GMT\r\nEtag: \"599c6b94a93d008297e0b715ce5dfcc6\"\r\nServer: MinIO\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nVary: Origin\r\nVary: Accept-Encoding\r\nX-Amz-Id-2: 031423072ef68e6879032cee2c46afaa185781ac4628bca4e176bb1050a24693\r\nX-Amz-Request-Id: 17E8B89B0528FCA2\r\nX-Amz-Version-Id: 0689d957-438e-4d49-aad6-446ab93cb482\r\nX-Content-Type-Options: nosniff\r\nX-Xss-Protection: 1; mode=block\r\n\r\n"}
{"level":"DEBUG","time":"2024/08/05 03:50:33.423162 +0000","caller":"fileservice/disk_cache.go:399","msg":"disk cache file written","path":"/var/lib/matrixone/data/etl-cache/fullsys/logs/2024/08/05/rawlog/1722829833_00000000-0000-0000-0000-000000000001_LOG_415036875.csv.mofscache"}
{"level":"INFO","time":"2024/08/05 03:50:33.423190 +0000","caller":"motrace/syncer.go:89","msg":"Wait signal done."}
panic: operation not supported

goroutine 534 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x0?, 0xc002bc0f00?})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001f33e10, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x24e
go.uber.org/zap.(*SugaredLogger).log(0xc000222a88, 0x4, {0x47b1aff?, 0x7fe69ca2d108?}, {0xc0020cc880?, 0xc0011ffe20?, 0xc00294cc38?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xec
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:189
github.com/matrixorigin/matrixone/pkg/logutil.DragonboatAdaptLogger.Panicf(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/logutil/dragonboat.go:65
github.com/lni/dragonboat/v4/logger.(*dragonboatLogger).Panicf(0xc002b882d0?, {0x47b1aff, 0x3}, {0xc0020cc880, 0x1, 0x1})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20240312080931-1b40809d7cea/logger/logger.go:132 +0x51
github.com/lni/dragonboat/v4.panicNow(...)
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20240312080931-1b40809d7cea/nodehost.go:2230
github.com/lni/dragonboat/v4.(*NodeHost).startShard(0xc000321c08, 0xc002cfff20, 0x0, 0xc00294d470, {0x20001, 0x0, 0x1, 0x1, 0xa, 0x1, ...}, ...)
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20240312080931-1b40809d7cea/nodehost.go:1649 +0xd88
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica(0x1?, 0x0?, 0x1?, 0x24?, {0x20001, 0x0, 0x1, 0x1, 0xa, 0x1, ...})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20240312080931-1b40809d7cea/nodehost.go:508 +0xe5
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica(0xc0068fe388, 0x20001, 0xa39b83?, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:216 +0xa8
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper(_, {_, _}, {{0x5331b20, 0x7b1e980}, 0x7ad1b65f09d8be6e, {0xc0007cf260, 0x24}, 0xc8, {0x47d6d42, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_bootstrap.go:41 +0x8a
main.startLogService.func1({0x529a918, 0xc00696db30})
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:367 +0x131
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:277 +0x6e
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 1
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:272 +0xb0

**Comment by Rosyrain** [comment]
您好，请问具体参考的k8s部署的文档是哪篇呢，能否麻烦给一个地址，谢谢您🌹🌹

**Comment by sukki37** [comment]
Closing due to inactivity. Feel free to reopen if needed.
