### ISSUE TITLE
[Bug]: regression bvt failed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#17893]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bca6edc16

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/10245788611/job/28342481777
![image](https://github.com/user-attachments/assets/c6165c55-52e0-48cd-9de2-af606cbf446a)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x263ab85]

goroutine 666 [running]:
github.com/matrixorigin/matrixone/pkg/util/export/etl/db.(*CSVWriter).Flush(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/db/db_holder.go:263
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*ContentBuffer).isEmpty(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace/buffer_content.go:141
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*ContentBuffer).IsEmpty(0xc008ef5900)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace/buffer_content.go:137 +0x85
github.com/matrixorigin/matrixone/pkg/util/export.(*bufferHolder).getGenerateReq(0xc0099b5cc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:236 +0xec
github.com/matrixorigin/matrixone/pkg/util/export.init.func1.1(0xc0099b5cc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:614 +0xa9
github.com/matrixorigin/matrixone/pkg/util/export.(*bufferHolder).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:119 +0x8d
created by time.goFunc
	/usr/local/go/src/time/sleep.go:177 +0x2d
```

### Steps to Reproduce

```Markdown
regression tke bvt
```

**Comment by xzxiong** [comment]
fixed
