### ISSUE TITLE
[Bug]: ut fail in TestBasicCluster, panic: missing sql executor in service "1-cn-1"

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#18154]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-08-15T08:03:46.2970982Z panic: missing sql executor in service "1-cn-1"
2024-08-15T08:03:46.2970995Z 
2024-08-15T08:03:46.2971195Z goroutine 1791 [running]:
2024-08-15T08:03:46.2972637Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.execReadSql({0x9eedf80, 0xc00bee9cc0}, {0x9fb2aa0, 0xc000136c08}, {0xc000162320, 0x9d}, 0x1)
2024-08-15T08:03:46.2973483Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:1783 +0x565
2024-08-15T08:03:46.2974613Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).replayCatalogCache(0xc00002b6e8, {0x9eedf80, 0xc00bee9cc0}, 0xc00002b600)
2024-08-15T08:03:46.2975354Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:628 +0x425
2024-08-15T08:03:46.2976382Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).connect(0xc00002b6e8, {0x9eedf80, 0xc00bee9cc0}, 0xc00002b600)
2024-08-15T08:03:46.2977123Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:717 +0xda5
2024-08-15T08:03:46.2977995Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*connector).run(0xc00d399700, {0x9eedf80, 0xc00bee9cc0})
2024-08-15T08:03:46.2978722Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:209 +0x99
2024-08-15T08:03:46.2979628Z created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).InitLogTailPushModel in goroutine 563
2024-08-15T08:03:46.2980362Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:1441 +0x392
2024-08-15T08:03:46.2980731Z FAIL	github.com/matrixorigin/matrixone/pkg/embed	11.407s
2024-08-15T08:04:06.2801468Z ?   	github.com/matrixorigin/matrixone/pkg/txn/storage	[no test files]
2024-08-15T08:04:13.2542972Z ?   	github.com/matrixorigin/matrixone/pkg/txn/storage/tae	[no test files]
2024-08-15T08:04:13.2549408Z ?   	github.com/matrixorigin/matrixone/pkg/txn/trace	[no test files]
2024-08-15T08:04:13.2554365Z ?   	github.com/matrixorigin/matrixone/pkg/txn/util	[no test files]
2024-08-15T08:04:13.2555521Z ?   	github.com/matrixorigin/matrixone/pkg/udf	[no test files]
2024-08-15T08:04:13.2557876Z ?   	github.com/matrixorigin/matrixone/pkg/udf/pythonservice	[no test files]
2024-08-15T08:04:16.6442439Z ?   	github.com/matrixorigin/matrixone/pkg/util/executor/test	[no test files]
2024-08-15T08:04:20.1310553Z ?   	github.com/matrixorigin/matrixone/pkg/util/export/example	[no test files]
2024-08-15T08:04:22.4270412Z ?   	github.com/matrixorigin/matrixone/pkg/util/internalExecutor	[no test files]
2024-08-15T08:04:25.9774510Z ?   	github.com/matrixorigin/matrixone/pkg/util/metric/v2	[no test files]
2024-08-15T08:04:27.8968394Z ?   	github.com/matrixorigin/matrixone/pkg/util/profile	[no test files]
2024-08-15T08:04:27.8971211Z ?   	github.com/matrixorigin/matrixone/pkg/util/protoc	[no test files]
2024-08-15T08:04:34.5255910Z ?   	github.com/matrixorigin/matrixone/pkg/util/sysview	[no test files]
2024-08-15T08:04:38.6611612Z ?   	github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace/example	[no test files]
2024-08-15T08:04:38.6620452Z ?   	github.com/matrixorigin/matrixone/pkg/vectorize/floor	[no test files]
2024-08-15T08:04:41.3571854Z ?   	github.com/matrixorigin/matrixone/pkg/vectorize/momath	[no test files]
2024-08-15T08:04:41.3574314Z ?   	github.com/matrixorigin/matrixone/pkg/vectorize/shuffle	[no test files]
2024-08-15T08:04:41.5476795Z ?   	github.com/matrixorigin/matrixone/pkg/version	[no test files]
2024-08-15T08:04:41.5478301Z ?   	github.com/matrixorigin/matrixone/pkg/vm	[no test files]
2024-08-15T08:05:01.2239577Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common/utils	[no test files]
2024-08-15T08:05:04.0036243Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db	[no test files]
2024-08-15T08:05:07.2248881Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/dbutils	[no test files]
2024-08-15T08:05:07.2251118Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v1	[no test files]
2024-08-15T08:05:07.2252765Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/merge	[no test files]
2024-08-15T08:05:13.9147573Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/testutil	[no test files]
2024-08-15T08:05:13.9154477Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/iface/data	[no test files]
2024-08-15T08:05:13.9156345Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/iface/handle	[no test files]
2024-08-15T08:05:13.9327794Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/iface/rpchandle	[no test files]
2024-08-15T08:05:13.9329566Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/iface/txnif	[no test files]
2024-08-15T08:05:18.3004190Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver	[no test files]
2024-08-15T08:05:18.8181958Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/entry	[no test files]
2024-08-15T08:05:22.3603309Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/samples/replay	[no test files]
2024-08-15T08:05:44.7577819Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs	[no test files]
2024-08-15T08:05:53.0914447Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks	[no test files]
2024-08-15T08:05:53.0916339Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops	[no test files]
2024-08-15T08:05:53.1174360Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/base	[no test files]
2024-08-15T08:05:53.1176440Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker	[no test files]
2024-08-15T08:05:53.1177914Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/base	[no test files]
2024-08-15T08:05:53.1179358Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/testutils	[no test files]
2024-08-15T08:05:53.1180738Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/testutils/config	[no test files]
2024-08-15T08:05:53.1651809Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/testutils/mocks	[no test files]
2024-08-15T08:05:53.1657070Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase	[no test files]
2024-08-15T08:06:02.9691054Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal	[no test files]
2024-08-15T08:06:15.4199782Z ?   	github.com/matrixorigin/matrixone/pkg/vm/engine/test/testutil	[no test files]
2024-08-15T08:06:15.4201496Z ?   	github.com/matrixorigin/matrixone/pkg/vm/message	[no test files]
2024-08-15T08:06:15.4212451Z ?   	github.com/matrixorigin/matrixone/pkg/vm/pipeline	[no test files]

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10400630190/job/28801546030?pr=18139
```

**Comment by zhangxu19830126** [comment]
must be use after internal sql executor initialization is complete

**Comment by aptend** [comment]
not working on it yet

**Comment by aptend** [comment]
fixed
