### ISSUE TITLE
[Bug]: ci ut failure. TestNodeGossip

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#18196]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0814-debug-3895

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/10428781554/job/28886436260?pr=18189
```

### Actual Behavior

2024-08-17T04:03:53.7845220Z === RUN   TestNodeGossip
2024-08-17T04:03:53.7845937Z 2024/08/17 03:42:30.984746 +0000 INFO cn-service.gossip node join cluster successfully {"uuid": "", "node ID": "n1", "joined nodes": 0}
2024-08-17T04:03:53.7846136Z     node_test.go:64: 
2024-08-17T04:03:53.7846861Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/gossip/node_test.go:64
2024-08-17T04:03:53.7847141Z         	Error:      	Received unexpected error:
2024-08-17T04:03:53.7849087Z         	            	internal error: CN gossip create node failed: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "127.0.0.1" port 38002: listen tcp 127.0.0.1:38002: bind: address already in use
2024-08-17T04:03:53.7849379Z         	Test:       	TestNodeGossip
2024-08-17T04:03:53.7849582Z     node_test.go:69: 
2024-08-17T04:03:53.7850134Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/gossip/node_test.go:69
2024-08-17T04:03:53.7850500Z         	Error:      	Received unexpected error:
2024-08-17T04:03:53.7851200Z         	            	internal error: cannot join gossip cluster, because node has not been created
2024-08-17T04:03:53.7851457Z         	Test:       	TestNodeGossip
2024-08-17T04:03:53.7852005Z 2024/08/17 03:42:30.985318 +0000 INFO cn-service.gossip leaving gossip cluster {"uuid": "", "node ID": "n1"}
2024-08-17T04:03:53.7852237Z --- FAIL: TestNodeGossip (0.00s)
2024-08-17T04:03:53.7852656Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-08-17T04:03:53.7853013Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-08-17T04:03:53.7853365Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf2e05d]
2024-08-17T04:03:53.7853372Z 
2024-08-17T04:03:53.7853514Z goroutine 171 [running]:
2024-08-17T04:03:53.7853749Z testing.tRunner.func1.2({0x1457020, 0x33372f0})
2024-08-17T04:03:53.7854132Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1631 +0x3f7
2024-08-17T04:03:53.7854328Z testing.tRunner.func1()
2024-08-17T04:03:53.7854636Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1634 +0x6b6
2024-08-17T04:03:53.7854816Z panic({0x1457020?, 0x33372f0?})
2024-08-17T04:03:53.7855117Z 	/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:770 +0x132
2024-08-17T04:03:53.7855494Z github.com/hashicorp/memberlist.(*Memberlist).NumMembers(0x0)
2024-08-17T04:03:53.7856173Z 	/home/runner/go/pkg/mod/github.com/matrixorigin/memberlist@v0.5.1-0.20230322082342-95015c95ee76/memberlist.go:581 +0x3d
2024-08-17T04:03:53.7856538Z github.com/matrixorigin/matrixone/pkg/gossip.(*Node).NumMembers(...)
2024-08-17T04:03:53.7856824Z 	/home/runner/work/matrixone/matrixone/pkg/gossip/node.go:198
2024-08-17T04:03:53.7857191Z github.com/matrixorigin/matrixone/pkg/gossip.TestNodeGossip(0xc000fd0000)

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10428781554/job/28886436260?pr=18189
```

**Comment by YANGGMM** [comment]
repo in : https://github.com/matrixorigin/matrixone/actions/runs/10449457667/job/28931833566?pr=18228

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
fixed
