### ISSUE TITLE
[Bug]: ut fails in Test_InsertRows

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#18238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-08-20T01:25:53.3101101Z panic: missing sql executor in service ""
2024-08-20T01:25:53.3101109Z 
2024-08-20T01:25:53.3101218Z goroutine 245 [running]:
2024-08-20T01:25:53.3101834Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.execReadSql({0x86c3d10, 0xc0002cf6c0}, {0x877a600, 0xc00013dc08}, {0xc0001de320, 0x9d}, 0x1)
2024-08-20T01:25:53.3102177Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:1786 +0x565
2024-08-20T01:25:53.3102798Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).replayCatalogCache(0xc0020d54e8, {0x86c3d10, 0xc0002cf6c0}, 0xc0020d5400)
2024-08-20T01:25:53.3103449Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:649 +0x69e
2024-08-20T01:25:53.3104136Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).connect(0xc0020d54e8, {0x86c3d10, 0xc0002cf6c0}, 0xc0020d5400)
2024-08-20T01:25:53.3104536Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:738 +0xda5
2024-08-20T01:25:53.3105001Z github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*connector).run(0xc0020a4a00, {0x86c3d10, 0xc0002cf6c0})
2024-08-20T01:25:53.3105402Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:210 +0x99
2024-08-20T01:25:53.3105886Z created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).InitLogTailPushModel in goroutine 22
2024-08-20T01:25:53.3106297Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:1470 +0x392
2024-08-20T01:25:53.3106530Z FAIL	github.com/matrixorigin/matrixone/pkg/vm/engine/test	0.232s
2024-08-20T01:25:53.3106701Z === RUN   TestWhatVectorCouldBeAcceptedForPool
2024-08-20T01:25:53.3106962Z --- PASS: TestWhatVectorCouldBeAcceptedForPool (0.00s)
2024-08-20T01:25:53.3107066Z === RUN   TestVectorPool
2024-08-20T01:25:53.3107212Z --- PASS: TestVectorPool (0.00s)
2024-08-20T01:25:53.3107295Z PASS
2024-08-20T01:25:53.3107509Z ok  	github.com/matrixorigin/matrixone/pkg/vm/process	1.184s
2024-08-20T01:25:53.3107584Z FAIL
2024-08-20T01:25:53.3108005Z find: ‘pkg/vm/engine/aoe/test/*’: No such file or directory
2024-08-20T01:25:53.3108132Z make: *** [Makefile:163: ut] Error 1

2024-08-20T01:25:53.3431599Z # FAILED CASES:
2024-08-20T01:25:53.3431606Z 
2024-08-20T01:25:53.3431762Z 
2024-08-20T01:25:53.3431862Z # UNKNOWN CASES:
2024-08-20T01:25:53.3431968Z === RUN   Test_InsertRows
2024-08-20T01:25:53.3431973Z 
2024-08-20T01:25:53.3432071Z # BUILD FAILED in UT:
2024-08-20T01:25:53.3432166Z echo ""
2024-08-20T01:25:53.3432172Z 

### Steps to Reproduce

```Markdown
https://github.com/badboynt1/matrixone/actions/runs/10463493728/job/28975591251?pr=316
```

**Comment by jensenojs** [comment]
辛苦红深哥帮忙跟踪一下这个问题, @gouhongshen

**Comment by gouhongshen** [comment]
blocking by other higher-priority issues
