### ISSUE TITLE
[Bug]: ut test fails in TestNewMOCollector_BufferCnt

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#18352]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-08-27T01:44:48.6417788Z 2024/08/27 01:14:48.618650 +0000 DEBUG export/batch_processor_test.go:146 wait BatchFinish
2024-08-27T01:44:48.6419166Z     batch_processor_test.go:284: done 2rd buffer fill, then send the last elem
2024-08-27T01:44:48.6420442Z     batch_processor_test.go:294: done all dummy action, then do check result
2024-08-27T01:44:48.6421592Z     batch_processor_test.go:288: dummy hung goroutine started.
2024-08-27T01:44:48.6422630Z     batch_processor_test.go:290: dummy hung goroutine finished.
2024-08-27T01:44:48.6425116Z 2024/08/27 01:14:53.616963 +0000 INFO cn-service.MOCollector export/batch_processor.go:729 stats {"uuid": "test", "MODiscardable": true, "MaxBufferCnt": 2, "TotalBufferCnt": 2, "QueueLength": 0, "NumBufferCnt": 2, "NumDiscardCnt": 0}
2024-08-27T01:44:48.6427451Z     batch_processor_test.go:301: success: hang by buffer alloc: no slot.
2024-08-27T01:44:48.6428719Z 2024/08/27 01:14:53.619234 +0000 DEBUG export/batch_processor_test.go:148 wait BatchFinish, Done
2024-08-27T01:44:48.6430120Z 2024/08/27 01:14:53.619260 +0000 DEBUG export/batch_processor_test.go:148 wait BatchFinish, Done
2024-08-27T01:44:48.6431536Z 2024/08/27 01:14:53.619359 +0000 DEBUG export/batch_processor_test.go:104 buffer reset, stack: 
2024-08-27T01:44:48.6432836Z github.com/matrixorigin/matrixone/pkg/util/export.(*dummyBuffer).Reset
2024-08-27T01:44:48.6434184Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor_test.go:104
2024-08-27T01:44:48.6435537Z github.com/matrixorigin/matrixone/pkg/util/export.(*bufferHolder).putBuffer
2024-08-27T01:44:48.6436873Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:137
2024-08-27T01:44:48.6438180Z github.com/matrixorigin/matrixone/pkg/util/export.(*bufferGenerateReq).handle
2024-08-27T01:44:48.6439522Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:205
2024-08-27T01:44:48.6440794Z github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doGenerate
2024-08-27T01:44:48.6442255Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:661
2024-08-27T01:44:48.6443320Z runtime.goexit
2024-08-27T01:44:48.6444002Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700
2024-08-27T01:44:48.6446142Z 2024/08/27 01:14:53.619414 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:146 release buffer {"uuid": "test", "MODiscardable": true, "item": "Num", "cnt": 1, "using": 1}
2024-08-27T01:44:48.6448246Z 2024/08/27 01:14:53.619393 +0000 DEBUG export/batch_processor_test.go:118 buffer shouldFlush: true
2024-08-27T01:44:48.6450747Z 2024/08/27 01:14:53.619508 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:146 new buffer {"uuid": "test", "MODiscardable": true, "item": "Num", "cnt": 2, "using": 2}
2024-08-27T01:44:48.6452725Z 2024/08/27 01:14:53.619587 +0000 DEBUG export/batch_processor_test.go:94 accept: 7, len: 1
2024-08-27T01:44:48.6453856Z     batch_processor_test.go:306: reset normally
2024-08-27T01:44:48.6454886Z 2024/08/27 01:14:53.619683 +0000 DEBUG export/batch_processor_test.go:133 GetBatch, len: 1
2024-08-27T01:44:48.6456185Z 2024/08/27 01:14:53.619731 +0000 DEBUG export/batch_processor_test.go:144 GetBatch: (7),
2024-08-27T01:44:48.6457529Z 2024/08/27 01:14:53.619625 +0000 DEBUG export/batch_processor_test.go:104 buffer reset, stack: 
2024-08-27T01:44:48.6458794Z github.com/matrixorigin/matrixone/pkg/util/export.(*dummyBuffer).Reset
2024-08-27T01:44:48.6460392Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor_test.go:104
2024-08-27T01:44:48.6461886Z github.com/matrixorigin/matrixone/pkg/util/export.(*bufferHolder).putBuffer
2024-08-27T01:44:48.6463277Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:137
2024-08-27T01:44:48.6464620Z github.com/matrixorigin/matrixone/pkg/util/export.(*bufferGenerateReq).handle
2024-08-27T01:44:48.6465946Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:205
2024-08-27T01:44:48.6467211Z github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doGenerate
2024-08-27T01:44:48.6468527Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:661
2024-08-27T01:44:48.6469449Z runtime.goexit
2024-08-27T01:44:48.6470105Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700
2024-08-27T01:44:48.6471263Z 2024/08/27 01:14:53.619774 +0000 DEBUG export/batch_processor_test.go:146 wait BatchFinish
2024-08-27T01:44:48.6472650Z 2024/08/27 01:14:53.619867 +0000 DEBUG export/batch_processor_test.go:148 wait BatchFinish, Done
2024-08-27T01:44:48.6474991Z 2024/08/27 01:14:53.619845 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:146 release buffer {"uuid": "test", "MODiscardable": true, "item": "Num", "cnt": 1, "using": 1}
2024-08-27T01:44:48.6477025Z 2024/08/27 01:14:53.619948 +0000 DEBUG export/batch_processor_test.go:104 buffer reset, stack: 
2024-08-27T01:44:48.6478310Z github.com/matrixorigin/matrixone/pkg/util/export.(*dummyBuffer).Reset
2024-08-27T01:44:48.6479652Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor_test.go:104
2024-08-27T01:44:48.6481009Z github.com/matrixorigin/matrixone/pkg/util/export.(*bufferHolder).putBuffer
2024-08-27T01:44:48.6482333Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:137
2024-08-27T01:44:48.6483636Z github.com/matrixorigin/matrixone/pkg/util/export.(*bufferGenerateReq).handle
2024-08-27T01:44:48.6484967Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:205
2024-08-27T01:44:48.6486247Z github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doGenerate
2024-08-27T01:44:48.6487571Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor.go:661
2024-08-27T01:44:48.6488554Z runtime.goexit
2024-08-27T01:44:48.6489394Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700
2024-08-27T01:44:48.6491704Z 2024/08/27 01:14:53.619992 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:146 release buffer {"uuid": "test", "MODiscardable": true, "item": "Num", "cnt": 0, "using": 0}
2024-08-27T01:44:48.6494684Z 2024/08/27 01:14:53.620056 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:683 doGenerate: Done. {"uuid": "test", "MODiscardable": true, "idx": 1}
2024-08-27T01:44:48.6497299Z 2024/08/27 01:14:53.620072 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:734 showStats Done. {"uuid": "test", "MODiscardable": true}
2024-08-27T01:44:48.6499800Z 2024/08/27 01:14:53.620106 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:710 doExport Done. {"uuid": "test", "MODiscardable": true, "idx": 1}
2024-08-27T01:44:48.6502482Z 2024/08/27 01:14:53.620131 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:710 doExport Done. {"uuid": "test", "MODiscardable": true, "idx": 2}
2024-08-27T01:44:48.6504518Z 2024/08/27 01:14:53.620152 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:683 doGenerate: Done. {"uuid": "test", "MODiscardable": true, "idx": 0}
2024-08-27T01:44:48.6507264Z 2024/08/27 01:14:53.620188 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:683 doGenerate: Done. {"uuid": "test", "MODiscardable": true, "idx": 3}
2024-08-27T01:44:48.6510006Z 2024/08/27 01:14:53.620203 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:710 doExport Done. {"uuid": "test", "MODiscardable": true, "idx": 3}
2024-08-27T01:44:48.6512621Z 2024/08/27 01:14:53.620241 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:710 doExport Done. {"uuid": "test", "MODiscardable": true, "idx": 0}
2024-08-27T01:44:48.6515011Z 2024/08/27 01:14:53.620246 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:599 doCollect: Done. {"uuid": "test", "MODiscardable": true, "idx": 3}
2024-08-27T01:44:48.6516443Z 2024/08/27 01:14:53.620284 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:599 doCollect: Done. {"uuid": "test", "MODiscardable": true, "idx": 1}
2024-08-27T01:44:48.6517869Z 2024/08/27 01:14:53.620038 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:683 doGenerate: Done. {"uuid": "test", "MODiscardable": true, "idx": 2}
2024-08-27T01:44:48.6519270Z 2024/08/27 01:14:53.621496 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:599 doCollect: Done. {"uuid": "test", "MODiscardable": true, "idx": 0}
2024-08-27T01:44:48.6520655Z 2024/08/27 01:14:53.621435 +0000 DEBUG cn-service.MOCollector export/batch_processor.go:599 doCollect: Done. {"uuid": "test", "MODiscardable": true, "idx": 2}
2024-08-27T01:44:48.6521479Z panic: test timed out after 30m0s
2024-08-27T01:44:48.6521816Z 	running tests:
2024-08-27T01:44:48.6522131Z 		TestNewMOCollector_BufferCnt (30m0s)
2024-08-27T01:44:48.6522387Z 
2024-08-27T01:44:48.6522498Z goroutine 161 [running]:
2024-08-27T01:44:48.6522805Z testing.(*M).startAlarm.func1()
2024-08-27T01:44:48.6523323Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2373 +0x265
2024-08-27T01:44:48.6523815Z created by time.goFunc
2024-08-27T01:44:48.6524241Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/time/sleep.go:215 +0x45
2024-08-27T01:44:48.6524584Z 
2024-08-27T01:44:48.6524720Z goroutine 1 [chan receive, 30 minutes]:
2024-08-27T01:44:48.6525175Z testing.(*T).Run(0xc000480b60, {0x3d9788c, 0x1c}, 0x3e15110)
2024-08-27T01:44:48.6525773Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1751 +0x851
2024-08-27T01:44:48.6526271Z testing.runTests.func1(0xc000480b60)
2024-08-27T01:44:48.6526794Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2168 +0x86
2024-08-27T01:44:48.6527311Z testing.tRunner(0xc000480b60, 0xc00006fae0)
2024-08-27T01:44:48.6527846Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-08-27T01:44:48.6528543Z testing.runTests(0xc000673500, {0x5ad85a0, 0xd, 0xd}, {0x7f851c5c05b8?, 0x40?, 0x5b4fea0?})
2024-08-27T01:44:48.6529494Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2166 +0x8bf
2024-08-27T01:44:48.6529979Z testing.(*M).Run(0xc0003cb900)
2024-08-27T01:44:48.6530477Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2034 +0xf18
2024-08-27T01:44:48.6530940Z main.main()
2024-08-27T01:44:48.6531296Z 	_testmain.go:69 +0x165
2024-08-27T01:44:48.6531635Z 
2024-08-27T01:44:48.6531740Z goroutine 6 [select]:
2024-08-27T01:44:48.6532294Z github.com/panjf2000/ants/v2.(*Pool).purgeStaleWorkers(0xc0003f83c0, {0x42f9e98, 0xc0003becd0})
2024-08-27T01:44:48.6533098Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/pool.go:83 +0x1ef
2024-08-27T01:44:48.6533786Z created by github.com/panjf2000/ants/v2.(*Pool).goPurge in goroutine 1
2024-08-27T01:44:48.6534497Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/pool.go:148 +0x185
2024-08-27T01:44:48.6534923Z 
2024-08-27T01:44:48.6535028Z goroutine 7 [select]:
2024-08-27T01:44:48.6535516Z github.com/panjf2000/ants/v2.(*Pool).ticktock(0xc0003f83c0, {0x42f9e98, 0xc0003bed20})
2024-08-27T01:44:48.6536261Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/pool.go:126 +0x1ec
2024-08-27T01:44:48.6536953Z created by github.com/panjf2000/ants/v2.(*Pool).goTicktock in goroutine 1
2024-08-27T01:44:48.6537675Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/pool.go:155 +0x187
2024-08-27T01:44:48.6538086Z 
2024-08-27T01:44:48.6538206Z goroutine 145 [chan receive]:
2024-08-27T01:44:48.6538676Z github.com/matrixorigin/matrixone/pkg/common/mpool.init.0.func1()
2024-08-27T01:44:48.6539396Z 	/home/runner/work/matrixone/matrixone/pkg/common/mpool/alloc_tracing.go:36 +0x45
2024-08-27T01:44:48.6540179Z created by github.com/matrixorigin/matrixone/pkg/common/mpool.init.0 in goroutine 1
2024-08-27T01:44:48.6541135Z 	/home/runner/work/matrixone/matrixone/pkg/common/mpool/alloc_tracing.go:33 +0x25
2024-08-27T01:44:48.6541594Z 
2024-08-27T01:44:48.6541733Z goroutine 127 [chan receive, 29 minutes]:
2024-08-27T01:44:48.6542376Z github.com/matrixorigin/matrixone/pkg/util/export.TestNewMOCollector_BufferCnt(0xc0005921a0)
2024-08-27T01:44:48.6543290Z 	/home/runner/work/matrixone/matrixone/pkg/util/export/batch_processor_test.go:311 +0x1105
2024-08-27T01:44:48.6543923Z testing.tRunner(0xc0005921a0, 0x3e15110)
2024-08-27T01:44:48.6544448Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-08-27T01:44:48.6544966Z created by testing.(*T).Run in goroutine 1
2024-08-27T01:44:48.6545500Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
2024-08-27T01:44:48.6546123Z FAIL	github.com/matrixorigin/matrixone/pkg/util/export	1800.164s

### Steps to Reproduce

https://github.com/matrixorigin/matrixone/actions/runs/10569790814/job/29283219716?pr=18339

**Comment by xzxiong** [comment]
[logs_27629339420.zip](https://github.com/user-attachments/files/16755984/logs_27629339420.zip)

**Comment by xzxiong** [comment]
如果复现频繁，再升级为 S0

**Comment by xzxiong** [comment]
not repro lately
