### ISSUE TITLE
[Bug]: MO panic: inconsistent refcnt count: -1 on memorycache.release

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#18538]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

3bca8536e

### Actual Behavior

```
{"level":"INFO","time":"2024/09/05 00:27:12.266530 +0000","caller":"cnservice/server_query.go:469","msg":"QueryService::GoMaxProcs","op":"set","in":8,"out":8}
{"level":"INFO","time":"2024/09/05 00:27:12.266699 +0000","caller":"cnservice/server_query.go:481","msg":"QueryService::GoMemLimit","op":"set","in":7730102272,"out":9663676416}
{"level":"INFO","time":"2024/09/05 00:27:12.306867 +0000","caller":"cnservice/server_query.go:500","msg":"cache size adjusted","type":"Memory","size":1287651328}
panic: inconsistent refcnt count: -1

goroutine 980632 [running]:
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.(*refcnt).release(0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/refcnt.go:45 +0x88
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.(*Data).Release(0xc11cc6f900)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/data.go:84 +0x25
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.NewCache.func3({{0xc0399e03f0?, 0x5406ba0?}, 0xc0d14b7400?, 0x4182e5?}, 0xc11cc6f900)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/cache.go:60 +0x45
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache.(*shard[...]).evict(0x54224e0, {0x5368090, 0x7c81c20?}, 0xc002786aa8?)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache/shard.go:85 +0x269
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache.(*LRU[...]).Evict(0x540f7e0, 0xc0cd4a2000)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache/lru.go:136 +0x8b
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.(*Cache).Evict(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/cache.go:118
github.com/matrixorigin/matrixone/pkg/fileservice.(*MemCache).Evict(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/mem_cache.go:213
github.com/matrixorigin/matrixone/pkg/fileservice.EvictMemoryCaches.func1({0x446d0c0?, 0xc001a28ee0?}, {0x3f3e980?, 0xc000521c80?})
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/cache.go:219 +0x7c
sync.(*Map).Range(0x11?, 0xc050b06fa0)
	/usr/local/go/src/sync/map.go:477 +0x1f8
github.com/matrixorigin/matrixone/pkg/fileservice.EvictMemoryCaches()
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/cache.go:216 +0x65
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleFileServiceCacheEvictRequest(0x7c81c53?, {0xc050b070d8?, 0x4af559?}, 0xc02e5f4018?, 0xc0c4540000)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:518 +0x39
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x533e100?, {0x5368198, 0xc0f1dfa6f0?}, 0xc114241228?, 0xc0c4540000?)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:65 +0x4c
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:196 +0x2b2
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage(0x5420040, {0x5368198, 0xc0f1dfa6f0?}, {{0x5368198, 0xc0f1dfa6f0}, 0xc039ca2000, {0x5391f30, 0xc071dd4120}, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:205 +0x550
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0005f0580, {0x53e4a00, 0xc024e11500}, {0x462fb00, 0xc0be5820a0}, 0x13)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:260 +0xc3e
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0005f0630, {0x53e4a00, 0xc024e11500})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:393 +0x390
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:356 +0x94
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 794
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:348 +0x3fa
```

### Expected Behavior

MO should not panic

### Steps to Reproduce

Occasionally happens when adjust memory cache size.

Original log: https://grafana.cn-dev.matrixone.tech/goto/OCQ1BieIg?orgId=1

**Comment by aronchanisme** [comment]
cc @reusee  @volgariver6 @xzxiong 
复现：
```sql
select * from system.statement_info where request_at>'2024-09-04 18:37:00' and request_at < '2024-09-04 20:37:00' and statement like '%DROP DATABASE IF EXISTS tpi_index%';
```

panic：
<img width="1675" alt="企业微信截图_64502502-3e3b-4f2b-8b99-9a0093ee7569" src="https://github.com/user-attachments/assets/dcadfae3-b171-4581-8bc7-a5bd34e822c4">

**Comment by aronchanisme** [comment]
multiple internal tests are affected in MOC DEV
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/e04581ae-266a-4078-8fb9-425cfcf86392">

**Comment by aronchanisme** [comment]
Multiple `insert` tests in MOC DEV failed due to same reason.
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/b2eb9b8b-710f-418c-9f24-242b7e6ecefc">

**Comment by reusee** [comment]
已经修复。

**Comment by aressu1985** [comment]
fixed
