### ISSUE TITLE
[Bug]: CN panics when querying statement_info

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#18568]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.2-f74862108-2024-09-05

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Run the following SQL in the cloud dev env and CN panics
```
explain analyze SELECT * FROM (select `statement`,system.statement_info.statement_id,IF(`status`='Running', TIMESTAMPDIFF(MICROSECOND,`request_at`,now())*1000, `duration`) AS `duration`,`status`,`query_type`,`request_at`,system.statement_info.response_at,`user`,`database`,`transaction_id`,`session_id`,`rows_read`,`bytes_scan`,`result_count`,IF(status = 'Running', NULL, CAST(IF(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[0]')) >= 4, JSON_UNQUOTE(JSON_EXTRACT(stats, '$[8]')), mo_cu_v1(stats, duration)) AS DECIMAL(32,4))) AS `cu` from system.statement_info where 1=1 AND `request_at` >= '2024-08-02 04:34:40' AND `request_at` <= '2024-09-02 06:34:40' AND system.statement_info.account = '0191461f-1289-719e-83cc-633fb2c0293c' AND sql_source_type IN ('cloud_user_sql','external_sql') )t ORDER BY request_at DESC LIMIT 20;
```
CN log: 
```
{"level":"INFO","time":"2024/09/06 02:29:43.980895 +0000","name":"cn-service.frontend","caller":"frontend/query_result.go:122","msg":"open save query result","uuid":"63336134-3738-3166-3365-346438343032","statemant id is:":"0191c52a-85ac-7503-be19-6daf3dea895f","fileservice name is:":"","write path is:":"SHARED:/query_result/sys_0191c52a-85ac-7503-be19-6daf3dea895f_1.blk","current result size:":0.0000152587890625,"session_info":"connectionId 509351717||{account sys:dump:moadmin -- 0:1:0}|goRoutineId 37250|migrate-goRoutineId 0|0191c52a-852f-778c-ad8d-0c67ae58fa1e","session_id":"0191c52a-852f-778c-ad8d-0c67ae58fa1e","statement_id":"0191c52a-85ac-7503-be19-6daf3dea895f","txn_id":"0191c52a85ac75499d911dc1549c35af","span":{"trace_id":"0578d2cc-b19a-9a02-12af-5b6e9abc8417","span_id":"f78cd6320c6e459b"}}
fatal error: concurrent map read and map write

goroutine 37113 [running]:
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache.(*shard[...]).Get(0xc000648fd0, {0x2a?, 0xc039566a80?}, 0x2a?, {{0xc039566a80?, 0x2a}, 0xa1df0, 0xa7})
        /go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache/shard.go:101 +0xc7
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache.(*LRU[...]).Get(0x5410b00, {0x53694b8, 0xc16023afc0}, {{0xc039566a80, 0x12d5e3a?}, 0x0?, 0x40edaa0?})
        /go/src/github.com/matrixorigin/matrixone/pkg/fileservice/memorycache/lrucache/lru.go:87 +0xd8
```
[cn.txt.zip](https://github.com/user-attachments/files/16902180/cn.txt.zip)

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/c018070bdd8eb85599cf425fdc651b35de2f6e67

**Comment by aressu1985** [comment]
fixed
