### ISSUE TITLE
[Bug]: ut TestReadDirSymlink failed

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#18855]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
024-09-19T07:05:13.5630958Z 
2024-09-19T07:05:13.5631072Z 130 total assertions
2024-09-19T07:05:13.5631079Z 
2024-09-19T07:05:13.5631248Z --- PASS: Test_getBatchData (0.02s)
2024-09-19T07:05:13.5631377Z === RUN   TestReadDirSymlink
2024-09-19T07:05:13.5631528Z     external_test.go:855: 
2024-09-19T07:05:13.5632214Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:855
2024-09-19T07:05:13.5633560Z         	Error:      	Expected nil, but got: &fs.PathError{Op:"lstat", Path:"/tmp/go-link-2368728721", Err:0x2}
2024-09-19T07:05:13.5634112Z         	Test:       	TestReadDirSymlink
2024-09-19T07:05:13.5634397Z     external_test.go:856: 
2024-09-19T07:05:13.5635570Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:856
2024-09-19T07:05:13.5635898Z         	Error:      	Not equal: 
2024-09-19T07:05:13.5636283Z         	            	expected: 1
2024-09-19T07:05:13.5636653Z         	            	actual  : 0
2024-09-19T07:05:13.5637030Z         	Test:       	TestReadDirSymlink
2024-09-19T07:05:13.5637261Z --- FAIL: TestReadDirSymlink (0.01s)
2024-09-19T07:05:13.5637548Z panic: runtime error: index out of range [0] with length 0 [recovered]
2024-09-19T07:05:13.5637787Z 	panic: runtime error: index out of range [0] with length 0
2024-09-19T07:05:13.5637801Z 
2024-09-19T07:05:13.5637919Z goroutine 122 [running]:
2024-09-19T07:05:13.5638119Z testing.tRunner.func1.2({0x5491300, 0xc0031b4378})
2024-09-19T07:05:13.5638424Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
2024-09-19T07:05:13.5638552Z testing.tRunner.func1()
2024-09-19T07:05:13.5638995Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
2024-09-19T07:05:13.5639128Z panic({0x5491300?, 0xc0031b4378?})
2024-09-19T07:05:13.5639409Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-19T07:05:13.5639828Z github.com/matrixorigin/matrixone/pkg/sql/colexec/external.TestReadDirSymlink(0xc0027c6340)
2024-09-19T07:05:13.5640258Z 	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:857 +0xa87
2024-09-19T07:05:13.5640407Z testing.tRunner(0xc0027c6340, 0x5829bc8)
2024-09-19T07:05:13.5640689Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-09-19T07:05:13.5640846Z created by testing.(*T).Run in goroutine 1
2024-09-19T07:05:13.5641128Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
2024-09-19T07:05:13.5641420Z FAIL	github.com/matrixorigin/matrixone/pkg/sql/colexec/external	0.330s
```

### Steps to Reproduce

```Markdown
ut : https://github.com/matrixorigin/matrixone/actions/runs/10935913714/job/30358528388?pr=18828
```

**Comment by reusee** [comment]
本地复现不了。

**Comment by reusee** [comment]
无复现。

**Comment by reusee** [comment]
无复现。

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/11949801831/job/33310403035

[job-logs (1).txt.zip](https://github.com/user-attachments/files/17846425/job-logs.1.txt.zip)

**Comment by reusee** [comment]
无进展

**Comment by badboynt1** [comment]
repro in https://github.com/matrixorigin/matrixone/actions/runs/12176308397/job/33961789246?pr=20587

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by volgariver6** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/12494289332/job/34863751982?pr=20933

```
[TEST]: TestReadDirSymlink
[START_AT]: 2024-12-25T15:21:01Z
[END_AT]: 2024-12-25T15:21:01Z
[RESULT]: fail
[ELAPSED]: 0.24
[OUTPUTS]:
=== RUN   TestReadDirSymlink
    external_test.go:489: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:489
        	Error:      	Expected nil, but got: &fs.PathError{Op:"lstat", Path:"/tmp/cckyS8Hz.s", Err:0x2}
        	Test:       	TestReadDirSymlink
    external_test.go:490: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:490
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestReadDirSymlink
--- FAIL: TestReadDirSymlink (0.24s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 202 [running]:
testing.tRunner.func1.2({0x5b18b40, 0xc00014b7a0})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
panic({0x5b18b40?, 0xc00014b7a0?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.TestReadDirSymlink(0xc000a9[38](https://github.com/matrixorigin/matrixone/actions/runs/12494289332/job/34863751982?pr=20933#step:10:39)60)
	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:491 +0xa87
testing.tRunner(0xc000a93860, 0x5ecb560)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:17[43](https://github.com/matrixorigin/matrixone/actions/runs/12494289332/job/34863751982?pr=20933#step:10:44) +0x826
steps.ut.conclusion: failure
FAIL_UT_CASES=TestReadDirSymlink,
```

**Comment by reusee** [comment]
未投入

**Comment by reusee** [comment]
未投入

**Comment by reusee** [comment]
未投入

**Comment by reusee** [comment]
未投入

**Comment by reusee** [comment]
未投入

**Comment by sukki37** [comment]
repro： https://github.com/matrixorigin/matrixone/actions/runs/12920525407/job/36032993250?pr=21299

```
=== RUN   TestReadDirSymlink
    external_test.go:490: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:490
        	Error:      	Expected nil, but got: &fs.PathError{Op:"lstat", Path:"/tmp/cc6hjkZr.res", Err:0x2}
        	Test:       	TestReadDirSymlink
    external_test.go:491: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:491
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestReadDirSymlink
--- FAIL: TestReadDirSymlink (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 139 [running]:
testing.tRunner.func1.2({0x59[44](https://github.com/matrixorigin/matrixone/actions/runs/12920525407/job/36032993250?pr=21299#step:10:45)620, 0xc00016d320})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
panic({0x594[46](https://github.com/matrixorigin/matrixone/actions/runs/12920525407/job/36032993250?pr=21299#step:10:47)20?, 0xc00016d320?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.TestReadDirSymlink(0xc000d35040)
	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:[49](https://github.com/matrixorigin/matrixone/actions/runs/12920525407/job/36032993250?pr=21299#step:10:50)2 +0xa87
testing.tRunner(0xc000d35040, 0x5cfca30)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
steps.ut.conclusion: failure
FAIL_UT_CASES=TestReadDirSymlink,
```

**Comment by reusee** [comment]
无进展

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/13194737609/job/36833883182?pr=21325

```
=== RUN   TestReadDirSymlink
    external_test.go:502: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:502
        	Error:      	Expected nil, but got: &fs.PathError{Op:"lstat", Path:"/tmp/cccx1anH.cdtor.o", Err:0x2}
        	Test:       	TestReadDirSymlink
    external_test.go:504: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:[50](https://github.com/matrixorigin/matrixone/actions/runs/13194541384/job/36833338097?pr=21325#step:10:51)4
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestReadDirSymlink
--- FAIL: TestReadDirSymlink (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 205 [running]:
testing.tRunner.func1.2({0x5bb5a00, 0xc000bc[51](https://github.com/matrixorigin/matrixone/actions/runs/13194541384/job/36833338097?pr=21325#step:10:52)58})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
panic({0x5bb5a00?, 0xc000bc5158?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.TestReadDirSymlink(0xc000d25040)
	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:505 +0xa7d
testing.tRunner(0xc000d25040, 0x5f6e218)
	/opt/hostedtoolcache/go/1.23.0/x[64](https://github.com/matrixorigin/matrixone/actions/runs/13194541384/job/36833338097?pr=21325#step:10:65)/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
steps.ut.conclusion: failure
FAIL_UT_CASES=TestReadDirSymlink,
```

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/13711663346/job/38349211200?pr=21494
```
[TEST]: TestReadDirSymlink
[START_AT]: 2025-03-07T01:32:53Z
[END_AT]: 2025-03-07T01:32:53Z
[RESULT]: fail
[ELAPSED]: 0.32
[OUTPUTS]:
=== RUN   TestReadDirSymlink
    external_test.go:502: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:502
        	Error:      	Expected nil, but got: &fs.PathError{Op:"lstat", Path:"/tmp/ccytL6Ls.res", Err:0x2}
        	Test:       	TestReadDirSymlink
    external_test.go:504: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:504
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestReadDirSymlink
--- FAIL: TestReadDirSymlink (0.32s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 11 [running]:
testing.tRunner.func1.2({0x5d69e40, 0xc0009ed200})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
panic({0x5d69e40?, 0xc0009ed200?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.TestReadDirSymlink(0xc0000f2b60)
	/home/runner/work/matrixone/matrixone/pkg/sql/colexec/external/external_test.go:505 +0xa7d
testing.tRunner(0xc0000f2b60, 0x613ce68)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:17[43](https://github.com/matrixorigin/matrixone/actions/runs/13711663346/job/38349211200?pr=21494#step:11:44) +0x826
steps.ut.conclusion: failure
FAIL_UT_CASES=TestReadDirSymlink,
```

**Comment by fengttt** [comment]
This is a really strange one.    Hmm, I think I know.   The assert.Equal is not fatal/panic, therefore it keeps on running even if the assert fails.    Therefore, same for the Nil(err) check.    Make the Nil(err) fatal and print out what exactly is the error, at least we will know why the test fail.

**Comment by XuPeng-SH** [comment]
should be fixed

**Comment by heni02** [comment]
confirm，closed
