### ISSUE TITLE
[Bug]: ut Test_mce fail panic: io: read/write on closed pipe

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#18965]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-09-24T03:08:41.7539267Z === RUN   Test_mce
2024-09-24T03:08:41.7539273Z 
2024-09-24T03:08:41.7539581Z   boot mce succ ✔panic: io: read/write on closed pipe
2024-09-24T03:08:41.7539827Z 
2024-09-24T03:08:41.7540066Z goroutine 954 [running]:
2024-09-24T03:08:41.7540618Z github.com/matrixorigin/matrixone/pkg/frontend.TestMySQLBufferMaxAllowedPacket.func1.2()
2024-09-24T03:08:41.7541176Z 	/home/runner/_work/matrixone/matrixone/matrixone/pkg/frontend/mysql_buffer_test.go:1007 +0x3d4
2024-09-24T03:08:41.7541926Z created by github.com/matrixorigin/matrixone/pkg/frontend.TestMySQLBufferMaxAllowedPacket.func1 in goroutine 995
2024-09-24T03:08:41.7542499Z 	/home/runner/_work/matrixone/matrixone/matrixone/pkg/frontend/mysql_buffer_test.go:966 +0x335
2024-09-24T03:08:41.7542773Z FAIL	github.com/matrixorigin/matrixone/pkg/frontend	29.864s

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11006180380/job/30560066301?pr=18955
```

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
fixed
