### ISSUE TITLE
[Bug]: `TestBalanceWithSingleTable (39m49s)`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#18999]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0924-fix-dashboard

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2024-09-25T02:12:12.4666375Z 2024/09/25 01:32:25.063089 +0000 ERROR cn-service.shard-service close conneciton failed {"uuid": "", "name": "shard-service", "session-id": 1, "error": "close unix /tmp/service-60030055-cn2.sock->@: use of closed network connection"}
2024-09-25T02:12:12.4670946Z 2024/09/25 01:32:26.154289 +0000 ERROR cn-service.shard-service close conneciton failed {"uuid": "", "name": "shard-service", "session-id": 1, "error": "close unix /tmp/service-148360479-cn2.sock->@: use of closed network connection"}
2024-09-25T02:12:12.4673357Z panic: test timed out after 40m0s
2024-09-25T02:12:12.4674255Z 	running tests:
2024-09-25T02:12:12.4674864Z 		TestBalanceWithSingleTable (39m49s)
2024-09-25T02:12:12.4675329Z 
2024-09-25T02:12:12.4675574Z goroutine 4442 [running]:
2024-09-25T02:12:12.4676350Z testing.(*M).startAlarm.func1()
2024-09-25T02:12:12.4677351Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2373 +0x265
2024-09-25T02:12:12.4678692Z created by time.goFunc
2024-09-25T02:12:12.4679536Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/time/sleep.go:215 +0x45
2024-09-25T02:12:12.4680189Z 
2024-09-25T02:12:12.4680617Z goroutine 1 [chan receive, 39 minutes]:
2024-09-25T02:12:12.4681526Z testing.(*T).Run(0xc000580820, {0x27d04cf, 0x1a}, 0x28484c0)
2024-09-25T02:12:12.4682937Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1751 +0x851
2024-09-25T02:12:12.4683940Z testing.runTests.func1(0xc000580820)
2024-09-25T02:12:12.4684940Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2168 +0x86
2024-09-25T02:12:12.4686105Z testing.tRunner(0xc000580820, 0xc00005dae0)
2024-09-25T02:12:12.4687371Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-09-25T02:12:12.4688927Z testing.runTests(0xc0000132a8, {0x3b5a120, 0x3b, 0x3b}, {0x7f3672584108?, 0x40?, 0x3bc2e60?})
2024-09-25T02:12:12.4690662Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2166 +0x8bf
2024-09-25T02:12:12.4691607Z testing.(*M).Run(0xc00048a640)
2024-09-25T02:12:12.4692766Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2034 +0xf18
2024-09-25T02:12:12.4693809Z main.main()

```

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11024581454?pr=18973
```

**Comment by zhangxu19830126** [comment]
fixed
