### ISSUE TITLE
[Bug]: ut failed in TestWrite

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#18993]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-09-25T03:06:11.2896175Z     test_utils.go:98: 
2024-09-25T03:06:11.2897076Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:98
2024-09-25T03:06:11.2898411Z         	            				/home/runner/work/matrixone/matrixone/pkg/common/runtime/runtime.go:219
2024-09-25T03:06:11.2899808Z         	            				/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:85
2024-09-25T03:06:11.2901140Z         	            				/home/runner/work/matrixone/matrixone/pkg/datasync/log_client_test.go:68
2024-09-25T03:06:11.2901510Z         	Error:      	Received unexpected error:
2024-09-25T03:06:11.2902320Z         	            	listen tcp 0.0.0.0:34496: bind: address already in use
2024-09-25T03:06:11.2902586Z         	Test:       	TestWrite
2024-09-25T03:06:11.2902835Z --- FAIL: TestWrite (0.05s)
2024-09-25T03:06:11.2903305Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-25T03:06:11.2903871Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-09-25T03:06:11.2904362Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-09-25T03:06:11.2904820Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3817757]
2024-09-25T03:06:11.2904832Z 
2024-09-25T03:06:11.2905011Z goroutine 2628 [running]:
2024-09-25T03:06:11.2905283Z testing.tRunner.func1.2({0x4a9d100, 0x7759d40})
2024-09-25T03:06:11.2905777Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
2024-09-25T03:06:11.2905972Z testing.tRunner.func1()
2024-09-25T03:06:11.2906443Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
2024-09-25T03:06:11.2906642Z panic({0x4a9d100?, 0x7759d40?})
2024-09-25T03:06:11.2907078Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-25T03:06:11.2907557Z github.com/matrixorigin/matrixone/pkg/logservice.(*Service).Close(0x0)
2024-09-25T03:06:11.2908129Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/service.go:211 +0x37
2024-09-25T03:06:11.2908668Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest.func1.2()
2024-09-25T03:06:11.2909262Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:100 +0x34
2024-09-25T03:06:11.2909600Z panic({0x4a9d100?, 0x7759d40?})
2024-09-25T03:06:11.2910074Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-25T03:06:11.2910529Z github.com/matrixorigin/matrixone/pkg/logservice.(*Service).ID(...)
2024-09-25T03:06:11.2911042Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/service.go:232
2024-09-25T03:06:11.2911746Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest.func1({0x775e8e0?, 0x4e09400?})
2024-09-25T03:06:11.2912348Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:104 +0x3ef
2024-09-25T03:06:11.2912970Z github.com/matrixorigin/matrixone/pkg/common/runtime.RunTest({0x0, 0x0}, 0xc002ca9e68)
2024-09-25T03:06:11.2913578Z 	/home/runner/work/matrixone/matrixone/pkg/common/runtime/runtime.go:219 +0x111
2024-09-25T03:06:11.2914466Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest(0xc00226b520, 0x0, 0x0, 0x51e5c28)
2024-09-25T03:06:11.2915208Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:85 +0xcd
2024-09-25T03:06:11.2915702Z github.com/matrixorigin/matrixone/pkg/datasync.TestWrite(0xc00226b520)
2024-09-25T03:06:11.2916319Z 	/home/runner/work/matrixone/matrixone/pkg/datasync/log_client_test.go:68 +0x32
2024-09-25T03:06:11.2916541Z testing.tRunner(0xc00226b520, 0x51e5820)
2024-09-25T03:06:11.2917041Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-09-25T03:06:11.2917288Z created by testing.(*T).Run in goroutine 1
2024-09-25T03:06:11.2917764Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
2024-09-25T03:06:11.2918149Z FAIL	github.com/matrixorigin/matrixone/pkg/datasync	26.332s
2024-09-25T03:06:11.2918337Z === RUN   TestBasicCluster

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11025426501/job/30620278527?pr=18980
```

**Comment by volgariver6** [comment]
fixed
