### ISSUE TITLE
[Bug]: ut TestGetLeaderID failed.

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19012]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0924-fix-dashboard

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```

2024-09-25T08:27:38.9423478Z 2024/09/25 08:20:00.114808 +0000 INFO dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:366 filesystem error injection mode enabled: false
2024-09-25T08:27:38.9425726Z 2024/09/25 08:20:00.115895 +0000 INFO transport transport/transport.go:238 transport type: go-tcp-transport
2024-09-25T08:27:38.9427708Z 2024/09/25 08:20:00.116047 +0000 ERROR transport transport/transport.go:240 transport failed to start listen tcp 0.0.0.0:60832: bind: address already in use
2024-09-25T08:27:38.9430146Z 2024/09/25 08:20:00.119103 +0000 ERROR cn-service failed to create log store {"uuid": "", "error": "listen tcp 0.0.0.0:60832: bind: address already in use"}
2024-09-25T08:27:38.9431528Z     test_utils.go:98: 
2024-09-25T08:27:38.9432749Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:98
2024-09-25T08:27:38.9435006Z         	            				/home/runner/work/matrixone/matrixone/pkg/common/runtime/runtime.go:219
2024-09-25T08:27:38.9437262Z         	            				/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:85
2024-09-25T08:27:38.9439517Z         	            				/home/runner/work/matrixone/matrixone/pkg/datasync/log_client_test.go:47
2024-09-25T08:27:38.9440678Z         	Error:      	Received unexpected error:
2024-09-25T08:27:38.9441950Z         	            	listen tcp 0.0.0.0:60832: bind: address already in use
2024-09-25T08:27:38.9442829Z         	Test:       	TestGetLeaderID
2024-09-25T08:27:38.9443517Z --- FAIL: TestGetLeaderID (0.05s)
2024-09-25T08:27:38.9474598Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-25T08:27:38.9475877Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-09-25T08:27:38.9477114Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-09-25T08:27:38.9478238Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x380d017]
2024-09-25T08:27:38.9478902Z 
2024-09-25T08:27:38.9479093Z goroutine 2360 [running]:
2024-09-25T08:27:38.9479697Z testing.tRunner.func1.2({0x4a90c40, 0x7704d40})
2024-09-25T08:27:38.9480665Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
2024-09-25T08:27:38.9481520Z testing.tRunner.func1()
2024-09-25T08:27:38.9482318Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
2024-09-25T08:27:38.9483164Z panic({0x4a90c40?, 0x7704d40?})
2024-09-25T08:27:38.9484120Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-25T08:27:38.9485238Z github.com/matrixorigin/matrixone/pkg/logservice.(*Service).Close(0x0)
2024-09-25T08:27:38.9486471Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/service.go:211 +0x37
2024-09-25T08:27:38.9487758Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest.func1.2()
2024-09-25T08:27:38.9489094Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:100 +0x34
2024-09-25T08:27:38.9490057Z panic({0x4a90c40?, 0x7704d40?})
2024-09-25T08:27:38.9490857Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-25T08:27:38.9491885Z github.com/matrixorigin/matrixone/pkg/logservice.(*Service).ID(...)
2024-09-25T08:27:38.9492996Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/service.go:232
2024-09-25T08:27:38.9494466Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest.func1({0x77098e0?, 0x4dfcda0?})
2024-09-25T08:27:38.9495956Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:104 +0x3ef
2024-09-25T08:27:38.9497270Z github.com/matrixorigin/matrixone/pkg/common/runtime.RunTest({0x0, 0x0}, 0xc000503e68)
2024-09-25T08:27:38.9498628Z 	/home/runner/work/matrixone/matrixone/pkg/common/runtime/runtime.go:219 +0x111
2024-09-25T08:27:38.9500042Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest(0xc0021664e0, 0x0, 0x0, 0x51d98e8)
2024-09-25T08:27:38.9501463Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:85 +0xcd
2024-09-25T08:27:38.9502704Z github.com/matrixorigin/matrixone/pkg/datasync.TestGetLeaderID(0xc0021664e0)
2024-09-25T08:27:38.9534245Z 	/home/runner/work/matrixone/matrixone/pkg/datasync/log_client_test.go:47 +0x32
2024-09-25T08:27:38.9535311Z testing.tRunner(0xc0021664e0, 0x51d9570)
2024-09-25T08:27:38.9536261Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-09-25T08:27:38.9537186Z created by testing.(*T).Run in goroutine 1
2024-09-25T08:27:38.9538146Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
2024-09-25T08:27:38.9539213Z FAIL	github.com/matrixorigin/matrixone/pkg/datasync	26.041s
2024-09-25T08:27:38.9540023Z === RUN   TestBasicCluster
```

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11029016584/job/30630494075?pr=18973
```

**Comment by volgariver6** [comment]
fixed
