### ISSUE TITLE
[Bug]: ut test failed in TestClientSendWithMsgSize

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19064]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-09-27T07:07:33.3162609Z --- FAIL: TestClientSendWithMsgSize (0.76s)
2024-09-27T07:07:33.3163216Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-27T07:07:33.3163804Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-09-27T07:07:33.3164297Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-09-27T07:07:33.3164760Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22c6bb7]
2024-09-27T07:07:33.3164782Z 
2024-09-27T07:07:33.3164982Z goroutine 4700 [running]:
2024-09-27T07:07:33.3165269Z testing.tRunner.func1.2({0x267c8c0, 0x3e7d5a0})
2024-09-27T07:07:33.3165794Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
2024-09-27T07:07:33.3165995Z testing.tRunner.func1()
2024-09-27T07:07:33.3166500Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
2024-09-27T07:07:33.3166703Z panic({0x267c8c0?, 0x3e7d5a0?})
2024-09-27T07:07:33.3167158Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-27T07:07:33.3167653Z github.com/matrixorigin/matrixone/pkg/logservice.(*Service).Close(0x0)
2024-09-27T07:07:33.3168247Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/service.go:211 +0x37
2024-09-27T07:07:33.3168810Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest.func1.2()
2024-09-27T07:07:33.3169433Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:135 +0x34
2024-09-27T07:07:33.3169662Z panic({0x267c8c0?, 0x3e7d5a0?})
2024-09-27T07:07:33.3170148Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-09-27T07:07:33.3170620Z github.com/matrixorigin/matrixone/pkg/logservice.(*Service).ID(...)
2024-09-27T07:07:33.3171155Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/service.go:232
2024-09-27T07:07:33.3171855Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest.func1({0x3e819c0?, 0x2842c80?})
2024-09-27T07:07:33.3172460Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:139 +0x3ef
2024-09-27T07:07:33.3246203Z github.com/matrixorigin/matrixone/pkg/common/runtime.RunTest({0x0, 0x0}, 0xc002b6ce68)
2024-09-27T07:07:33.3247198Z 	/home/runner/work/matrixone/matrixone/pkg/common/runtime/runtime.go:219 +0x111
2024-09-27T07:07:33.3248192Z github.com/matrixorigin/matrixone/pkg/logservice.RunClientTest(0xc002f94000, 0x0, 0x2a7eba8, 0x2a7ebb0)
2024-09-27T07:07:33.3248879Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/test_utils.go:120 +0xcd
2024-09-27T07:07:33.3249780Z github.com/matrixorigin/matrixone/pkg/logservice.TestClientSendWithMsgSize(0xc002f94000)
2024-09-27T07:07:33.3250391Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/client_test.go:286 +0x37
2024-09-27T07:07:33.3250639Z testing.tRunner(0xc002f94000, 0x2a7e4b0)
2024-09-27T07:07:33.3251140Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-09-27T07:07:33.3251401Z created by testing.(*T).Run in goroutine 1
2024-09-27T07:07:33.3251886Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
2024-09-27T07:07:33.3252327Z FAIL	github.com/matrixorigin/matrixone/pkg/logservice	11.204s

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11065951839/job/30746268163?pr=19055
```

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/19025
