### ISSUE TITLE
[Bug]: ut failed in TestSyncer_Create

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19100]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-09-30T01:43:18.8683857Z === RUN   TestSyncer_Create
2024-09-30T01:43:18.8684555Z === RUN   TestSyncer_Create/create_consumer_error
2024-09-30T01:43:18.8686118Z 2024/09/30 01:36:20.534226 +0000 ERROR cn-service failed to create source fileservice {"uuid": "", "module": "datasync", "error": "service SHARED not found"}
2024-09-30T01:43:18.8687366Z === RUN   TestSyncer_Create/ok
2024-09-30T01:43:18.8688801Z 2024/09/30 01:36:20.535125 +0000 ERROR cn-service failed to start consumer worker {"uuid": "", "module": "datasync", "error": "internal error: runner is unavailable"}
2024-09-30T01:43:18.8691044Z 2024/09/30 01:36:20.535209 +0000 ERROR cn-service failed to start producer worker {"uuid": "", "module": "datasync", "error": "internal error: runner is unavailable"}
2024-09-30T01:43:18.8692626Z panic: failed to start datasync module, internal error: runner is unavailable
2024-09-30T01:43:18.8693283Z 
2024-09-30T01:43:18.8693462Z goroutine 6173 [running]:
2024-09-30T01:43:18.8694557Z github.com/matrixorigin/matrixone/pkg/datasync.(*syncer).start(0xc004652180, {0x441748?, 0x48ae51?})
2024-09-30T01:43:18.8696200Z 	/home/runner/work/matrixone/matrixone/pkg/datasync/syncer.go:173 +0x834
2024-09-30T01:43:18.8697698Z github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
2024-09-30T01:43:18.8699046Z 	/home/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:277 +0xcf
2024-09-30T01:43:18.8700506Z created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 6167
2024-09-30T01:43:18.8701971Z 	/home/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:272 +0x165
2024-09-30T01:43:18.8702994Z FAIL	github.com/matrixorigin/matrixone/pkg/datasync	34.761s

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11097762097/job/30829472464?pr=18980
```

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/19159
