### ISSUE TITLE
[Bug]: ut failed in TestGetHeartbeatMessage

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19180]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-10-09T07:59:13.1600623Z {"Time":"2024-10-09T07:58:43.993133663Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"    store_test.go:173: \n"}
2024-10-09T07:59:13.1604425Z {"Time":"2024-10-09T07:58:43.99314331Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"        \tError Trace:\t/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:173\n"}
2024-10-09T07:59:13.1780545Z {"Time":"2024-10-09T07:58:43.99314821Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"        \t            \t\t\t\t/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:482\n"}
2024-10-09T07:59:13.1784695Z {"Time":"2024-10-09T07:58:43.993152387Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"        \tError:      \tReceived unexpected error:\n"}
2024-10-09T07:59:13.1789462Z {"Time":"2024-10-09T07:58:43.993156816Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"        \t            \tCould not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 42562: listen tcp 0.0.0.0:42562: bind: address already in use\n"}
2024-10-09T07:59:13.1794497Z {"Time":"2024-10-09T07:58:43.993161314Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"        \tTest:       \tTestGetHeartbeatMessage\n"}
2024-10-09T07:59:13.1797997Z {"Time":"2024-10-09T07:58:43.993418785Z","Action":"output","Package":"github.com/matrixorigin/matrixone/pkg/logservice","Test":"TestGetHeartbeatMessage","Output":"--- FAIL: TestGetHeartbeatMessage (0.13s)\n"}

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11250540145/job/31279630899?pr=19170
```

**Comment by sukki37** [comment]
[job-logs.txt.zip](https://github.com/user-attachments/files/17308111/job-logs.txt.zip)

```
8:28:20.7215669Z 2024/10/09 07:58:43.982815 +0000 ERROR registry registry/gossip.go:331 failed to create memberlist, Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 42562: listen tcp 0.0.0.0:42562: bind: address already in use
2024-10-09T08:28:20.7220105Z 2024/10/09 07:58:43.982980 +0000 DEBUG dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:410 0.0.0.0:32000 is stopping the nh stopper
2024-10-09T08:28:20.7224064Z 2024/10/09 07:58:43.983140 +0000 DEBUG dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:413 0.0.0.0:32000 is stopping the tranport module
2024-10-09T08:28:20.7227909Z 2024/10/09 07:58:43.983291 +0000 DEBUG dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:421 0.0.0.0:32000 is stopping the engine module
2024-10-09T08:28:20.7231594Z 2024/10/09 07:58:43.983440 +0000 DEBUG dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:427 0.0.0.0:32000 is stopping the logdb module
2024-10-09T08:28:20.7233167Z 2024/10/09 07:58:43.992551 +0000 DEBUG dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:432 0.0.0.0:32000 is stopping the env module
2024-10-09T08:28:20.7237282Z 2024/10/09 07:58:43.992641 +0000 DEBUG dragonboat v4@v4.0.0-20240911092336-c85cbba24527/nodehost.go:434 NodeHost 0.0.0.0:32000 stopped
2024-10-09T08:28:20.7240299Z     store_test.go:173: 
2024-10-09T08:28:20.7243267Z         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:173
2024-10-09T08:28:20.7244680Z         	            				/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:482
2024-10-09T08:28:20.7248605Z         	Error:      	Received unexpected error:
2024-10-09T08:28:20.7253264Z         	            	Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 42562: listen tcp 0.0.0.0:42562: bind: address already in use
2024-10-09T08:28:20.7256887Z         	Test:       	TestGetHeartbeatMessage
2024-10-09T08:28:20.7257602Z --- FAIL: TestGetHeartbeatMessage (0.13s)
2024-10-09T08:28:20.7260500Z panic: runtime error: invalid memory address or nil pointer dereference
2024-10-09T08:28:20.7263849Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-10-09T08:28:20.7331409Z 	panic: runtime error: invalid memory address or nil pointer dereference
2024-10-09T08:28:20.7332330Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22f490a]
2024-10-09T08:28:20.7335354Z 
2024-10-09T08:28:20.7335553Z goroutine 39942 [running]:
2024-10-09T08:28:20.7338762Z testing.tRunner.func1.2({0x269aee0, 0x3eea5a0})
2024-10-09T08:28:20.7341711Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
2024-10-09T08:28:20.7342418Z testing.tRunner.func1()
2024-10-09T08:28:20.7345678Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
2024-10-09T08:28:20.7348979Z panic({0x269aee0?, 0x3eea5a0?})
2024-10-09T08:28:20.7351996Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-10-09T08:28:20.7353120Z github.com/matrixorigin/matrixone/pkg/logservice.(*store).close(0x0)
2024-10-09T08:28:20.7356603Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/store.go:187 +0x2a
2024-10-09T08:28:20.7360083Z github.com/matrixorigin/matrixone/pkg/logservice.runStoreTest.func1()
2024-10-09T08:28:20.7363206Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:175 +0x34
2024-10-09T08:28:20.7363958Z panic({0x269aee0?, 0x3eea5a0?})
2024-10-09T08:28:20.7366928Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
2024-10-09T08:28:20.7370473Z github.com/matrixorigin/matrixone/pkg/logservice.(*store).id(...)
2024-10-09T08:28:20.7373258Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/store.go:196
2024-10-09T08:28:20.7376520Z github.com/matrixorigin/matrixone/pkg/logservice.TestGetHeartbeatMessage.func1(0xc0004181a0, 0x0)
2024-10-09T08:28:20.7379628Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:468 +0x4f
2024-10-09T08:28:20.7382607Z github.com/matrixorigin/matrixone/pkg/logservice.runStoreTest(0xc0004181a0, 0x2a9dc08)
2024-10-09T08:28:20.7383641Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:177 +0x2f8
2024-10-09T08:28:20.7386740Z github.com/matrixorigin/matrixone/pkg/logservice.TestGetHeartbeatMessage(0xc0004181a0)
2024-10-09T08:28:20.7389942Z 	/home/runner/work/matrixone/matrixone/pkg/logservice/store_test.go:482 +0x2e
2024-10-09T08:28:20.7392631Z testing.tRunner(0xc0004181a0, 0x2a9d510)
2024-10-09T08:28:20.7393371Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
2024-10-09T08:28:20.7396353Z created by testing.(*T).Run in goroutine 1
2024-10-09T08:28:20.7399243Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826
2024-10-09T08:28:20.7503918Z ##[group]Run find ./ut-report -name top.txt -exec cat {} \;
```

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/19167, please rerun

**Comment by volgariver6** [comment]
fixed
