### ISSUE TITLE
[Bug]: TestCancelRunningTask timeout

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19185]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:1008-remove-global-vars

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
3.6367390Z panic: test timed out after 40m0s
2024-10-09T09:16:43.6370024Z 	running tests:
2024-10-09T09:16:43.6373088Z 		TestCancelRunningTask (39m59s)
2024-10-09T09:16:43.6373448Z 
2024-10-09T09:16:43.6373617Z goroutine 311 [running]:
2024-10-09T09:16:43.6377970Z testing.(*M).startAlarm.func1()
2024-10-09T09:16:43.6380515Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2373 +0x265
2024-10-09T09:16:43.6383225Z created by time.goFunc
2024-10-09T09:16:43.6383873Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/time/sleep.go:215 +0x45
2024-10-09T09:16:43.6386196Z 
2024-10-09T09:16:43.6386401Z goroutine 1 [chan receive, 39 minutes]:
2024-10-09T09:16:43.6388806Z testing.(*T).Run(0xc0000dc680, {0x213de95, 0x15}, 0x21b3380)
2024-10-09T09:16:43.6393296Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1751 +0x851
```

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11251022598/job/31281164414?pr=19174
```

**Comment by w-zr** [comment]
尚无进度。

**Comment by w-zr** [comment]
尚无进度。

**Comment by w-zr** [comment]
尚无进度。

**Comment by daviszhen** [comment]
最近没复现先关了。

**Comment by ck89119** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764320787?pr=20385
