### ISSUE TITLE
[Bug]: select column name with inner join caused crash 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1922]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): v0.3.0 commit-id:commit c473412af2842cd3c5e5fad6ea0626c7bbd095d3
- Hardware parameters: Macbook Pro, M1 16GB memory
- OS type: OSX
- Others:
```

### Actual Behavior

I tried to select some columns from inner join result. MatrixOne crashed with this sql. below is my sql:
```
(dump@127.0.0.1) [abc]>select * from variance2;
+------+------+
| a    | b    |
+------+------+
|   14 | 3514 |
|   10 | 3514 |
|    1 |   61 |
+------+------+
3 rows in set (0.03 sec)

(dump@127.0.0.1) [abc]>select * from variance;
+------+------+
| a    | b    |
+------+------+
|    1 |    4 |
|   10 |    3 |
|   19 |   12 |
|  239 |  114 |
|   49 |  149 |
|   10 |  159 |
|    1 |    3 |
|   34 |   35 |
+------+------+
8 rows in set (0.05 sec)
(dump@127.0.0.1) [abc]>select variance.a,variance2.b from variance inner join variance2 on variance.a =  variance2.a group by variance.a;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)
ERROR:
Can't connect to the server

```

The error log was:
```
{"level":"info","ts":"2022-03-21 12:17:59.152","logger":"goetty","caller":"goetty@v1.13.0/application.go:155","msg":"application accept loop started","listen-address":"0.0.0.0:20100"}
{"level":"info","ts":"2022-03-21 12:17:59.152","logger":"goetty","caller":"goetty@v1.13.0/application.go:96","msg":"application started","listen-address":"0.0.0.0:6001"}
{"level":"info","ts":"2022-03-21 12:17:59.152","logger":"goetty","caller":"goetty@v1.13.0/application.go:155","msg":"application accept loop started","listen-address":"0.0.0.0:6001"}
{"level":"info","ts":"2022-03-21 12:17:59.152","logger":"goetty","caller":"goetty@v1.13.0/application.go:96","msg":"application started","listen-address":"0.0.0.0:20100"}
{"level":"info","ts":"2022-03-21 12:18:21.906","logger":"goetty","caller":"goetty@v1.13.0/application.go:216","msg":"session connected","listen-address":"0.0.0.0:6001","session-id":1,"addr":"127.0.0.1:55927"}
{"level":"info","ts":"2022-03-21 12:18:21.932","logger":"goetty","caller":"goetty@v1.13.0/application.go:226","msg":"session read failed","listen-address":"0.0.0.0:6001","session-id":1,"addr":"127.0.0.1:55927","error":"read tcp4 127.0.0.1:6001->127.0.0.1:55927: use of closed network connection"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x106069eec]

goroutine 627 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.getDataFromPipeline({0x1066f6e00, 0x1400497a800}, 0x140032b22a0)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:260 +0x7bc
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.Call(0x1400053fd40, {0x106606ea0, 0x140004f1c20})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/sql/colexec/output/output.go:45 +0x184
github.com/matrixorigin/matrixone/pkg/vm.Run({0x140004f1c80, 0x2, 0x2}, 0x1400053fd40)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/vm/vm.go:48 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunMerge(0x14004323820, 0x1400053fd40)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/vm/pipeline/pipeline.go:114 +0x130
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0x1400465e100, {0x106970bb8, 0x14002dc1ce0})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/sql/compile/scope.go:475 +0x1e4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0x140041af700, 0x5144)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/sql/compile/exec.go:77 +0xa0
github.com/matrixorigin/matrixone/pkg/frontend.(*ComputationWrapperImpl).Run(0x140041ab3e8, 0x5144)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:901 +0x34
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0x14003c7aeb0, {0x1400051c200, 0x71})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:1152 +0x284c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x14003c7aeb0, 0x140041b1700)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:1280 +0x668
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x14002f80840)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/routine.go:100 +0x328
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
```

**Comment by domingozhang** [comment]
it seems fixed  

mysql> select variance.a,variance2.b from variance inner join variance2 on variance.a =  variance2.a group by variance.a;
+------------+-------------+
| variance.a | variance2.b |
+------------+-------------+
|          1 |          61 |
|         10 |        3514 |
+------------+-------------+
2 rows in set (0.03 sec)
