### ISSUE TITLE
[Bug]: ut TestSqlWorker_GetCNServerByConnID failed

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#19289]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
=== RUN   TestSqlWorker_GetCNServerByConnID
panic: missing free: address 0x7ff064900000, size 1048576, allocated at github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate.func1
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:87
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ClosureDeallocatorPool[...]).Get2
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/closure_deallocator.go:76
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:80
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*RandomAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/random_allocator.go:[42](https://github.com/matrixorigin/matrixone/actions/runs/11312356433/job/31459676822?pr=19233#step:9:43)
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ProfileAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/profile_allocator.go:119
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*MetricsAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/metrics_allocator.go:92
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*SizeBoundedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/size_bounded_allocator.go:78
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ManagedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/managed_allocator.go:48
	github.com/matrixorigin/matrixone/pkg/frontend.(*SessionAllocator).Alloc
		/home/runner/work/matrixone/matrixone/pkg/frontend/types.go:[44](https://github.com/matrixorigin/matrixone/actions/runs/11312356433/job/31459676822?pr=19233#step:9:45)7
	github.com/matrixorigin/matrixone/pkg/frontend.(*BufferAllocator).Alloc
		/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_buffer.go:61
	github.com/matrixorigin/matrixone/pkg/frontend.NewIOSession
		/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_buffer.go:213
	github.com/matrixorigin/matrixone/pkg/proxy.(*testCNServer).Start
		/home/runner/work/matrixone/matrixone/pkg/proxy/server_conn_test.go:250
	github.com/matrixorigin/matrixone/pkg/proxy.startTestCNServer.func1
		/home/runner/work/matrixone/matrixone/pkg/proxy/server_conn_test.go:170
	runtime.goexit
		/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700
	

goroutine 5 [running]:
github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate.func2()
	/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:100 +0x1a7
============================================
```

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
ci ut test
```

**Comment by volgariver6** [comment]
fixed
