### ISSUE TITLE
[Bug]: Calling `pb.CmdMethod_GetReplicaCount` will cause CN panic

### ISSUE THREAD

**Issue by cyberchen98** [matrixorigin/matrixone#19319]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0cc06f96e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"ERROR","time":"2024/10/14 12:33:35.976169 +0000","caller":"frontend/server.go:204","msg":"HandShake error","error":"internal error: check password failed"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x39fe70e]

goroutine 1042 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleGetReplicaCount(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:488
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x55b5f40, {0x55e42d8, 0xc0161afd10?}, 0x4f391b8?, 0xc0161b2140?, 0x1b6)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/method_based.go:70 +0x53
github.com/matrixorigin/matrixone/pkg/common/morpc.(*methodBasedServer[...]).onMessage.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/method_based.go:213 +0x2ce
github.com/matrixorigin/matrixone/pkg/common/morpc.(*methodBasedServer[...]).onMessage(0x56a4880, {0x55e42d8, 0xc0161afd10}, {{0x55e42d8, 0xc0161afd10}, 0xc01617b1f0, {0x560f9c8, 0xc01616de60}, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/method_based.go:229 +0x302
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0006c7a20, {0x5666460, 0xc016126700}, {0x4abcc40, 0xc0161addb0}, 0x2)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:260 +0xc3e
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0006c7ad0, {0x5666460, 0xc016126700})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:393 +0x365
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:356 +0x82
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 690
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:348 +0x3fa
```

### Expected Behavior

When the shardService is not enabled, the `GetReplicaCount` method of the queryService returns 0 instead of panic.

### Steps to Reproduce

```Markdown
Calling `pb.CmdMethod_GetReplicaCount` RPC via queryService
```

**Comment by zhangxu19830126** [comment]
fixed
