### ISSUE TITLE
[Bug]: select variance.b, count(*) from variance; crashed

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1932]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): v0.3.0 commit-id:commit c473412af2842cd3c5e5fad6ea0626c7bbd095d3
- Hardware parameters: Macbook Pro, M1 16GB memory
- OS type: OSX
- Others:
```

### Actual Behavior

```
(dump@127.0.0.1) [abc]>select * from variance
    -> ;
+------+------+
| a    | b    |
+------+------+
|    1 |    4 |
|   10 |    3 |
|   19 |   12 |
|  239 |  114 |
|   49 |  149 |
|   10 |  159 |
|    1 |    3 |
|   34 |   35 |
+------+------+
8 rows in set (0.04 sec)

(dump@127.0.0.1) [abc]>select variance.b,count(*) from variance;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

Error message:
```
{"level":"ERROR","time":"2022/03/22 15:54:13.672302 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647935653694477000}
{"level":"ERROR","time":"2022/03/22 15:54:13.723256 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
{"level":"ERROR","time":"2022/03/22 17:09:13.616994 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647940155542823000}
{"level":"ERROR","time":"2022/03/22 17:09:13.786663 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
{"level":"ERROR","time":"2022/03/22 20:39:43.788400 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647952783941531000}
{"level":"ERROR","time":"2022/03/22 20:39:43.793457 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
{"level":"ERROR","time":"2022/03/22 22:39:55.852227 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647959999527185000}
{"level":"ERROR","time":"2022/03/22 22:39:55.880747 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
{"level":"ERROR","time":"2022/03/22 23:22:20.785209 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647962540919662000}
{"level":"ERROR","time":"2022/03/22 23:22:20.819500 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
{"level":"ERROR","time":"2022/03/23 02:37:16.671649 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647974236852914000}
{"level":"ERROR","time":"2022/03/23 02:37:16.675134 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
{"level":"ERROR","time":"2022/03/23 08:40:09.429817 +0800","name":"cube.prophet","caller":"prophet/systime_mon.go:35","msg":"system time jump backward","node":"node0","last":1647996009446690000}
{"level":"ERROR","time":"2022/03/23 08:40:09.664110 +0800","name":"cube.prophet","caller":"prophet/prophet.go:336","msg":"system time jumps backward","node":"node0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x10073cd90]

goroutine 1260 [running]:
github.com/matrixorigin/matrixone/pkg/container/vector.Length(0x0)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/container/vector/vector.go:166 +0x20
github.com/matrixorigin/matrixone/pkg/frontend.getDataFromPipeline({0x101ca6e00, 0x140049c9e00}, 0x14002946460)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:231 +0x3f8
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.Call(0x14002ac2120, {0x101bb6ea0, 0x14004bcdbc0})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/sql/colexec/output/output.go:45 +0x184
github.com/matrixorigin/matrixone/pkg/vm.Run({0x14004bcdbf0, 0x2, 0x2}, 0x14002ac2120)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/vm/vm.go:48 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunMerge(0x140031bf820, 0x14002ac2120)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/vm/pipeline/pipeline.go:114 +0x130
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0x1400afc0500, {0x101f20bb8, 0x14003350b70})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/sql/compile/scope.go:475 +0x1e4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0x1400b012980, 0x990e)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/sql/compile/exec.go:77 +0xa0
github.com/matrixorigin/matrixone/pkg/frontend.(*ComputationWrapperImpl).Run(0x1400b841d58, 0x990e)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:901 +0x34
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0x1400b18c5f0, {0x1400599b320, 0x28})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:1152 +0x284c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x1400b18c5f0, 0x1400ac7e840)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_cmd_executor.go:1280 +0x668
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x140057ca960)
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/routine.go:100 +0x328
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/routine.go:152 +0x1ac
```

**Comment by domingozhang** [comment]
mysql> select variance.b,count(*) from variance;
+------------+----------+
| variance.b | count(*) |
+------------+----------+
|          3 |        8 |
+------------+----------+
1 row in set (0.01 sec)


it seems fixed
