### ISSUE TITLE
[Bug]: txn leak during restore test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19411]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cf5296b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

告警信息：
```
【【MO-OB】 • mo_logs_txn_leak • 告警中:1
 
2024-10-17T16:33:27+08:00
详请
当前全部告警
历史告警查询
 
🚨 触发中告警 [1]
 
告警处理人:  @sukki37(秦姝琦) 
 告警名称 : mo_logs_txn_leak
 告警级别 : 
 命名空间 : mo-big-data-20241016
完整 Label 
alertOwner : shuqi.qin
alertTeam : CN Team
alertname : mo_logs_txn_leak
alerttype : error-log
namespace : mo-big-data-20241016
node_name : 10.129.0.102
pod : nightly-regression-dis-tp-cn-jhblk
serviceScope : mo-cluster
severity : ctitical
 告警状态 : 🚨 FIRING
 开始时间 : 2024-10-17T16:33:17+08:00
 结束时间 : Not End
 告警描述 : 事务泄漏告警: mo-big-data-20241016/nightly-regression-dis-tp-cn-jhblk
---
```
restore 执行的sql：restore account sys from snapshot sp01;

日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%223wf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241016%5C%22%7D%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729137600000%22,%22to%22:%221729155600000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile：
[restore.tar.gz](https://github.com/user-attachments/files/17409696/restore.tar.gz)

### Steps to Reproduce

```Markdown
测试步骤：

create snapshot sp01 for account sys ;
drop database big_data_test;
restore account sys from snapshot sp01;  （执行的utc+8时间，大约在2024-10-17 12:00:00-2024-10-17 17:00:00）
```

**Comment by daviszhen** [comment]
```

goroutine 477585 [semacquire, 13 minutes]:
sync.runtime_Semacquire(0x11e50f8?)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*WaitGroup).Wait(0x0?)
	/usr/local/go/src/sync/waitgroup.go:118 +0x48
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc0089e6820)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:481 +0x20b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc0089e6820, 0xc03f8c1508?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile2.go:235 +0x7fb
github.com/matrixorigin/matrixone/pkg/frontend.executeStatusStmtInBack(0xc015486808, 0xc05526f7c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_status_stmt.go:35 +0x122
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtInBack(0xc015486808, 0xc05526f7c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_exec.go:457 +0x985
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x56af730, 0xc015486808}, 0xc05526f7c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2610 +0x319
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x56af730, 0xc015486808}, 0xc05526f7c0, {0x5686108, 0xc03f8c1508})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2577 +0x20c
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x56af730, 0xc015486808}, 0xc05526f7c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2537 +0x55f
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x56af730, 0xc015486808}, 0xc05526f7c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2429 +0x109
github.com/matrixorigin/matrixone/pkg/frontend.doComQueryInBack(0xc015486808, 0xc05526f7c0, 0xc057c92850)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_exec.go:367 +0x102d
github.com/matrixorigin/matrixone/pkg/frontend.(*backExec).Exec(0xc011174968, {0x55bd838, 0xc037062480}, {0xc057bb87e0, 0x90})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_exec.go:131 +0x60b
github.com/matrixorigin/matrixone/pkg/frontend.recreateTable({0x55bd838, 0xc0cb39f200}, {0xc0006c9170, 0x24}, {0x561a238, 0xc011174968}, {0xc03e83d673, 0x4}, 0xc06e959c40, 0x0, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/snapshot.go:1068 +0x7b9
github.com/matrixorigin/matrixone/pkg/frontend.restoreToDatabaseOrTable({0x55bd838, 0xc0cb39f200}, {0xc0006c9170, 0x24}, {0x561a238, 0xc011174968}, {0xc03e83d673, 0x4}, {0xc06e7d4180, 0xd}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/snapshot.go:826 +0x12e9
github.com/matrixorigin/matrixone/pkg/frontend.restoreToDatabase({0x55bd838, 0xc0cb39f200}, {0xc0006c9170, 0x24}, {0x561a238, 0xc011174968}, {0xc03e83d673, 0x4}, {0xc06e7d4180, 0xd}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/snapshot.go:663 +0x1fe
github.com/matrixorigin/matrixone/pkg/frontend.restoreToAccount({0x55bd838, 0xc0cb39f200}, {0xc0006c9170, 0x24}, {0x561a238, 0xc011174968}, {0xc03e83d673, 0x4}, 0x0, 0xc06e226db0, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/snapshot.go:620 +0x5a7
github.com/matrixorigin/matrixone/pkg/frontend.doRestoreSnapshot({0x55bd838, 0xc0cb39f200}, 0xc05503c008, 0xc03f8aafc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/snapshot.go:465 +0x1285
github.com/matrixorigin/matrixone/pkg/frontend.handleRestoreSnapshot(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:1189
github.com/matrixorigin/matrixone/pkg/frontend.execInFrontend(0xc05503c008, 0xc03f66c280)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/self_handle.go:422 +0x3fb2
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt(0xc05503c008, 0xc03f66c280)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2640 +0xc59
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x56af448, 0xc05503c008}, 0xc03f66c280)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2608 +0x2cf
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x56af448, 0xc05503c008}, 0xc03f66c280, {0x5686108, 0xc03f8c0008})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2577 +0x20c
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x56af448, 0xc05503c008}, 0xc03f66c280)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2537 +0x55f
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x56af448, 0xc05503c008}, 0xc03f66c280)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2429 +0x109
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc05503c008, 0xc03f66c280)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2393 +0x3b3
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc05503c008, 0xc03f66c280, 0xc03f8aaf50)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2997 +0x1d9a
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest(0xc05503c008, 0xc03f66c280, 0xc02ebb7b88)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3072 +0x785
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc037d21b00, 0xc02ebb7b88)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:287 +0x63d
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc00710e180, 0xc0546786c0, {0xc03e83d650, 0x27, 0x27})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385 +0x327
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest(0xc007097180, 0xc0546786c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:511 +0x1eb
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc007097180, {0x55bd870, 0xc0072a6f50}, 0xc0546786c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:479 +0x94
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0xc007097180?, {0x55bd870?, 0xc0072a6f50?}, 0xc0006c9170?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:211 +0x2f
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc007097180, {0x55bd870, 0xc0072a6f50}, {0x56038f8?, 0xc06953e2c8?})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:207 +0x4a6
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 898
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:176 +0x165


```

**Comment by daviszhen** [comment]
fixed

**Comment by Ariznawlll** [comment]
👀一下
