### ISSUE TITLE
[Bug]: `TestAppendAndGC` failed again

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19461]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```

2024/10/19 05:18:46.689336 +0000 INFO v3/checkpoint.go:1396 GC-TRACE-PROCESS {"task": "gc-process-28", "duration": "52.45469ms", "start-scan-watermark": "CKP[I][2][ckp 215, truncate 215](1729315126151691697-1->1729315126300021457-0)", "end-scan-watermark": "CKP[I][2][ckp 215, truncate 215](1729315126151691697-1->1729315126300021457-0)", "start-gc-watermark": "CKP[G][2][ckp 214, truncate 214](0-0->1729315126151691697-1)", "end-gc-watermark": "CKP[G][2][ckp 214, truncate 214](0-0->1729315126151691697-1)"}
--- FAIL: TestAppendAndGC (1.72s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 7935 [running]:
testing.tRunner.func1.2({0x579a060, 0xc0048d0480})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
panic({0x579a060?, 0xc0048d0480?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v3.(*checkpointCleaner).DoCheck(0xc0039c10e0)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gc/v3/checkpoint.go:1251 +0x4b85
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/test.TestAppendAndGC(0xc00054b040)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/test/db_test.go:6409 +0xf5d
testing.tRunner(0xc00054b040, 0x5b42148)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826

```

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11414737539/job/31764006028?pr=19454
```

**Comment by LeftHandCold** [comment]
写wal的时候报错。

**Comment by LeftHandCold** [comment]
fixed
