### ISSUE TITLE
[Bug]: upgrade from 6f3e65b4 to 4e2df0637 cause CN panic

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#19556]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4e2df0637

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN panic after upgrade

```
panic: Unable to find target column from predefined table columns

goroutine 623 [running]:
github.com/matrixorigin/matrixone/pkg/sql/plan.GetColDefFromTable(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/make.go:505
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache.getTableDef(0xc011f0cdc0, {0xc01a3491d0, 0x5, 0xc0135ec8f0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache/catalog.go:840 +0x1d18
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache.InitTableItemWithColumns(0xc011f0cdc0, {0xc013602008, 0x5, 0xc00008b600?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache/catalog.go:598 +0x245
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).replayCatalogCache.(*CatalogCache).InsertColumns.func11(0xc007e44a20)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache/catalog.go:618 +0x272
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache.ParseColumnsBatchAnd(0xc018d42a20, 0xc00008bd50)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache/catalog.go:582 +0xcc8
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache.(*CatalogCache).InsertColumns(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/cache/catalog.go:602
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).replayCatalogCache(0xc000da6a00, {0x58ff8f0, 0xc000eac0f0}, 0xc000da6908)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:764 +0x10c6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).connect(0xc000da6a00, {0x58ff8f0, 0xc000eac0f0}, 0xc000da6908)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:808 +0x80e
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*connector).run(0xc0010a8780, {0x58ff8f0, 0xc000eac0f0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:261 +0x4b
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).InitLogTailPushModel in goroutine 483
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:1542 +0x252
```

log: 
[panic.log.txt](https://github.com/user-attachments/files/17494610/panic.log.txt)

### Steps to Reproduce

```Markdown
upgrade from 6f3e65b4 to 4e2df0637
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by aylei** [comment]
验证了
