### ISSUE TITLE
[Bug]:ut TestSnapshotGC failed

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19826]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
+------------------------------------------------------------------------------------------------------------------------------+
| Failed UT Packages                                                                                                           |
+-------------------------------------------------------------+----------------------+----------------------+--------+---------+
| PACKAGE                                                     | START_TIME           | END_TIME             | RESULT | ELAPSED |
+-------------------------------------------------------------+----------------------+----------------------+--------+---------+
| github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/test | 20[24](https://github.com/matrixorigin/matrixone/actions/runs/11695364942/job/32570668615?pr=19804#step:9:25)-11-06T01:37:41Z | 2024-11-06T01:38:19Z | fail   | 37.52   |
+-------------------------------------------------------------+----------------------+----------------------+--------+---------+
============================================
[TEST]: TestSnapshotGC
[START_AT]: 2024-11-06T01:38:17Z
[END_AT]: 2024-11-06T01:38:19Z
[RESULT]: fail
[ELAPSED]: 1.66
[OUTPUTS]:
=== RUN   TestSnapshotGC

```

```
2024/11/06 01:38:18.962449 +0000 INFO v3/checkpoint.go:1392 GC-TRACE-PROCESS {"task": "gc-process-30", "duration": "55.237675ms", "error": "file 0192ff1f-58b6-78c1-a7e1-80839b1c5fad_00000 is not found", "start-scan-watermark": "CKP[I][2][ckp 1, truncate 1](0-0->1730857097404665868-0)", "end-scan-watermark": "CKP[I][2][ckp 1, truncate 1](0-0->1730857097404665868-0)", "start-gc-watermark": "CKP[G][2][ckp 6, truncate 6](0-0->1730857097526825857-1)", "end-gc-watermark": "CKP[G][2][ckp 6, truncate 6](0-0->1730857097526825857-1)"}
2024/11/06 01:38:18.962548 +0000 INFO v3/checkpoint.go:248 GC-Task-Done {"task": "gc-process-30", "duration": "55.427177ms"}
--- FAIL: TestSnapshotGC (1.66s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 8323 [running]:
testing.tRunner.func1.2({0x5aba660, 0xc003830168})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1635 +0x6b6
panic({0x5aba660?, 0xc003830168?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v3.(*checkpointCleaner).DoCheck(0xc00098e240)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gc/v3/checkpoint.go:1247 +0x4b85
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/test.TestSnapshotGC(0xc00098c000)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/test/db_test.go:6681 +0x2abb
testing.tRunner(0xc00098c000, 0x5e7a760)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826

```

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11695364942/job/32570668615?pr=19804
```

**Comment by LeftHandCold** [comment]
GC-SCAN-WINDOW-ERROR {"error": "file 0192ff1f-58b6-78c1-a7e1-80839b1c5fad_00000 is not found", "checkpoint": "CKP[I][2][ckp 6, truncate 6](1730857097404665868-1->1730857097526825857-0)"}

https://github.com/matrixorigin/matrixone/pull/19891 fixed
