### ISSUE TITLE
[Bug]: UT TestRemoveRunningTask failed

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#20020]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
=== RUN   TestRemoveRunningTask
2024/11/13 05:13:49.284325 +0000 DEBUG task-runner heartbeat task started {"runner-id": "r1"}
2024/11/13 05:13:49.284485 +0000 DEBUG task-runner fetch task started {"runner-id": "r1"}
2024/11/13 05:13:49.284610 +0000 DEBUG task-runner done task started {"runner-id": "r1"}
2024/11/13 05:13:49.284748 +0000 DEBUG task-runner dispatch task started {"runner-id": "r1"}
2024/11/13 05:13:49.285052 +0000 DEBUG task-runner retry task started {"runner-id": "r1"}
2024/11/13 05:13:49.284241 +0000 DEBUG task-runner executor registered {"runner-id": "r1", "code": "TestOnly"}
2024/11/13 05:13:49.287743 +0000 INFO task-runner task added to wait queue {"runner-id": "r1", "task": "t1/0"}
2024/11/13 05:13:49.287904 +0000 DEBUG task-runner task start execute {"runner-id": "r1", "task": "t1/0"}
2024/11/13 05:13:49.287990 +0000 DEBUG task-runner task execute completed {"runner-id": "r1", "task": "t1/0", "cost": "107.141µs"}
2024/11/13 05:13:49.288172 +0000 INFO task-runner task removed {"runner-id": "r1", "task-id": 1}
2024/11/13 05:13:49.288348 +0000 INFO task-runner task removed {"runner-id": "r1", "task-id": 1}
2024/11/13 05:13:49.288419 +0000 INFO task-runner task completed {"runner-id": "r1", "task": "t1/0"}
    task_runner_test.go:249: 
        	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/taskservice/task_runner_test.go:249
        	            				/home/runner/work/matrixone/matrixone/pkg/taskservice/task_runner_test.go:287
        	            				/home/runner/work/matrixone/matrixone/pkg/taskservice/task_runner_test.go:233
        	Error:      	Should be true
        	Test:       	TestRemoveRunningTask
        	Messages:   	task should be added to completedTasks
2024/11/13 05:13:49.289270 +0000 DEBUG task-runner done task stopped {"runner-id": "r1"}
2024/11/13 05:13:49.289331 +0000 DEBUG task-runner fetch task stopped {"runner-id": "r1"}
2024/11/13 05:13:49.289[38](https://github.com/matrixorigin/matrixone/actions/runs/11810899765/job/32903630148?pr=19953#step:9:39)7 +0000 INFO task-runner daemon task poll worker stopped {"runner-id": "r1"}
2024/11/13 05:13:49.289436 +0000 DEBUG task-runner dispatch task stopped {"runner-id": "r1"}
2024/11/13 05:13:49.289486 +0000 DEBUG task-runner retry task stopped {"runner-id": "r1"}
2024/11/13 05:13:49.289531 +0000 DEBUG task-runner heartbeat task stopped {"runner-id": "r1"}
2024/11/13 05:13:49.289228 +0000 DEBUG task-runner heartbeat task stopped {"runner-id": "r1"}
--- FAIL: TestRemoveRunningTask (0.01s)
```

### Steps to Reproduce

```Markdown
run ut in ci
```

**Comment by jensenojs** [comment]
在removeRunningTask之后sleep之后能稳定复现

这个问题的原因是, 在sleep期间fetch-task的异步任务把r.runningTasks.completedTasks这个map给清空了. 是预期的行为, 需要更正这个ut的行为

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11852190244/job/33029927379?pr=20106
repro

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11854650788/job/33037240969?pr=20125

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/11860903245/job/33057111950?pr=20119

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11884674881/job/33113211658?pr=20136

**Comment by jensenojs** [comment]
本地复现成功, 还在定位根因

**Comment by reusee** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11875024153/job/33091731083?pr=20130

**Comment by jensenojs** [comment]
确认了一下这几个failed的原因
- 之前在轮询的时候忘记在完成测试内容之后释放锁了. 导致doFetch任务无法获取锁, 来结束任务.

```
2024-11-15T08:33:18.0408391Z goroutine 325 [sync.RWMutex.Lock, 39 minutes]:
2024-11-15T08:33:18.0408891Z sync.runtime_SemacquireRWMutex(0xc0024cad3c?, 0x1?, 0x309b9b0?)
2024-11-15T08:33:18.0409485Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/sema.go:105 +0x25
2024-11-15T08:33:18.0409957Z sync.(*RWMutex).Lock(0xc0024cad28)
2024-11-15T08:33:18.0410430Z 	/opt/hostedtoolcache/go/1.23.0/x64/src/sync/rwmutex.go:153 +0x8b
2024-11-15T08:33:18.0411119Z github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).doFetch(0xc0024cac40)
2024-11-15T08:33:18.0411935Z 	/home/runner/work/matrixone/matrixone/pkg/taskservice/task_runner.go:367 +0x477
2024-11-15T08:33:18.0412846Z github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).fetch(0xc0024cac40, {0x23df6e8, 0xc0023f4540})
...
```

**Comment by qingxinhome** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11886724978/job/33118333211?pr=20050

**Comment by jensenojs** [comment]
fix完了, 再观察一段时间
