### ISSUE TITLE
[Bug]: UT TestPartitionBasedShardCanBeCreated failed(2.0dev)

### ISSUE THREAD

**Issue by zengyan1** [matrixorigin/matrixone#20044]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

7fd55f20c6e703a4efaa4423814db360ca2dfec4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: writeto tcp4 127.0.0.1:47780->127.0.0.1:12460: read tcp4 127.0.0.1:47780->127.0.0.1:12460: read: connection reset by peer

goroutine 14329 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).bootstrap(0xc072c95088)
	/home/runner/work/matrixone/matrixone/pkg/cnservice/server.go:914 +0x6aa
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).initEngine(0xc072c95088, {0x8605040, 0xc4ac800}, {0x8605260, 0xc037d7dd60}, 0xc049128b40)
	/home/runner/work/matrixone/matrixone/pkg/cnservice/server.go:504 +0x2d7
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).initMOServer(0xc072c95088, {0x8605040, 0xc4ac800}, 0xc049128b40, 0xc0a6eafd58)
	/home/runner/work/matrixone/matrixone/pkg/cnservice/server.go:468 +0x226
github.com/matrixorigin/matrixone/pkg/cnservice.NewService(0xc043c99808, {0x8605040, 0xc4ac800}, {0x86631d0, 0xc03fe48708}, 0x0, {0xc02e7b7e30, 0x4, 0x4})
	/home/runner/work/matrixone/matrixone/pkg/cnservice/server.go:204 +0x1d5b
github.com/matrixorigin/matrixone/pkg/embed.(*operator).startCNServiceLocked(0xc09916d008, {0x86631d0, 0xc03fe48708})
	/home/runner/work/matrixone/matrixone/pkg/embed/operator.go:259 +0x71b
github.com/matrixorigin/matrixone/pkg/embed.(*operator).Start(0xc09916d008)
	/home/runner/work/matrixone/matrixone/pkg/embed/operator.go:163 +0x212
github.com/matrixorigin/matrixone/pkg/embed.(*cluster).doStartLocked.func1(0xc09916d008)
	/home/runner/work/matrixone/matrixone/pkg/embed/cluster.go:127 +0x7c
created by github.com/matrixorigin/matrixone/pkg/embed.(*cluster).doStartLocked in goroutine 13323
	/home/runner/work/matrixone/matrixone/pkg/embed/cluster.go:125 +0x2e9

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11814519211/job/32913739186?pr=20030
```

**Comment by volgariver6** [comment]
[mo.log](https://github.com/user-attachments/files/17732028/mo.log)

**Comment by volgariver6** [comment]
未处理

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/11953383425/job/33321154193?pr=20241

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/11974736312/job/33386483041?pr=20303

**Comment by volgariver6** [comment]
hard to repro

**Comment by volgariver6** [comment]
hard to repro

**Comment by fengttt** [comment]
If we cannot repro this in the last few months, we should close.    Make sure we have the necessary logs added.

**Comment by XuPeng-SH** [comment]
@heni02 please help to close this issue
