### ISSUE TITLE
[Bug]: client cannot cancel connection when max-active queue is full

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#20076]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest main

### Actual Behavior

Connection cannot be canceled when wait-active queue is full.

### Expected Behavior

Client should be able to cancel the connection even if wait-active queue is full, either via connection-timeout or proactive cancelation

### Steps to Reproduce

```Markdown
1. launcn an CN locally, with max-active=1
2. create a connection and start a txn
3. create a new connection to the CN and cancel the connection
4. the connection cannot be canceled


➜  ~ mysql -h 127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```
```


### Additional information

_No response_

**Comment by daviszhen** [comment]
这个是因为 wait active 满了，卡住。kill 又是走新的连接，登录，又因为wait ative 满了，再此卡住。

死锁了。

**Comment by xzxiong** [comment]
mysql 关于 connect timeout 的配置

- variable
https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_connect_timeout
![image](https://github.com/user-attachments/assets/2c9ee917-2597-4089-a10f-1b8ecb814717)

- go sdk settings
https://pkg.go.dev/github.com/go-sql-driver/mysql#section-readme
![image](https://github.com/user-attachments/assets/11da81f6-01e0-4707-aeb3-933947267717)

**Comment by daviszhen** [comment]
https://www.cnblogs.com/xiaoboluo768/p/6222862.html

**Comment by xzxiong** [comment]
note:
目前方案:
- 新增配置项: connect_timeout, 集群配置
- 新增配置项: createTxnOpTimout, 集群配置

key point:
- 目前 session variables 是在 鉴权时，需要启动事务去读取；与目前等待 active-txn 冲突。
![企业微信截图_19080c86-671d-45ba-bbe2-baba1eb299bc](https://github.com/user-attachments/assets/42700625-c867-4aa7-a0f7-f65891684235)

**Comment by daviszhen** [comment]
配置项目已经增加：

- createTxnOpTimeout New/RestartTxn事务句柄的超时时间。默认值1分钟。

避免在wait active时死等。

- connectTimeout 用户登录验证超时时间。默认值1分钟。

避免在验证用户信息时，遇到事务队列满了后，创建事务卡死。

- cn级别的配置。不会相互影响。

用法：

默认值是1min.

```
[cn.frontend]
createTxnOpTimeout = 2m
connectTimeout = 2m
```

**Comment by aylei** [comment]
> 配置项目已经增加：
> 
> * createTxnOpTimeout New/RestartTxn事务句柄的超时时间。默认值1分钟。
> 
> 避免在wait active时死等。
> 
> * connectTimeout 用户登录验证超时时间。默认值1分钟。
> 
> 避免在验证用户信息时，遇到事务队列满了后，创建事务卡死。
> 
> * cn级别的配置。不会相互影响。
> 
> 用法：
> 
> 默认值是1min.
> 
> ```
> [cn.frontend]
> createTxnOpTimeout = 2m
> connectTimeout = 2m
> ```

@xzxiong 是否需要修改 mo_logger 里的 timeout

**Comment by aylei** [comment]
@volgariver6 PTAL, proxy should set connectTimeout when connects to CN

**Comment by xzxiong** [comment]
> > 配置项目已经增加：
> > 
> > * createTxnOpTimeout New/RestartTxn事务句柄的超时时间。默认值1分钟。
> > 
> > 避免在wait active时死等。
> > 
> > * connectTimeout 用户登录验证超时时间。默认值1分钟。
> > 
> > 避免在验证用户信息时，遇到事务队列满了后，创建事务卡死。
> > 
> > * cn级别的配置。不会相互影响。
> > 
> > 用法：
> > 默认值是1min.
> > ```
> > [cn.frontend]
> > createTxnOpTimeout = 2m
> > connectTimeout = 2m
> > ```
> 
> @xzxiong 是否需要修改 mo_logger 里的 timeout

共有2参数：客户端的参数，客户端主动主动断开。server端的参数，是server端主动断开。
这个场景，需生效的是 Server端的参数，但mo 有个问题：要拿 variable 需要先通过鉴权，鉴权需建事务。
现在有点折中，在配置里加，但是全局生效。（不是 mysql 当中的租户级别的参数）

**Comment by aylei** [comment]
启动 CN 后把 max-active 占满，再启动一个 session，连上去了 @daviszhen 

```
➜  ~ mysql -h 127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 109
Server version: 8.0.30-MatrixOne-v2.0

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

CN log:
```
{"level":"WARN","time":"2024/11/20 15:33:32.741696 +0800","name":"cn-service","caller":"client/client.go:589","msg":"txn closed","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"70f70f4866a9b62a18099cbfe645020d","stack":"goroutine 4649 [running]:\nruntime/debug.Stack()\n\t/opt/homebrew/Cellar/go/1.23.3/libexec/src/runtime/debug/stack.go:26 +0x64\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnClient).closeTxn(_, {{0x63, {0x1083060c1, 0x6}}, {{0x1402c66bb40, 0x10, 0x10}, 0x5, {0x18099cdc8af55b20, 0x1, ...}, ...}, ...})\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/client.go:591 +0x35c\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).triggerEventLocked(...)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/operator_events.go:74\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).closeLocked(0x140235088c0?)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/operator.go:1268 +0x120\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Rollback.func2()\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/operator.go:689 +0x28\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Rollback(0x140286ae008, {0x109920920, 0x1402e359880})\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/operator.go:697 +0x5cc\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnClient).doCreateTxn(0x140010a77a0, {0x109920920, 0x1402e359880}, 0x140286ae008, {0x0, 0x0, 0x0, {}, {0x0, 0x0, ...}, ...})\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/client.go:358 +0x324\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnClient).New(0x140010a77a0, {0x109920920, 0x1402e359880}, {0x0, 0x0, 0x0, {}, {0x0, 0x0, 0x0}, ...}, ...)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/txn/client/client.go:286 +0x224\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).createTxnOpUnsafe.func1()\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/txn.go:422 +0xf4\ngithub.com/matrixorigin/matrixone/pkg/frontend.ExecuteFuncWithRecover(0x1099208b0?)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/mysql_buffer.go:870 +0x60\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).createTxnOpUnsafe(0x1402c17dd40, 0x1400b84d900)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/txn.go:421 +0x8dc\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).createUnsafe(0x1402c17dd40, 0x1400b84d900)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/txn.go:323 +0x198\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).Create(0x1402c17dd40, 0x1400b84d900)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/txn.go:268 +0xd4\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x109a0e328, 0x1402e2e4008}, 0x0, 0x1400b84d900)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2512 +0x220\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x109a0e328, 0x1402e2e4008}, 0x0, 0x1400b84d900)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2453 +0xf4\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0x1402e2e4008, 0x1400b84d900)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2416 +0x304\ngithub.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0x1402e2e4008, 0x1400b84d900, 0x1402e359810)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3050 +0x172c\ngithub.com/matrixorigin/matrixone/pkg/frontend.ExecRequest(0x1402e2e4008, 0x1400b84d900, 0x1402e2efb70)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3127 +0x608\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0x14021e31380, 0x1402e2efb70)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/routine.go:298 +0x4ec\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0x14018890500, 0x1402acddd40, {0x1402e3567e0, 0x1a, 0x1a})\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385 +0x258\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest(0x140188a06e0, 0x1402acddd40)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/server.go:516 +0x18c\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0x140188a06e0, {0x1099208b0, 0x14018c9be00}, 0x1402acddd40)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/server.go:484 +0x78\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0x140188a06e0?, {0x1099208b0?, 0x14018c9be00?}, 0x1400b0ed1d0?)\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/server.go:212 +0x28\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0x140188a06e0, {0x1099208b0, 0x14018c9be00}, {0x109966db8?, 0x1402e2a8698?})\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/server.go:208 +0x3a4\ncreated by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 2005\n\t/Users/aylei/repo/matrixorigin/matrixone/pkg/frontend/server.go:177 +0x154\n"}
{"level":"ERROR","time":"2024/11/20 15:33:32.742341 +0800","name":"cn-service","caller":"frontend/txn.go:64","msg":"context deadline exceeded","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 147|127.0.0.1:52921|account sys:fde5c68e-ed2e-4f78-b54d-ff8364f336bd|goRoutineId 4649|migrate-goRoutineId 0|0193487d-78b1-7052-b68b-9d46be8863ed","role":"moadmin","session_id":"0193487d-78b1-7052-b68b-9d46be8863ed","statement_id":"0193487d-78b4-7995-87f0-4fd0c22c4685","span":{"trace_id":"4537f6cd-063a-178d-f5dc-c4c4187436f7","span_id":"260b5e90f4c1fd2f"}}
```

**Comment by aylei** [comment]
@daviszhen PTAL

**Comment by aylei** [comment]
```
➜  ~ mysql -h 127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
^C
➜  ~
```

验证在 max-active 满时客户端能正常退出

**Comment by aressu1985** [comment]
fixed
