### ISSUE TITLE
[Bug]: ci bvt test report 'no available backend'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20182]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

e197a1fc63f0b0156ccf6e86961b416186b0e5ab

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/matrixone/actions/runs/11908512516/job/33184075285?pr=20171

<img width="1402" alt="image" src="https://github.com/user-attachments/assets/553904aa-a363-439a-8237-3ec4e778f2e3">

log：[Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports.zip](https://github.com/user-attachments/files/17812308/Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64.LAUNCH.PROXY.-reports.zip)

### Steps to Reproduce

```Markdown
trigger ci test.
```

**Comment by sukki37** [comment]
```
panic: missing free: address 0x7f342862a000, size 32768, allocated at github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate.func1
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/checked_allocator.go:91
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ClosureDeallocatorPool[...]).Get2
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/closure_deallocator.go:76
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/checked_allocator.go:84
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*RandomAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/random_allocator.go:42
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ProfileAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/profile_allocator.go:118
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*MetricsAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/metrics_allocator.go:92
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*InuseTrackingAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/inuse_tracking_allocator.go:58
	github.com/matrixorigin/matrixone/pkg/container/hashtable.(*StringHashMap).allocate
		/home/runner/work/matrixone/matrixone/head/pkg/container/hashtable/string_hash_map.go:74
	github.com/matrixorigin/matrixone/pkg/container/hashtable.(*StringHashMap).Init
		/home/runner/work/matrixone/matrixone/head/pkg/container/hashtable/string_hash_map.go:99
	github.com/matrixorigin/matrixone/pkg/common/hashmap.NewStrMap
		/home/runner/work/matrixone/matrixone/head/pkg/common/hashmap/strhashmap.go:37
	github.com/matrixorigin/matrixone/pkg/sql/colexec/hashmap_util.(*HashmapBuilder).BuildHashmap
		/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec/hashmap_util/hashmap_util.go:199
	github.com/matrixorigin/matrixone/pkg/sql/colexec/shufflebuild.(*ShuffleBuild).Call
		/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec/shufflebuild/build.go:79
	github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
		/home/runner/work/matrixone/matrixone/head/pkg/vm/pipeline/pipeline.go:71
	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
		/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:165
	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
		/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:484
	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
		/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:341
	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
		/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:393
	github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
		/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:296
	github.com/panjf2000/ants/v2.(*goWorker).run.func1
		/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
	runtime.goexit
		/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700
	 goId 875

goroutine 18 [running]:
github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate.func2()
	/home/runner/work/matrixone/matrixone/head/pkg/common/malloc/checked_allocator.go:105 +0x154
[mysql] 2024/11/19 07:57:05 connection.go:49: unexpected EOF
2024/11/19 07:57:05.512313 +0000 INFO etl/content.go:200 generate req sql {"type": "rawlog", "csv": 10478085, "sql": 10503764}
```

**Comment by badboynt1** [comment]
在设置export MO_MALLOC_DEBUG=1之后，跑了很多次仍然跑不出来。待继续观察

**Comment by badboynt1** [comment]
暂未复现

**Comment by badboynt1** [comment]
暂未复现

**Comment by Ariznawlll** [comment]
暂未复现，先关闭
