### ISSUE TITLE
[Bug]: ut TestSpeedupAbortAllTxn failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#20318]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/11980044139/job/33403510179?pr=20286

[job-logs.txt.zip](https://github.com/user-attachments/files/17878620/job-logs.txt.zip)

### Steps to Reproduce

```Markdown
run ut
```

**Comment by zhangxu19830126** [comment]
logtail consumer panic

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/20328

**Comment by jensenojs** [comment]
repro : https://github.com/matrixorigin/matrixone/actions/runs/12006737306/job/33465911471?pr=20347

[job-logs-2.zip](https://github.com/user-attachments/files/17901361/job-logs-2.zip)

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/12078917026/job/33684048760?pr=20440

**Comment by XuPeng-SH** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/12143992324/job/33862230251?pr=20537

**Comment by volgariver6** [comment]
fixed

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/12483364431/job/34840545182?pr=20906

```
2024/12/24 16:28:28.547805 +0000 INFO tn-service.logtail-server service/session.go:526 send subscription response {"service": "11002-tn", "uuid": "11002-tn", "server-id": "0193f97e-9627-7800-af11-537ec2e971e2", "stream-id": 1, "remote": "127.0.0.1:41050", "table": "db_id:1 tb_id:2 db_name:\"mo_catalog\" tb_name:\"mo_tables\" primary_seqnum:19 ", "To": "PhysicalTime:1735057708547140513 "}
panic: ExpectedEOB

goroutine 6304 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScanDataSource(0xc036c941a0, 0xc03e312960)
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/compile.go:1872 +0x26bb
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).initDataSource(...)
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:131
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InitAllDataSource(0xc03e312960, 0xc036c941a0)
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:220 +0xdc
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).prePipelineInitializer(0xc036c941a0)
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/compile.go:481 +0x165
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc036c941a0, 0x8722b68?)
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/compile2.go:238 +0xe45
github.com/matrixorigin/matrixone/pkg/sql/compile.(*txnExecutor).Exec(0xc03ea192c0, {0xc052b49500, 0x26}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0})
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/sql_executor.go:378 +0x1bd8
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).watch.func1.1({0x87273f8, 0xc03ea192c0})
	/home/runner/work/matrixone/matrixone/pkg/txn/trace/service.go:425 +0xe6
github.com/matrixorigin/matrixone/pkg/sql/compile.(*sqlExecutor).ExecTxn(0xc033e59050, {0x8722c10, 0xc051de36c0}, 0xc052234588, {0x0, {0x0, 0x0}, {0x7bbd0fa, 0x8}, 0x0, ...})
	/home/runner/work/matrixone/matrixone/pkg/sql/compile/sql_executor.go:138 +0xcd
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).watch.func1()
	/home/runner/work/matrixone/matrixone/pkg/txn/trace/service.go:421 +0x45c
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).watch(0xc0206a7440, {0x8722b68, 0xc03423f830})
	/home/runner/work/matrixone/matrixone/pkg/txn/trace/service.go:454 +0x208
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/home/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:277 +0xcf
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 4934
	/home/runner/work/matrixone/matrixone/pkg/common/stopper/stopper.go:272 +0x165
steps.ut.conclusion: failure
FAIL_UT_CASES=TestSpeedupAbortAllTxn,
```

**Comment by qingxinhome** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/12491690676/job/34858019573?pr=20905

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/20934

**Comment by sukki37** [comment]
testing

**Comment by sukki37** [comment]
Not repro recently
