### ISSUE TITLE
[Bug]: ut TestSpeedupAbortAllTxn failed

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#20312]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

pr commit

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
+---------------------------------------------------------------------------------------------------------------------+
| Failed UT Packages                                                                                                  |
+----------------------------------------------------+----------------------+----------------------+--------+---------+
| PACKAGE                                            | START_TIME           | END_TIME             | RESULT | ELAPSED |
+----------------------------------------------------+----------------------+----------------------+--------+---------+
| github.com/matrixorigin/matrixone/pkg/tests/issues | 20[24](https://github.com/matrixorigin/matrixone/actions/runs/11971929285/job/33377778817?pr=20308#step:9:25)-11-22T11:59:54Z | 2024-11-22T12:05:12Z | fail   | 318.74  |
+----------------------------------------------------+----------------------+----------------------+--------+---------+
============================================
[TEST]: TestSpeedupAbortAllTxn
[START_AT]: 2024-11-22T12:04:49Z
[END_AT]: 2024-11-22T12:05:12Z
[RESULT]: fail
[ELAPSED]: 22.44
[OUTPUTS]:
=== RUN   TestSpeedupAbortAllTxn
2024/11/22 12:04:49.673882 +0000 INFO malloc/config.go:92 malloc: set default config {"config": {"Allocator":null,"CheckFraction":null,"FullStackFraction":null,"EnableMetrics":null,"HashmapSoftLimit":null,"HashmapHardLimit":null}}
2024/11/22 12:04:49.6760[25](https://github.com/matrixorigin/matrixone/actions/runs/11971929285/job/33377778817?pr=20308#step:9:26) +0000 INFO mergesort/task.go:153 [MERGE-END] {"task": "[MT-28]-272596-t", "to-objs": "a63cd15b80d2(3, 185KiB)Rows(20000),", "to-size": "185KiB", "duration": "435.2049ms"}
2024/11/22 12:04:49.696677 +0000 INFO embed/config.go:372 hakeeper client cfg: { [1[27](https://github.com/matrixorigin/matrixone/actions/runs/11971929285/job/33377778817?pr=20308#step:9:28).0.0.1:11220] 100 false}


2024/11/22 12:05:12.067131 +0000 INFO disttae/logtail_consumer.go:931 [logtail-consumer] unsubscribe process exit.
2024/11/22 12:05:12.067286 +0000 INFO disttae/logtail_consumer.go:672 [logtail-consumer] logtail consumer stopped
2024/11/22 12:05:12.074493 +0000 ERROR disttae/logtail_consumer.go:562 [logtail-consumer] receive an error from log tail client, err: context canceled
2024/11/22 12:05:12.074997 +0000 ERROR disttae/logtail_consumer.go:617 [logtail-consumer] receive one logtail failed, err: context canceled
2024/11/22 12:05:12.080146 +0000 INFO task-runner taskservice/daemon_task.go:304 daemon task poll worker stopped {"service": "0-cn-11002", "runner-id": "0-cn-11002"}
2024/11/22 12:05:12.082149 +0000 ERROR compile/sql_executor.go:140 internal sql executor error: context canceled
panic: context canceled

goroutine 12685 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).connect(0xc03487c340, {0x8644180, 0xc04e286500}, 0xc03487c248)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:877 +0xa25
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*connector).run(0xc0379fa400, {0x8644180, 0xc04e286500})
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:265 +0x99
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).InitLogTailPushModel in goroutine 11299
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:1602 +0x2fa
```

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11971929285/job/33377778817?pr=20308
```

**Comment by reusee** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11978337515/job/33398183189?pr=20244

**Comment by xzxiong** [comment]
repo: https://github.com/matrixorigin/matrixone/actions/runs/11980519977/job/33404932560?pr=20292

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/20328
