### ISSUE TITLE
[Bug]: `ERROR 20101 (HY000): internal error: no available CN server` is reported when connecting to MO

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#20320]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

v2.0.0-7852a2fdb-2024-11-22

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql -h freetier-02.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u 0193516a-52e5-70f9-9c19-a6f40ff84d18:admin:accountadmin  -pxyz
ERROR 20101 (HY000): internal error: no available CN server

mysql> show backend servers;
+--------------------------------------+---------------------+------------+-----------------------------------------------+
| UUID                                 | Address             | Work State | Labels                                        |
+--------------------------------------+---------------------+------------+-----------------------------------------------+
| 63633762-6234-3239-3232-663333343561 | 172.20.120.211:6001 | Working    | account:0193516a-52e5-70f9-9c19-a6f40ff84d18; |

kgp --show-labels | grep 0193516a-52e5-70f9-9c19-a6f40ff84d18
freetier-02-s2-85464754cb-cn-8n7nf           1/1     Running     9 (11h ago)      27h     apps.kruise.io/cloneset-instance-id=8n7nf,controller-revision-hash=freetier-02-s2-85464754cb-cn-5d9bf4b5d,lifecycle.apps.kruise.io/state=Normal,matrixone.cloud/cn-uuid=63633762-6234-3239-3232-663333343561,matrixone.cloud/component=cn,matrixone.cloud/main-cluster=freetier-02,matrixone.cloud/migration-requested=y,matrixone.cloud/organization=019-70211,matrixone.cloud/profile=cn.s2,matrixone.cloud/vertical-scaling=y,matrixorigin.io/claimset=0193516a-52e5-70f9-9c19-a6f40ff84d18-normal,matrixorigin.io/component=CNSet,matrixorigin.io/instance=freetier-02-s2-85464754cb,matrixorigin.io/last-owner=freetier-02-sys,matrixorigin.io/namespace=freetier-02,matrixorigin.io/owner=0193516a-52e5-70f9-9c19-a6f40ff84d18,pod-template-hash=5d9bf4b5d,pod.matrixone.cloud/instance-id=0193516a-52e5-70f9-9c19-a6f40ff84d18,pod.matrixone.cloud/instance-type=serverless,pod.matrixone.cloud/provider=aliyun,pod.matrixone.cloud/region=cn-hangzhou,pool.matrixorigin.io/claimed-by=0193516a-52e5-70f9-9c19-a6f40ff84d18-normal-qcss5,pool.matrixorigin.io/phase=Bound,pool.matrixorigin.io/pool-name=freetier-02-s2
```

### Expected Behavior

Login succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by daviszhen** [comment]
![image](https://github.com/user-attachments/assets/a7c59f71-0b68-429d-888e-2e13aa8de32f)

https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22eUY%22:%7B%22datasource%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60found%20leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221732482000000%22,%22to%22:%221732483859000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aylei** [comment]
```
goroutine 209604 [select, 312 minutes]:
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).wait(0xc00ff70a80, {0x57ffe70, 0xc0698b9a90}, 0xc007ad7ae0)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter.go:220 +0x145
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock(0xc0470b8300, 0xc076612008, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:145 +0xf6
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock(0xc0470b8300, {0x57ffe70, 0xc0698b9a90}, 0xc03d5ab110, {0xc06d32d6b0, 0x2, 0x2}, {{0x1, 0x0, 0x0, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:93 +0x245
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(_, {_, _}, _, {_, _, _}, {0xc05bbc88c0, 0x10, 0x10}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:185 +0x7b1
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockWithMayUpgrade({_, _}, {_, _}, _, {_, _, _}, {0xc05bbc88c0, 0x10, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:651 +0x138
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.lockWithRetry({_, _}, {_, _}, _, {_, _, _}, {0xc05bbc88c0, 0x10, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:624 +0x193
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock({0x57ffe70, 0xc0698b9a90}, {0x58a49e0, 0xc02dd77220}, {0x58ae280, 0xc0318c3e00}, {0x0, 0x0}, 0x2a88eb, 0xc044f96680, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:469 +0x9f0
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockTable({0x58a49e0, 0xc02dd77220}, 0xc044f96680, 0x2a88eb, {0x3d, 0x0, 0x0, 0x0, 0x18, 0x24, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:282 +0x36f
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.lockTalbeIfLockCountIsZero(0xc044f96680, 0xc036bb31e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:1042 +0x338
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking(0xc044f96680, 0xc036bb31e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:130 +0x285
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*LockOp).Call(0xc036bb31e0, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:113 +0x108
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x585e870, 0xc036bb31e0}, 0xc044f96680, {0x58ae280, 0xc0318c34f0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call(0xc08d5f1900, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:68 +0xef
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x585f0f8, 0xc08d5f1900}, 0xc044f96680, {0x58ae280, 0xc0318c3540})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/order.(*Order).Call(0xc0697c7b00, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:188 +0x388
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x585efc0, 0xc0697c7b00}, 0xc044f96680, {0x58ae280, 0xc0318c3590})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeorder.(*MergeOrder).Call(0xc0697c7c00, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeorder/order.go:222 +0x15a
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x585f570, 0xc0697c7c00}, 0xc044f96680, {0x58ae280, 0xc0318c35e0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call(0xc01c2c4780, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:68 +0xef
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x585f0f8, 0xc01c2c4780}, 0xc044f96680, {0x58ae280, 0xc0318c3ae0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call(0xc08c26dc20, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:68 +0xef
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x585f0f8, 0xc08c26dc20}, 0xc044f96680, {0x58ae280, 0xc0318c3b30})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.(*Output).Call(0xc0584e79a0, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/output/output.go:89 +0x56a
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc05f264f20, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71 +0xfe
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunWithReader(0xc05f264f20, {0x5813280, 0xc04f3d22c0}, 0x0, 0xc044f96680)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:59 +0xd1
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc064002e10, 0xc066088a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:197 +0x3fe
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc064002e10, 0xc066088a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:484 +0x129
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc064002e10, 0xc066088a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:275 +0x785
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc064002e10, 0xc066088a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:393 +0x525
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc066088a80, 0xc064002e10)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:358 +0x8b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc066088a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:487 +0x56
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc066088a80, 0x10?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile2.go:251 +0x959
github.com/matrixorigin/matrixone/pkg/frontend.executeResultRowStmt(0xc07c515208, 0xc05eb81040)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/result_row_stmt.go:64 +0x4ef
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt(0xc07c515208, 0xc05eb81040)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2794 +0x118d
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x58f43a8, 0xc07c515208}, 0x0, 0xc05eb81040)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2647 +0x2ef
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x58f43a8, 0xc07c515208}, 0x0, 0xc05eb81040, {0x58ccab0, 0xc084cc6a08})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2616 +0x35c
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x58f43a8, 0xc07c515208}, 0x0, 0xc05eb81040)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2560 +0x567
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x58f43a8, 0xc07c515208}, 0x0, 0xc05eb81040)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2451 +0x118
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc07c515208, 0xc05eb81040)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2414 +0x3d5
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc07c515208, 0xc05eb81040, 0xc06abd28c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3048 +0x1d74
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest(0xc07c515208, 0xc05eb81040, 0xc05f267b88)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3184 +0x1118
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc07d981080, 0xc05f267b88)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:298 +0x61d
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc033e26a00, 0xc07d9bafc0, {0xc0077fdf80, 0x5b, 0x5b})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385 +0x327
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest(0xc033e47400, 0xc07d9bafc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:516 +0x1eb
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc033e47400, {0x57ffe70, 0xc033e24f50}, 0xc07d9bafc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:484 +0x94
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0xc033e47400?, {0x57ffe70?, 0xc033e24f50?}, 0xc002aa05d0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:212 +0x2f
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc033e47400, {0x57ffe70, 0xc033e24f50}, {0x5846498?, 0xc07d4baf10?})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:208 +0x4a6
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 742
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:177 +0x165
```

goroutines that wait for locks occupy max-active queue.

source: [gorutines.txt.zip](https://github.com/user-attachments/files/17896611/gorutines.txt.zip)

**Comment by daviszhen** [comment]
这是新问题。

看链接 connectionId 38119472 行为。

![image](https://github.com/user-attachments/assets/bde53044-de58-4e53-ad33-ecab194a0dc3)

![image](https://github.com/user-attachments/assets/904c0360-5f88-417a-93c4-b5967424eb6f)


https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22eUY%22:%7B%22datasource%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%6038119472%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221732404600000%22,%22to%22:%221732406400000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
正在分析日志

**Comment by zhangxu19830126** [comment]
正在fix验证

**Comment by zhangxu19830126** [comment]
fixed
