### ISSUE TITLE
[Bug]: panic occurred during  TestRegisterCdcExecutor

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#20390]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/12028594691/job/33532086164?pr=20380

[job-logs (1).txt.zip](https://github.com/user-attachments/files/17919646/job-logs.1.txt.zip)

```

2024-11-26T10:32:15.2377950Z 2024/11/26 10:30:28.764671 +0000 INFO frontend/cdc.go:1051 cdc task task1 start on cn 
2024-11-26T10:32:15.2378281Z panic: runtime error: invalid memory address or nil pointer dereference
2024-11-26T10:32:15.2378630Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x404883a]
2024-11-26T10:32:15.2378638Z 
2024-11-26T10:32:15.2378794Z goroutine 614 [running]:
2024-11-26T10:32:15.2379192Z github.com/matrixorigin/matrixone/pkg/frontend.NewRoutineManager.func1()
2024-11-26T10:32:15.2379718Z 	/home/runner/_work/matrixone/matrixone/matrixone/pkg/frontend/routine_manager.go:523 +0x5a
2024-11-26T10:32:15.2380271Z created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutineManager in goroutine 611
2024-11-26T10:32:15.2380793Z 	/home/runner/_work/matrixone/matrixone/matrixone/pkg/frontend/routine_manager.go:515 +0x218
2024-11-26T10:32:15.2381075Z FAIL	github.com/matrixorigin/matrixone/pkg/frontend	0.470s
```

### Steps to Reproduce

```Markdown
run ut
```

**Comment by daviszhen** [comment]
fixed
