### ISSUE TITLE
[Bug]:  UT TestWWConflict failed

### ISSUE THREAD

**Issue by ck89119** [matrixorigin/matrixone#20479]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

ck89119:quit_cdc_task_when_pause

### Commit ID

2dbbd42ecb178e5c1de43e704c805c8ecaafc644

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
```
[TEST]: TestWWConflict
[START_AT]: 2024-12-02T03:10:29Z
[END_AT]: 2024-12-02T03:10:29Z
[RESULT]: fail
[ELAPSED]: 0.03
[OUTPUTS]:
=== RUN   TestWWConflict
2024/12/02 03:10:29.602487 +0000 INFO malloc/config.go:92 malloc: set default config {"config": {"Allocator":null,"CheckFraction":null,"FullStackFraction":null,"EnableMetrics":null,"HashmapSoftLimit":null,"HashmapHardLimit":null}}
2024/12/02 03:10:29.604837 +0000 INFO embed/config.go:372 hakeeper client cfg: { [127.0.0.1:11020] 100 false}
2024/12/02 03:10:29.605163 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:2251 go version: go1.23.0, linux/amd64
2024/12/02 03:10:29.605194 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:2253 dragonboat version: 4.0.0 (Dev)
2024/12/02 03:10:29.605207 +0000 WARN config config/config.go:537 mutual TLS disabled, communication is insecure
2024/12/02 03:10:29.605249 +0000 INFO config config/config.go:659 using default EngineConfig
2024/12/02 03:10:29.605287 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:349 DeploymentID set to 1
2024/12/02 03:10:29.619281 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:1789 logdb memory limit: 48 MBytes
2024/12/02 03:10:29.623[43](https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764323778?pr=20385#step:12:44)1 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:358 NodeHost ID: 14fd947e-27c8-48c3-b74f-c6dd46f366b1
2024/12/02 03:10:29.623[45](https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764323778?pr=20385#step:12:46)6 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:1836 AddressByNodeHostID: true, use gossip based node registry
2024/12/02 03:10:29.623505 +0000 INFO registry registry/gossip.go:297 gossip probe interval set to 5s
2024/12/02 03:10:29.623520 +0000 INFO registry registry/gossip.go:307 gossip bind address 0.0.0.0 port 11060
2024/12/02 03:10:29.623527 +0000 INFO registry registry/gossip.go:315 gossip advertise address 0.0.0.0 port 11060
2024/12/02 03:10:29.623648 +0000 ERROR registry registry/gossip.go:331 failed to create memberlist, Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 11060: listen tcp 0.0.0.0:11060: bind: address already in use
2024/12/02 03:10:29.623687 +0000 ERROR log-service logservice/service.go:131 failed to create log store {"service": "14fd947e-27c8-48c3-b74f-c6dd[46](https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764323778?pr=20385#step:12:47)f366b1", "uuid": "14fd9[47](https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764323778?pr=20385#step:12:48)e-27c8-48c3-b74f-c6dd46f366b1", "error": "Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 11060: listen tcp 0.0.0.0:11060: bind: address already in use"}
--- FAIL: TestWWConflict (0.03s)
panic: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 11060: listen tcp 0.0.0.0:11060: bind: address already in use [recovered]
	panic: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 11060: listen tcp 0.0.0.0:11060: bind: address already in use

goroutine 40 [running]:
testing.tRunner.func1.2({0x4ffae00, 0xc002af4700})
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1635 +0x35e
panic({0x4ffae00?, 0xc002af4700?})
	/home/runner/_work/_tool/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/embed.(*cluster).doStartLocked(0xc000119540, 0x0)
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/cluster.go:119 +0x22b
github.com/matrixorigin/matrixone/pkg/embed.(*cluster).Start(0xc000119540)
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/cluster.go:107 +0xdf
github.com/matrixorigin/matrixone/pkg/embed.RunBaseClusterTests.func1()
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/testing.go:66 +0x17d
sync.(*Once).doSlow(0x8ff9520?, 0xc000f975a0?)
	/home/runner/_work/_tool/go/1.23.0/x64/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/home/runner/_work/_tool/go/1.23.0/x64/src/sync/once.go:67
github.com/matrixorigin/matrixone/pkg/embed.RunBaseClusterTests(0xc002abbf[50](https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764323778?pr=20385#step:12:51))
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/testing.go:47 +0xf5
github.com/matrixorigin/matrixone/pkg/tests/issues.TestWWConflict(0xc000fbd1e0?)
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/tests/issues/issue_test.go:50 +0x29
testing.tRunner(0xc000fbd1e0, 0x5ae1ed0)
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1743 +0x390
steps.ut.conclusion: 
FAIL_UT_CASES=TestWWConflict,
```

### Steps to Reproduce

```Markdown
run ut
```

### Additional information
https://github.com/matrixorigin/matrixone/actions/runs/12111836718/job/33764323778?pr=20385

_No response_

**Comment by ck89119** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/12135725421/job/33835365091?pr=20515

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/12159282984/job/33909100669?pr=20553

**Comment by volgariver6** [comment]
需要加上重试逻辑

**Comment by volgariver6** [comment]
in process

**Comment by volgariver6** [comment]
in process

**Comment by volgariver6** [comment]
不知道原因，还需要再看一下

**Comment by volgariver6** [comment]
暂无进展

**Comment by volgariver6** [comment]
暂无进展

**Comment by volgariver6** [comment]
端口冲突的问题，没有找到原因，先降为s1

**Comment by fengttt** [comment]
Please check if this is still relevant.   Close if not actionable/repro.

**Comment by volgariver6** [comment]
没有复现的ut，先关闭吧
