### ISSUE TITLE
[Bug]: dn can not restarted successfully by replay failed after restarted for several times

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20575]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ef38060

### Other Environment Information

```Markdown
- Hardware parameters:64C 256G
- OS type:
- Others:
```

### Actual Behavior

During chaos testing, DN can not restarted after restarted for several times, the panic info is:

{"level":"INFO","time":"2024/12/04 09:01:14.785835 +0000","caller":"logservicedriver/truncate.go:156","msg":"TRACE-WAL-TRUNCATE-Get Truncate 6860885"}
{"level":"INFO","time":"2024/12/04 09:01:14.785881 +0000","caller":"logservicedriver/replay.go:63","msg":"truncated 6860885"}
gc 7 @1.935s 1%: 0.19+26+0.041 ms clock, 1.3+0.13/51/99+0.28 ms cpu, 297->317->291 MB, 347 MB goal, 3 MB stacks, 0 MB globals, 7 P
gc 8 @2.075s 1%: 0.18+37+0.044 ms clock, 1.2+0.20/60/104+0.30 ms cpu, 528->528->413 MB, 587 MB goal, 3 MB stacks, 0 MB globals, 7 P
panic: ExpectedEOB

goroutine 3110 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).replayAppend(0xc0165fd8b0, 0xc006f7c180, {0x785e5e0, 0xc0123afe80})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:195 +0x2f8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).replayDataCmds(0xc0165fd8b0, 0xc006f7c180, {0x785e5e0, 0xc0123afe80})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:180 +0x57
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).prepareCmd(0xc0165fd8b0, {0x78eb900, 0xc006f7c180})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:117 +0x3a5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).prepareCommit(0xc0165fd8b0, {0x794a430, 0xc000f02000})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:82 +0x12d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PrepareCommit(0xc000f02000)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:326 +0x106
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreparCommit(0xc002ec4a90, {0x794a430, 0xc000f02000})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:301 +0x2b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare(0xc002ec4a90, 0xc0165fee70, {0x0, 0x0, 0x0, 0x0, 0x48, 0x3f, 0xac, 0x21, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:355 +0x46
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare1PC(0xc002ec4a90, 0xc0165fee70, {0x0, 0x0, 0x0, 0x0, 0x48, 0x3f, 0xac, 0x21, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:380 +0x65
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).dequeuePreparing(0xc002ec4a90, {0xc010d70008, 0x1, 0x3e8})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:474 +0x270
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x423
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 1043
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0x145

log link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22ijK%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-ef38060-202412032207%5C%22,%20matrixorigin_io_component%3D%5C%22DNSet%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733282083083%22,%22to%22:%221733308270694%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
NA
```

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
出现率较低，DELAY到后续版本，持续跟踪

**Comment by aressu1985** [comment]
update on 01.03
mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22jqJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-bad5761-202501022113%5C%22,%20matrixorigin_io_component%3D%5C%22DNSet%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221735868485236%22,%22to%22:%221735872046332%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aressu1985** [comment]
fixed
