### ISSUE TITLE
[Bug]: DN PANIC worker exits from panic: 01938fc8-294b-7938-bcd3-8c38d8b5645e_0-19 find no transfer mapping for row 948, mapping range (0, 8191)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20576]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ef38060

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*PROXY: 3C 7G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

During chaos testing, DN report error " worker exits from panic: 01938fc8-294b-7938-bcd3-8c38d8b5645e_0-19 find no transfer mapping for row 948, mapping range (0, 8191)" after restarted several times

024-12-04 12:38:21.1912024/12/04 04:38:21.191780 [ants]: worker exits from panic: 01938fc8-294b-7938-bcd3-8c38d8b5645e_0-19 find no transfer mapping for row 948, mapping range (0, 8191)Fieldsappmo-chaos-regression-dis-dncontainermaincontroller_revision_hashmo-chaos-regression-dis-dn-587c5f97b9filename/var/log/pods/mo-chaos-ef38060-202412032207_mo-chaos-regression-dis-dn-0_274a67f1-5966-4eb6-8f0c-9d203ee74537/main/3.logjobmo-chaos-ef38060-202412032207/mo-chaos-regression-dis-dnlifecycle_apps_kruise_io_stateNormalmatrixorigin_io_clustermo-chaos-regression-dismatrixorigin_io_componentDNSetmatrixorigin_io_instancemo-chaos-regression-dismatrixorigin_io_namespacemo-chaos-ef38060-202412032207namespacemo-chaos-ef38060-202412032207node_namehost-10-222-1-135podmo-chaos-regression-dis-dn-0statefulset_kubernetes_io_pod_namemo-chaos-regression-dis-dn-0streamstderr | 024-12-04 12:38:21.191 | 2024/12/04 04:38:21.191780 [ants]: worker exits from panic: 01938fc8-294b-7938-bcd3-8c38d8b5645e_0-19 find no transfer mapping for row 948, mapping range (0, 8191) |   |   | Fieldsappmo-chaos-regression-dis-dncontainermaincontroller_revision_hashmo-chaos-regression-dis-dn-587c5f97b9filename/var/log/pods/mo-chaos-ef38060-202412032207_mo-chaos-regression-dis-dn-0_274a67f1-5966-4eb6-8f0c-9d203ee74537/main/3.logjobmo-chaos-ef38060-202412032207/mo-chaos-regression-dis-dnlifecycle_apps_kruise_io_stateNormalmatrixorigin_io_clustermo-chaos-regression-dismatrixorigin_io_componentDNSetmatrixorigin_io_instancemo-chaos-regression-dismatrixorigin_io_namespacemo-chaos-ef38060-202412032207namespacemo-chaos-ef38060-202412032207node_namehost-10-222-1-135podmo-chaos-regression-dis-dn-0statefulset_kubernetes_io_pod_namemo-chaos-regression-dis-dn-0streamstderr | Fields |   | app | mo-chaos-regression-dis-dn |   | container | main |   | controller_revision_hash | mo-chaos-regression-dis-dn-587c5f97b9 |   | filename | /var/log/pods/mo-chaos-ef38060-202412032207_mo-chaos-regression-dis-dn-0_274a67f1-5966-4eb6-8f0c-9d203ee74537/main/3.log |   | job | mo-chaos-ef38060-202412032207/mo-chaos-regression-dis-dn |   | lifecycle_apps_kruise_io_state | Normal |   | matrixorigin_io_cluster | mo-chaos-regression-dis |   | matrixorigin_io_component | DNSet |   | matrixorigin_io_instance | mo-chaos-regression-dis |   | matrixorigin_io_namespace | mo-chaos-ef38060-202412032207 |   | namespace | mo-chaos-ef38060-202412032207 |   | node_name | host-10-222-1-135 |   | pod | mo-chaos-regression-dis-dn-0 |   | statefulset_kubernetes_io_pod_name | mo-chaos-regression-dis-dn-0 |   | stream | stderr
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
024-12-04 12:38:21.191 | 2024/12/04 04:38:21.191780 [ants]: worker exits from panic: 01938fc8-294b-7938-bcd3-8c38d8b5645e_0-19 find no transfer mapping for row 948, mapping range (0, 8191) |  
  | Fieldsappmo-chaos-regression-dis-dncontainermaincontroller_revision_hashmo-chaos-regression-dis-dn-587c5f97b9filename/var/log/pods/mo-chaos-ef38060-202412032207_mo-chaos-regression-dis-dn-0_274a67f1-5966-4eb6-8f0c-9d203ee74537/main/3.logjobmo-chaos-ef38060-202412032207/mo-chaos-regression-dis-dnlifecycle_apps_kruise_io_stateNormalmatrixorigin_io_clustermo-chaos-regression-dismatrixorigin_io_componentDNSetmatrixorigin_io_instancemo-chaos-regression-dismatrixorigin_io_namespacemo-chaos-ef38060-202412032207namespacemo-chaos-ef38060-202412032207node_namehost-10-222-1-135podmo-chaos-regression-dis-dn-0statefulset_kubernetes_io_pod_namemo-chaos-regression-dis-dn-0streamstderr | Fields |   | app | mo-chaos-regression-dis-dn |   | container | main |   | controller_revision_hash | mo-chaos-regression-dis-dn-587c5f97b9 |   | filename | /var/log/pods/mo-chaos-ef38060-202412032207_mo-chaos-regression-dis-dn-0_274a67f1-5966-4eb6-8f0c-9d203ee74537/main/3.log |   | job | mo-chaos-ef38060-202412032207/mo-chaos-regression-dis-dn |   | lifecycle_apps_kruise_io_state | Normal |   | matrixorigin_io_cluster | mo-chaos-regression-dis |   | matrixorigin_io_component | DNSet |   | matrixorigin_io_instance | mo-chaos-regression-dis |   | matrixorigin_io_namespace | mo-chaos-ef38060-202412032207 |   | namespace | mo-chaos-ef38060-202412032207 |   | node_name | host-10-222-1-135 |   | pod | mo-chaos-regression-dis-dn-0 |   | statefulset_kubernetes_io_pod_name | mo-chaos-regression-dis-dn-0 |   | stream | stderr
Fields
  | app | mo-chaos-regression-dis-dn
  | container | main
  | controller_revision_hash | mo-chaos-regression-dis-dn-587c5f97b9
  | filename | /var/log/pods/mo-chaos-ef38060-202412032207_mo-chaos-regression-dis-dn-0_274a67f1-5966-4eb6-8f0c-9d203ee74537/main/3.log
  | job | mo-chaos-ef38060-202412032207/mo-chaos-regression-dis-dn
  | lifecycle_apps_kruise_io_state | Normal
  | matrixorigin_io_cluster | mo-chaos-regression-dis
  | matrixorigin_io_component | DNSet
  | matrixorigin_io_instance | mo-chaos-regression-dis
  | matrixorigin_io_namespace | mo-chaos-ef38060-202412032207
  | namespace | mo-chaos-ef38060-202412032207
  | node_name | host-10-222-1-135
  | pod | mo-chaos-regression-dis-dn-0
  | statefulset_kubernetes_io_pod_name | mo-chaos-regression-dis-dn-0
  | stream | stderr
2024-12-04 12:38:21.191goroutine 7136 [running]:2024-12-04 12:38:21.191runtime/debug.Stack()2024-12-04 12:38:21.191	/usr/local/go/src/runtime/debug/stack.go:26 +0x6b2024-12-04 12:38:21.191github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()2024-12-04 12:38:21.191	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0xca2024-12-04 12:38:21.191panic({0x6769320?, 0xc03127f770?})2024-12-04 12:38:21.191	/usr/local/go/src/runtime/panic.go:785 +0x1362024-12-04 12:38:21.191github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*mergeObjectsEntry).transferObjectDeletes(0xc02a309ea0, {0x7896678, 0xc007b36810}, 0xc0124f6300, {0x0, 0x0, 0x0, 0x0, 0x6a, 0xaa, ...}, ...)2024-12-04 12:38:21.191	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:292 +0x143c2024-12-04 12:38:21.191github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*mergeObjectsEntry).collectDelsAndTransfer(0xc02a309ea0, {0x7896678, 0xc007b36810}, {0x0, 0x0, 0x0, 0x0, 0x6a, 0xaa, 0x72, ...}, ...)2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:370 +0x3e52024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.NewMergeObjectsEntry({0x7896678, 0xc007b36810}, {0x794a6c8, 0xc02f750400}, {0xc02a9d0800, 0x1d}, {0x792f240, 0xc03127f690}, {0xc02a3366c0, 0x5, ...}, ...)2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:99 +0x61f2024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.HandleMergeEntryInTxn({0x7896678, 0xc007b36810}, {0x794a6c8, 0xc02f750400}, {0xc02a9d0800, 0x1d}, 0xc025540ea0, {0xc025a86780, 0x2d, 0x2d}, ...)2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:465 +0xf4f2024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*mergeObjectsTask).Execute(0xc0252f91e0, {0x7896678, 0xc007b36810})2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:385 +0x8852024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03d1cfce0, {0x7896678, 0xc007b36810})2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0xc42024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc03431b200, {0x7896678, 0xc007b36810})2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/task.go:64 +0x3de2024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc0326e28c0, {0x7896678, 0xc007b36810})2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0xc42024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc00857ce00, {0x7f0b90f917f0, 0xc03431b200})2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:216 +0x4c2024-12-04 12:38:21.192github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()2024-12-04 12:38:21.192	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:60 +0x4c2024-12-04 12:38:21.192github.com/panjf2000/ants/v2.(*goWorker).run.func1()2024-12-04 12:38:21.192	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf62024-12-04 12:38:21.192created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 30242024-12-04 12:38:21.192	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85 |   |   | 2024-12-04 12:38:21.191 | goroutine 7136 [running]: |   |   |   | 2024-12-04 12:38:21.191 | runtime/debug.Stack() |   |   |   | 2024-12-04 12:38:21.191 | /usr/local/go/src/runtime/debug/stack.go:26 +0x6b |   |   |   | 2024-12-04 12:38:21.191 | github.com/panjf2000/ants/v2.(*goWorker).run.func1.1() |   |   |   | 2024-12-04 12:38:21.191 | /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0xca |   |   |   | 2024-12-04 12:38:21.191 | panic({0x6769320?, 0xc03127f770?}) |   |   |   | 2024-12-04 12:38:21.191 | /usr/local/go/src/runtime/panic.go:785 +0x136 |   |   |   | 2024-12-04 12:38:21.191 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*mergeObjectsEntry).transferObjectDeletes(0xc02a309ea0, {0x7896678, 0xc007b36810}, 0xc0124f6300, {0x0, 0x0, 0x0, 0x0, 0x6a, 0xaa, ...}, ...) |   |   |   | 2024-12-04 12:38:21.191 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:292 +0x143c |   |   |   | 2024-12-04 12:38:21.191 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*mergeObjectsEntry).collectDelsAndTransfer(0xc02a309ea0, {0x7896678, 0xc007b36810}, {0x0, 0x0, 0x0, 0x0, 0x6a, 0xaa, 0x72, ...}, ...) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:370 +0x3e5 |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.NewMergeObjectsEntry({0x7896678, 0xc007b36810}, {0x794a6c8, 0xc02f750400}, {0xc02a9d0800, 0x1d}, {0x792f240, 0xc03127f690}, {0xc02a3366c0, 0x5, ...}, ...) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:99 +0x61f |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.HandleMergeEntryInTxn({0x7896678, 0xc007b36810}, {0x794a6c8, 0xc02f750400}, {0xc02a9d0800, 0x1d}, 0xc025540ea0, {0xc025a86780, 0x2d, 0x2d}, ...) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:465 +0xf4f |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*mergeObjectsTask).Execute(0xc0252f91e0, {0x7896678, 0xc007b36810}) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:385 +0x885 |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03d1cfce0, {0x7896678, 0xc007b36810}) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0xc4 |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc03431b200, {0x7896678, 0xc007b36810}) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/task.go:64 +0x3de |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc0326e28c0, {0x7896678, 0xc007b36810}) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0xc4 |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc00857ce00, {0x7f0b90f917f0, 0xc03431b200}) |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:216 +0x4c |   |   |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1() |   |   |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:60 +0x4c |   |   |   | 2024-12-04 12:38:21.192 | github.com/panjf2000/ants/v2.(*goWorker).run.func1() |   |   |   | 2024-12-04 12:38:21.192 | /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf6 |   |   |   | 2024-12-04 12:38:21.192 | created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 3024 |   |   |   | 2024-12-04 12:38:21.192 | /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85
  |   | 2024-12-04 12:38:21.191 | goroutine 7136 [running]: |  
  |   | 2024-12-04 12:38:21.191 | runtime/debug.Stack() |  
  |   | 2024-12-04 12:38:21.191 | /usr/local/go/src/runtime/debug/stack.go:26 +0x6b |  
  |   | 2024-12-04 12:38:21.191 | github.com/panjf2000/ants/v2.(*goWorker).run.func1.1() |  
  |   | 2024-12-04 12:38:21.191 | /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0xca |  
  |   | 2024-12-04 12:38:21.191 | panic({0x6769320?, 0xc03127f770?}) |  
  |   | 2024-12-04 12:38:21.191 | /usr/local/go/src/runtime/panic.go:785 +0x136 |  
  |   | 2024-12-04 12:38:21.191 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*mergeObjectsEntry).transferObjectDeletes(0xc02a309ea0, {0x7896678, 0xc007b36810}, 0xc0124f6300, {0x0, 0x0, 0x0, 0x0, 0x6a, 0xaa, ...}, ...) |  
  |   | 2024-12-04 12:38:21.191 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:292 +0x143c |  
  |   | 2024-12-04 12:38:21.191 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*mergeObjectsEntry).collectDelsAndTransfer(0xc02a309ea0, {0x7896678, 0xc007b36810}, {0x0, 0x0, 0x0, 0x0, 0x6a, 0xaa, 0x72, ...}, ...) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:370 +0x3e5 |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.NewMergeObjectsEntry({0x7896678, 0xc007b36810}, {0x794a6c8, 0xc02f750400}, {0xc02a9d0800, 0x1d}, {0x792f240, 0xc03127f690}, {0xc02a3366c0, 0x5, ...}, ...) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries/mergeobjects.go:99 +0x61f |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.HandleMergeEntryInTxn({0x7896678, 0xc007b36810}, {0x794a6c8, 0xc02f750400}, {0xc02a9d0800, 0x1d}, 0xc025540ea0, {0xc025a86780, 0x2d, 0x2d}, ...) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:465 +0xf4f |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*mergeObjectsTask).Execute(0xc0252f91e0, {0x7896678, 0xc007b36810}) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/mergeobjects.go:385 +0x885 |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03d1cfce0, {0x7896678, 0xc007b36810}) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0xc4 |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc03431b200, {0x7896678, 0xc007b36810}) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/task.go:64 +0x3de |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc0326e28c0, {0x7896678, 0xc007b36810}) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0xc4 |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc00857ce00, {0x7f0b90f917f0, 0xc03431b200}) |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:216 +0x4c |  
  |   | 2024-12-04 12:38:21.192 | github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1() |  
  |   | 2024-12-04 12:38:21.192 | /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:60 +0x4c |  
  |   | 2024-12-04 12:38:21.192 | github.com/panjf2000/ants/v2.(*goWorker).run.func1() |  
  |   | 2024-12-04 12:38:21.192 | /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf6 |  
  |   | 2024-12-04 12:38:21.192 | created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 3024 |  
  |   | 2024-12-04 12:38:21.192 | /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85

log link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22ijK%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-ef38060-202412032207%5C%22,%20matrixorigin_io_component%3D%5C%22DNSet%5C%22%7D%20%7C%3D%20%60worker%20exits%20from%20panic:%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733286798303%22,%22to%22:%221733287509214%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
NA
```

**Comment by XuPeng-SH** [comment]
@aressu1985, please help to close it. we can create a new issue if it happens later
