### ISSUE TITLE
[Bug]:ut TestBaseClusterCanWorkWithNewCluster failed

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#20604]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

pr commit

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```

+--------------------------------------------------------------------------------------------------------------+
| Failed UT Packages                                                                                           |
+---------------------------------------------+----------------------+----------------------+--------+---------+
| PACKAGE                                     | START_TIME           | END_TIME             | RESULT | ELAPSED |
+---------------------------------------------+----------------------+----------------------+--------+---------+
| github.com/matrixorigin/matrixone/pkg/embed | 2024-12-05T12:51:06Z | 2024-12-05T12:55:25Z | fail   | 258.10  |
+---------------------------------------------+----------------------+----------------------+--------+---------+
============================================
[TEST]: TestBaseClusterCanWorkWithNewCluster
[START_AT]: 2024-12-05T12:55:24Z
[END_AT]: 2024-12-05T12:55:25Z
[RESULT]: fail
[ELAPSED]: 0.02
[OUTPUTS]:
=== RUN   TestBaseClusterCanWorkWithNewCluster
2024/12/05 12:55:24.863631 +0000 INFO malloc/config.go:92 malloc: set default config {"config": {"Allocator":null,"CheckFraction":null,"FullStackFraction":null,"EnableMetrics":null,"HashmapSoftLimit":null,"HashmapHardLimit":null}}
2024/12/05 12:55:24.865420 +0000 INFO embed/config.go:372 hakeeper client cfg: { [127.0.0.1:10980] 100 false}
2024/12/05 12:55:24.865670 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:2251 go version: go1.23.0, linux/amd64
2024/12/05 12:55:24.865694 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:2253 dragonboat version: 4.0.0 (Dev)
2024/12/05 12:55:24.865701 +0000 WARN config config/config.go:537 mutual TLS disabled, communication is insecure
2024/12/05 12:55:24.865722 +0000 INFO config config/config.go:659 using default EngineConfig
2024/12/05 12:55:24.865758 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:[34](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:35)9 DeploymentID set to 1
2024/12/05 12:55:24.873861 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:1789 logdb memory limit: 48 MBytes
2024/12/05 12:55:24.874824 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:[35](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:36)8 NodeHost ID: a160d04e-7d02-4cf5-9866-7f4fdaaa3c58
2024/12/05 12:55:24.874852 +0000 INFO dragonboat v4@v4.0.0-20241019050137-1c6138e9cf8b/nodehost.go:18[36](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:37) AddressByNodeHostID: true, use gossip based node registry
2024/12/05 12:55:24.874875 +0000 INFO registry registry/gossip.go:297 gossip probe interval set to 5s
2024/12/05 12:55:24.874886 +0000 INFO registry registry/gossip.go:307 gossip bind address 0.0.0.0 port 11020
2024/12/05 12:55:24.874893 +0000 INFO registry registry/gossip.go:315 gossip advertise address 0.0.0.0 port 11020
2024/12/05 12:55:24.874962 +0000 ERROR registry registry/gossip.go:331 failed to create memberlist, Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 11020: listen tcp 0.0.0.0:11020: bind: address already in use
2024/12/05 12:55:24.875007 +0000 ERROR log-service logservice/service.go:131 failed to create log store {"service": "a160d04e-7d02-4cf5-9866-7f4fdaaa3c58", "uuid": "a160d04e-7d02-4cf5-9866-7f4fdaaa3c58", "error": "Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 11020: listen tcp 0.0.0.0:11020: bind: address already in use"}
--- FAIL: TestBaseClusterCanWorkWithNewCluster (0.02s)
panic: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 11020: listen tcp 0.0.0.0:11020: bind: address already in use [recovered]
	panic: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on "0.0.0.0" port 11020: listen tcp 0.0.0.0:11020: bind: address already in use

goroutine 18183 [running]:
testing.tRunner.func1.2({0x501f0e0, 0xc003[38](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:39)8880})
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1635 +0x35e
panic({0x501f0e0?, 0xc003388880?})
	/home/runner/_work/_tool/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/embed.(*cluster).doStartLocked(0xc10e2e7680, 0x0)
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/cluster.go:119 +0x22b
github.com/matrixorigin/matrixone/pkg/embed.(*cluster).Start(0xc10e2e7680)
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/cluster.go:107 +0xdf
github.com/matrixorigin/matrixone/pkg/embed.RunBaseClusterTests.func1()
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/testing.go:66 +0x17d
sync.(*Once).doSlow(0xc031c072c0?, 0x5cd80d?)
	/home/runner/_work/_tool/go/1.23.0/x64/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/home/runner/_work/_tool/go/1.23.0/x64/src/sync/once.go:67
github.com/matrixorigin/matrixone/pkg/embed.RunBaseClusterTests(0xc003[39](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:40)1f50)
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/testing.go:47 +0xf5
github.com/matrixorigin/matrixone/pkg/embed.TestBaseClusterCanWorkWithNewCluster(0xc09506b0[40](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:41))
	/home/runner/_work/matrixone/matrixone/matrixone/pkg/embed/cluster_test.go:117 +0x35
testing.tRunner(0xc09506b040, 0x5b08868)
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/home/runner/_work/_tool/go/1.23.0/x64/src/testing/testing.go:17[43](https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599#step:13:44) +0x390
steps.ut.conclusion: 
FAIL_UT_CASES=TestBaseClusterCanWorkWithNewCluster,

```

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/12179976896/job/33973312660?pr=20599
```

**Comment by zhangxu19830126** [comment]
端口被占用了

**Comment by daviszhen** [comment]
只能重跑
