### ISSUE TITLE
[Bug]: `window` fucntion timeout during bvt test on race enabled mo

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#20642]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,2.0-dev

### Commit ID

6c37ff0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/12209792527/job/34065474667
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/e99fdc27-db36-462c-96eb-10fd12f285b4">

```
2024/12/07 06:59:55.316272 +0000 ERROR cn-service found long running txn {"uuid": "", "txn-id": "70f70f4866a9b62a180ecb5ee0407ee0", "create-at": "2024/12/07 06:56:39.202909 +0000", "options": "Features:1 CN:\"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf\" SessionID:\"01939f6c-beb4-7c60-ab72-c5afb77e0296\" ConnectionID:5 UserName:\"dump\" counter:\"commit: enter:0, exit:0 rollback: enter:0, exit:0 runSql: enter:1, exit:0 incrStmt: enter:1, exit:1 rollbackStmt: enter:0, exit:0 txnMeta: 70f70f4866a9b62a180ecb5ee0407ee0/Active/S:1733554599201749584-1 footPrints: [6: enter:1, exit:0] [7: enter:1, exit:0] [8: enter:1, exit:0] [13: enter:1, exit:0] [15: enter:1, exit:0] [16: enter:1, exit:0] [92: enter:4, exit:4] [93: enter:4, exit:4] [95: enter:4, exit:4] [99: enter:1, exit:0] [101: enter:1, exit:0] [102: enter:1, exit:0] [114: enter:1, exit:1] [115: enter:4, exit:4] \" sessionInfo:\"connectionId 5|127.0.0.1:36218|account sys:dump|goRoutineId 2307|migrate-goRoutineId 0|01939f6c-beb4-7c60-ab72-c5afb77e0296\" inRunSql:true autocommit:true ", "profile": "ETL:/profile/CN_dd1dccb4-4d3c-41f8-b482-5251dc7a41bf_leakcheck_routine_01939fea-f333-7c5b-b1cc-6b877645b13e.gz"}

```

```
goroutine 2307 [chan receive, 12 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc147397040)
	/home/runner/_work/matrixone/matrixone/head/pkg/sql/compile/compile.go:534 +0x632
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc147397040, 0x0)
	/home/runner/_work/matrixone/matrixone/head/pkg/sql/compile/compile2.go:245 +0x1670
github.com/matrixorigin/matrixone/pkg/frontend.executeResultRowStmt(0xc02390e008, 0xc054872a00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/result_row_stmt.go:64 +0xba5
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt(0xc02390e008, 0xc054872a00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2889 +0x2e1d
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0xd5be498, 0xc02390e008}, 0x0, 0xc054872a00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2742 +0x6f7
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0xd5be498, 0xc02390e008}, 0x0, 0xc054872a00, {0xd5a47a8, 0xc047ad7508})
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2711 +0x9b6
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0xd5be498, 0xc02390e008}, 0x0, 0xc054872a00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2655 +0x116f
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0xd5be498, 0xc02390e008}, 0x0, 0xc054872a00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2530 +0x385
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc02390e008, 0xc054872a00)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2493 +0xa47
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc02390e008, 0xc054872a00, 0xc03b822ee0)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:3143 +0x4b05
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest(0xc02390e008, 0xc054872a00, 0xc0705a6ae0)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:3223 +0x1365
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc009bca480, 0xc0705a6ae0)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/routine.go:298 +0x10f2
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc005d78580, 0xc025e1a360, {0xc14e5d2660, 0x5d, 0x5d})
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:385 +0x876
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest(0xc024b168c0, 0xc025e1a360)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/server.go:520 +0x485
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc024b168c0, {0xd504070, 0xc02eb60a00}, 0xc025e1a360)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/server.go:488 +0x10b
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0xc024b168c0, {0xd504070, 0xc02eb60a00}, 0xc025e1a360)
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/server.go:212 +0x92
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc024b168c0, {0xd504070, 0xc02eb60a00}, {0xd541278, 0xc006eb6568})
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/server.go:208 +0x8fb
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 2178
	/home/runner/_work/matrixone/matrixone/head/pkg/frontend/server.go:177 +0x60d

```

[dump-stacks.log](https://github.com/user-attachments/files/18048030/dump-stacks.log)

### Steps to Reproduce

```Markdown
run bvt on race enabled mo
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by Ariznawlll** [comment]
观察了ci中的bvt测试没再出现了，close
