### ISSUE TITLE
[Bug]: segmentation violation when executing `select`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2131]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f6dd5ff0bedaf1374df508c0fb23d8ba146930a7
- Hardware parameters:16c64G, amd
- OS type:ubuntu
- Others:
```

### Client Output
```
(2013, 'Lost connection to MySQL server during query')

```

### Server Logs
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f81154]

goroutine 870 [running]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.Call(0xc0030f6ab0, {0x22e9d00, 0xc013e798b0})
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/sql/colexec/projection/projection.go:56 +0x394
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc002f34c00, 0x6, 0x18}, 0x7fea93c6c108)
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/vm/vm.go:48 +0x9c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunMerge(0xc00338b890, 0xc0030f6ab0)
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:114 +0x126
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc00efb7600, {0x2918ea0, 0xc003b5ccb0})
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/sql/compile/scope.go:501 +0x4aa
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0xc012ae5d80, 0xd79397)
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/sql/compile/exec.go:84 +0x91
github.com/matrixorigin/matrixone/pkg/frontend.(*ComputationWrapperImpl).Run(0xc009154120, 0x292c428)
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:901 +0x1c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc009175f40, {0xc01c9a0f00, 0xfd})
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:1152 +0x282e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc009175f40, 0xc0004fcb00)
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:1281 +0x5b3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc00959a1e0)
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/frontend/routine.go:100 +0x39c
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
        /mnt/datadisk0/service/actions-runner/_work/matrixone/matrixone/pkg/frontend/routine.go:152 +0x1e7
```

### Steps to Reproduce

```markdown
1. start mo
2. create tables in ssb and load data(row size of lineorder is 600,000,000) into tables
3. execute `select sum(lo_revenue) as lo_revenue, year(d_datekey) as d_year, p_brand from lineorder join dates on lo_orderdate = d_datekey join part on lo_partkey = p_partkey join supplier on lo_suppkey = s_suppkey group by d_year, p_brand order by d_year, p_brand;`
```

**Comment by nnsgmsone** [comment]
fixed by #2180
