### ISSUE TITLE
[Bug]: moerr panic stack

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#2271]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

If our code panic, moerr will catch it and convert it to an moerr.   We try to include a stack.   For example, #2270.
This is good, how ever, the printed out stack is when the panic get recovered.   We want the stack when the panic happens.

`ERROR 1105 (HY000): unknown error:Internal error: panic interface conversion: interface {} is float32, not float64: goroutine 954 [running]:
runtime/debug.Stack()
/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
[github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2589460](http://github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError(%7B0x2589460)?, 0xc00084b5c0})
/data/zhangxiao/matrixone/pkg/common/moerr/error.go:77 +0x53
[github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Compile.func1()](http://github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Compile.func1())
/data/zhangxiao/matrixone/pkg/sql/compile/exec.go:46 +0x31`

### Expected Behavior

Better stack printout.

**Comment by fengttt** [comment]
Done, by xzx.
