### ISSUE TITLE
[Bug]: Instance crashed during load data

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2308]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ab3a78f31bcaa342a523095959477702dd876a1a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> load data infile '/data/zhangxiao/ssb-dbgen/lineorder_flat.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)

**Comment by domingozhang** [comment]
goroutine 26843 [runnable]:
strings.TrimSpace({0xc0391f736d?, 0x6?})
	/usr/lib/golang/src/strings/strings.go:940 +0x14b fp=0xc04d15f290 sp=0xc04d15f288 pc=0xe817eb
github.com/matrixorigin/matrixone/pkg/frontend.rowToColumnAndSaveToStorage(0xc003414d00, 0x0?, 0x1)
	/data/zhangxiao/matrixone/pkg/frontend/load.go:666 +0x2ee5 fp=0xc04d15ff38 sp=0xc04d15f290 pc=0x229cec5
github.com/matrixorigin/matrixone/pkg/frontend.glob..func10.1()
	/data/zhangxiao/matrixone/pkg/frontend/load.go:1474 +0xa5 fp=0xc04d15ffe0 sp=0xc04d15ff38 pc=0x22a2c05
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc04d15ffe8 sp=0xc04d15ffe0 pc=0xde3601
created by github.com/matrixorigin/matrixone/pkg/frontend.glob..func10
	/data/zhangxiao/matrixone/pkg/frontend/load.go:1470 +0x165

goroutine 24081 [chan receive]:
runtime.gopark(0xc092ac16b012c5ea?, 0xdea953f334?, 0x0?, 0xe6?, 0xc092ac16b012be4c?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc005e8ced0 sp=0xc005e8ceb0 pc=0xdb18f6
runtime.chanrecv(0xc00e7ff080, 0xc005e8cfa8, 0x1)
	/usr/lib/golang/src/runtime/chan.go:577 +0x56c fp=0xc005e8cf60 sp=0xc005e8ced0 pc=0xd7b54c
runtime.chanrecv2(0xc00012f810?, 0xc00b4f4b10?)
	/usr/lib/golang/src/runtime/chan.go:445 +0x18 fp=0xc005e8cf88 sp=0xc005e8cf60 pc=0xd7afb8
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:66 +0x7b fp=0xc005e8cfe0 sp=0xc005e8cf88 pc=0x1f0c9bb
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc005e8cfe8 sp=0xc005e8cfe0 pc=0xde3601
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

goroutine 26190 [chan receive]:
runtime.gopark(0xc092ac16e61182b4?, 0xdedaed79fd?, 0x0?, 0xe6?, 0xc092ac16e6117a16?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc00d51aed0 sp=0xc00d51aeb0 pc=0xdb18f6
runtime.chanrecv(0xc0089f7920, 0xc00d51afa8, 0x1)
	/usr/lib/golang/src/runtime/chan.go:577 +0x56c fp=0xc00d51af60 sp=0xc00d51aed0 pc=0xd7b54c
runtime.chanrecv2(0xc00012f810?, 0xc00f54ad50?)
	/usr/lib/golang/src/runtime/chan.go:445 +0x18 fp=0xc00d51af88 sp=0xc00d51af60 pc=0xd7afb8
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:66 +0x7b fp=0xc00d51afe0 sp=0xc00d51af88 pc=0x1f0c9bb
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00d51afe8 sp=0xc00d51afe0 pc=0xde3601
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65
