### ISSUE TITLE
[Bug]: TestComparisonOperator Failed under different environment 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2453]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):680f9b1073467d44e491a39fadbe3fb0ab26aa99
- Hardware parameters: arm64,amd64
- OS type: Ubuntu, MacOS
- Others:
```

### Actual Behavior

Occasionally reproduced: 
```
2022-05-10T07:11:26.4677318Z --- FAIL: TestComparisonOperator (0.05s)
2022-05-10T07:11:26.4709274Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-05-10T07:11:26.4709745Z 	panic: runtime error: invalid memory address or nil pointer dereference
2022-05-10T07:11:26.4710139Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x162d33e]
2022-05-10T07:11:26.4710349Z 
2022-05-10T07:11:26.4710458Z goroutine 1329 [running]:
2022-05-10T07:11:26.4710736Z testing.tRunner.func1.2({0x20359c0, 0x2f749f0})
2022-05-10T07:11:26.4711139Z 	/opt/hostedtoolcache/go/1.18.1/x64/src/testing/testing.go:1389 +0x24e
2022-05-10T07:11:26.4711448Z testing.tRunner.func1()
2022-05-10T07:11:26.4711803Z 	/opt/hostedtoolcache/go/1.18.1/x64/src/testing/testing.go:1392 +0x39f
2022-05-10T07:11:26.4712102Z panic({0x20359c0, 0x2f749f0})
2022-05-10T07:11:26.4712444Z 	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/panic.go:838 +0x207
2022-05-10T07:11:26.4712973Z github.com/matrixorigin/matrixone/pkg/sql/unittest.test(0x0?, {0xc000af7ab8, 0xa9, 0x0?})
2022-05-10T07:11:26.4713718Z 	/home/runner/work/matrixone/matrixone/pkg/sql/unittest/types.go:128 +0x6de
2022-05-10T07:11:26.4714249Z github.com/matrixorigin/matrixone/pkg/sql/unittest.TestComparisonOperator(0xc0006d9860?)
2022-05-10T07:11:26.4718859Z 	/home/runner/work/matrixone/matrixone/pkg/sql/unittest/operator_test.go:1663 +0x3c5a
2022-05-10T07:11:26.4721679Z testing.tRunner(0xc0006d9860, 0x22c2d50)
2022-05-10T07:11:26.4724891Z 	/opt/hostedtoolcache/go/1.18.1/x64/src/testing/testing.go:1439 +0x102
2022-05-10T07:11:26.4727583Z created by testing.(*T).Run
2022-05-10T07:11:26.4731614Z 	/opt/hostedtoolcache/go/1.18.1/x64/src/testing/testing.go:1486 +0x35f
2022-05-10T07:11:26.4822727Z FAIL	github.com/matrixorigin/matrixone/pkg/sql/unittest	0.281s
```
-------
Can be reproduced: When server  time is not UTC time:
```
--- FAIL: TestComparisonOperator (0.05s)
    types.go:143: 
                Error Trace:    types.go:143
                                                        operator_test.go:1695
                Error:          Not equal: 
                                expected: [][]string{[]string{"2020-01-01 11:12:13.000000"}, []string{"2021-01-01 11:12:13.000000"}, []string{"2022-01-01 11:12:13.000000"}}
                                actual  : [][]string{[]string{"2020-01-01 03:12:13.000000"}, []string{"2021-01-01 03:12:13.000000"}, []string{"2022-01-01 03:12:13.000000"}}
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,9 +2,9 @@
                                  ([]string) (len=1) {
                                -  (string) (len=26) "2020-01-01 11:12:13.000000"
                                +  (string) (len=26) "2020-01-01 03:12:13.000000"
                                  },
                                  ([]string) (len=1) {
                                -  (string) (len=26) "2021-01-01 11:12:13.000000"
                                +  (string) (len=26) "2021-01-01 03:12:13.000000"
                                  },
                                  ([]string) (len=1) {
                                -  (string) (len=26) "2022-01-01 11:12:13.000000"
                                +  (string) (len=26) "2022-01-01 03:12:13.000000"
                                  }
                Test:           TestComparisonOperator
                Messages:       select * from ts_table where ts1 <= '2022-01-02 11:12:13';
FAIL
exit status 1
FAIL    github.com/matrixorigin/matrixone/pkg/sql/unittest      0.588s
```

**Comment by nnsgmsone** [comment]
There are some problems with the logic of the judgement. Because of the possibility of err being nil, this can lead to panic.
```
require.Equal(t, tc.err, err.Error(), tc.sql)

**Comment by broccoliSpicy** [comment]
failure on server when time is not utc should be fixed by pr#2452

**Comment by m-schen** [comment]
I fix the test-tool function bug.

**Comment by cnutshell** [comment]
Related with issue #2134

**Comment by cnutshell** [comment]
`TestComparisonOperator` passed.
```bash
go test -race -run=TestComparisonOperator github.com/matrixorigin/matrixone/pkg/sql/unittest
ok  	github.com/matrixorigin/matrixone/pkg/sql/unittest	2.627s
```
