### ISSUE TITLE
[Bug]: unittest panic TestAppend2

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2467]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/matrixorigin/matrixone/actions/runs/2304649153
- Hardware parameters: 
- OS type:
- Others:
```

### Actual Behavior

unittest panic
```
2022-05-11T03:57:04.7845820Z 2022/05/11 03:57:04 worker exits from a panic: tae sched: cannot schedule
2022-05-11T03:57:04.7846236Z 2022/05/11 03:57:04 worker exits from panic: goroutine 616 [running]:
2022-05-11T03:57:04.7846638Z github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
2022-05-11T03:57:04.7847364Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
2022-05-11T03:57:04.7847751Z panic({0x1e6f2c0, 0xc000054110})
2022-05-11T03:57:04.7848559Z 	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/panic.go:838 +0x207
2022-05-11T03:57:04.7849240Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).OnUnload(0xc027b25980)
2022-05-11T03:57:04.7849746Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tables/node.go:183 +0x165
2022-05-11T03:57:04.7850408Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*Node).Unload(0xc027757600)
2022-05-11T03:57:04.7851035Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/buffer/node.go:135 +0x65
2022-05-11T03:57:04.7851417Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*Node).Close(0xc027757600)
2022-05-11T03:57:04.7851996Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/buffer/node.go:98 +0x5d
2022-05-11T03:57:04.7852447Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).Close(0xc027b25980)
2022-05-11T03:57:04.7852991Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tables/node.go:194 +0x2e
2022-05-11T03:57:04.7853379Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).Destroy(0x1?)
2022-05-11T03:57:04.7853839Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tables/block.go:132 +0x71
2022-05-11T03:57:04.7854217Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*BlockEntry).DestroyData(...)
2022-05-11T03:57:04.7854683Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/catalog/block.go:170
2022-05-11T03:57:04.7855284Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcBlockClosure.func1()
2022-05-11T03:57:04.7856702Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/gcop.go:33 +0xc4
2022-05-11T03:57:04.7857676Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*FnTask).Execute(0x100000002fc2a80?)
2022-05-11T03:57:04.7858207Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tasks/types.go:99 +0x22
2022-05-11T03:57:04.7858689Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc028469d40)
2022-05-11T03:57:04.7859340Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x77
2022-05-11T03:57:04.7860034Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0009c7500, {0x7f88900426d8, 0xc028446720})
2022-05-11T03:57:04.7861367Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:198 +0x36
2022-05-11T03:57:04.7862130Z github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
2022-05-11T03:57:04.7862817Z 	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x38
2022-05-11T03:57:04.7863395Z github.com/panjf2000/ants/v2.(*goWorker).run.func1()
2022-05-11T03:57:04.7864040Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
2022-05-11T03:57:04.7864665Z created by github.com/panjf2000/ants/v2.(*goWorker).run
2022-05-11T03:57:04.7865301Z 	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65
```
[1_Build on CentOSx64.txt](https://github.com/matrixorigin/matrixone/files/8666774/1_Build.on.CentOSx64.txt)

Full log is:

**Comment by XuPeng-SH** [comment]
Fixed by #2478
