### ISSUE TITLE
[Bug]:  `create db` panic, plan2,tae

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2635]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d3293ca03ea563d7c17de549873f81070dd0780d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

special config:
```
usePlan2 = true
storageEngine = "tae"
```

error log from mysql-client:
```
mysql> create database T;
ERROR 1105 (HY000): unknown error:Internal error: panic tae: not found: goroutine 292 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x1042eb5c0?, 0x14000880200})
        /Users/maomao/code/matrixone/pkg/common/moerr/error.go:77 +0x50
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*compile).Run.func1()
        /Users/maomao/code/matrixone/pkg/sql/compile2/compile.go:75 +0x38
panic({0x1042eb5c0, 0x14000880200})
        /usr/local/go/src/runt
```

server log:
```
{"level":"INFO","time":"2022/05/24 15:45:47.402163 +0800","caller":"frontend/mysql_cmd_executor.go:1613","msg":"cmd 3"}
{"level":"INFO","time":"2022/05/24 15:45:47.402223 +0800","caller":"frontend/mysql_cmd_executor.go:1636","msg":"query:create database T"}
{"level":"INFO","time":"2022/05/24 15:45:47.402691 +0800","caller":"frontend/session.go:327","msg":"start txn autocommit if needed"}
{"level":"ERROR","time":"2022/05/24 15:45:47.402773 +0800","caller":"logutil/api.go:62","msg":"error tae catalog: not found","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/maomao/code/matrixone/pkg/logutil/api.go:62\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).DatabaseExists\n\t/Users/maomao/code/matrixone/pkg/frontend/session.go:511\ngithub.com/matrixorigin/matrixone/pkg/sql/plan2.buildCreateDatabase\n\t/Users/maomao/code/matrixone/pkg/sql/plan2/build_ddl.go:264\ngithub.com/matrixorigin/matrixone/pkg/sql/plan2.BuildPlan\n\t/Users/maomao/code/matrixone/pkg/sql/plan2/build.go:57\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/Users/maomao/code/matrixone/pkg/frontend/mysql_cmd_executor.go:1195\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/maomao/code/matrixone/pkg/frontend/mysql_cmd_executor.go:1461\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/maomao/code/matrixone/pkg/frontend/mysql_cmd_executor.go:1660\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/maomao/code/matrixone/pkg/frontend/routine.go:106"}

```

### Expected Behavior
1. execute correctly
2. don't throw err stack to client
3. server crash is reasonable under this scenario?

**Comment by daviszhen** [comment]
I have found the problem yesterday. it will be solved in the next pr.

**Comment by sukki37** [comment]
double checked with 093b68c84585b2cc039756e66d97649382aed4e7
