### ISSUE TITLE
[Bug]: server panic when executing unsupport sql syntax `CREATE TABLE t2970 (a INT, b INT, c INT, d INT, KEY(a), KEY(a, b));`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2650]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d3293ca03e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

server panic, the error log from client is as follows:
```
panic: aoe: dup index

goroutine 294 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/adaptor.TableInfoToSchema(0xc008e0c380?, 0xc00347d650)
	/home/sudong/matrixone/pkg/vm/engine/aoe/storage/adaptor/meta.go:94 +0x611
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).createTable(0xc000792f60, 0x3, 0x0, 0x1, 0x5, {0xc008e0c000, 0x377, 0x380}, {0x0, 0x0, ...})
	/home/sudong/matrixone/pkg/vm/driver/aoe/storage.go:301 +0x2a8
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).Write(0xc0003f4000?, {0x2d5ca70, 0xc003322580})
	/home/sudong/matrixone/pkg/vm/driver/aoe/storage.go:537 +0x1f8
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).execWriteRequest(0xc003318540, _)
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_state_machine_exec.go:439 +0x246
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).applyRequestBatch(0xc003318540, 0xc003177b00)
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_state_machine.go:280 +0x887
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).applyCommittedEntries(0xc003318540, {0xc002fac5a0, 0x1, 0x1?})
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_state_machine.go:190 +0x34b
github.com/matrixorigin/matrixcube/raftstore.(*replica).doApplyCommittedEntries(0xc00370e000, {0xc002fac5a0?, 0x2a2caea?, 0x20?})
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_event_raft_ready.go:345 +0x5d
github.com/matrixorigin/matrixcube/raftstore.(*replica).applyCommittedEntries(_, {0x0, {0x2, 0x9, 0x3}, {0x0, 0x0, 0x0}, {0xc002fac5a0, 0x1, ...}, ...})
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_event_raft_ready.go:207 +0x1ec
github.com/matrixorigin/matrixcube/raftstore.(*replica).processReady(_, {0x0, {0x2, 0x9, 0x3}, {0x0, 0x0, 0x0}, {0xc002fac5a0, 0x1, ...}, ...}, ...)
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_event_raft_ready.go:62 +0x225
github.com/matrixorigin/matrixcube/raftstore.(*replica).handleRaftReady(0xc00370e000, 0xc00370a000?)
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_event_raft_ready.go:37 +0x134
github.com/matrixorigin/matrixcube/raftstore.(*replica).handleEvent(0xc00370e000, 0x676e696b63656863?)
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/replica_event_loop.go:232 +0x1c5
github.com/matrixorigin/matrixcube/raftstore.(*replicaWorker).handleEvent(0xc000734e10, {0x2d45c78, 0xc00370e000})
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/worker_pool.go:114 +0x5f
github.com/matrixorigin/matrixcube/raftstore.(*replicaWorker).workerMain(0xc000734e10)
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/worker_pool.go:91 +0xbc
github.com/matrixorigin/matrixcube/raftstore.newReplicaWorker.func1()
	/home/sudong/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.3.1-0.20220511071845-cfc4bac02bb4/raftstore/worker_pool.go:72 +0x1d
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1()
	/home/sudong/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79 +0xc5
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
	/home/sudong/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:74 +0xea
```

**Comment by m-schen** [comment]
should compute-layer reject the case ? @LeftHandCold 
but I found that it's panic in cube.

**Comment by m-schen** [comment]
tae has the same bug, I think it's a problem of cube.
Or we should just reject the case now.

**Comment by nnsgmsone** [comment]
> tae has the same bug, I think it's a problem of cube. Or we should just reject the case now.

tae no use of cube. So the problem must not be related to the cube.

**Comment by nnsgmsone** [comment]
There is a problem with aoe's code on key, which cannot handle duplicate attributes.
```
func (is *IndexSchema) Append(index *IndexInfo) error {
    // TODO: validation
    for _, idx := range is.Indice {
        if idx.Name == index.Name {
            return ErrDupIndex
        }
    }                                                                                                     
    is.Indice = append(is.Indice, index)
    return nil                                                                                             
}

**Comment by sukki37** [comment]
Update:
on 934f524c2f7194d5637eb7913880410fd8234dda, this works on TAE(bug existed, but not related to cube), but still failed on AOE, new error occurred:
```

mysql> CREATE TABLE t2970 (a INT, b INT, c INT, d INT, KEY(a), KEY(a, b));
ERROR 1105 (HY000): unknown error:db not exist
mysql>
```
