### ISSUE TITLE
[Bug]: server crash, insert, plan2, tae

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2681]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3eb066b
- Hardware parameters:
- OS type:
- Others: https://github.com/matrixorigin/matrixone/pull/2678
```

### Actual Behavior

server crash when executing `insert into t1 values (1,1,1);`

```
{"level":"INFO","time":"2022/05/27 08:16:46.568970 +0000","caller":"frontend/mysql_cmd_executor.go:2057","msg":"cmd 3"}
{"level":"INFO","time":"2022/05/27 08:16:46.568986 +0000","caller":"frontend/mysql_cmd_executor.go:2080","msg":"query:insert into t1 values (1,1,1);\n"}
{"level":"INFO","time":"2022/05/27 08:16:46.569098 +0000","caller":"frontend/session.go:326","msg":"start txn autocommit if needed"}
{"level":"INFO","time":"2022/05/27 08:16:46.569109 +0000","caller":"frontend/session.go:312","msg":"start txn by autocommit"}
{"level":"INFO","time":"2022/05/27 08:16:46.569125 +0000","caller":"frontend/session.go:465","msg":"clean tae txn"}
{"level":"info","ts":"2022-05-27 08:16:46.569","logger":"goetty","caller":"goetty@v1.13.0/application.go:226","msg":"session read failed","listen-address":"0.0.0.0:6001","session-id":1,"addr":"127.0.0.1:39800","error":"read tcp4 127.0.0.1:6001->127.0.0.1:39800: use of closed network connection"}
{"level":"INFO","time":"2022/05/27 08:16:46.569186 +0000","caller":"frontend/routine_manager.go:76","msg":"will close iosession"}
{"level":"ERROR","time":"2022/05/27 08:16:46.569195 +0000","caller":"logutil/api.go:62","msg":"close tcp conn failed. error:the session is closing in other goroutine","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/runner/work/matrixone/matrixone/pkg/logutil/api.go:62\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*ProtocolImpl).Quit\n\t/home/runner/work/matrixone/matrixone/pkg/frontend/protocol.go:199\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).Quit\n\t/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_protocol.go:312\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Quit\n\t/home/runner/work/matrixone/matrixone/pkg/frontend/routine.go:134\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed\n\t/home/runner/work/matrixone/matrixone/pkg/frontend/routine_manager.go:77\ngithub.com/fagongzi/goetty.(*server).doStart.func1.2\n\t/home/runner/go/pkg/mod/github.com/fagongzi/goetty@v1.13.0/application.go:201\ngithub.com/fagongzi/goetty.(*server).doStart.func1\n\t/home/runner/go/pkg/mod/github.com/fagongzi/goetty@v1.13.0/application.go:208"}
panic: runtime error: index out of range [7] with length 0

goroutine 111 [running]:
encoding/binary.bigEndian.Uint64(...)
	/opt/hostedtoolcache/go/1.18.2/x64/src/encoding/binary/binary.go:125
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.IDCtxToID(...)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/txn/txnbase/txnctx.go:32
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).GetTxnByCtx(...)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:114
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*DB).GetTxnByCtx(0xc0042ee7c0?, {0x0?, 0x132ad77?, 0xc0042f85a0?})
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/db.go:71 +0x65
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnEngine).Database(0xf52f4e?, {0xc0041e97d5, 0x8}, {0x0?, 0x629088ee?, 0x1?})
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/moengine/engine.go:64 +0x38
github.com/matrixorigin/matrixone/pkg/frontend.getTableRef(0xc0042f9400, {0xc0041e97d5?, 0x0?}, {0x2fcefe0?, 0xc000011c78?})
	/home/runner/work/matrixone/matrixone/pkg/frontend/insert.go:65 +0x74
github.com/matrixorigin/matrixone/pkg/frontend.buildInsertValues(0xc00435b680, 0xc00020d920, {0x2fcefe0?, 0xc000011c78?}, {0xc0042fcf50, 0x8, 0x8})
	/home/runner/work/matrixone/matrixone/pkg/frontend/insert.go:88 +0xc5
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleInsertValues(0xc0000acd20, 0x0?, 0x1?)
	/home/runner/work/matrixone/matrixone/pkg/frontend/insert.go:46 +0x113
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc0000acd20, {0xc0042ef3e0, 0x1f})
	/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:1755 +0x1577
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc0000acd20, 0xc0043105a0)
	/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:2104 +0x5d3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc000500840)
	/home/runner/work/matrixone/matrixone/pkg/frontend/routine.go:106 +0x258
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/home/runner/work/matrixone/matrixone/pkg/frontend/routine.go:158 +0x1e5
```
[mo-server.log](https://github.com/matrixorigin/matrixone/files/8785220/mo-server.log)

**Comment by jiangxinmeng1** [comment]
`(engine.Engine).Database(string, engine.Snapshot)` needs a []byte with length 8(uint64) as the second parameter. 65 row in insert.go provides nil

**Comment by sukki37** [comment]
double checked with aeb1ce2a5ded5dae42
