### ISSUE TITLE
[Bug]: frontend panic,plan2,aoe

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2715]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 24a9e013b2d4e0c01a9b4f0ee6b4925c3b860074
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"INFO","time":"2022/05/30 12:55:29.309065 +0000","caller":"frontend/mysql_cmd_executor.go:2061","msg":"query:INSERT INTO t3 VALUES (3359356,405,3359356,'Muster..."}
{"level":"INFO","time":"2022/05/30 12:55:29.309174 +0000","caller":"frontend/session.go:392","msg":"start txn autocommit if needed"}
{"level":"INFO","time":"2022/05/30 12:55:29.309187 +0000","caller":"frontend/session.go:378","msg":"start txn by autocommit"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309206 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"7a6e044ea23a4d1ba2cc999cc79f69a3"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309218 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"7a6e044ea23a4d1ba2cc999cc79f69a3","to-shard":2,"to-store":"localhost:20000","request":"id: 7a6e044ea23a4d1ba2cc999cc79f69a3, key: 6d6574610000000000000001444249446f70657261746f72, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309237 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"7a6e044ea23a4d1ba2cc999cc79f69a3","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309281 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"7a6e044ea23a4d1ba2cc999cc79f69a3"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309298 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"7a628bc49bb1457991029e3520ed7e2b"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309310 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"7a628bc49bb1457991029e3520ed7e2b"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309329 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"7a6e044ea23a4d1ba2cc999cc79f69a3","request":"id: 7a6e044ea23a4d1ba2cc999cc79f69a3, key: 6d6574610000000000000001444249446f70657261746f72, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309352 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: 7a6e044ea23a4d1ba2cc999cc79f69a3, pid: 0, type: Read, error: , value: 8 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309370 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"7a6e044ea23a4d1ba2cc999cc79f69a3"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309384 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of Get cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309399 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"af785063cb9e4dfab6dd0e09c4def442"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309408 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"af785063cb9e4dfab6dd0e09c4def442","to-shard":2,"to-store":"localhost:20000","request":"id: af785063cb9e4dfab6dd0e09c4def442, key: 6d65746100000000000000014442494e464f0000000000000009, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309418 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"af785063cb9e4dfab6dd0e09c4def442","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309463 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"af785063cb9e4dfab6dd0e09c4def442"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309505 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"aaf52837dbd449698c54ebbe83102094"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309521 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"aaf52837dbd449698c54ebbe83102094"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309543 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"af785063cb9e4dfab6dd0e09c4def442","request":"id: af785063cb9e4dfab6dd0e09c4def442, key: 6d65746100000000000000014442494e464f0000000000000009, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309577 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: af785063cb9e4dfab6dd0e09c4def442, pid: 0, type: Read, error: , value: 84 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309596 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"af785063cb9e4dfab6dd0e09c4def442"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309611 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of Get cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309631 +0000","caller":"catalog/catalog.go:302","msg":"GetDatabase cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309640 +0000","caller":"engine/engine.go:107","msg":"time cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309656 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"549dfd1b91c440a09e14bd8986bded6d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309667 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"549dfd1b91c440a09e14bd8986bded6d","to-shard":2,"to-store":"localhost:20000","request":"id: 549dfd1b91c440a09e14bd8986bded6d, key: 6d65746100000000000000014442494e464f0000000000000009, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309677 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"549dfd1b91c440a09e14bd8986bded6d","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309723 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"549dfd1b91c440a09e14bd8986bded6d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309740 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"19d3053a381d47cd85d3d3f6599aeae9"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309757 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"19d3053a381d47cd85d3d3f6599aeae9"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309778 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"549dfd1b91c440a09e14bd8986bded6d","request":"id: 549dfd1b91c440a09e14bd8986bded6d, key: 6d65746100000000000000014442494e464f0000000000000009, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309797 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: 549dfd1b91c440a09e14bd8986bded6d, pid: 0, type: Read, error: , value: 84 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309813 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"549dfd1b91c440a09e14bd8986bded6d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309825 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of Get cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309848 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"53b9a442ff0a41439199fcd72e8ca7d5"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309858 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"53b9a442ff0a41439199fcd72e8ca7d5","to-shard":2,"to-store":"localhost:20000","request":"id: 53b9a442ff0a41439199fcd72e8ca7d5, key: 6d657461000000000000000154494400000000000000097433, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309875 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"53b9a442ff0a41439199fcd72e8ca7d5","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309918 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"53b9a442ff0a41439199fcd72e8ca7d5"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309934 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"d6b60dcb256142268999f18bf96ea2ff"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309945 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"d6b60dcb256142268999f18bf96ea2ff"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309962 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"53b9a442ff0a41439199fcd72e8ca7d5","request":"id: 53b9a442ff0a41439199fcd72e8ca7d5, key: 6d657461000000000000000154494400000000000000097433, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309980 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: 53b9a442ff0a41439199fcd72e8ca7d5, pid: 0, type: Read, error: , value: 8 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.309994 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"53b9a442ff0a41439199fcd72e8ca7d5"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310006 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of Get cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310021 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"a145de0b0e5c4764bf0c0fa63603df5d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310031 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"a145de0b0e5c4764bf0c0fa63603df5d","to-shard":2,"to-store":"localhost:20000","request":"id: a145de0b0e5c4764bf0c0fa63603df5d, key: 6d65746100000000000000015461626c6500000000000000090000000000000006, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310040 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"a145de0b0e5c4764bf0c0fa63603df5d","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310083 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"a145de0b0e5c4764bf0c0fa63603df5d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310111 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"088b99d078d443a98ba34bdd1830df0d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310125 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"088b99d078d443a98ba34bdd1830df0d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310142 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"a145de0b0e5c4764bf0c0fa63603df5d","request":"id: a145de0b0e5c4764bf0c0fa63603df5d, key: 6d65746100000000000000015461626c6500000000000000090000000000000006, pid: 0, type: Read, custom-type: 2, cmd: 0 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310166 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: a145de0b0e5c4764bf0c0fa63603df5d, pid: 0, type: Read, error: , value: 855 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310182 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"a145de0b0e5c4764bf0c0fa63603df5d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310194 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of Get cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310316 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"34142f71ecbb4a13ac00771e0a33d338"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310329 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"34142f71ecbb4a13ac00771e0a33d338","to-shard":2,"to-store":"localhost:20000","request":"id: 34142f71ecbb4a13ac00771e0a33d338, key: 6d657461000000000000000150726553706c6974, pid: 0, type: Read, custom-type: 3, cmd: 44 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310368 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"34142f71ecbb4a13ac00771e0a33d338","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310416 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"34142f71ecbb4a13ac00771e0a33d338"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310433 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"813ce24d749e481180bd58bcd9999be4"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310450 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"813ce24d749e481180bd58bcd9999be4"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310469 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"34142f71ecbb4a13ac00771e0a33d338","request":"id: 34142f71ecbb4a13ac00771e0a33d338, key: 6d657461000000000000000150726553706c6974, pid: 0, type: Read, custom-type: 3, cmd: 44 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310491 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: 34142f71ecbb4a13ac00771e0a33d338, pid: 0, type: Read, error: , value: 0 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310507 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"34142f71ecbb4a13ac00771e0a33d338"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310520 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of PrefixScan cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310538 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"1fc5072174d5419d9bbffa060bdecd94"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310547 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"1fc5072174d5419d9bbffa060bdecd94","to-shard":2,"to-store":"localhost:20000","request":"id: 1fc5072174d5419d9bbffa060bdecd94, key: 6d6574610000000000000001526f7574650000000000000006, pid: 0, type: Read, custom-type: 3, cmd: 54 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310558 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"1fc5072174d5419d9bbffa060bdecd94","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310602 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"1fc5072174d5419d9bbffa060bdecd94"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310624 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"id":"0e9bab2ffbf741238599166789f97501"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310636 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"index":71,"batch-id":"0e9bab2ffbf741238599166789f97501"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310654 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":2,"replica-id":3,"request-id":"1fc5072174d5419d9bbffa060bdecd94","request":"id: 1fc5072174d5419d9bbffa060bdecd94, key: 6d6574610000000000000001526f7574650000000000000006, pid: 0, type: Read, custom-type: 3, cmd: 54 bytes, to-shard: 0"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310679 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: 1fc5072174d5419d9bbffa060bdecd94, pid: 0, type: Read, error: , value: 55 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310694 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"1fc5072174d5419d9bbffa060bdecd94"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310706 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of PrefixScan cost 0 ms"}
{"level":"INFO","time":"2022/05/30 12:55:29.310723 +0000","caller":"catalog/catalog.go:719","msg":"[getShardidsWithTimeout] get shard for 6, returns [14], <nil>, cost 0 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310732 +0000","caller":"catalog/catalog.go:690","msg":"GetTablets return 1 tablets, cost 1 ms"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310748 +0000","name":"cube.cube-client","caller":"client/client.go:277","msg":"begin to send request","request-id":"1a848828a4cc46bf95c0988770d6d353"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310757 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"1a848828a4cc46bf95c0988770d6d353","to-shard":14,"to-store":"localhost:20000","request":"id: 1a848828a4cc46bf95c0988770d6d353, key: , pid: 0, type: Read, custom-type: 107, cmd: 3 bytes, to-shard: 14"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310766 +0000","name":"cube.store","caller":"raftstore/store.go:353","msg":"receive request","store":"node0","request-id":"1a848828a4cc46bf95c0988770d6d353","store-id":1}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310812 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:76","msg":"push to proposal batch","store":"node0","store-id":1,"shard-id":14,"replica-id":18,"id":"1a848828a4cc46bf95c0988770d6d353"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310829 +0000","name":"cube.store","caller":"raftstore/replica_event_proposal.go:173","msg":"call read index","store":"node0","store-id":1,"shard-id":14,"replica-id":18,"id":"98d71ee3114b4920841aa528f7f24d9d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310845 +0000","name":"cube.store","caller":"raftstore/read_index_queue.go:74","msg":"read index ready","store":"node0","store-id":1,"shard-id":14,"replica-id":18,"index":4,"batch-id":"98d71ee3114b4920841aa528f7f24d9d"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310863 +0000","name":"cube.store","caller":"raftstore/replica.go:483","msg":"begin to exec read requests","store":"node0","store-id":1,"shard-id":14,"replica-id":18,"request-id":"1a848828a4cc46bf95c0988770d6d353","request":"id: 1a848828a4cc46bf95c0988770d6d353, key: , pid: 0, type: Read, custom-type: 107, cmd: 3 bytes, to-shard: 14"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310893 +0000","name":"cube.store.proxy","caller":"raftstore/proxy.go:309","msg":"requests done","store":"node0","store-id":1,"resp":"id: 1a848828a4cc46bf95c0988770d6d353, pid: 0, type: Read, error: , value: 22 bytes"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310914 +0000","name":"cube.cube-client","caller":"client/client.go:300","msg":"response received","request-id":"1a848828a4cc46bf95c0988770d6d353"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310926 +0000","caller":"driver/cube_driver.go:1020","msg":"Exec of GetSegmentIds cost 0 ms"}
{"level":"INFO","time":"2022/05/30 12:55:29.310941 +0000","caller":"engine/database.go:142","msg":"nodes: [], tablets len: 1"}
{"level":"DEBUG","time":"2022/05/30 12:55:29.310950 +0000","caller":"engine/database.go:82","msg":"time cost 1 ms"}
{"level":"INFO","time":"2022/05/30 12:55:29.310966 +0000","caller":"frontend/session.go:531","msg":"clean tae txn"}
{"level":"info","ts":"2022-05-30 12:55:29.311","logger":"goetty","caller":"goetty@v1.13.0/application.go:226","msg":"session read failed","listen-address":"0.0.0.0:6001","session-id":1,"addr":"127.0.0.1:59416","error":"read tcp4 127.0.0.1:6001->127.0.0.1:59416: use of closed network connection"}
{"level":"INFO","time":"2022/05/30 12:55:29.311059 +0000","caller":"frontend/routine_manager.go:76","msg":"will close iosession"}
{"level":"ERROR","time":"2022/05/30 12:55:29.311069 +0000","caller":"logutil/api.go:62","msg":"close tcp conn failed. error:the session is closing in other goroutine","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/runner/work/matrixone/matrixone/head/pkg/logutil/api.go:62\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*ProtocolImpl).Quit\n\t/home/runner/work/matrixone/matrixone/head/pkg/frontend/protocol.go:199\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).Quit\n\t/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_protocol.go:312\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Quit\n\t/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:134\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed\n\t/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:77\ngithub.com/fagongzi/goetty.(*server).doStart.func1.2\n\t/home/runner/go/pkg/mod/github.com/fagongzi/goetty@v1.13.0/application.go:201\ngithub.com/fagongzi/goetty.(*server).doStart.func1\n\t/home/runner/go/pkg/mod/github.com/fagongzi/goetty@v1.13.0/application.go:208"}
panic: interface conversion: interface {} is int32, not int64

goroutine 816 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.makeExprFromVal({0x16, 0x4, 0x20, 0x0, 0x0}, {0x2932c60?, 0xc003b3dbd4?}, 0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/insert.go:589 +0x806
github.com/matrixorigin/matrixone/pkg/frontend.buildInsertValues(0xc002ad03c0, 0xc008b0d928, {0x3016760?, 0xc003264c50?}, {0x0, 0x0, 0x0})
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/insert.go:107 +0x50d6
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleInsertValues(0xc008eabe00, 0xe?, 0x1?)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/insert.go:46 +0x113
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc008eabe00, {0xc00013f040, 0x45})
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:1736 +0x1497
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc008eabe00, 0xc0032d47e0)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2085 +0x5d3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc008c6dd40)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:106 +0x258
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:158 +0x1e5

```

### Steps to Reproduce

```markdown
CREATE TABLE t3(
  cont_nr int(11) NOT NULL auto_increment primary key,
  ver_nr int(11) NOT NULL default 0,
  aufnr int(11) NOT NULL default 0,
  username varchar(50) NOT NULL default ''
);
INSERT INTO t3 VALUES (3359356,405,3359356,'Mustermann Musterfrau');
```

**Comment by daviszhen** [comment]
insert crashed.

**Comment by sukki37** [comment]
test passed using 832401b19005d0af14c27dc99a9ebe8282502587
