### ISSUE TITLE
[Bug]:  panic runtime error: invalid memory address or nil pointer, plan2, tae

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2719]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): aeb1ce2a5ded5dae426c23ba9adb7e9724644f61
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. unexcepted error
2. unhandled error msg is thrown to the MySQL client
3. no err log can be found in mo-server logs

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/77312370/171036039-d2fdd2cc-5f9a-4d2a-95ab-bb042ec9aff0.png">

```
mysql> select power(a,2) as a1, power(b,2) as b1 from t1 where power(a,2) > power(b,2) order by a1 asc;
unknown error:Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 290 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2a86940?, 0x40041c0})
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/common/moerr/error.go:77 +0x53
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/vm/overload/run.go:50 +0x31
panic({0x2a86940, 0x40041c0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/matrixorigin/matrixone/pkg/sql/colexec2/mergeorder.Call(0xc000473e40, {0x2940380?, 0xc000024b20})
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/sql/colexec2/mergeorder/order.go:59 +0xe8
github.com/matrixorigin/matrixone/pkg/vm/overload.Run({0xc0002d3620?, 0x3, 0x7f2b1c6bcab8?}, 0x10?)
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/vm/overload/run.go:54 +0xee
github.com/matrixorigin/matrixone/pkg/vm/pipeline2.(*Pipeline).MergeRun(0xc00020bf20, 0xc000473e40)
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/vm/pipeline2/pipeline.go:188 +0x1af
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun(0xc000400b40, {0x309b020?, 0xc0000103c8})
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/sql/compile2/scope.go:317 +0x574
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun.func2(0xc000630340?)
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/sql/compile2/scope.go:296 +0x79
created by github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun
	/mnt/datadisk0/tmp/0530/0530/matrixone/pkg/sql/compile2/scope.go:291 +0x2b8
        /mnt/datadisk0/tmp/0530/0530/matrixone/pkg/vm/overload/run.go:50 +0x31
```

### Steps to Reproduce

```markdown
create table t1(a int,b int);
select * from t1;
insert into t1 values(5,-2),(10,3),(100,0),(4,3),(6,-3);
select power(a,2) as a1, power(b,2) as b1 from t1 where power(a,2) > power(b,2) order by a1 asc;
```

**Comment by nnsgmsone** [comment]
When plan2 is combined with tae, it behaves very strangely。。。

**Comment by nnsgmsone** [comment]
The cast function takes two arguments, currently plan2 generates only one, the second argument is used to specify the target type.

**Comment by sukki37** [comment]
test passed using 832401b19005d0af14c27dc99a9ebe8282502587
