### ISSUE TITLE
[Bug]: lpad error, Got packet bigger than 'max_allowed_packet' bytes, plan2

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2736]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bff431beed70834075a89f7d2ec8eebfa5b58f3a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

client stuck when exec `select lpad('hello', 4294967295, '1');`

```
mysql> select lpad('hello', 4294967295, '1');
ERROR 2020 (HY000): Got packet bigger than 'max_allowed_packet' bytes
```

server logs
```
{"level":"ERROR","time":"2022/05/31 23:50:41.939205 +0800","caller":"logutil/api.go:62","msg":"routine send response failed &{1 0 3 0xc000aea150 0 0 0}. error:write tcp4 127.0.0.1:6001->127.0.0.1:55556: write: broken pipe ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/mnt/datadisk0/tmp/0531/matrixone/pkg/logutil/api.go:62\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/mnt/datadisk0/tmp/0531/matrixone/pkg/frontend/routine.go:112"}

```

**Comment by aressu1985** [comment]
and if the para of lpad is negative, this func will cause mo memory error,and cause the cpu overload 

mysql> select lpad('hello', -4294967295, '1');
ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [0] with length 0: goroutine 1885 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2a794a0?, 0xc0032923a8})
	/home/sudong/matrixone/pkg/common/moerr/error.go:77 +0x53
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
	/home/sudong/matrixone/pkg/vm/overload/run.go:50 +0x31
panic({0x2a794a0, 0xc0032923a8})
	/usr/lib/golang/s

**Comment by qingxinhome** [comment]
> 
Indeed, the previous implementation logic of the lpad function is incorrect. I will make a simple correction. I think it will be refactored later

**Comment by sukki37** [comment]
Some problems have not been fixed. (50463ec1c7268be63668a95b0900fef73d01281d)
<img width="952" alt="image" src="https://user-images.githubusercontent.com/77312370/172355141-43434c0b-13f1-41dc-ba4c-d5f956ede4c0.png">
