### ISSUE TITLE
[Bug]:  server crashed error,plan2,tae

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2737]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):57d85fb278af0d0093fcc22cddee0fd27eda381e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CLI:
```
mysql> create table t1(a float,  b float);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 values(10, 100), (2, 5);
Query OK, 2 rows affected (0.00 sec)

mysql> select distinct * from t1 where power(a, b)>0;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR: 
Can't connect to the server
```

server log:
```
{"level":"INFO","time":"2022/06/01 01:34:45.757741 +0800","caller":"frontend/mysql_cmd_executor.go:2057","msg":"query:select distinct * from t1 where power(a, b)>0"}
{"level":"INFO","time":"2022/06/01 01:34:45.757913 +0800","caller":"frontend/session.go:410","msg":"start txn autocommit if needed"}
{"level":"INFO","time":"2022/06/01 01:34:45.757935 +0800","caller":"frontend/session.go:396","msg":"start txn by autocommit"}
{"level":"INFO","time":"2022/06/01 01:34:45.757970 +0800","caller":"frontend/session.go:609","msg":"dbName t tableNames [t1]"}
{"level":"INFO","time":"2022/06/01 01:34:45.758061 +0800","caller":"frontend/mysql_cmd_executor.go:1826","msg":"time of Exec.Build : 106.602µs"}
{"level":"INFO","time":"2022/06/01 01:34:45.758103 +0800","caller":"frontend/session.go:549","msg":"clean tae txn"}
{"level":"info","ts":"2022-06-01 01:34:45.758","logger":"goetty","caller":"goetty@v1.13.0/application.go:226","msg":"session read failed","listen-address":"0.0.0.0:6001","session-id":1,"addr":"127.0.0.1:36304","error":"read tcp4 127.0.0.1:6001->127.0.0.1:36304: use of closed network connection"}
{"level":"INFO","time":"2022/06/01 01:34:45.758192 +0800","caller":"frontend/routine_manager.go:76","msg":"will close iosession"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2668418]

goroutine 274 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).GetColumns(0x2d4632a?)
	/mnt/datadisk0/tmp/0531/old_version/matrixone/pkg/frontend/mysql_cmd_executor.go:1512 +0xb8
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc000032690, {0xc000752480, 0x2d})
	/mnt/datadisk0/tmp/0531/old_version/matrixone/pkg/frontend/mysql_cmd_executor.go:1837 +0x1fd2
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc000032690, 0xc000157140)
	/mnt/datadisk0/tmp/0531/old_version/matrixone/pkg/frontend/mysql_cmd_executor.go:2081 +0x5d3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc000358480)
	/mnt/datadisk0/tmp/0531/old_version/matrixone/pkg/frontend/routine.go:106 +0x264
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/mnt/datadisk0/tmp/0531/old_version/matrixone/pkg/frontend/routine.go:158 +0x1e5
```

### Additional information

seems introduce by https://github.com/matrixorigin/matrixone/pull/2713

**Comment by daviszhen** [comment]
In the case, the `Typ` field of the `ColDef` is nil. That is invalid.

![1654077343379](https://user-images.githubusercontent.com/60595215/171378519-2b8d630c-39d2-4960-9707-088cc063f545.jpg)

**Comment by ouyuanning** [comment]
when function was not registered,  all the statement with function will error.

it seems fixed now.

**Comment by aressu1985** [comment]
fixed

mysql> create table t1(a float,  b float);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 values(10, 100), (2, 5);
Query OK, 2 rows affected (0.01 sec)

mysql> 
mysql> 
mysql>  select distinct * from t1 where power(a, b)>0;
+------+------+
| a    | b    |
+------+------+
|   10 |  100 |
|    2 |    5 |
+------+------+
2 rows in set (0.01 sec)

mysql> 
mysql>
