### ISSUE TITLE
[Bug]: too many open files error

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2783]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/fengttt/matrixone/commit/d44671336c57b3ca244a9437495cab1789d900cb
- Hardware parameters:
- OS type: macos, m1
- Others:
```

### Actual Behavior

server panic during running bvt test
```
{"level":"INFO","time":"2022/06/04 03:47:51.744218 +0800","caller":"frontend/session.go:490","msg":"commit autocommit only"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1034b9e7c]

goroutine 263 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFile).OpenBlock(0x0, 0x14010213260?, 0x140002c16c8?, 0x102f9a794?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:205 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.newBlock(0x14030fb0ff0, {0x104f54c60, 0x0}, {0x104f573a0?, 0x140000ac2a0?}, {0x104f54cd8?, 0x140006d4048})
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/tables/block.go:69 +0x100
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*DataFactory).MakeBlockFactory.func1(0x140002c18d8?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/tables/tables.go:58 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.NewBlockEntry(0x1400b4b6140, {0x104f60128?, 0x14004d80d70}, 0x0, 0x1403870efc0)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/catalog/block.go:59 +0x18c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*SegmentEntry).CreateBlock(0x1400b4b6140, {0x104f60128, 0x14004d80d70}, 0x1d?, 0x511?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/catalog/segment.go:226 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).createBlock(0x14002441f40, 0x105f840b8?, 0x0)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:231 +0xd4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).CreateBlock(...)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:214
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).CreateBlock(0x14039d52700?, 0x104d7f100?, 0x140002c1a01?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:263 +0x50
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).CreateBlock(0x0?, 0x14005e46c00?, 0x1400b4b6140?, 0x0?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:331 +0x94
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnSegment).CreateBlock(0x14005e46c00)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/segment.go:187 +0x80
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).prepareApplyNode(0x14039d52780, {0x104f5fbc0?, 0x14039d52800})
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:130 +0x210
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).PrepareApply(...)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:110
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PreCommit(0x140002c1c58?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:648 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PreCommit(0x1400b4b6040)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:332 +0xfc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PreCommit(0x140002c1d78?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:378 +0x7c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PreCommit(0x1401a992536?)
        /Users/maomao/tmp/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:237 +0x2c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreCommit(0x140002c1ea8?, {0x104f5ffc0, 0x14014a373f0})
```

**Comment by XuPeng-SH** [comment]
The root cause is "too many open files error". The actual error message is ignored, it should be exposed later @LeftHandCold.

TAE requires a number of file handles, it's better to enlarge the default ulimit. What makes it worse is that `GC`(release dropped table-related file handles) is not completely ready now. Even if `GC` can work normally, under normal circumstances, it will not release resources too quickly.

**Comment by LeftHandCold** [comment]
The actual error message has been panic in #2779 .
