### ISSUE TITLE
[Bug]: An panic is reported when the dayofyear function parameter is null，panic interface conversion: interface {} is nil

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#2789]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select DAYOFYEAR(null) from d_table4;
ERROR 1105 (HY000): unknown error:Internal error: panic interface conversion: interface {} is nil, not []types.Date: goroutine 7054 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2b4d400?, 0xc00540db60})
	/home/yiming/workspace/matrixone/pkg/common/moerr/error.go:77 +0x53
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
	/home/yiming/workspace/matrixone/pkg/vm/overload/run.go:50 +0x31
panic({0x2b4d400, 0xc0054

### Expected Behavior

mysql> select DAYOFYEAR(NULL) from t1;
+-----------------+
| DAYOFYEAR(NULL) |
+-----------------+
|            NULL |
|            NULL |
|            NULL |
|            NULL |
|            NULL |
+-----------------+

**Comment by qingxinhome** [comment]
select ceiling(3.2567) from t1;

**Comment by qingxinhome** [comment]
Similar problems exist in: ceiling（）

**Comment by yingfeng** [comment]
Left panic interface conversion: 

```
2022-06-09T08:04:29.7574701Z 2022-06-09 08:04:29 ERROR Executor:222 - [cases/function/builtin.sql][select b from t1 where acos(a*pi()/180)<=acos(b*pi()/180)  order by a;] is executed failed
2022-06-09T08:04:29.7576729Z 2022-06-09 08:04:29 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T08:04:29.7577180Z b
2022-06-09T08:04:29.7577962Z -20.0
2022-06-09T08:04:29.7578240Z 0.0
2022-06-09T08:04:29.7578652Z 2022-06-09 08:04:29 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T08:04:29.7579143Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not *types.Bytes: goroutine 57702 [running]:


2022-06-09T08:04:41.5785964Z 2022-06-09 08:04:41 ERROR Executor:222 - [cases/function/func_aggr_max.test][select (min(a4)+max(a4))/2 from t1;] is executed failed
2022-06-09T08:04:41.5787299Z 2022-06-09 08:04:41 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T08:04:41.5787898Z (min(a4)+max(a4))/2
2022-06-09T08:04:41.5788388Z 0.085
2022-06-09T08:04:41.5788957Z 2022-06-09 08:04:41 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T08:04:41.5789635Z unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64: goroutine 68388 [running]:



2022-06-09T08:04:43.7235024Z 2022-06-09 08:04:43 ERROR Executor:222 - [cases/function/func_aggr_mysql.test][select (min(a4)+max(a4))/2 from t1;] is executed failed
2022-06-09T08:04:43.7235923Z 2022-06-09 08:04:43 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T08:04:43.7236517Z (min(a4)+max(a4))/2
2022-06-09T08:04:43.7236739Z 0.085
2022-06-09T08:04:43.7237204Z 2022-06-09 08:04:43 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T08:04:43.7237699Z unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64: goroutine 72041 [running]:



2022-06-09T08:05:15.5340925Z 2022-06-09 08:05:15 ERROR Executor:222 - [cases/function/func_group.test][select (min(a4)+max(a4))/2 from t1;] is executed failed
2022-06-09T08:05:15.5341511Z 2022-06-09 08:05:15 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T08:05:15.5341820Z (min(a4)+max(a4))/2
2022-06-09T08:05:15.5342056Z 0.085
2022-06-09T08:05:15.5342414Z 2022-06-09 08:05:15 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T08:05:15.5342860Z unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64: goroutine 89339 [running]:



2022-06-09T08:05:34.5417381Z 2022-06-09 08:05:34 ERROR Executor:222 - [cases/function/func_string_substring.test][select substring('abc', cast(2 as unsigned int));] is executed failed
2022-06-09T08:05:34.5418084Z 2022-06-09 08:05:34 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T08:05:34.5418609Z substring('abc', cast(2 as unsigned int))
2022-06-09T08:05:34.5418841Z bc
2022-06-09T08:05:34.5419324Z 2022-06-09 08:05:34 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T08:05:34.5419879Z unknown error:Internal error: panic interface conversion: interface {} is []uint64, not []int64: goroutine 105669 [running]:

```

**Comment by daviszhen** [comment]
it was fixed
