### ISSUE TITLE
[Bug]: result error when para is negative for SINH

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

022-06-06 18:57:08 ERROR Executor:135 - [cases/function/func_math_sinh.test][SELECT SINH(-2);] is executed failed
2022-06-06 18:57:08 ERROR Executor:136 - [EXPECT RESULT]:

2022-06-06 18:57:08 ERROR Executor:137 - [ACTUAL RESULT]:
sinh(-2)
0.0
Exception in thread "main" java.lang.NumberFormatException: For input string: "+Inf"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDouble(MysqlTextValueDecoder.java:228)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:127)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:250)
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:954)
	at io.mo.db.Executor.getRS(Executor.java:566)
	at io.mo.db.Executor.run(Executor.java:97)
	at io.mo.Tester.run(Tester.java:89)
	at io.mo.Tester.run(Tester.java:107)
	at io.mo.Tester.main(Tester.java:53)
[sudong@VM-0-12-centos mo-test]$

**Comment by daviszhen** [comment]
it was fixed
