### ISSUE TITLE
[Bug]: data_add segmentation fault

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#2870]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sql
mysql> select a FROM dt;
+----------------------------+
| a                          |
+----------------------------+
| 1990-09-09 11:11:11.123400 |
| 1990-09-09 11:11:11.123500 |
| 1990-09-09 11:11:11.123500 |
+----------------------------+
3 rows in set (0.02 sec)

mysql> select date_add(a, INTERVAL 1 DAY) FROM dt;
ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [1] with length 1: goroutine 1693 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x106d33820, 0x14013a7ae88})
        /Users/arya/extract/pkg/common/moerr/error.go:77 +0x98
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
        /Users/arya/extract/pkg/vm/overload/run.go:50 +0x44
panic({0x106d33820, 0x14013a7ae88})
        /usr/local/go/src/ru
```

**Comment by broccoliSpicy** [comment]
```go
func dateAdd(xs []types.Date, ys []int64, zs []int64, rs []types.Date) []types.Date {
	for i, d := range xs {
		rs[i] = d.ToTime().AddInterval(ys[i], types.IntervalType(zs[i])).ToDate()
	}
	return rs
}
```
perhaps write different function implementation when inputs aren't aligned would solve this problem

**Comment by bbbearxyz** [comment]
dt is a string or datetime type

**Comment by broccoliSpicy** [comment]
```sql
mysql> create table dt(a datetime);
Query OK, 0 rows affected (0.48 sec)

mysql> insert into dt values("2020-01-01 11:12:12");
Query OK, 1 row affected (0.07 sec)

mysql> select date_add(a, INTERVAL 1 DAY) FROM dt;
+------------------------------+
| date_add(a, interval(1 day)) |
+------------------------------+
| 2020-01-02 11:12:12          |
+------------------------------+
1 row in set (0.02 sec)

mysql> insert into dt values("2020-01-01 11:12:12");
Query OK, 1 row affected (0.03 sec)

mysql> select date_add(a, INTERVAL 1 DAY) FROM dt;
ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [1] with length 1: goroutine 1208 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x102befe60, 0x1400e1be000})
        /Users/arya/fix_minor_bugs/pkg/common/moerr/error.go:77 +0x98
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
        /Users/arya/fix_minor_bugs/pkg/vm/overload/run.go:50 +0x44
panic({0x102befe60, 0x1400e1be000})
        /usr/l
```

As I stated in my previous comment, 

```go
func dateAdd(xs []types.Date, ys []int64, zs []int64, rs []types.Date) []types.Date {
	for i, d := range xs {
		rs[i] = d.ToTime().AddInterval(ys[i], types.IntervalType(zs[i])).ToDate()
	}
	return rs
}
```
in your dateAdd function, you assume that xs and ys are the same length, but in queries like this:
```sql
 select date_add(a, INTERVAL 1 DAY) FROM dt;
```
XS has length 2 whereas ys is length 1, perhaps just take a look at how another functions handle this...

**Comment by bbbearxyz** [comment]
I fix it

**Comment by aressu1985** [comment]
fixed

mysql> create table dt(a datetime);
Query OK, 0 rows affected (0.05 sec)

mysql> 
mysql> insert into dt values("2020-01-01 11:12:12");
Query OK, 1 row affected (0.08 sec)

mysql> select date_add(a, INTERVAL 1 DAY) FROM dt;
+-------------------------------+
| date_add(a, interval(1, day)) |
+-------------------------------+
| 2020-01-02 11:12:12.000000    |
+-------------------------------+
1 row in set (0.00 sec)

mysql> insert into dt values("2020-01-01 11:12:12");
Query OK, 1 row affected (0.01 sec)

mysql> select date_add(a, INTERVAL 1 DAY) FROM dt;
+-------------------------------+
| date_add(a, interval(1, day)) |
+-------------------------------+
| 2020-01-02 11:12:12.000000    |
| 2020-01-02 11:12:12.000000    |
+-------------------------------+
2 rows in set (0.01 sec)

mysql>
