### ISSUE TITLE
[Bug]: aoe panic of invalid memory address when executing update statements

### ISSUE THREAD

**Issue by yingfeng** [matrixorigin/matrixone#2900]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):head
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are 269 same errors altogether in the AOE bvt test results right now

```
update t1 set a=a+(a MOD 2) where a is null;
```
```
unknown error:Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 1343 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2be6740?, 0x42171e0})
	/home/runner/work/matrixone/matrixone/head/pkg/common/moerr/error.go:77 +0x53
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2126 +0x45
panic({0x2be6740, 0x42171e0})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve(0xc002beb4d0, {0x0?, 0xc010c4d740?}, {0xc0036cf117, 0x2})
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/session.go:668 +0x435
github.com/matrixorigin/matrixone/pkg/sql/plan2.getResolveTable({0x0, 0x0}, {0xc0036cf117, 0x2}, {0x3223c18?, 0xc002beb4d0?}, 0xc003f4b3a8)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_util.go:430 +0x50
github.com/matrixorigin/matrixone/pkg/sql/plan2.buildTable({0x31ff6e0?, 0xc0112c1950?}, {0x3223c18, 0xc002beb4d0}, 0xc00f40b030, 0xc003f4b3a8)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_from.go:87 +0x6d1
github.com/matrixorigin/matrixone/pkg/sql/plan2.buildTable({0x31ff0a0?, 0xc0091ceea0}, {0x3223c18, 0xc002beb4d0}, 0xc00f40b030, 0xc003f4b3a8)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_from.go:117 +0x46c
github.com/matrixorigin/matrixone/pkg/sql/plan2.buildFrom({0xc00bc73d20, 0x1, 0xfe96b2?}, {0x3223c18, 0xc002beb4d0}, 0xc00f40b030, 0xc003f4af18?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_from.go:28 +0x95
github.com/matrixorigin/matrixone/pkg/sql/plan2.buildSelectClause(0xc0091cf560, {0x3223c18, 0xc002beb4d0}, 0xc00f40b030, 0x3c1e60a?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_select.go:332 +0x7a
github.com/matrixorigin/matrixone/pkg/sql/plan2.buildSelect(0xc0112c19f0, {0x3223c18, 0xc002beb4d0}, 0xc00f40b030, 0xc003f4b3a8)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_select.go:39 +0x125
github.com/matrixorigin/matrixone/pkg/sql/plan2.buildUpdate(0xc0113b4a00, {0x3223c18, 0xc002beb4d0})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build_update.go:46 +0x390
github.com/matrixorigin/matrixone/pkg/sql/plan2.BuildPlan({0x3223c18?, 0xc002beb4d0?}, {0x3208e28?, 0xc0113b4a00?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/build.go:47 +0x426
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0xc0105d9050, {0x1f?, 0x0?}, 0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:1552 +0x51
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc00322a230, {0xc0036cf110, 0x2d})
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:1909 +0x1bd6
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc00322a230, 0xc0031ea280)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:2178 +0x79b
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc00039bce0)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:106 +0x264
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:158 +0x1e5
```

### Expected Behavior

no panic, just report error

**Comment by yingfeng** [comment]
Abandoned due to tae only for 0.5
