### ISSUE TITLE
[Bug]: corruption of tae task worker accidentally

### ISSUE THREAD

**Issue by yingfeng** [matrixorigin/matrixone#2918]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):﻿﻿7f4e00fb5a38cf8b78b331d4070250a3771bdc87
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Corrupt during bvt workflow

```
{"level":"DEBUG","time":"2022/06/10 12:23:10.744124 +0000","caller":"db/gcop.go:62","msg":"[GCSEG] | [Appendable]SEGMENT[<0:1331-1292-0-0-0>] | Started"}
{"level":"DEBUG","time":"2022/06/10 12:23:10.744131 +0000","caller":"db/gcop.go:36","msg":"[GCBLK] | [Appendable]BLOCK[<0:1331-1292-1292-0-0>] | Started"}
{"level":"INFO","time":"2022/06/10 12:23:10.744139 +0000","caller":"tables/node.go:209","msg":"[TS=3468] Unloading block <0:1331-1292-1292-0-0>"}
{"level":"INFO","time":"2022/06/10 12:23:10.744151 +0000","caller":"tables/blocktasks.go:196","msg":"FLUSH ABLK | [[Appendable]BLOCK[Op=Create][ID=1292][3468=>0]<Inde
x[1239:1/3]>] | CANCELLED | (Stale Request: Already Compacted)"}
{"level":"INFO","time":"2022/06/10 12:23:10.744163 +0000","caller":"segmentio/colblk.go:180","msg":"Destroying Block 1292 Col @ TS 0"}
{"level":"INFO","time":"2022/06/10 12:23:10.744178 +0000","caller":"db/gcop.go:39","msg":"[GCBLK] | [Appendable]BLOCK[<0:1331-1292-1292-0-0>] | Removed"}
{"level":"INFO","time":"2022/06/10 12:23:10.744186 +0000","caller":"db/gcop.go:67","msg":"[GCSEG] | [Appendable]SEGMENT[<0:1331-1292-0-0-0>] | BLKS=[<0:1331-1292-1292
-0-0>,] | Removed"}
{"level":"INFO","time":"2022/06/10 12:23:10.744194 +0000","caller":"db/gcop.go:95","msg":"[GCTABLE] | TABLE[Op=Create][ID=1331][3462=>0]<Index[1236:0/1]>[name=t12] |
Ended: <nil> | SEGS=[<0:1331-1292-0-0-0>,]"}
{"level":"INFO","time":"2022/06/10 12:23:10.744212 +0000","caller":"db/gcop.go:118","msg":"[GCDB] | DB[Op=SoftDelete][ID=1030][3063=>3596]<Index[1289:0/1]>[name=doubl
e] | Ended: <nil> | TABLES=[<0:1344-0-0-0-0>,<0:1343-0-0-0-0>,<0:1342-0-0-0-0>,<0:1341-0-0-0-0>,<0:1340-0-0-0-0>,<0:1339-0-0-0-0>,<0:1338-0-0-0-0>,<0:1337-0-0-0-0>,<0
:1336-0-0-0-0>,<0:1335-0-0-0-0>,<0:1331-0-0-0-0>,]"}
panic: runtime error: index out of range [408] with length 64

goroutine 192 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*BitmapAllocator).Allocate(0xc01c7dbf80, 0x200)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go:250 +0x3d9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Log).Append(0xc0031e68a0, 0xc037578940)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/log.go:270 +0x54c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Log).RemoveInode(0xc0031e68a0, 0xc037578940)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/log.go:202 +0x2a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).ReleaseFile(0xc037557030, 0xc037578940)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/driver.go:256 +0x3f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*columnBlock).Destroy(0xc01fb6a960)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/colblk.go:190 +0x1a5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*columnBlock).close(0xc03928ae70?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/colblk.go:176 +0x19
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.(*RefHelper).Unref(0xc0137c8300?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/common/refs.go:50 +0x36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*blockFile).Destroy(0xc0033fc060)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/block.go:185 +0xe5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).Destroy(0x2ea62de?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tables/block.go:202 +0x16f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*BlockEntry).DestroyData(...)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/catalog/block.go:212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcBlockClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:46 +0xe4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcSegmentClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:75 +0x250
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcTableClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:102 +0x23c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcDatabaseClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:124 +0x1f0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*FnTask).Execute(0xc0004e4b40?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/types.go:99 +0x1b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc011601ad0)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x6f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc000284380, {0x7f77f807a620, 0xc0a4699050})
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/worker/worker.go:214 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/worker/worker.go:144 +0xad
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/worker/worker.go:136 +0xb6
(END)
```
Overall logs [here](https://github.com/matrixorigin/matrixone/files/8879054/mo-server.log.zip)

**Comment by yingfeng** [comment]
New corruption @LeftHandCold :


Environment:

```
- Version or commit-id (e.g. v0.1.0 or 8b23a93):﻿﻿712dd213f5acec87722854da521b8c4f023ecea0
```

Panic Information:

```
panic: remove ^@^@^@^@^@^@^@^@e/1045.seg: invalid argument

goroutine 203 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Destroy(0xc0096cbce0)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/driver.go:176 +0x149
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFile).Destroy(0xc00979d320)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/segment.go:285 +0x18c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFile).close(0xc006c98a20?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/dataio/segmentio/segment.go:272 +0x19
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.(*RefHelper).Unref(0xc006c98a20?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/common/refs.go:50 +0x36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataSegment).Destory(0xc06f28b680?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tables/segment.go:60 +0x4f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*SegmentEntry).DestroyData(...)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/catalog/segment.go:388
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcSegmentClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:81 +0x2bc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcTableClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:102 +0x23c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcDatabaseClosure.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/gcop.go:124 +0x1f0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*FnTask).Execute(0xc0002ce8a0?)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/types.go:122 +0x1b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc0347d1a40)
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x6f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc000215810, {0x7fe73436bd40, 0xc06e695160})
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/worker/worker.go:214 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start.func1()
        /home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/worker/worker.go:144 +0xad
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start
```

**Comment by LeftHandCold** [comment]
Same bug as #3484
