### ISSUE TITLE
[Bug]: error happens when select UNIX_TIMESTAMP(datetime) DIV 30 * 30 from ...

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#3018]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> use system_metrics;
mysql> SELECT UNIX_TIMESTAMP(collecttime) DIV 30 * 30  FROM sys_cpu_combined_percent;
ERROR 1105 (HY000): Internal error: panic runtime error: index out of range [1] with length 1: goroutine 2440 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x5f64ea0?, 0xc00c016000})
        /Users/aptend/code/matrixone/pkg/common/moerr/error.go:85 +0x53
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
        /Users/aptend/code/matrixone/pkg/vm/overload/run.go:50 +0x31
panic({0x5f64ea0, 0xc00c016000})
        /usr/local/go/src/run

### Expected Behavior

no errors

**Comment by aptend** [comment]
solved
