### ISSUE TITLE
[Bug]: Data truncation failed in datetime type

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3362]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 ( a int not null default 1, big datetime(4) primary key);
insert into t1 (big) values ('20220103'),('2022-01-01'),('2022-01-01 00:00:01'),('2022-01-02 00:00.00.000050');
Incorrect DATETIME value: '2022-01-02 00:00.00.000050' for column 'big' at row 3

**Comment by bbbearxyz** [comment]
this is '2022-01-02 00:00.00.000050' format wrong, I already change to '2022-01-02 00:00:00.000050'

**Comment by aressu1985** [comment]
issue tag did not be removed

[sudong@mo-srv-128 matrixone]$ grep -r "#3362" test/
test/cases/dtype/datetime.test:-- @bvt:issue#3362
test/cases/dtype/timestamp.test:-- @bvt:issue#3362

**Comment by domingozhang** [comment]
when

**Comment by domingozhang** [comment]
when inputing the wrong format, the error message is abnormal.

mysql> insert into t1 (big) values ('20220103'),('2022-01-01'),('2022-01-01 00:00:01'),('2022-01-02 00:00.00.000050');
ERROR 1105 (HY000): Internal error: panic runtime error: index out of range [2] with length 2: goroutine 79188 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x3129840?, 0xc04e15eaf8})
	/home/sudong/matrixone/pkg/common/moerr/error.go:103 +0x53
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:2350 +0x45
panic({0x3129840, 0xc04e

**Comment by bbbearxyz** [comment]
I fix the issue by pr #3797
