### ISSUE TITLE
[Bug]: panic of operator.EqGeneral

### ISSUE THREAD

**Issue by yingfeng** [matrixorigin/matrixone#3369]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f61b51cf48af4226fd4afba26f03e8817f382654
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic1:
```
[ERROR]
[SCRIPT   FILE]: cases/function/func_if.test
[ROW    NUMBER]: 76
[SQL STATEMENT]: SELECT a FROM t1 WHERE a IN(1, (SELECT IF(1=0,1,2/1)));
[EXPECT RESULT]:
a
1
[ACTUAL RESULT]:
Internal error: panic unexpected parameter types were received: goroutine 7261 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2c36a20?, 0x335dba0})
	/home/runner/work/matrixone/matrixone/head/pkg/common/moerr/error.go:91 +0x53
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
	/home/runner/work/matrixone/matrixone/head/pkg/vm/overload/run.go:50 +0x31
panic({0x2c36a20, 0x335dba0})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
github.com/matrixorigin/matrixone/pkg/container/vector.MustTCols[...](...)
	/home/runner/work/matrixone/matrixone/head/pkg/container/vector/tools.go:38
github.com/matrixorigin/matrixone/pkg/sql/plan2/function/operator.EqGeneral[...]({0xc02ba14860?, 0x2?, 0x2?}, 0x30a4eb0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/function/operator/eq.go:108 +0x525
github.com/matrixorigin/matrixone/pkg/sql/plan2/function.glob..func173({0xc02ba14860?, 0x0?, 0x0?}, 0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/function/operators.go:567 +0x31
github.com/matrixorigin/matrixone/pkg/sql/plan2/function.Function.VecFn({0x9, 0x0, 0x8, 0x5, {0xc00019be4c, 0x2, 0x2}, 0xa, 0x30a45e8, 0x30a4ca0, ...}, ...)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/function/function.go:139 +0x2b
github.com/matrixorigin/matrixone/pkg/sql/colexec2.EvalExpr(0xc048b99860, 0xc03bbe7c30, 0xc0497cb320?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec2/expr_eval.go:156 +0x158b
github.com/matrixorigin/matrixone/pkg/sql/colexec2.EvalExpr(0xc048b99860, 0xc03bbe7c30, 0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec2/expr_eval.go:126 +0x1425
github.com/matrixorigin/matrixone/pkg/sql/colexec2/restrict.Call(0xc03bbe7c30, {0x2bce1e0?, 0xc02785aa10?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec2/restrict/restrict.go:46 +0xa7
github.com/matrixorigin/matrixone/pkg/vm/overload.Run({0xc04979e780?, 0x5, 0x7f3bb4fc1ca0?}, 0x40?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/overload/run.go:54 +0xee
github.com/matrixorigin/matrixone/pkg/vm/pipeline2.(*Pipeline).MergeRun(0xc02bf15c30, 0xc03bbe7c30)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/pipeline2/pipeline.go:134 +0x1af
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun(0xc02992d0e0, {0x338adc0?, 0xc0000101d0})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:355 +0x574
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).DispatchRun(0xc02992d0e0, {0x338adc0, 0xc0000101d0})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:417 +0x8d4
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).ParallelRun(0x2?, {0x338adc0?, 0xc0000101d0?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:430 +0x1af
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).RemoteRun(0xc02992c960?, {0x338adc0?, 0xc0000101d0?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:422 +0x25
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun.func3(0xc0007ddfa0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:342 +0x79
created by github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:337 +0x4ed

```

panic2(similar with panic1):

```
[ERROR]
[SCRIPT   FILE]: cases/function/func_if.test
[ROW    NUMBER]: 78
[SQL STATEMENT]: SELECT a FROM t1 WHERE a IN(1, (SELECT IF(1=0,1,2/1)));
[EXPECT RESULT]:
a
1
2
[ACTUAL RESULT]:
Internal error: panic unexpected parameter types were received: goroutine 7267 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2c36a20?, 0x335dba0})
	/home/runner/work/matrixone/matrixone/head/pkg/common/moerr/error.go:91 +0x53
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
	/home/runner/work/matrixone/matrixone/head/pkg/vm/overload/run.go:50 +0x31
panic({0x2c36a20, 0x335dba0})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
github.com/matrixorigin/matrixone/pkg/container/vector.MustTCols[...](...)
	/home/runner/work/matrixone/matrixone/head/pkg/container/vector/tools.go:38
github.com/matrixorigin/matrixone/pkg/sql/plan2/function/operator.EqGeneral[...]({0xc02ba14bf0?, 0x2?, 0x2?}, 0x30a4eb0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/function/operator/eq.go:108 +0x525
github.com/matrixorigin/matrixone/pkg/sql/plan2/function.glob..func173({0xc02ba14bf0?, 0x0?, 0x0?}, 0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/function/operators.go:567 +0x31
github.com/matrixorigin/matrixone/pkg/sql/plan2/function.Function.VecFn({0x9, 0x0, 0x8, 0x5, {0xc00019be4c, 0x2, 0x2}, 0xa, 0x30a45e8, 0x30a4ca0, ...}, ...)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/plan2/function/function.go:139 +0x2b
github.com/matrixorigin/matrixone/pkg/sql/colexec2.EvalExpr(0xc048b99ef0, 0xc03b9a7970, 0xc049705d40?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec2/expr_eval.go:156 +0x158b
github.com/matrixorigin/matrixone/pkg/sql/colexec2.EvalExpr(0xc048b99ef0, 0xc03b9a7970, 0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec2/expr_eval.go:126 +0x1425
github.com/matrixorigin/matrixone/pkg/sql/colexec2/restrict.Call(0xc03b9a7970, {0x2bce1e0?, 0xc02949a2e0?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec2/restrict/restrict.go:46 +0xa7
github.com/matrixorigin/matrixone/pkg/vm/overload.Run({0xc048dc5800?, 0x5, 0x7f3bb4b40ac8?}, 0x40?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/overload/run.go:54 +0xee
github.com/matrixorigin/matrixone/pkg/vm/pipeline2.(*Pipeline).MergeRun(0xc02bf15c30, 0xc03b9a7970)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/pipeline2/pipeline.go:134 +0x1af
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun(0xc02a0ec280, {0x338adc0?, 0xc0000101d0})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:355 +0x574
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).DispatchRun(0xc02a0ec280, {0x338adc0, 0xc0000101d0})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:417 +0x8d4
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).ParallelRun(0x2?, {0x338adc0?, 0xc0000101d0?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:430 +0x1af
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).RemoteRun(0xc02992c8c0?, {0x338adc0?, 0xc0000101d0?})
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:422 +0x25
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun.func3(0xc0007da7b8?)
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:342 +0x79
created by github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile2/scope.go:337 +0x4ed
```

**Comment by yingfeng** [comment]
duplicate with part of #3391
