### ISSUE TITLE
[Bug]: panic when write data into `mo_catalog`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#3546]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 08db8ed16508874079bc7c173745ab348a1d8242
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic message received by client:
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/77312370/176467571-2ef85e11-27dd-4a0e-893e-8d9056cec673.png">

error log in server side:
```
{"level":"ERROR","time":"2022/06/29 22:05:40.136250 +0800","caller":"logutil/api.go:63","msg":"routine execute request failed. error:Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 2046 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x68\ngithub.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x104419480?, 0x10593e980})\n\t/Users/maomao/tmp/0628/matrixone/pkg/common/moerr/error.go:103 +0x50\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/mysql_cmd_executor.go:2351 +0x40\npanic({0x104419480, 0x10593e980})\n\t/usr/local/go/src/runtime/panic.go:838 +0x204\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).DoDedup(0x14004155180, {0x104752ea8, 0x14001738410}, 0x0)\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:568 +0x220\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).DoBatchDedup(0x14004155180, {0x14000eb75f8?, 0x1, 0x1})\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:630 +0x1cc\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0x14004155180, 0x140047c5980)\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:336 +0x8c\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0x14004891900?, 0x140049f2f00?, 0x103df8dcb?)\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:106 +0x54\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0x14000eb76b8?, 0x10373ffe0?, 0x5?, 0x104752ea8?)\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:131 +0x8c\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0x14004ad47e0, 0x103df8dcb?)\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:162 +0x7c\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0x140049f2e40, 0x14000eb7878?, 0x140008a25a0, {0x1400051a408?, 0x14004690b58?, 0x8?})\n\t/Users/maomao/tmp/0628/matrixone/pkg/vm/engine/tae/moengine/relation.go:147 +0x2c4\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleInsertValues(0x14004b35db0, 0x1f?, 0x0?)\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/insert.go:51 +0x144\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0x14004b35db0, {0x140005f63c0, 0x3a})\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/mysql_cmd_executor.go:2009 +0x1578\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x14004b35db0, 0x140005a3aa0)\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/mysql_cmd_executor.go:2403 +0x628\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x140048e4540)\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/routine.go:106 +0x1d4\ncreated by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/routine.go:158 +0x1cc\n \n","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/maomao/tmp/0628/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/maomao/tmp/0628/matrixone/pkg/frontend/routine.go:107"}
```

### Expected Behavior

depends on our design

### Steps to Reproduce

```Markdown
1. use mo_catalog;
2. insert into mo_tables values('a','a','p','r','','todosql');
```

**Comment by aressu1985** [comment]
fixed:fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

mysql> insert into mo_tables values('a','a','p','r','','test','7','8','2022-11-10','fda','fdasf','fdsa','fdsafd','');
ERROR 20101 (HY000): internal error: do not have privilege to execute the statement
mysql>
