### ISSUE TITLE
[Bug]: panic runtime error when explaining

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3829]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t1;
create table t1 (spID int,userID int,score smallint);
insert into t1 values (1,1,1);
insert into t1 values (2,2,2);
insert into t1 values (2,1,4);
insert into t1 values (3,3,3);
insert into t1 values (1,1,5);
insert into t1 values (4,6,10);
insert into t1 values (5,11,99);
select userID,MAX(score) max_score from t1 where userID <2 || userID > 3 group by userID order by max_score;
+--------+-----------+
| userid | max_score |
+--------+-----------+
|      1 |         5 |
|      6 |        10 |
|     11 |        99 |
+--------+-----------+

explain select userID,MAX(score) max_score from t1 where userID <2 || userID > 3 group by userID order by max_score;
ERROR 1105 (HY000): Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 125524 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2c55260?, 0x453c2d0})
	/home/sudong/matrixone/pkg/common/moerr/error.go:103 +0x53
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1938 +0x45
panic({0x2c55

**Comment by domingozhang** [comment]
same issue as following

err: sql:explain select max(ti),min(si),avg(fl) from (select * from t1) sub where id < 4 || id > 5;: run "explain select max(ti),min(si),avg(fl) from (select * from t1) sub where id < 4 || id > 5;" at line 100 err Error 1105: Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 139977 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2c55260?, 0x453c2d0})
	/home/sudong/matrixone/pkg/common/moerr/error.go:103 +0x53
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1938 +0x45
panic({0x2c55260, 0x453c2d0})
	/usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.funcExprExplain(0xc021afda28, 0x0, 0xc0094853e8?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_expr.go:162 +0x5e8
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.describeExpr(0x6a?, 0x37e8c3b?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_expr.go:58 +0x8e
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.(*NodeDescribeImpl).GetFilterConditionInfo(0xc009485540?, 0xc0094858f0)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_node.go:341 +0x1b2
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.(*NodeDescribeImpl).GetExtraInfo(0xc009485618, 0xc013ff6aa0?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_node.go:267 +0x4c5
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.explainStep(0x1?, 0xc009485850, 0xc0094858f0)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_query.go:101 +0x272
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.traversalPlan(0xc014aaeb00, {0xc01b47f840?, 0x4, 0x4}, 0xc009485850, 0x7?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_query.go:120 +0x54
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.traversalPlan(0xc014aaef20, {0xc01b47f840?, 0x4, 0x4}, 0xc009485850, 0x1?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_query.go:132 +0x185
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.traversalPlan(0xc014aaf340, {0xc01b47f840?, 0x4, 0x4}, 0xc009485850, 0xc00000e4e0?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_query.go:132 +0x185
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.traversalPlan(0xc014aaf4a0, {0xc01b47f840?, 0x4, 0x4}, 0xc009485850, 0x1?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_query.go:132 +0x185
github.com/matrixorigin/matrixone/pkg/sql/plan2/explain.(*ExplainQueryImpl).ExplainPlan(0x32a1f30?, 0xc009485a08, 0x327eda0?)
	/home/sudong/matrixone/pkg/sql/plan2/explain/explain_query.go:46 +0x165
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleExplainStmt(0xc01593fd10, 0x1f?)
	/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1199 +0x169
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc01593fd10, {0xc011c19380, 0x5a})
	/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1674 +0x126b
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc01593fd10, 0xc01b47ec60)
	/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1982 +0x75b
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc00f77d200)
	/home/sudong/matrixone/pkg/frontend/routine.go:106 +0x237
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/home/sudong/matrixone/pkg/frontend/routine.go:158 +0x1e5
