### ISSUE TITLE
[Bug]: the txn illegal state when excute bvt test long time

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3843]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022-07-10 14:51:02 INFO  Executor:36 - Now start to run the file[/home/sudong/matrixone/test/cases/benchmark/tpch/01_DDL/01_create_table.sql]....................................................
java.sql.SQLException: the txn is in the illegal state and needed to be cleaned before using again
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.mo.db.ConnectionManager.<clinit>(ConnectionManager.java:25)
	at io.mo.db.Executor.run(Executor.java:37)
	at io.mo.Tester.run(Tester.java:158)
	at io.mo.Tester.run(Tester.java:176)
	at io.mo.Tester.run(Tester.java:176)
	at io.mo.Tester.run(Tester.java:176)
	at io.mo.Tester.run(Tester.java:176)
	at io.mo.Tester.main(Tester.java:114)
2022-07-10 14:51:03 ERROR Executor:46 - The mo-tester can not get valid conneciton from mo,will wait 30 seconds,and retry one time ...

n\t/home/sudong/matrixone/pkg/util/metric/metric_collector.go:216"}
{"level":"ERROR","time":"2022/07/10 14:54:10.081946 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/home/sudong/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1467\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1794\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*internalExecutor).Exec\n\t/home/sudong/matrixone/pkg/frontend/internal_executor.go:60\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/home/sudong/matrixone/pkg/util/metric/metric_collector.go:215"}
{"level":"ERROR","time":"2022/07/10 14:54:10.081989 +0800","caller":"logutil/api.go:63","msg":"[Metric] insert error. sql: insert into system_metrics.sql_latency_seconds values (\"2022-07-10 06:53:53\", 0.000147,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000130,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000109,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000102,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000099,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000098,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000099,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000105,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:54\", 0.000145,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-10 06:53:55\", 0.000154,0,\"monolithic\",\"1\",\"insert\"); err: the txn is in the illegal state and needed to be cleaned before using again","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/home/sudong/matrixone/pkg/util/metric/metric_collector.go:216"}

**Comment by daviszhen** [comment]
sudong provided the related server log when the issue happened.
I think tae txn was wrong when issue happened. So the frontend reported the error.
[server.log.gz](https://github.com/matrixorigin/matrixone/files/9081124/server.log.gz)

**Comment by daviszhen** [comment]
In pr #3948 
We remove the error "clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again".
We replace it by "start tae txn error:XXX" or "commit tae txn error:XXX" or "rollback tae txn error:XXX" based on the situation when the error happens.

**Comment by aressu1985** [comment]
fixed
