### ISSUE TITLE
[Bug]: panic: remove store/tae/1031.seg: no such file or directory

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3947]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2022/07/13 17:00:19.949387 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=Create][ID=1149][4828=>0]<Index[2046:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949413 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1150][4842=>4849]<Index[2053:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949430 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1151][4851=>4856]<Index[2056:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949449 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1152][4858=>4863]<Index[2059:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949466 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1153][4865=>4868]<Index[2061:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949483 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1154][4870=>4877]<Index[2064:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949501 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1155][4879=>4888]<Index[2067:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949518 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1156][4890=>4901]<Index[2073:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949535 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1157][4904=>4923]<Index[2081:0/1]>[name=t1]"}
{"level":"INFO","time":"2022/07/13 17:00:19.949552 +0800","caller":"db/scanner.go:167","msg":"StopRecurScanTable: TABLE[Op=SoftDelete][ID=1158][4906=>4925]<Index[2082:0/1]>[name=t2]"}
panic: remove store/tae/1031.seg: no such file or directory

goroutine 104 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Destroy(0x404fdff780)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:196 +0x260
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFile).Destroy(0x406a9d6b40)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:285 +0x1c0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFile).close(0x4016747040?)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:272 +0x20
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.(*RefHelper).Unref(0x400b273b60?)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/common/refs.go:50 +0x6c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataSegment).Destory(0x4016747100)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/tables/segment.go:60 +0xa0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*SegmentEntry).DestroyData(...)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/catalog/segment.go:387
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcSegmentClosure.func1()
        /mnt/disk2/matrixone/pkg/vm/engine/tae/db/gcop.go:81 +0x218
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcTableClosure.func1()
        /mnt/disk2/matrixone/pkg/vm/engine/tae/db/gcop.go:102 +0x1b0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcDatabaseClosure.func1()
        /mnt/disk2/matrixone/pkg/vm/engine/tae/db/gcop.go:124 +0x180
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*FnTask).Execute(0x4069464f8c?)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/tasks/types.go:122 +0x28
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0x40f3a7bc00)
        /mnt/disk2/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x8c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0x400030a2a0, {0xfffe47634ca8, 0x4044e73d00})
        /mnt/disk2/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:214 +0x34
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start.func1()
        /mnt/disk2/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:144 +0xac
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start
        /mnt/disk2/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:136 +0xb8

**Comment by LeftHandCold** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/14086886/178764766-5990d915-614e-4392-bace-dc9c7676bd65.png">
There is only one delete record in the log, so the file has already been deleted before the mo-server deletes it.

**Comment by XuPeng-SH** [comment]
Cannot reproduce.
Stability-related problems, solve it @ 0.6.

**Comment by LeftHandCold** [comment]
The layout has been modified, and 0.6 will no longer have this bug

**Comment by aressu1985** [comment]
it is a problem of stability test, and I trace this type of issue every daoy , when stability is OK , I will process all of these issues.

**Comment by aressu1985** [comment]
wait for testing

**Comment by aressu1985** [comment]
fixed
