### ISSUE TITLE
[Bug]: dnservice.Service do not support start repeatedly

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#4342]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 833fdf3ebb0cb3fd91250e2c478422c68c8eb084
- Hardware parameters: CI Environment
- OS type: MaxOS | Linux
- Others:
```

### Actual Behavior

If start `dnservice.Service` instance repeatedly, it would panic with error `close of closed channel`, detailed information is as follow:
```bash
panic: close of closed channel

goroutine 1154 [running]:
github.com/fagongzi/goetty/v2.(*server).doStart.func1()
   vendor/github.com/fagongzi/goetty/v2/application.go:249 +0x50
github.com/fagongzi/goetty/v2.(*server).doStart(0x14001a745a0)
   vendor/github.com/fagongzi/goetty/v2/application.go:272 +0x588
created by github.com/fagongzi/goetty/v2.(*server).Start
    vendor/github.com/fagongzi/goetty/v2/application.go:189 +0xc0
exit status 2
FAIL    github.com/matrixorigin/matrixone/pkg/tests/service 0.649s
```

### Expected Behavior

`dnservice.Service` could start repeatedly.

**Comment by cnutshell** [comment]
[CI Running Link](https://github.com/matrixorigin/matrixone/runs/7644322613)
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/20291742/182517592-dc2c95ff-7dc7-42dd-9307-8a11d36c304a.png">

**Comment by cnutshell** [comment]
After reconfirmation with @lni, the `dnservice` or `logservice` are limited to start once, and close once.

Repeated starting/closing wouldn't be supported.
