### ISSUE TITLE
[Bug]: `logservice.Service` do not support start repeatedly

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#4347]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3610c79ff2181a
- Hardware parameters: CI Environment
- OS type: MaxOS or Linux
- Others:
```

### Actual Behavior

It would panic with `NodeHost.Stop called twice` when starting/closing `logservice.Service` repeatedly:
```bash
panic: NodeHost.Stop called twice [recovered]
        panic: NodeHost.Stop called twice

goroutine 34 [running]:
testing.tRunner.func1.2({0x103485460, 0x1035fbd80})
        /usr/local/go/src/testing/testing.go:1389 +0x1c8
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1392 +0x384
panic({0x103485460, 0x1035fbd80})
        /usr/local/go/src/runtime/panic.go:838 +0x204
github.com/lni/dragonboat/v4.(*NodeHost).Close(0x14000330a80)
        matrixone/vendor/github.com/lni/dragonboat/v4/nodehost.go:390 +0x980
github.com/matrixorigin/matrixone/pkg/logservice.(*store).close(0x1400020e400)
        matrixone/pkg/logservice/store.go:159 +0x48
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).Close(0x14000ffe9c0)
       matrixone/pkg/logservice/service.go:146 +0xa0
github.com/matrixorigin/matrixone/pkg/logservice.(*WrappedService).Close(...)
        matrixone/pkg/logservice/service_wrap.go:39
github.com/matrixorigin/matrixone/pkg/tests/service.(*logService).Close(0x140001bf3e0)
        matrixone/pkg/tests/service/logservice.go:94 +0xcc
github.com/matrixorigin/matrixone/pkg/tests/service.TestLogServiceStart(0x29?)
        matrixone/pkg/tests/service/service_test.go:233 +0x33c
testing.tRunner(0x140001031e0, 0x1035f9430)
        /usr/local/go/src/testing/testing.go:1439 +0x110
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x300
exit status 2
FAIL    github.com/matrixorigin/matrixone/pkg/tests/service     1.005s
```

**Comment by cnutshell** [comment]
[CI Running Link](https://github.com/matrixorigin/matrixone/runs/7646271442)
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/20291742/182543246-1822fd9f-d3b9-4421-8c78-edb9d10285bd.png">

**Comment by cnutshell** [comment]
After reconfirmation with @lni, the `dnservice` or `logservice` are limited to start once, and to close once.

Repeated starting/closing wouldn't be supported.
