### ISSUE TITLE
[Bug]: panic runtime error: slice bounds out of range when loading data

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4617]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

load data infile '/var/root/mo_columns.tbl' into table columns  fields terminated by ',' lines terminated by '\n';

ERROR 1105 (HY000): panic runtime error: slice bounds out of range [:2] with capacity 0: goroutine 20716 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x533dca0?, 0xc005be9c80})
	/var/root/matrixone/pkg/common/moerr/error.go:235 +0x65
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
	/var/root/matrixone/pkg/vm/vm.go:57 +0x31
panic({0x533dca0, 0xc005be9c80})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/matri

**Comment by domingozhang** [comment]
fixed
