### ISSUE TITLE
[Bug]: jdbc mo-test check select @@autocommit; default value. execute  abnormal.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4626]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

jdbc error:

check select @@autocommit; default value is on.

execute abnormal;

Error: Exception in thread "main" java.lang.NumberFormatException: For input string: "on"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at io.mo.result.RSCell.equals(RSCell.java:62)
	at io.mo.result.RSRow.equals(RSRow.java:57)
	at io.mo.result.RSSet.equals(RSSet.java:153)
	at io.mo.result.StmtResult.equals(StmtResult.java:76)
	at io.mo.cases.SqlCommand.checkResult(SqlCommand.java:152)
	at io.mo.db.Executor.run(Executor.java:110)
	at io.mo.Tester.run(Tester.java:139)
	at io.mo.Tester.run(Tester.java:148)
	at io.mo.Tester.run(Tester.java:148)
	at io.mo.Tester.main(Tester.java:94)
Error: Process completed with exit code 1.

**Comment by tianyahui-python** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/3352150837/jobs/5554097667

**Comment by qingxinhome** [comment]
The problem has been solved and PR has been merged. Now submit the test. @jianwan0214 @tianyahui-python

**Comment by tianyahui-python** [comment]
@qingxinhome distributed bvt tag no remove.
