### ISSUE TITLE
[Bug]: panic when sql with limit 0

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#4662]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> SELECT f1 FROM t1 ORDER BY 1 LIMIT 0;
ERROR 1105 (HY000): panic runtime error: index out of range [0] with length 0: goroutine 1486 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x103582660?, 0x14004cfdb00})
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/common/moerr/error.go:235 +0x5c
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/vm.go:57 +0x34
panic({0x103582660, 0x14004cfdb00})
	/usr/local/go/src

**Comment by aressu1985** [comment]
mysql> select * from t2 limit 0;
Empty set (0.03 sec)
