### ISSUE TITLE
[Bug]: Running tpch for a long time (about two hours), the update will fail a lot.

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#4745]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7a1d323a5e1da28c03133bb6a5d4861fd5d6ba5f
- Hardware parameters:
- OS type: centos
- Others:
```

### Actual Behavior

Running tpch for a long time (about two hours), the update will fail a lot, and mo will report the "panic allocBoolVec OOM" error

### Expected Behavior

{"level":"INFO","time":"2022/08/29 11:16:22.913257 +0800","caller":"operator/compare.go:48","msg":"error","span":{"TraceId":"00000000-0000-0000-0000-000000000000","SpanId":"0000000000000000"},"error":"panic allocBoolVec OOM: goroutine 15995367 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x1c7bb40?, 0x22fa270})\n\t/data/shenjiangwei/tae/matrixone/pkg/common/moerr/error.go:235 +0x65\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.allocateBoolVector(0x9b33, 0x1e400?)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:48 +0x13c\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.CompareOrdered({0xc140ad3a20?, 0x2?, 0x2?}, 0x17?, 0xc15b1098f8)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:76 +0x1b6\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.EqGeneral[...]({0xc140ad3a20?, 0xc01aa44000?, 0xc140ad3a20?}, 0xc0f9b2eb60?)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:87 +0x4a\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function.glob..func108({0xc140ad3a20?, 0x10?, 0x203038?}, 0x8?)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operators.go:819 +0x31\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function.Function.VecFn({0x7, 0x0, 0x0, 0x8, 0x5, {0xc0007ddc5e, 0x2, 0x2}, 0xa, 0x209cdc0, ...}, ...)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/function.go:150 +0x2b\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpr(0xc11e231000, 0xc13b557200, 0x7f66c0163200?)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/colexec/expr_eval.go:157 +0x1429\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.Call(0x0?, 0xc13b557200, {0x1c30d20?, 0xc0efde1d20})\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/colexec/restrict/restrict.go:50 +0x1b6\ngithub.com/matrixorigin/matrixone/pkg/vm.Run({0xc163ede080?, 0x4, 0x5?}, 0x5?)\n\t/data/shenjiangwei/tae/matrixone/pkg/vm/vm.go:61 +0xf6\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc15b109f28, {0x2321760, 0xc01ddadb00}, 0xc13b557200)\n\t/data/shenjiangwei/tae/matrixone/pkg/vm/pipeline/pipeline.go:76 +0x205\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc117828480?, 0xc11bf7e540?)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:59 +0xc8\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0xc0015c37a0?)\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:77 +0x75\ncreated by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun\n\t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:72 +0x18d\n","errorVerbose":"panic allocBoolVec OOM: goroutine 15995367 [running]:\n(1)\nWraps: (2)\n  -- stack trace:\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.allocateBoolVector\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:48\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.CompareOrdered\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:76\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.EqGeneral[...]\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:87\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function.glob..func108\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operators.go:819\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function.Function.VecFn\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/function.go:150\n  | github.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpr\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/colexec/expr_eval.go:157\n  | github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.Call\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/colexec/restrict/restrict.go:50\n  | github.com/matrixorigin/matrixone/pkg/vm.Run\n  | \t/data/shenjiangwei/tae/matrixone/pkg/vm/vm.go:61\n  | github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n  | \t/data/shenjiangwei/tae/matrixone/pkg/vm/pipeline/pipeline.go:76\n  | github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:59\n  | github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:77\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1571\nWraps: (3) panic allocBoolVec OOM: goroutine 15995367 [running]:\n  | runtime/debug.Stack()\n  | \t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\n  | github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x1c7bb40?, 0x22fa270})\n  | \t/data/shenjiangwei/tae/matrixone/pkg/common/moerr/error.go:235 +0x65\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.allocateBoolVector(0x9b33, 0x1e400?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:48 +0x13c\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.CompareOrdered({0xc140ad3a20?, 0x2?, 0x2?}, 0x17?, 0xc15b1098f8)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:76 +0x1b6\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function/operator.EqGeneral[...]({0xc140ad3a20?, 0xc01aa44000?, 0xc140ad3a20?}, 0xc0f9b2eb60?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operator/compare.go:87 +0x4a\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function.glob..func108({0xc140ad3a20?, 0x10?, 0x203038?}, 0x8?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/operators.go:819 +0x31\n  | github.com/matrixorigin/matrixone/pkg/sql/plan/function.Function.VecFn({0x7, 0x0, 0x0, 0x8, 0x5, {0xc0007ddc5e, 0x2, 0x2}, 0xa, 0x209cdc0, ...}, ...)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/plan/function/function.go:150 +0x2b\n  | github.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpr(0xc11e231000, 0xc13b557200, 0x7f66c0163200?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/colexec/expr_eval.go:157 +0x1429\n  | github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.Call(0x0?, 0xc13b557200, {0x1c30d20?, 0xc0efde1d20})\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/colexec/restrict/restrict.go:50 +0x1b6\n  | github.com/matrixorigin/matrixone/pkg/vm.Run({0xc163ede080?, 0x4, 0x5?}, 0x5?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/vm/vm.go:61 +0xf6\n  | github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc15b109f28, {0x2321760, 0xc01ddadb00}, 0xc13b557200)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/vm/pipeline/pipeline.go:76 +0x205\n  | github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc117828480?, 0xc11bf7e540?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:59 +0xc8\n  | github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0xc0015c37a0?)\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:77 +0x75\n  | created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun\n  | \t/data/shenjiangwei/tae/matrixone/pkg/sql/compile/scope.go:72 +0x18d\nError types: (1) *errors.withContext (2) *errors.withStack (3) *moerr.Error"}

### Additional information

<img width="912" alt="image" src="https://user-images.githubusercontent.com/14086886/187116695-67521f90-91f8-4388-98cc-91ec513fdba2.png">

**Comment by LeftHandCold** [comment]
The root cause was that I modified defaultQueueSize = 13107200
