### ISSUE TITLE
[Bug]: lsn is too small

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#4786]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

````
panic: lsn is too small

goroutine 30 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*DB).onReplayAppendCmd(0xc0002aa000, 0xc004ebc460, {0x241ca38, 0xc0006c59a0})
	/tmp/matrixone/pkg/vm/engine/tae/db/replay.go:298 +0x787
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayCmd(0xc0006c59a0, {0x2457da0?, 0xc004ebc460?}, 0x0)
	/tmp/matrixone/pkg/vm/engine/tae/db/replay.go:252 +0x5bf
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayCmd(0xc0006c59a0, {0x2457c80?, 0xc004e4e020?}, 0xc0066b6020)
	/tmp/matrixone/pkg/vm/engine/tae/db/replay.go:242 +0x647
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayEntry(0xc0006c59a0, 0x28c000?, 0x17a, {0xc004ec2000, 0x5754, 0x8000}, 0x18f?, {0x17a?, 0xc0007ed568?})
	/tmp/matrixone/pkg/vm/engine/tae/db/replay.go:211 +0x125
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).replayhandle.func1(0x1e040a0?, 0xc000283c20?, {0xc004ec2000, 0x5754, 0x8000}, 0x6010?, {0x1eeebc0?, 0xc004ebc050?})
	/tmp/matrixone/pkg/vm/engine/tae/wal/driver.go:89 +0xb1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).replayEntry(0xc000140160, 0xc0066c8040?, 0xc0006e6060)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/store/replay.go:75 +0x285
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).Replay.func1(0x1e04e80?)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/store/replay.go:23 +0x27
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*replayer).replayHandler(0xc0006e0210, 0xc000001900)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/replay.go:90 +0xd5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vFile).Replay(0xc0001460c0?, 0x49?)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vfile.go:247 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*rotateFile).Replay(0xc0001400b0, 0x18?)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/file.go:185 +0x145
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*baseStore).Replay(0xc0002ac300, 0xc0006e6078)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go:274 +0xc7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).Replay(0xc000140160, 0xc0006e6060)
	/tmp/matrixone/pkg/vm/engine/tae/logstore/store/replay.go:22 +0xaa
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).Replay(0xc000193880, 0x0?)
	/tmp/matrixone/pkg/vm/engine/tae/wal/driver.go:93 +0x37
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).Replay(0xc0006c59a0)
	/tmp/matrixone/pkg/vm/engine/tae/db/replay.go:106 +0x6d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*DB).Replay(0xc0002aa000, 0xc001ca0000)
	/tmp/matrixone/pkg/vm/engine/tae/db/db.go:102 +0x1d8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0xc00012e0a0, 0xb}, 0x0?)
	/tmp/matrixone/pkg/vm/engine/tae/db/open.go:79 +0x610
github.com/matrixorigin/matrixone/pkg/cnservice.initTAE({0x20fd2c9?, 0x503eb1?}, 0xc0000c4300)
	/tmp/matrixone/pkg/cnservice/tae.go:45 +0x18d
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).initEngine(0x20fd2c9?, {0xc0000c9200?, 0x0?}, {0x24317d0?, 0xc0001100c0?}, 0x41f1c7?)
	/tmp/matrixone/pkg/cnservice/server.go:147 +0x58
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).initMOServer(0xc001970000, {0x24317d0, 0xc0000c9200}, 0xc0000c4300)
	/tmp/matrixone/pkg/cnservice/server.go:128 +0x148
github.com/matrixorigin/matrixone/pkg/cnservice.NewService(0xc0001e8000, {0x24317d0, 0xc0000c9200}, {0x243c400?, 0xc000254900}, {0xc001869a48, 0x1, 0x20e570a?})
	/tmp/matrixone/pkg/cnservice/server.go:66 +0x25b
main.startCNService.func1({0x24317d0, 0xc0000c9200})
	/tmp/matrixone/cmd/mo-service/main.go:104 +0x21f
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/tmp/matrixone/pkg/common/stopper/stopper.go:257 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/tmp/matrixone/pkg/common/stopper/stopper.go:252 +0x12c


### Expected Behavior

_No response_

### Steps to Reproduce

```Markdown
load tpch 10GB
```


### Additional information

_No response_

**Comment by LeftHandCold** [comment]
0.6 uses logservice without this bug
