### ISSUE TITLE
[Bug]: MO crash and cannot reboot after an intensive write

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4799]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.5.1
- Hardware parameters: dev1
- OS type: CentOS 8.4
- Others:
```

### Actual Behavior

Write to MO with 20-50 terminals with a simple script running "tcpdump". 
Insert to MO with each line. 

```
def sh(command, print_msg=True):

    db = pymysql.connect(host='127.0.0.1',
                     port=6001,
                     user='dump',
                     password='111',
                     database='tcpdump')
    cursor = db.cursor()
    cursor.execute('insert into tcp values("helloworld")')

    print("mo connected")
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    lines = []
    for line in iter(p.stdout.readline, b''):
        line = line.rstrip().decode('utf8')
        if print_msg:
            cursor.execute('insert into tcp values(%s)', line)
            print(">>>", line)
        lines.append(line)
    return lines

sh("sudo tcpdump")
```

After several minutes, from 5-30 minutes, MO stopped without crash log. 
Client reports lost connection.

Trying to reboot MO will fail too. With an error log of :

```
{"level":"DEBUG","time":"2022/08/31 14:25:04.812462 +0800","caller":"logutil/internal.go:34","msg":"MO logger init, level=debug, log file="}
{"level":"INFO","time":"2022/08/31 14:25:04.812517 +0800","caller":"db-server/main.go:200","msg":"Shutdown The Server With Ctrl+C | Ctrl+\\."}
Initialize the TAE engine ...
{"level":"DEBUG","time":"2022/08/31 14:25:04.821345 +0800","caller":"worker/worker.go:131","msg":"PoolHandler Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.821402 +0800","caller":"worker/worker.go:131","msg":"gc Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.821502 +0800","caller":"worker/worker.go:131","msg":"[ckpworker-0] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.821610 +0800","caller":"worker/worker.go:131","msg":"[ckpworker-1] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.821718 +0800","caller":"worker/worker.go:131","msg":"[ckpworker-2] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.821823 +0800","caller":"worker/worker.go:131","msg":"[ckpworker-3] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.821935 +0800","caller":"worker/worker.go:131","msg":"[ioworker-0] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822050 +0800","caller":"worker/worker.go:131","msg":"[ioworker-1] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822158 +0800","caller":"worker/worker.go:131","msg":"[ioworker-2] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822264 +0800","caller":"worker/worker.go:131","msg":"[ioworker-3] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822371 +0800","caller":"worker/worker.go:131","msg":"[ioworker-4] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822482 +0800","caller":"worker/worker.go:131","msg":"[ioworker-5] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822588 +0800","caller":"worker/worker.go:131","msg":"[ioworker-6] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822694 +0800","caller":"worker/worker.go:131","msg":"[ioworker-7] Started"}
{"level":"DEBUG","time":"2022/08/31 14:25:04.822706 +0800","caller":"worker/worker.go:131","msg":"taskScheduler Started"}
{"level":"INFO","time":"2022/08/31 14:25:04.827010 +0800","caller":"catalog/database.go:218","msg":"[Catalog]","operation":"remove","operand":"TABLE[Op=SoftDelete][ID=1016][11567315=>11567429]<Index[5782873:0/1]>[name=tcp]"}
{"level":"DEBUG","time":"2022/08/31 14:25:27.812379 +0800","caller":"db-server/debug.go:163","msg":"runtime metrics","/gc/heap/allocs:bytes":8633160632,"/gc/heap/frees:bytes":2691418752,"/gc/heap/goal:bytes":6476045216,"/memory/classes/heap/free:bytes":0,"/memory/classes/heap/objects:bytes":5941741880,"/memory/classes/heap/released:bytes":6709248,"/memory/classes/heap/unused:bytes":48125640,"/memory/classes/total:bytes":6328452600,"/sched/goroutines:goroutines":116}
panic: wrong wal

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*replayer).replayHandler(0xc00015e500, {0x154a270?, 0xc00044be40}, {0x1514920?, 0xc0001160c0?})
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/logstore/store/replayer.go:255 +0x558
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*vFile).Replay(0xc00044be40, 0x54?, {0x151ede8?, 0x209a4d8?})
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/logstore/store/vfile.go:311 +0x5c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*rotateFile).Replay(0xc00014a000, 0xc0000061a0?, {0x151ede8, 0x209a4d8})
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/logstore/store/file.go:188 +0x2b9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).Replay(0xc0000e66c0, 0xc00229c160)
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/logstore/store/store.go:509 +0x1e8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).Replay(0x410887?, 0x203000?)
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/wal/driver.go:52 +0x22
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).Replay(0xc0022ce280)
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/db/replay.go:90 +0x6d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*DB).Replay(0xc0001ac0c0, 0xc000165840)
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/db/db.go:100 +0x14b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0xc00003f840, 0xb}, 0x0)
	/home/dengnan/0.5.1/matrixone/pkg/vm/engine/tae/db/open.go:79 +0x75c
main.initTae()
	/home/dengnan/0.5.1/matrixone/cmd/db-server/main.go:110 +0x9c
main.main()
	/home/dengnan/0.5.1/matrixone/cmd/db-server/main.go:212 +0x95f

### Expected Behavior

_No response_

### Steps to Reproduce

_No response_

### Additional information

_No response_

**Comment by dengn** [comment]
It only reboots successfully after removing the store directory.
