### ISSUE TITLE
[Bug]: mo return malform package exception when prepraredStmt execute executeBatch() method

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#4994]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

exception from jdbc is :
java.sql.SQLException: malform packet
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:634)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:414)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:387)
	at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:385)
	at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
	at java.lang.Thread.run(Thread.java:750)
Worker 001: ERROR: malform packet

the java code is :
stmtItem.executeBatch();

**Comment by aressu1985** [comment]
fixed
