### ISSUE TITLE
[Bug]: result is not correct for jdbc when prepareStatement run executeQuery mehtod

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5017]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

java.sql.SQLException: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:437)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
	at io.mo.jTPCCUtil.getConfig(jTPCCUtil.java:82)
	at io.mo.jTPCC.<init>(jTPCC.java:315)
	at io.mo.jTPCC.main(jTPCC.java:57)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:382)
	at com.mysql.cj.protocol.a.NativePacketPayload.readBytes(NativePacketPayload.java:507)
	at com.mysql.cj.protocol.a.BinaryRowFactory.extractNativeEncodedColumn(BinaryRowFactory.java:148)
	at com.mysql.cj.protocol.a.BinaryRowFactory.unpackBinaryResultSetRow(BinaryRowFactory.java:115)
	at com.mysql.cj.protocol.a.BinaryRowFactory.createFromMessage(BinaryRowFactory.java:75)
	at com.mysql.cj.protocol.a.BinaryRowFactory.createFromMessage(BinaryRowFactory.java:51)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:87)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1685)
	at com.mysql.cj.protocol.a.BinaryResultsetReader.read(BinaryResultsetReader.java:90)
	at com.mysql.cj.protocol.a.BinaryResultsetReader.read(BinaryResultsetReader.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1698)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1752)
	at com.mysql.cj.ServerPreparedQuery.readExecuteResult(ServerPreparedQuery.java:427)
	at com.mysql.cj.ServerPreparedQuery.serverExecute(ServerPreparedQuery.java:210)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:632)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:414)
	... 4 more

the java code is：
if (dbConn == null)
	{
	    dbConn = DriverManager.getConnection(db, dbProps);
	    stmtGetConfig = dbConn.prepareStatement(
		"SELECT cfg_value FROM bmsql_config " +
		" WHERE cfg_name = ?");
	}
	stmtGetConfig.setString(1, option);
	rs = stmtGetConfig.executeQuery();

**Comment by aressu1985** [comment]
fixed
