### ISSUE TITLE
[Bug]: panic: invalid markIndex 4, readIndex 4, writeIndex 21

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5060]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7290f95735ce218f279dc48b6dde0040a4fe3b37
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
panic: invalid markIndex 4, readIndex 4, writeIndex 21

goroutine 1209 [running]:
github.com/fagongzi/goetty/v2/buf.(*ByteBuf).SetMarkIndex(0xc002f5cb40, 0x0?)
        /opt/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220812142536-dfcb3d33cfdc/buf/buf.go:154 +0xd9
github.com/matrixorigin/matrixone/pkg/frontend.(*sqlCodec).Decode(0x2537e40?, 0xc002f5cb40)
        /workspace/matrixone/pkg/frontend/codec.go:55 +0xe8
github.com/fagongzi/goetty/v2.(*baseIO).readFromConn(0xc0045d1600, 0x0?)
        /opt/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220812142536-dfcb3d33cfdc/session.go:465 +0x117
github.com/fagongzi/goetty/v2.(*baseIO).Read(0xc0045d1600, {0x21e845c?})
        /opt/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220812142536-dfcb3d33cfdc/session.go:384 +0xaf
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc00080c5a0, {0x259f120, 0xc0045d1600})
        /opt/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220812142536-dfcb3d33cfdc/application.go:316 +0x22f
github.com/fagongzi/goetty/v2.(*server).doStart.func2()
        /opt/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220812142536-dfcb3d33cfdc/application.go:301 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart
        /opt/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220812142536-dfcb3d33cfdc/application.go:293 +0x4bb
```

### Steps to Reproduce

```Markdown
mo panic without query running
```

### Additional information

[mo.log](https://github.com/matrixorigin/matrixone/files/9582812/mo.log)

**Comment by zhangxu19830126** [comment]
@sukki37 fixed
