### ISSUE TITLE
[Bug]:   `ParallelRun` runtime panic

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5066]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): f654c361de555effafc9ea76e232aa619612770f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
panic: runtime error: index out of range [0] with length 0

goroutine 700391 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc02ef517c0, 0xc02ae8cf70)
 /home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:181 +0xb74
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0x0?, 0x0?)
 /home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:151 +0x37
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0x0?)
 /home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:90 +0xb8
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
 /home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:85 +0xb0f
```

### Steps to Reproduce

```Markdown
1. ./mo-service -cfg ./etc/cn-standalone-mem-engine-test.toml &>mo-service.log &
2.  ./run.sh -n -g -p ${mo_source_code}/test/cases -e isolation 2>&1
```

### Additional information

I've checked the full log （which can be downloaded at https://github.com/sukki37/matrixone/actions/runs/3071825667）, This error occurs during the following sql execution:
```
SELECT * FROM t1
WHERE EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1) AND
EXISTS (SELECT * FROM t1);
```

**Comment by nnsgmsone** [comment]
It looks like the engine is returning the wrong number of readers.

**Comment by sukki37** [comment]
this way of startup is outdated, close
