### ISSUE TITLE
[Bug]: panic when run tpcc payment txn,  operation is stmtPaymentUpdateDistrict

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5086]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

JAVA CODE:
stmtPaymentUpdateDistrict = dbConn.prepareStatement(
  "UPDATE bmsql_district " +
  "    SET d_ytd = d_ytd + ? " +
  "    WHERE d_w_id = ? AND d_id = ?");

stmt = db.stmtPaymentUpdateDistrict;
   stmt.setDouble(1, payment.h_amount);
   stmt.setInt(2, payment.w_id);
   stmt.setInt(3, payment.d_id);
   stmt.executeUpdate();

MO paninc:

2022-09-19 16:34:51 ERROR jTPCCTerminal:945 - panic interface conversion: interface {} is []float64, not []types.Decimal64: goroutine 3362 [running]:
runtime/debug.Stack()
 /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x102572ec0?, 0x140001c1470})
 /Users/sudong/Program/aressu1985/matrixone/pkg/common/moerr/error.go:230 +0x5c
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/vm.go:57 +0x34
panic({0x102572ec0, 0x140001c1470})
 /usr/local/go/src/runtime/panic.go:884 +0x204
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).extendData(0x140000118b8, {0x1028fc9a0, 0x140073dafa0?}, 0x0?, 0x1)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/containers/vecbase.go:103 +0x110
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*nullableVecImpl[...]).ExtendWithOffset(0x140000118c0, {0x1028fc9a0, 0x140073dafa0}, 0x0, 0xc0)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/containers/vecimpl.go:186 +0x138
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).ExtendWithOffset(0x1400112ef08?, {0x1028fc9a0?, 0x140073dafa0?}, 0x1400718d450?, 0x0?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/containers/vector.go:180 +0x40
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*insertNode).Append(0x14007987f10, 0x14007a75600, 0x0)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/node.go:361 +0x514
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).Append.func1()
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:211 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*Node).Expand(0x140076b9e40, 0xa4, 0x1400112f1b8)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/buffer/node.go:181 +0xd0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).Append(0x1400151ec80, 0x14007a75600)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:210 +0x184
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0x1400780ed20, 0x14007a75600)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:348 +0x130
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0x1400780eaa0?, 0x140001c12f0?, 0x14000513489?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121 +0x50
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0x1400112f318?, 0x101a81a64?, 0xa?, 0x1028fc5c8?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:184 +0x88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0x140011a1520, 0x14000513489?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:162 +0x78
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0x14006f2e5d0, {0x14002eb2070?, 0x1028a5da8?}, 0x1400151e300)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:54 +0x2b8
github.com/matrixorigin/matrixone/pkg/sql/colexec/update.Call(0x0?, 0x14001193040, {0x102425a00?, 0x140006b5a80})
 /Users/sudong/Program/aressu1985/matrixone/pkg/sql/colexec/update/update.go:116 +0x868
github.com/matrixorigin/matrixone/pkg/vm.Run({0x140011b62c0?, 0x2, 0x0?}, 0x12bc6d328?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/vm.go:61 +0xe8
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0x1400112f700, 0x14001193040)
 /Users/sudong/Program/aressu1985/matrixone/pkg/vm/pipeline/pipeline.go:147 +0x154
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0x14007763c20, 0x140011ac5b0)
 /Users/sudong/Program/aressu1985/matrixone/pkg/sql/compile/scope.go:111 +0x5e0
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Update(0x0?, 0x0?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/sql/compile/dml.go:60 +0x54
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0x140011ac5b0, 0x14006f2e2d0?)
 /Users/sudong/Program/aressu1985/matrixone/pkg/sql/compile/compile.go:129 +0x3e4
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0x14001988d20, {0x1028a5018?, 0x14006f2e1e0}, {0x140179b8820, 0x50})
 /Users/sudong/Program/aressu1985/matrixone/pkg/frontend/mysql_cmd_executor.go:2118 +0x2844
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x14001988d20, {0x1028a5018, 0x14006f2e1e0}, 0x140077691e0)
 /Users/sudong/Program/aressu1985/matrixone/pkg/frontend/mysql_cmd_executor.go:2306 +0xad0
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x14002e7c770, {0x1028a4f70?, 0x140071addc0?})
 /Users/sudong/Program/aressu1985/matrixone/pkg/frontend/routine.go:122 +0x290
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
 /Users/sudong/Program/aressu1985/matrixone/pkg/frontend/routine.go:179 +0x218

**Comment by aressu1985** [comment]
this panic has been fixed, bug still has problem, tracking it in issue#6099
