### ISSUE TITLE
[Bug]: panic while startup with metric

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#5122]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e08f768b3ebd3990077e4e047f5fdeb5c2210497
- Hardware parameters:
- OS type: 
- Others: etc/cn-standalone-test.toml
- dev: 1.14.248.236
- log: /workspace/matrixone/mo.log.1663604401
```

### Actual Behavior

```
{"level":"DEBUG","time":"2022/09/20 00:20:01.892701 +0800","caller":"logutil/internal.go:36","msg":"MO logger init, level=debug, log file="}
{"level":"DEBUG","time":"2022/09/20 00:20:01.892923 +0800","caller":"metric/metric.go:150","msg":"[Metric] register to prom register: descriptor Desc{fqName: \"process_max_fds\", help: \"Maximum number of open file descriptors.\", constLabels: {}, variableLabels: []} already exist\
s with the same fully-qualified name and const label values"}
panic: interface conversion: interface {} is nil, not *trace.SpanContext

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/util/trace.DefaultSpanContext(...)
        /workspace/matrixone/pkg/util/trace/trace.go:180
github.com/matrixorigin/matrixone/pkg/util/trace.ReportZap({0x242c060, 0xc000298d40}, {0xff, {0xc0c2438c7538f026, 0xaf2cfc, 0x35073a0}, {0x0, 0x0}, {0xc000030000, 0xee}, ...}, ...)
        /workspace/matrixone/pkg/util/trace/report_log.go:181 +0x5e5
github.com/matrixorigin/matrixone/pkg/logutil.(*TraceLogEncoder).EncodeEntry(0xc0000a41e0, {0xff, {0xc0c2438c7538f026, 0xaf2cfc, 0x35073a0}, {0x0, 0x0}, {0xc000030000, 0xee}, {0x1, ...}, ...}, ...)
        /workspace/matrixone/pkg/logutil/report.go:140 +0x323
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0003821e0, {0xff, {0xc0c2438c7538f026, 0xaf2cfc, 0x35073a0}, {0x0, 0x0}, {0xc000030000, 0xee}, {0x1, ...}, ...}, ...)
        /opt/go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/core.go:86 +0x7c
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00002a180, {0x0, 0x0, 0x0})
        /opt/go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:220 +0x1d9
go.uber.org/zap.(*Logger).Debug(0x20b093c?, {0xc000030000?, 0xc00039fb58?}, {0x0, 0x0, 0x0})
        /opt/go/pkg/mod/go.uber.org/zap@v1.21.0/logger.go:184 +0x59
github.com/matrixorigin/matrixone/pkg/logutil.Debugf({0x20b093c?, 0x23ce008?}, {0xc00039fb58?, 0x0?, 0x0?})
        /workspace/matrixone/pkg/logutil/api.go:49 +0x95
github.com/matrixorigin/matrixone/pkg/util/metric.mustRegiterToProm({0x23ce008?, 0xc000112180?})
        /workspace/matrixone/pkg/util/metric/metric.go:150 +0x79
github.com/matrixorigin/matrixone/pkg/util/metric.mustRegister({0x23e5840?, 0xc000112180})
        /workspace/matrixone/pkg/util/metric/metric.go:157 +0xb9
github.com/matrixorigin/matrixone/pkg/util/metric.registerAllMetrics(...)
        /workspace/matrixone/pkg/util/metric/m_register.go:27
github.com/matrixorigin/matrixone/pkg/util/metric.InitMetric({0x23e4bc8?, 0xc000040080}, 0x2?, 0xc0000a4280, {0xc0000ba660, 0x24}, {0x207f1f4, 0xa}, {0xc00039fdb0, 0x1, ...})
        /workspace/matrixone/pkg/util/metric/metric.go:101 +0x5b8
main.initTraceMetric({0x23e4bc8, 0xc000040080}, 0xc000179800, 0xc0004de240?, {0x23ef8a0, 0xc00000f4e8})
        /workspace/matrixone/cmd/mo-service/main.go:310 +0x63d
main.startService(0xc000179800, 0xc00003c190?)
        /workspace/matrixone/cmd/mo-service/main.go:91 +0x68
main.main()
        /workspace/matrixone/cmd/mo-service/main.go:67 +0x1c5
```

**Comment by xzxiong** [comment]
thx, @jinqinghui
