### ISSUE TITLE
[Bug]: error when run jdbc getTimestamp method

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5133]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

code:
payment.c_since = rs.getTimestamp("c_since").toString();

error:
java.sql.SQLException: Invalid length (19) for type TIMESTAMP
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:99)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:1019)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:1064)
	at io.mo.jTPCCTData.executePayment(jTPCCTData.java:864)
	at io.mo.jTPCCTData.execute(jTPCCTData.java:103)
	at io.mo.jTPCCTerminal.executeTransactions(jTPCCTerminal.java:162)
	at io.mo.jTPCCTerminal.run(jTPCCTerminal.java:90)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.mysql.cj.exceptions.DataReadException: Invalid length (19) for type TIMESTAMP
	at com.mysql.cj.protocol.a.MysqlBinaryValueDecoder.decodeTimestamp(MysqlBinaryValueDecoder.java:51)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:87)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:250)
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:656)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getDateOrTimestampValueFromRow(ResultSetImpl.java:679)
	... 7 more

**Comment by aressu1985** [comment]
fixed
