### ISSUE TITLE
[Bug]: mo panic when jdbc run prepraed update stmt with timestamp value

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5188]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

code:
stmt = db.stmtNewOrderInsertOrder;
	    stmt.setInt(1, o_id);
	    stmt.setInt(2, newOrder.d_id);
	    stmt.setInt(3, newOrder.w_id);
	    stmt.setInt(4, newOrder.c_id);
	    stmt.setTimestamp(5, new Timestamp(System.currentTimeMillis()));
	    stmt.setInt(6, ol_cnt);
	    stmt.setInt(7, o_all_local);
	    stmt.executeUpdate();

error:

2022-09-22 11:47:40 ERROR jTPCCTerminal:945 - internal error: panic runtime error: index out of range [0] with length 0: goroutine 2192 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.ConvertPanicError({0x10674e760?, 0x1400520e8e8})
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/common/moerr/error.go:410 +0x5c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2434 +0xe0
panic({0x10674e760, 0x1400520e8e8})
	/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).readDate(0x14034019a88?, {0x0, 0x0, 0x1?}, 0x14034019a28?)
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_protocol.go:661 +0x10c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).readDateTime(0x14008001790?, {0x0, 0x0, 0x105e5c000?}, 0x14008001790?)
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_protocol.go:669 +0x28
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).readTimestamp(0x140198b4280, {0x0, 0x0, 0x0}, 0x2?)
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_protocol.go:680 +0x2c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).ParseExecuteData(0x140198b4280, 0x140340ad300, {0x140005ba6c1, 0x54, 0x54}, 0x98a?)
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_protocol.go:633 +0xbe8
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).parseStmtExecute(0x14006439310, {0x140005ba6c1, 0x54, 0x54})
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2583 +0x104
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x14006439310, {0x106900758, 0x14018451380}, 0x1400179f420)
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2538 +0xa28
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x14032976230, {0x1069006b0?, 0x14001949200?})
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:122 +0x290
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:179 +0x218

java.sql.SQLException: internal error: panic runtime error: index out of range [0] with length 0: goroutine 2192 [running]:
runtime/debug.Stack()

**Comment by aressu1985** [comment]
fixed
