### ISSUE TITLE
[Bug]: parallel insert cause TAE error

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#5302]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

t1 contains 6000k rows.
t2 has same structure as t1.

mysql> insert into t2 select * from t1;
ERROR 20101 (HY000): internal error: buffer: no space left

If we expand the buffer size `DefaultTxnCacheSize`, it will panic at TAE. here is the stack informations
`
panic: runtime error: slice bounds out of range [:479135] with capacity 479133

goroutine 119 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).extendData(0x14056f8eb60, {0x103053848, 0x1404e350500?}, 0x0?, 0x9c40)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers/vecbase.go:99 +0x220
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).ExtendWithOffset(0x1000000065?, {0x103053848?, 0x1404e350500?}, 0x1401a59f888?, 0x100f7b25c?)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers/vecbase.go:111 +0x80
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Extend(0x100fbd75c, {0x103053848?, 0x1404e350500})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers/vecbase.go:91 +0x58
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Extend(0x1406825f9a0?, {0x103053848?, 0x1404e350500?})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers/vector.go:178 +0x38
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).ApplyAppend(0x140615df2e0, 0x14057350380, {0x1401a59f988?, 0x1024d23f4?})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/node.go:164 +0x2a8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*blockAppender).ApplyAppend(0x14000627a60, 0x14057350380, {0x10305a508, 0x140574184d0})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/appender.go:102 +0xa0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).ApplyAppend(0x1404d98e680)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:106 +0x1bc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).ApplyAppend(...)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:706
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PreApplyCommit(...)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:728
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PreApplyCommit(0xffffffffffffffff?)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:418 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PreApplyCommit(0x14056df55e0)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:495 +0x84
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PreApplyCommit(0x1401a59fcc8?)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:264 +0x28
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreApplyCommit(0x1404dcd5d40?, {0x10305a340, 0x1405723f050})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:224 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare(0x1401a59fd00?, 0x14056df0870, {0x0, 0x0, 0x0, 0x0, 0x97, 0x3, 0x0, 0x0, ...})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:270 +0xc8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare1PC(0x1400063e900?, 0x14056df0870?, {0x0, 0x0, 0x0, 0x0, 0x97, 0x3, 0x0, 0x0, ...})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:283 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).dequeuePreparing(0x1400063e900, {0x14056c7c000, 0x1, 0x14000086ec0?})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:350 +0x110
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:83 +0x1bc
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:62 +0xf0
`
 

### Expected Behavior

insert successful.

### Steps to Reproduce

```Markdown
parallel insert base code : 
https://github.com/m-schen/matrixone/tree/parallel-insert-for-tae

I temporarily use two concurrent routines for writing. If need, you can change the number.
`var insertParallelNumber = 2` at compile.go

1. create a table t1.
2. load big data.
3. commit
4. create a new table t2.
5. insert into t2 select * from t1.


I used 1g data of tpch for testing, and the table used was lineitem.tbl.
here is the create sql and load sql.

create table sql:
`
create table t1 ( L_ORDERKEY    BIGINT NOT NULL,
                 L_PARTKEY     INTEGER NOT NULL,
                 L_SUPPKEY     INTEGER NOT NULL,
                 L_LINENUMBER  INTEGER NOT NULL,
                 L_QUANTITY    INTEGER /*DECIMAL(15,2)*/ NOT NULL,
                 L_EXTENDEDPRICE  DOUBLE /* PRECISION */ /*DECIMAL(15,2)*/ NOT NULL,
                 L_DISCOUNT    DOUBLE /* PRECISION */ /*DECIMAL(15,2)*/ NOT NULL,
                 L_TAX         DOUBLE /* PRECISION */ /*DECIMAL(15,2)*/ NOT NULL,
                 L_RETURNFLAG  VARCHAR(1) NOT NULL,
                 L_LINESTATUS  VARCHAR(1) NOT NULL,
                 L_SHIPDATE    DATE NOT NULL,
                 L_COMMITDATE  DATE NOT NULL,
                 L_RECEIPTDATE DATE NOT NULL,
                 L_SHIPINSTRUCT VARCHAR(25) /*CHAR(25)*/ NOT NULL,
                 L_SHIPMODE     VARCHAR(10) /*CHAR(10)*/ NOT NULL,
                 L_COMMENT      VARCHAR(44) NOT NULL);
`

load sql:
`
load DATA infile '../tbl/lineitem.tbl' into table t1 FIELDS TERMINATED BY '|' ENCLOSED BY '\"' LINES TERMINATED BY '\n';
`
```

**Comment by m-schen** [comment]
no need now.
