### ISSUE TITLE
[Bug]: tae painc when run batch insert with Composite primary key

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5311]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

java.sql.BatchUpdateException: internal error: panic runtime error: index out of range [17] with length 17: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:336
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:184
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:163
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:53
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InsertValues
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/dml.go:117
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:134
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2217
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2507
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:122
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1165
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.util.Util.handleNewInstance(Util.java:191)
        at com.mysql.cj.util.Util.getInstance(Util.java:166)
        at com.mysql.cj.util.Util.getInstance(Util.java:173)
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:371)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:452)
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:814)
        at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:403)
        at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: internal error: panic runtime error: index out of range [17] with length 17: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:336
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:184
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:163
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:53
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InsertValues
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/dml.go:117
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:134
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2217
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2507
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:122
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1165
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:634)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:414)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1109)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1057)
        at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:353)
        ... 5 more
Worker 001: ERROR: internal error: panic runtime error: index out of range [17] with length 17: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:336
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:184
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:163
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:53
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InsertValues
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/dml.go:117
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:134
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2217
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2507
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:122
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1165

**Comment by aressu1985** [comment]
fixed
