### ISSUE TITLE
[Bug]: CN panic in distributed deployment using mem-engine 

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#5378]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8a168b23a730735404bb64b5faeb4a502ff262ba
- Hardware parameters: MacOS
```

### Actual Behavior

CN will panic when there is a sql connection and crash continuously afterwards.

```
# CN running
> kubectl get po -n e2e-1664516897612298000
kubectl get po -n e2e-1664516897612298000
NAME           READY   STATUS             RESTARTS        AGE
test-dn-0      1/1     Running            0               3m47s
test-log-0     1/1     Running            0               4m35s
test-log-1     1/1     Running            1 (3m44s ago)   4m35s
test-log-2     1/1     Running            0               4m35s
test-tp-cn-0   1/1     Running            2 (3m24s ago)   3m47s
test-tp-cn-1   0/1     CrashLoopBackOff   4 (39s ago)     3m47s

> kubectl -n e2e-1664516897612298000 port-forward test-tp-cn-0  6002:6001
# CN crash
> mysql -h 127.0.0.1 -P6002 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0

# CN will continuously crash afterwards even if there is no connection
kubectl get po -n e2e-1664516897612298000

NAME           READY   STATUS             RESTARTS        AGE
test-dn-0      1/1     Running            0               5m34s
test-log-0     1/1     Running            0               6m22s
test-log-1     1/1     Running            1 (5m31s ago)   6m22s
test-log-2     1/1     Running            0               6m22s
test-tp-cn-0   0/1     CrashLoopBackOff   3 (10s ago)     5m34s
test-tp-cn-1   0/1     CrashLoopBackOff   5 (53s ago)     5m34s
```

CN crash log:

1. the first time CN crash:

```
{"level":"ERROR","time":"2022/09/30 09:04:35.496104 +0000","caller":"morpc/backend.go:494","msg":"read from backend failed","remote":"0.0.0.0:6001","error":"too big body size 1224736768, max is 10485760"}
{"level":"ERROR","time":"2022/09/30 09:04:35.496169 +0000","caller":"morpc/backend.go:499","msg":"read loop stopped","remote":"0.0.0.0:6001"}
panic: interface conversion: morpc.Message is nil, not *pipeline.Message

goroutine 324 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).remoteRun(0xc00012e6e0, 0xc0037e12b0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/cnserviceDriver.go:225 +0xa8a
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00012e6e0, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:130 +0x4c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:89 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:84 +0x58d
```

raw log: [cn-log.tgz](https://github.com/matrixorigin/matrixone/files/9682621/cn-log.tgz)

2. crashes afterwards:

```
{"level":"INFO","time":"2022/09/30 08:04:15.129396 +0000","caller":"compile/scope.go:43","msg":"\t:2 projection(typ:<id:61 width:100 > col:<name:\"mo_database.datname\" > ) -> projection(typ:<id:61 width:100 > col:<name:\"mo_database.datname\" > ) -> pipe connector"}
{"level":"INFO","time":"2022/09/30 08:04:15.129413 +0000","caller":"compile/scope.go:43","msg":":0  union all  -> sql output"}
{"level":"INFO","time":"2022/09/30 08:04:15.132873 +0000","caller":"frontend/mysql_cmd_executor.go:2221","msg":"time of Exec.Run : 3.5573ms"}
{"level":"INFO","time":"2022/09/30 08:04:15.132934 +0000","caller":"frontend/util.go:459","msg":"Connection id: 4294967295 Status: success Statement: show databases"}
{"level":"INFO","time":"2022/09/30 08:04:15.132948 +0000","caller":"frontend/mysql_cmd_executor.go:2618","msg":"----close mce"}
panic: it must have result set

goroutine 95 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.checkSysExistsOrNot({0x2742858, 0xc0010cc9f0}, 0xc0001581e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:3358 +0x6d8
github.com/matrixorigin/matrixone/pkg/frontend.InitSysTenant({0x2742858, 0xc0003df320})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:3431 +0x14c
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).createMOServer(0xc000288000, {0x27427b0, 0xc00027c1c0}, 0xc0001581e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:231 +0x1be
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).initMOServer(0xc000288000, {0x27427b0, 0xc00054c680}, 0xc0001581e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:175 +0x170
github.com/matrixorigin/matrixone/pkg/cnservice.NewService(0xc000280840, {0x27427b0, 0xc00054c680}, {0x274e340?, 0xc0003e6bd0?}, {0xc0006a9a58, 0x1, 0x0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:86 +0x3af
main.startCNService.func1({0x27427b0, 0xc00054c680})
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:133 +0x258
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:257 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:252 +0x12c
```

raw log: [cn-log-after.tgz](https://github.com/matrixorigin/matrixone/files/9682623/cn-log-after.tgz)

### Expected Behavior

CN should not panic

### Steps to Reproduce

follow the deployment config `etc/distributed-mem-engine-example/` to reproduce

https://github.com/matrixorigin/matrixone/blob/main/etc/distributed-mem-engine-example/README.md

**Comment by aylei** [comment]
cc @daviszhen @zhangxu19830126

**Comment by reusee** [comment]
cc @m-schen

**Comment by aylei** [comment]
panic after restart is tracked in https://github.com/matrixorigin/matrixone/issues/5441

**Comment by m-schen** [comment]
I will add a type check logic here.

but we got a wrong cn-server address information from clusterDetails. It's the root cause.

**Comment by m-schen** [comment]
> I will add a type check logic here.
> 
> but we got a wrong cn-server address information from clusterDetails. It's the root cause.

I have fixed the wrong address bug.

**Comment by sukki37** [comment]
@aylei could u pls test and update status
