### ISSUE TITLE
[Bug]: [CN-DN BVT] load_data panic

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#5788]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): c3c29a0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: extend instead of shink vector

goroutine 2856 [running]:
github.com/matrixorigin/matrixone/pkg/container/vector.SetVectorLength(0xc011ecb080, 0x9c40)
        /Users/aptend/code/matrixone/pkg/container/vector/vector.go:831 +0x127
github.com/matrixorigin/matrixone/pkg/container/vector.SetLength(0xc011ecb080, 0x9c40)
        /Users/aptend/code/matrixone/pkg/container/vector/vector.go:825 +0x59
github.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpr(0xc011259f80, 0xc00d0249a0, 0xc0095a2e40)
        /Users/aptend/code/matrixone/pkg/sql/colexec/expr_eval.go:146 +0x1af0
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.partitionBatch(0xc011259f80, 0xc0095a2e40, 0xc00d0249a0, 0x1)
        /Users/aptend/code/matrixone/pkg/vm/engine/disttae/tools.go:867 +0x99
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*table).Write(0xc000173ce0, {0x7234d78, 0xc00a0e5470}, 0xc011259f80)
        /Users/aptend/code/matrixone/pkg/vm/engine/disttae/table.go:238 +0xf4
github.com/matrixorigin/matrixone/pkg/frontend.writeBatchToStorage(0xc0002e0780, 0x1)
        /Users/aptend/code/matrixone/pkg/frontend/load.go:1823 +0xfa2
github.com/matrixorigin/matrixone/pkg/frontend.rowToColumnAndSaveToStorage(0xc0002e0780, 0x1, 0x1)
        /Users/aptend/code/matrixone/pkg/frontend/load.go:1605 +0xcf9
github.com/matrixorigin/matrixone/pkg/frontend.glob..func10.1()
        /Users/aptend/code/matrixone/pkg/frontend/load.go:1881 +0xcd
created by github.com/matrixorigin/matrixone/pkg/frontend.glob..func10
        /Users/aptend/code/matrixone/pkg/frontend/load.go:1877 +0x24c

### Steps to Reproduce

```Markdown
1. `./mo-service -launch etc/launch-tae-CN-tae-DN/launch.toml` in matrixone

2. `./run.sh -n -g -p ../matrixone/test/cases/load_data` in mo-test
```

### Additional information

no panic

**Comment by aptend** [comment]
root cause: Vector Zs should be shrinked
