### ISSUE TITLE
[Bug]: docker image config error

### ISSUE THREAD

**Issue by wanglei4687** [matrixorigin/matrixone#5827]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run latest docker image: matrixorigin/matrixone:nightly-052f1439

`cn-standalone-test.toml`
Config Error

### Steps to Reproduce

```Markdown
docker run -p 6001:6001 matrixorigin/matrixone:nightly-052f1439
```

### Additional information

```
2022/10/21 03:44:39.330902 +0000 ERROR hakeeper-client-backend morpc/backend.go:617 init remote connection failed, retry later {"remote": "1", "error": "dial tcp4: address 1: missing port in address"}
2022/10/21 03:44:40.335746 +0000 ERROR hakeeper-client-backend morpc/backend.go:200 connect to remote failed {"remote": "1", "error": "backend closed"}
2022/10/21 03:44:40.335964 +0000 ERROR hakeeper-client morpc/client.go:406 create backend failed {"backend": "1", "error": "backend closed"}
2022/10/21 03:44:40.336379 +0000 ERROR hakeeper-client-backend morpc/backend.go:617 init remote connection failed, retry later {"remote": "2", "error": "dial tcp4: address 2: missing port in address"}
2022/10/21 03:44:41.341053 +0000 ERROR hakeeper-client-backend morpc/backend.go:200 connect to remote failed {"remote": "2", "error": "backend closed"}
2022/10/21 03:44:41.341145 +0000 ERROR hakeeper-client morpc/client.go:406 create backend failed {"backend": "2", "error": "backend closed"}
panic: backend closed

goroutine 1 [running]:
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:77 +0x37b
```

**Comment by zhangxu19830126** [comment]
@wanglei4687 you need to see you config, a address is "2" in the config file

**Comment by zhangxu19830126** [comment]
see the log: 2022/10/21 03:44:40.336379 +0000 ERROR hakeeper-client-backend morpc/backend.go:617 init remote connection failed, retry later {"remote": "2", "error": "dial tcp4: address 2: missing port in address"}

**Comment by zhangxu19830126** [comment]
see your config file. it's wrong.  etc/cn-standalone-test.toml is wrong.

**Comment by zhangxu19830126** [comment]
standalone is already not supported.
