### ISSUE TITLE
[Bug]: Cannot query data by primary key

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#6027]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
main
```

### Actual Behavior

2022-10-27T09:26:47.0693939Z --- FAIL: TestAllocateWithNotExistTask (0.00s)
2022-10-27T09:26:47.0716732Z panic: query task by primary key, return 0 records [recovered]
2022-10-27T09:26:47.0717438Z 	panic: query task by primary key, return 0 records
2022-10-27T09:26:47.0717730Z 
2022-10-27T09:26:47.0717943Z goroutine 114 [running]:
2022-10-27T09:26:47.0718356Z testing.tRunner.func1.2({0xdd55c0, 0xc000490ff0})
2022-10-27T09:26:47.0718895Z 	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1396 +0x372
2022-10-27T09:26:47.0719322Z testing.tRunner.func1()
2022-10-27T09:26:47.0719787Z 	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1399 +0x5f0
2022-10-27T09:26:47.0720209Z panic({0xdd55c0, 0xc000490ff0})
2022-10-27T09:26:47.0720938Z 	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:890 +0x262
2022-10-27T09:26:47.0721566Z github.com/matrixorigin/matrixone/pkg/taskservice.(*taskService).Allocate(_, {_, _}, {0x1, {{0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...}, ...}, ...)
2022-10-27T09:26:47.0722180Z 	/home/runner/work/matrixone/matrixone/pkg/taskservice/task_service.go:134 +0x799
2022-10-27T09:26:47.0722786Z github.com/matrixorigin/matrixone/pkg/taskservice.TestAllocateWithNotExistTask(0xc00022b040)
2022-10-27T09:26:47.0723428Z 	/home/runner/work/matrixone/matrixone/pkg/taskservice/task_service_test.go:148 +0x423
2022-10-27T09:26:47.0724223Z testing.tRunner(0xc00022b040, 0xf0b4f8)
2022-10-27T09:26:47.0725157Z 	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1446 +0x217
2022-10-27T09:26:47.0725505Z created by testing.(*T).Run
2022-10-27T09:26:47.0725893Z 	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1493 +0x75e
2022-10-27T09:26:47.0736817Z FAIL	github.com/matrixorigin/matrixone/pkg/taskservice	3.404s

**Comment by daviszhen** [comment]
It was fixed i think.
