### ISSUE TITLE
[Bug]: [cn-dn with flushing] invalid mpool id panic 

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#6100]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sh
[ERROR]
[SCRIPT   FILE]: /home/foz/repo/matrixone/test/distributed/cases/accesscontrol/create_role.sql
[ROW    NUMBER]: 62
[SQL STATEMENT]: select count(*) from mo_user_grant,mo_user,mo_role_privs where mo_user_grant.user_id=mo_user.user_id and mo_role_privs.role_id=mo_user_grant.role_id and role_name='role2';
[EXPECT RESULT]:
count(*)
0
[ACTUAL RESULT]:
internal error: invalid mpool id 13
```

### Steps to Reproduce

```Markdown
./mo-service -launch etc/launch-flush-tae-CN-tae-DN/launch.toml

and run bvt ./run.sh -n -g -p path/to/matrixone/test/distributed/cases
```

### Additional information

I have checked Original field of returned batch of BlockRead is true

**Comment by aptend** [comment]
panic stack
```sh
goroutine 26733 [running]:
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0x23ed4e0?, {0xc017308d10, 0x8, 0x8})
	/home/foz/repo/matrixone/pkg/common/mpool/mpool.go:569 +0x1b4
github.com/matrixorigin/matrixone/pkg/sql/colexec/agg.(*UnaryAgg[...]).Free(0xc0188b9e00?, 0x45c574)
	/home/foz/repo/matrixone/pkg/sql/colexec/agg/agg.go:50 +0x3c
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).Clean(0xc00c38c080, 0xc00f2d2700)
	/home/foz/repo/matrixone/pkg/container/batch/batch.go:247 +0x19b
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergegroup.(*container).processH0(0xc00cc3a120?, 0xc00c38c080?, 0xc006086d00?)
	/home/foz/repo/matrixone/pkg/sql/colexec/mergegroup/group.go:182 +0x114
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergegroup.(*container).process(0xc0162c5b00, 0xc00bb01680?, 0xc0146b38c0)
	/home/foz/repo/matrixone/pkg/sql/colexec/mergegroup/group.go:156 +0x73
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergegroup.(*container).build(0xc0162c5b00, 0xc0146b38c0, {0x290c7e0, 0xc00d442040})
	/home/foz/repo/matrixone/pkg/sql/colexec/mergegroup/group.go:111 +0xd1
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergegroup.Call(0x1?, 0xc0146b38c0, {0x20a89c0?, 0xc00ccba600})
	/home/foz/repo/matrixone/pkg/sql/colexec/mergegroup/group.go:47 +0x19b
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc019020880?, 0x4, 0x7fc0241dc728?}, 0x20?)
	/home/foz/repo/matrixone/pkg/vm/vm.go:60 +0xa4
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc010bb9f28, 0xc0146b38c0)
	/home/foz/repo/matrixone/pkg/vm/pipeline/pipeline.go:147 +0x1a5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc00af80140, 0xc01aa40000)
	/home/foz/repo/matrixone/pkg/sql/compile/scope.go:110 +0x617
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0xc0084feb40?)
	/home/foz/repo/matrixone/pkg/sql/compile/scope.go:81 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/home/foz/repo/matrixone/pkg/sql/compile/scope.go:76 +0x27e
```

**Comment by nnsgmsone** [comment]
Looked like it was caused by incorrectly populating the agg information. Kind of like the blockio.Read padding.

**Comment by aptend** [comment]
commit: eff64a343 fix bug (#6098)
macos 12.5

```
./mo-service -launch etc/launch-flush-tae-CN-tae-DN/launch.toml

./run.sh -n -g -p /Users/aptend/code/matrixone/test/distributed/cases/benchmark
```

repro

```txt
[ERROR]
[SCRIPT   FILE]: /Users/aptend/code/matrixone/test/distributed/cases/benchmark/tpch/02_LOAD/10_select_count.sql
[ROW    NUMBER]: 3
[SQL STATEMENT]: select count(*) from lineitem;
[EXPECT RESULT]:
count(*)
6005
[ACTUAL RESULT]:
internal error: invalid mpool id 3328210909095473713
```

@triump2020 can also repro this issue using same commit

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/blob/c241f48036d61266110606c4c66237bf1566fdba/pkg/vm/engine/tae/dataio/blockio/read.go#L78-L84

BlockRead doesn't touch Batch.Aggs field

**Comment by m-schen** [comment]
I have fixed it.
