### ISSUE TITLE
[Bug]: mo restart timeout 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6284]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1feeb04254c6fdab0ae0061ecc32349136d6ee10
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

022/11/04 17:37:47.072617 +0800 ERROR frontend/mysql_cmd_executor.go:3011 internal error: the deleted batch is nil
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
 /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3011
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
 /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3143
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
 /data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:159
2022/11/04 17:37:47.072655 +0800 ERROR frontend/util.go:476 query trace status {"connection_id": 1068, "statement": "execute __mo_stmt_id_1 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4,@__mo_stmt_var_5,@__mo_stmt_var_6,@__mo_stmt_var_7,@__mo_stmt_var_8,@__mo_stmt_var_9,@__mo_stmt_var_10", "status": "fail", "error": "internal error: the deleted batch is nil"}
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus
 /data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:476
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus
 /data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:468
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
 /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3019
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
 /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3143
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
 /data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:159
2022/11/04 17:37:47.072717 +0800 ERROR log-service task/task_scheduler.go:83 new tasks create failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "Error 20101: internal error: the deleted batch is nil"}
2022/11/04 17:37:47.072753 +0800 ERROR log-service logservice/service_bootstrap.go:84 failed to create init tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "Error 20101: internal error: the deleted batch is nil"}

2022/11/04 17:41:18.499611 +0800 INFO frontend/mysql_cmd_executor.go:2702 time of Exec.Build : 3.000582ms
2022/11/04 17:41:18.500062 +0800 INFO frontend/mysql_cmd_executor.go:2793 time of Exec.Run : 322.461µs
2022/11/04 17:41:18.500117 +0800 INFO frontend/util.go:474 query trace status {"connection_id": 1130, "statement": "select task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, task_parent_id, task_status, task_runner, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_status = 0 order by task_id", "status": "success"}
2022/11/04 17:41:18.940035 +0800 INFO cn-service logutil/action.go:52 async task exited {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "action": "run-async-task", "async-task": "cnservice/wait-system-init-task", "cost": "5m0.468345366s"}
panic: wait system init timeout

goroutine 490 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).waitSystemInitCompleted(0xc006f08000, {0x292b7f0, 0xc00b444800})
        /data1/sudong/mo-regression/matrixone/pkg/cnservice/server_task.go:177 +0x551
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /data1/sudong/mo-regression/matrixone/pkg/common/stopper/stopper.go:257 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /data1/sudong/mo-regression/matrixone/pkg/common/stopper/stopper.go:252 +0x12c

**Comment by XuPeng-SH** [comment]
It may be the same issue as #6254 and it should be fixed by #6291
