### ISSUE TITLE
[Bug]: logservice/store.go:657 SIGSEGV

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#6295]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): reuse/matrixone:cf8c698ae23e3e084f9487533a6a153948133bbc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"INFO","time":"2022/11/04 12:19:00.594523 +0000","name":"log-service","caller":"logservice/store.go:657","msg":"HAKeeper ticker stopped","uuid":"00000000-0000-0000-0000-000000000002"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xcf1956]

goroutine 274 [running]:
github.com/matrixorigin/matrixone/pkg/pb/logservice.(*ScheduleCommand).LogString(0xc00335dae0)
 /go/src/github.com/matrixorigin/matrixone/pkg/pb/logservice/logservice.go:192 +0x396
github.com/matrixorigin/matrixone/pkg/logservice.(*store).healthCheck(0xc0058f4500, 0xc00a8eb1a0?, 0x0?)
 /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:195 +0x385
github.com/matrixorigin/matrixone/pkg/logservice.(*store).hakeeperCheck(0xc0058f4500)
 /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:157 +0x62f
github.com/matrixorigin/matrixone/pkg/logservice.(*store).ticker(0xc0058f4500, {0x292d430, 0xc005891ec0})
 /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:667 +0x387
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica.func1({0x292d430, 0xc005891ec0})
 /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:224 +0x5d
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
 /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:257 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
 /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:252 +0x12c
```

### Steps to Reproduce

```Markdown
it's difficult to describe in words, pls contact me with wechat if you need
```

**Comment by zhangxu19830126** [comment]
@w-zr already fixed it?

**Comment by w-zr** [comment]
> @w-zr already fixed it?

@zhangxu19830126  Already fixed.

**Comment by sukki37** [comment]
I think this NPE has been fixed, but not sure why a NPE is thrown here. 
Anyway, I will close this issue, but @w-zr pls keep an eye on it and try to find out the root cause, thank u.
