### ISSUE TITLE
[Bug]: mo oom when run tpcc test with 10-terminal-10-warehouse for 2 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6352]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):777b7ebbe34b8d1d3fe0733de2db588a4fc40c71
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo error logs :
[sudong@mo-srv-128 matrixone]$ vi server.log 
2022/11/07 00:11:24.077969 +0800 INFO mpool/mpool.go:526 error: error: out of memory {"span": {}}
2022/11/07 00:11:24.078019 +0800 INFO mpool/mpool.go:526 error: error: out of memory {"span": {}}
2022/11/07 00:11:24.078158 +0800 INFO frontend/util.go:498 time of Exec.Build : 18.607596ms connectionId 1057
panic: error: out of memory

goroutine 15444495 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand(0xc094d21e00?, 0x428c0d)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:76 +0x1d1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append(0xc094d21e00?, {0x0, 0x0, 0x0, 0x0, 0x4, 0xc, 0x0, 0x0, 0x0, ...})
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:156 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append(0x0?, {0x21efa60?, 0xc14b245260?})
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vecbase.go:74 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append(0x1000000000?, {0x21efa60?, 0xc14b245260?})
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vector.go:174 +0x32
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/model.PreparePhyAddrDataWithPool({0x65, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0}, {0xc054acd8f8, 0xc, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/model/preparer.go:36 +0x163
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc({0x2960838, 0xc0e2c1c210}, 0x130c, 0x40c, {0xc15bd7d540?, 0xc000701c00?}, {0xc0ff505b00, 0xa, 0x217dfe0?}, {0xc1323fab40, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:133 +0x957
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner({0x2960838, 0xc0e2c1c210}, 0xc03dd64c38, {0xc0ff505b00, 0xa, 0x10}, {0xc1323fab40?, 0xc05a7b3c58?, 0xe8c9ae?}, {0xc121e7cd00, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:93 +0x11c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead({0x2960838, 0xc0e2c1c210}, 0x1d3a2eb?, {0xc0ff505b00, 0xa, 0x10}, {0xc1323fab40, 0xa, 0xa}, {0xc121e7cd00, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:62 +0x27a
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read(0xc03fc429c0, {0xc0ff505b00?, 0xa?, 0x10?}, 0x453c60?, 0xc01aa03800?)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/reader.go:70 +0x393
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc054acdf28, {0x293b238, 0xc03fc429c0}, 0xc0c2397980)
        /data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:68 +0x1aa
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc1173e6f00?, 0xc0fc6b7790?)
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:55 +0xc8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x3d4d3c0?)
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:68 +0x18d

### Steps to Reproduce

```Markdown
1.git clone https://github.com/aressu1985/mo-tpcc
  
2.start MO：
  
3. create databas and tables;
   source xxx/mo-tpcc/sql/tableCreates_pk.sql; 

4. modify props.mo
  warehouses=10
  terminals=10
  runMins any value > 120

5. generate tpcc data
   mkdir data
   ./runLoader.sh props.mo warehouse 10 filelocation data/

6、laod data to tpcc database
load data infile '/path/to/mo-tpcc/data/config.csv' into table bmsql_config;
load data infile '/path/to/mo-tpcc/data/cust-hist.csv' into table bmsql_history;
load data infile '/path/to/mo-tpcc/data/customer.csv' into table bmsql_customer;
load data infile '/path/to/mo-tpcc/data/district.csv' into table bmsql_district;
load data infile '/path/to/mo-tpcc/data/item.csv' into table bmsql_item;
load data infile '/path/to/mo-tpcc/data/new-order.csv' into table bmsql_new_order;
load data infile '/path/to/mo-tpcc/data/order-line.csv' into table bmsql_order_line;
load data infile '/path/to/mo-tpcc/data/order.csv' into table bmsql_oorder;
load data infile '/path/to/mo-tpcc/data/stock.csv' into table bmsql_stock;
load data infile '/path/to/mo-tpcc/data/warehouse.csv' into table bmsql_warehouse;

7. run benchmark test
./runBenchmark.sh props.mo
```

**Comment by LeftHandCold** [comment]
I can't reproduce

2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-06, mTOTAL: 176832    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-06, Closing statement and connection...
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-06,
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-06, Terminal 'Term-06' finished after 0 transaction(s).
2022-11-07 17:38:09 FATAL jTPCCTerminal:282 - TT_NEW_ORDER: Unexpected SQLException on transaction execution: Duplicate entry '3a15063a16a898' for key '__mo_cpkey_006s_w_id006s_i_id'
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-04, mTOTAL: 176844    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-04, Closing statement and connection...
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-04,
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-04, Terminal 'Term-04' finished after 0 transaction(s).
2022-11-07 17:38:09 FATAL jTPCCTerminal:169 - TT_PAYMENT: Unexpected SQLException on transaction execution: w-w conflict
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-01, mTOTAL: 176856    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-01, Closing statement and connection...
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-01,
2022-11-07 17:38:09 INFO  jTPCCTerminal:350 - Term-01, Terminal 'Term-01' finished after 0 transaction(s).
2022-11-07 17:38:10 FATAL jTPCCTerminal:169 - TT_PAYMENT: Unexpected SQLException on transaction execution: w-w conflict
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-09, mTOTAL: 176868    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-09, Closing statement and connection...
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-09,
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-09, Terminal 'Term-09' finished after 0 transaction(s).
2022-11-07 17:38:10 FATAL jTPCCTerminal:282 - TT_NEW_ORDER: Unexpected SQLException on transaction execution: Duplicate entry '3a15053a165498' for key '__mo_cpkey_006s_w_id006s_i_id'
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-10, mTOTAL: 176880    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-10, Closing statement and connection...
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-10,
2022-11-07 17:38:10 INFO  jTPCCTerminal:350 - Term-10, Terminal 'Term-10' finished after 0 transaction(s).
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-07, mTOTAL: 176892    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-07, Closing statement and connection...
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-07,
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-07, Terminal 'Term-07' finished after 0 transaction(s).
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-08, mTOTAL: 176892    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-08, Closing statement and connection...
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-08,
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-08, Terminal 'Term-08' finished after 0 transaction(s).
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-05, mTOTAL: 176892    Memory Usage: 258MB / 1963MB
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-05, Closing statement and connection...
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-05,
2022-11-07 17:38:15 INFO  jTPCCTerminal:350 - Term-05, Terminal 'Term-05' finished after 0 transaction(s).
2022-11-07 17:38:15 INFO  jTPCC:710 - Term-00, All terminals finished executing 2022-11-07 17:38:15

2022-11-07 17:38:15 INFO  jTPCC:694 - Term-00,
2022-11-07 17:38:15 INFO  jTPCC:695 - Term-00,
2022-11-07 17:38:15 INFO  jTPCC:696 - Term-00, Measured tpmC (NewOrders) = 16.98
2022-11-07 17:38:15 INFO  jTPCC:697 - Term-00, Measured tpmTOTAL = 139.68
2022-11-07 17:38:15 INFO  jTPCC:698 - Term-00, Measured tpmE (ErrorCount) = 111.85
2022-11-07 17:38:15 INFO  jTPCC:699 - Term-00, Session Start     = 2022-11-07 15:38:07
2022-11-07 17:38:15 INFO  jTPCC:700 - Term-00, Session End       = 2022-11-07 17:38:15
2022-11-07 17:38:15 INFO  jTPCC:701 - Term-00, Transaction Count = 16780
2022-11-07 17:38:15 INFO  jTPCC:702 - Term-00, Transaction Error = 13438
2022-11-07 17:38:15 INFO  jTPCC:703 - Term-00, Transaction NewOrders = 2041
2022-11-07 17:38:15 INFO  jTPCC:710 - Term-00, Session finished!

**Comment by LeftHandCold** [comment]
I haven't reproduced it yet

**Comment by LeftHandCold** [comment]
no progress yet

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
it is tracked by another issue #6528 ,and this can be cloesed
