### ISSUE TITLE
[Bug]: Fix goroutine leaks.

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#6393]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 393e938197847675e340c61d763b1acb78e28fe1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are many goroutine leaks in unit tests. Such leaks can be detected by adding `defer leaktest.AfterTest(t)()` at the beginning of tests. Some leaks may come from tests(not call close() after test, e.g.), some may come from source code. These leaks may fail other unit tests, make the cluster stuck, etc.

For example, after adding leak test, `TestCheckpointUC` will fail and report
```
    leak.go:138: Leaked goroutine: goroutine 275 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a180)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 276 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a200)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 277 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a280)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 278 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a300)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 279 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a380)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 280 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a480)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 281 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a500)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 282 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a580)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 283 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a600)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 284 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a680)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 285 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a700)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 286 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc00062a780)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 43 [select]:
        github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.(*vInfo).logLoop(0xc004208300)
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:88 +0xf3
        created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver.newVInfo
        	/home/wei/matrixone/pkg/vm/engine/tae/logstore/driver/batchstoredriver/vinfo.go:69 +0x1d7
    leak.go:138: Leaked goroutine: goroutine 69 [chan receive]:
        github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0030d4a10)
        	/home/wei/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x8b
        created by github.com/panjf2000/ants/v2.NewPool
        	/home/wei/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:137 +0x365
    leak.go:138: Leaked goroutine: goroutine 70 [chan receive]:
        github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0030d4a80)
        	/home/wei/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x8b
        created by github.com/panjf2000/ants/v2.NewPool
        	/home/wei/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:137 +0x365
--- FAIL: TestCheckpointUC (5.29s)

FAIL
```

### Expected Behavior

We should fix all possible goroutine leaks.

**Comment by w-zr** [comment]
Tests with goroutine leaks:
* TestSetupMOLogger
* TestTaskHolderCanCreateTaskService
* TestRefreshTaskStorageCanRefresh
* TestMysqlResultSet
* Test_Closed
* TestNewSenderWithOptions
* TestMOCollector_HangBug
* TestNewMerge
* TestMergeTaskExecutorFactory
* TestDriver
* TestCheckpointUC
* TestHandle_HandlePreCommit1PC
* TestHandle_HandlePreCommit2PCForCoordinator
* TestHandle_HandlePreCommit2PCForParticipant
* TestHandle_MVCCVisibility
* TestEngine
* TestEngineAllType
* TestTxnRelation_GetHideKey
* TestSysRelation
* TestTxnCleintNewWithSnapshot
* TestReplay
* TestWal
* TestAppendRead
* Many other tests under `pkg/vm/engine/tae/db`, `pkg/vm/engine/tae/txn/txnimpl`.
