### ISSUE TITLE
[Bug]: mo panic for invalid slice by range  when run sysbench mixed cases

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6422]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2af3bb113fd38e77ba739956fa87fc6c2c91ebf1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022/11/09 00:05:55.439471 +0800 INFO frontend/util.go:495 query trace status {"connection_id": 4294967295, "statement": "commit", "status": "success", "session_info": ""}
2022/11/09 00:05:55.439742 +0800 ERROR cn-service morpc/backend.go:506 read from backend failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000", "error": "read tcp4 127.0.0.1:44136->127.0.0.1:22000: use of closed network connection"}
2022/11/09 00:05:55.439847 +0800 INFO cn-service morpc/backend.go:336 write loop stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000"}
panic: invalid slice by range [964, 968), writeIndex 62

goroutine 1738 [running]:
github.com/fagongzi/goetty/v2/buf.(*ByteBuf).RawSlice(0xc0034296d0, 0x1bf?, 0x3c8)
        /home/sudong/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/buf/buf.go:199 +0x109
github.com/matrixorigin/matrixone/pkg/common/morpc.(*baseCodec).Encode(0xc0007c96b0, {0x23d48a0?, 0xc0b83973e0?}, 0xc0034296d0, {0x292cc60, 0xc0058826a8})
        /data1/sudong/mo-regression/matrixone/pkg/common/morpc/codec.go:252 +0x585
github.com/matrixorigin/matrixone/pkg/common/morpc.(*messageCodec).Encode(0x30?, {0x23d48a0?, 0xc0b83973e0?}, 0xc009593ba0?, {0x292cc60?, 0xc0058826a8?})
        /data1/sudong/mo-regression/matrixone/pkg/common/morpc/codec.go:97 +0x31
github.com/fagongzi/goetty/v2.(*baseIO).Write(0xc005bdcb00, {0x23d48a0, 0xc0b83973e0}, {0xd?, 0x0?})
        /home/sudong/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/session.go:420 +0xaf
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).writeLoop(0xc005dfa5a0, {0x296bcd0, 0xc00697c380})
        /data1/sudong/mo-regression/matrixone/pkg/common/morpc/backend.go:449 +0x6f8
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /data1/sudong/mo-regression/matrixone/pkg/common/stopper/stopper.go:258 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /data1/sudong/mo-regression/matrixone/pkg/common/stopper/stopper.go:253 +0x12c
"server.log" 1199581L, 170499704C

### Steps to Reproduce

```Markdown
run mo with etc/launch-tae-CN-tae-DN/launch.toml
run sysbench mixed case test just for several seconds
how to run sysbench insert test:
1.git clone https://github.com/aressu1985/mo-load.git
2.modify mo addr in mo.yml
3.create database
create database sbtest;
4. git clone https://github.com/aressu1985/mo-sysbench.git
5.generate data
cd mo-sysbench & sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_common.lua --tables=10 --table_size=10000 --threads=1 --time=30 --report-interval=10 --create_secondary=off --auto_inc=off prepare

6.run test
./start.sh -c cases/sysbench/mixed_10_10000/
```

### Additional information

[Uploading server.log.panic.slice.zip…]()

**Comment by aressu1985** [comment]
fixed:2af3bb113fd38e77ba739956fa87fc6c2c91ebf1
