### ISSUE TITLE
[Bug]: mo panic for invalid slice by range when run tpcc test for about 1 hour

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6488]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):aa08658ede5fe71a6d9cfa93e19601a7b7439adc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

error:
2022/11/10 22:47:52.844367 +0800 DEBUG cn-service morpc/backend.go:445 write request {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000", "request-id": 603372, "request": "603372: <ce1838fc163b4f1fa83f4557e95ab986/Active/S:1668091600836089430-0>/Write/F-0/<O:1002-D:17776>/=><2-262146-0-127.0.0.1:22000>"}
2022/11/10 22:47:52.844445 +0800 DEBUG cn-service morpc/backend.go:445 write request {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000", "request-id": 603373, "request": "603373: <430242fde07c41fe9b5bc84a0455917a/Active/S:1668091670940906509-0>/Read/F-0/<O:1000-D:447>/=><2-262146-0-127.0.0.1:22000>"}
2022/11/10 22:47:52.844531 +0800 ERROR cn-service morpc/backend.go:505 read from backend failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000", "error": "read tcp4 127.0.0.1:56202->127.0.0.1:22000: use of closed network connection"}
2022/11/10 22:47:52.844576 +0800 DEBUG cn-service v2@v2.0.3-0.20221103025002-a4c7a0d38815/session.go:487 conneciton disconnected {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000", "session-id": 0}
2022/11/10 22:47:52.844609 +0800 DEBUG cn-service v2@v2.0.3-0.20221103025002-a4c7a0d38815/session.go:372 IOSession closed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000", "session-id": 0}
2022/11/10 22:47:52.844631 +0800 INFO cn-service morpc/backend.go:336 write loop stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "remote": "127.0.0.1:22000"}
panic: invalid slice by range [964, 968), writeIndex 62

goroutine 687 [running]:
github.com/fagongzi/goetty/v2/buf.(*ByteBuf).RawSlice(0xc08fa99400, 0x1bf?, 0x3c8)
	/home/sudong/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/buf/buf.go:199 +0x109
github.com/matrixorigin/matrixone/pkg/common/morpc.(*baseCodec).Encode(0xc005a104b0, {0x23ea480?, 0xc095d9d860?}, 0xc08fa99400, {0x2941620, 0xc02fbe1298})
	/data1/sudong/mo-regression/matrixone/pkg/common/morpc/codec.go:252 +0x585
github.com/matrixorigin/matrixone/pkg/common/morpc.(*messageCodec).Encode(0x30?, {0x23ea480?, 0xc095d9d860?}, 0xc005bda820?, {0x2941620?, 0xc02fbe1298?})
	/data1/sudong/mo-regression/matrixone/pkg/common/morpc/codec.go:97 +0x31
github.com/fagongzi/goetty/v2.(*baseIO).Write(0xc004a8c200, {0x23ea480, 0xc095d9d860}, {0xc0663ba380?, 0x2?})
	/home/sudong/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/session.go:420 +0xaf
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).writeLoop(0xc0002345a0, {0x2980bd0, 0xc0007a8400})
	/data1/sudong/mo-regression/matrixone/pkg/common/morpc/backend.go:448 +0x6d4
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/data1/sudong/mo-regression/matrixone/pkg/common/stopper/stopper.go:258 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/data1/sudong/mo-regression/matrixone/pkg/common/stopper/stopper.go:253 +0x12c

2022/11/10 22:47:52.789903 +0800 DEBUG cn-service.txn util/log.go:31 txn created {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "txn": "939fae11e8054b8d9bdb6f306d3d3457/Active/S:1668091672789894628-0"}
2022/11/10 22:47:52.790050 +0800 ERROR disttae/util.go:191 error: internal error: zonemap is nil
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.getZonemapDataFromMeta
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/util.go:191
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.needRead
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/txn.go:718
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*table).Ranges
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/table.go:122
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:1251
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:609
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:362
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:379
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:487
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:232
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:157
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/compile.go:74
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:2165
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:2720
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3179
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:159

### Steps to Reproduce

```Markdown
1.git clone https://github.com/aressu1985/mo-tpcc
  
2.start MO：
  
3. create databas and tables;
   source xxx/mo-tpcc/sql/tableCreates_pk.sql; 

4. modify props.mo
  warehouses=10
  terminals=10
  runMins any value > 120

5. generate tpcc data
   mkdir data
   ./runLoader.sh props.mo warehouse 10 filelocation data/

6、laod data to tpcc database
load data infile '/path/to/mo-tpcc/data/config.csv' into table bmsql_config;
load data infile '/path/to/mo-tpcc/data/cust-hist.csv' into table bmsql_history;
load data infile '/path/to/mo-tpcc/data/customer.csv' into table bmsql_customer;
load data infile '/path/to/mo-tpcc/data/district.csv' into table bmsql_district;
load data infile '/path/to/mo-tpcc/data/item.csv' into table bmsql_item;
load data infile '/path/to/mo-tpcc/data/new-order.csv' into table bmsql_new_order;
load data infile '/path/to/mo-tpcc/data/order-line.csv' into table bmsql_order_line;
load data infile '/path/to/mo-tpcc/data/order.csv' into table bmsql_oorder;
load data infile '/path/to/mo-tpcc/data/stock.csv' into table bmsql_stock;
load data infile '/path/to/mo-tpcc/data/warehouse.csv' into table bmsql_warehouse;

7. run benchmark test
./runBenchmark.sh props.mo
```

### Additional information

the size of log is more than 2.8G, if want complete log, contact me

**Comment by zhangxu19830126** [comment]
fixed by 6516

**Comment by zhangxu19830126** [comment]
I ran Sysbench for 10 minutes without the panic problem. I think it is solved

**Comment by aressu1985** [comment]
tonight I  will test it for a whole night

**Comment by aressu1985** [comment]
continue testing

**Comment by aressu1985** [comment]
fixed:c12eb45b1314e80f11fe8883055982c8ab0ca7fd
