### ISSUE TITLE
[Bug]: DN crashed during startup

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#6523]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b9c225f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when I deployed a mo cluster in eks, dn crashed the first time error log is as follows:
```
{"level":"INFO","time":"2022/11/12 07:49:43.095601 +0000","name":"dn-service","caller":"service/service.go:125","msg":"gc zombie txn task started","uuid":"00000000-0000-0000-0000-100000000000","dn-shard":"2-262148-1-mo-dn-0.mo-dn-headless.maomao.svc:41010","dn-shard":"2-262148-1-mo-dn-0.mo-dn-headless.maomao.svc:41010","dn-shard":"2-262148-1-mo-dn-0.mo-dn-headless.maomao.svc:41010"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x190bb15]

goroutine 4463 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).dedupWithPK(0xc006969ef0, {0x2a1a878, 0xc0089df8c0}, {0x0, 0x0, 0x0, 0x0, 0x11, 0xf9, 0x1e, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/block.go:888 +0x135
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).BatchDedup(0xc006969ef0, {0x2a27fb0, 0xc0089daaa0}, {0x2a1a878?, 0xc0089df8c0}, 0x0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/block.go:961 +0x6a6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Dedup(0xc00800e1b0, {0x2a1a878, 0xc0089df8c0})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:716 +0x232
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).DoBatchDedup(0xc00800e1b0, {0x2a1a878, 0xc0089df8c0})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:817 +0x113
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0xc00800e1b0, 0xc0089d9180)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:515 +0x6c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0xc0089d2280?, 0xc0089d6800?, 0xc008a5463c?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121 +0x4f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0xc0089dfa40?, 0x2?, 0x2a1c218?, 0x23e8b60?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:181 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0xc0089dab60, 0xc008a5463c?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:162 +0x68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0xc0089e07e0, {0x1726c6ea?, 0x16?}, 0xc008a2ac80)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:54 +0x318
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(_, {_, _}, {{0xc008a54200, 0x10, 0x10}, 0x0, {0x1726c6ea001ef911, 0x0, 0x38b2, ...}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:566 +0x232
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(0xc008012420, {_, _}, {{0xc008a54200, 0x10, 0x10}, 0x0, {0x1726c6ea001ef911, 0x0, 0x38b2, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:118 +0x785
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(0x2169e80?, {_, _}, {{0xc008a54200, 0x10, 0x10}, 0x0, {0x1726c6ea001ef911, 0x0, 0x38b2, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:70 +0x75
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc007fd3320, {0x29a1ab8, 0xc0089e04b0}, 0xc007fe69a0, 0xc0061fd300)
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:231 +0xd05
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc003277448?, {0x29a1ab8, 0xc0089e04b0}, 0xc007fe69a0, 0xc0061fd300)
        /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0xc003277400, {0x29a1ab8, 0xc0089e04b0}, {0x29c6318?, 0xc007fe69a0?}, 0x10?, {0x29604c0, 0xc0068bc2c0})
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:140 +0x462
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0030a3d40, {0x29ed300, 0xc00657d600}, {0x23ff2c0?, 0xc0089e0510}, 0x17c)
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:194 +0x552
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc003141ea0, {0x29ed300, 0xc00657d600})
        /go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221112031939-24c732da4b95/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
        /go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221112031939-24c732da4b95/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
        /go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221112031939-24c732da4b95/application.go:336 +0x4c5

```

### Steps to Reproduce

```Markdown
just deploy a mo cluster, this failure occasionally occurred. configuration I use is here: 

apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
  namespace: maomao
spec:
  dn:
    cacheVolume:
      size: 1Gi
    config: |2

      [dn]

      [dn.Ckp]
      flush-interval = "60s"
      global-interval = "100000s"
      incremental-interval = "180s"
      min-count = 100
      scan-interval = "5s"

      [dn.Txn]

      [dn.Txn.Storage]
      backend = "TAE"
      fileservice = "S3"
      log-backend = "logservice"

      [dn.rpc]
      max-message-size = "100mb"

      [log]
      level = "info"

      [observability]
      disableMetric = true
      disableTrace = true
    nodeSelector:
      kubernetes.io/arch: amd64
    replicas: 1
    resources: {}
  imageRepository: matrixorigin/matrixone
  logService:
    config: |2

      [log]
      level = "info"

      [observability]
      disableMetric = true
      disableTrace = true
    initialConfig:
      dnShards: 1
      logShardReplicas: 3
      logShards: 1
    nodeSelector:
      kubernetes.io/arch: amd64
    pvcRetentionPolicy: Delete
    replicas: 3
    resources: {}
    sharedStorage:
      s3:
        path: maomao-moc-test/test1112-0
        region: us-west-2
        secretRef:
          name: aws
    storeFailureTimeout: 5m0s
    volume:
      size: 1Gi
  tp:
    cacheVolume:
      size: 1Gi
    config: |2

      [cn]

      [cn.Engine]
      type = "distributed-tae"

      [cn.rpc]
      max-message-size = "100mb"

      [log]
      level = "info"

      [observability]
      disableMetric = true
      disableTrace = true
    nodeSelector:
      kubernetes.io/arch: amd64
    replicas: 2
    resources: {}
    serviceType: ClusterIP
  version: nightly-b9c225f4


```
```


### Additional information

the full log is here: 
[dn-crash.log](https://github.com/matrixorigin/matrixone/files/9994589/dn-crash.log)

**Comment by sukki37** [comment]
verified that the log service's data caused the issue was not stored persistently
