### ISSUE TITLE
[Bug]: moo panic by oom when run tpcc and sysbench for about 1.5 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6528]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b9c225f4f44dcd62d6f577394d705b6aed55188e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022/11/13 00:52:38.191750 +0800 INFO frontend/util.go:495 query trace {"connection_id": 1057, "query": "UPDATE sbtest2 SET k=k+100 WHERE id = 386;", "session_info": "connectionId 1057"}
2022/11/13 00:52:38.194608 +0800 INFO mpool/mpool.go:84 MPool global new high watermark
     allocations : 197002205
     frees : 155975614
     go runtime allocations : 0
     alloc bytes : 3878609755645
     free bytes : 2779098387695
     current bytes : 1099511367950
     high water mark : 1099511892238

2022/11/13 00:52:38.194965 +0800 ERROR mpool/mpool.go:526 error: error: out of memory
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Alloc
        /data1/sudong/mo-regression/matrixone/pkg/common/mpool/mpool.go:526
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:74
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:156
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vecbase.go:74
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vector.go:174
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/model.PreparePhyAddrDataWithPool
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/model/preparer.go:36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:133
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:93
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:62
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/reader.go:81
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
        /data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:63
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:55
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73
panic: error: out of memory

goroutine 32909261 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand(0xc0b285c1e0?, 0x428c0d)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:76 +0x1d1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append(0xc0b285c1e0?, {0x0, 0x0, 0x0, 0x0,  
0x4, 0x0, 0x0, 0x0, 0x0, ...})
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:156 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append(0x0?, {0x221f0a0?, 0xc04a693ab0?})
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vecbase.go:74 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append(0x1000000000?, {0x221f0a0?, 0xc04a693ab0?})
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vector.go:174 +0x32
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/model.PreparePhyAddrDataWithPool({0x65, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0},,
 {0xc19863b900, 0xc, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/model/preparer.go:36 +0x163
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc({0x299f678, 0xc1a962b080}, 0x2e38, 00
x400, {0xc206adc370?, 0x184280?}, {0xc1c7efd7a0, 0x11, 0x2000?}, {0xc0a5265c20, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:133 +0x957
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner({0x299f678, 0xc1a962b080}, 0xc190e72f28, {0xc11
c7efd7a0, 0x11, 0x11}, {0xc0a5265c20?, 0xc24256dc58?, 0x41e6ff?}, {0xc11fb7b080, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:93 +0x11c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead({0x299f678, 0xc1a962b080}, 0x3d76b20?, {0xc1c7efd7aa
0, 0x11, 0x11}, {0xc0a5265c20, 0x11, 0x11}, {0xc11fb7b080, ...}, ...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:62 +0x27a
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read(0xc1a2ddfd40, {0xc1c7efd7a0?, 0x11?, 0x11?}, 0xc24255
6df50?, 0x68?)

### Steps to Reproduce

```Markdown
run sysbench mixed cases and tpcc 10warehouse-10terminals about 1.5 hours
```

### Additional information

the log size is more than 1.5 G, if want, contact me offline

**Comment by nnsgmsone** [comment]
I don't know how to run tpcc, so I can't analyze this issue for now.

**Comment by nnsgmsone** [comment]
The reason for this is that the mpool used internally by tae is not properly freed after allocation. In addition to the tae, the loaded memory is also not freed properly. A very simple way to verify this is to replace the make of mpool with the malloc of c. This will block the gc of go, and the problem of unfree memory can be easily seen. @LeftHandCold  please take a look.

**Comment by aressu1985** [comment]
Appear again


2022/11/13 23:03:15.554226 +0800 INFO frontend/util.go:510 time of Exec.Run : 29.964043ms connectionId 1035
2022/11/13 23:03:15.554323 +0800 INFO frontend/util.go:510 time of SendResponse 1.651µs connectionId 1035
2022/11/13 23:03:15.554517 +0800 INFO frontend/util.go:495 query trace status {"connection_id": 1035, "statement": "delete from sbtest4 where id = 87781", "status": "success", "session_info": "connectionId 1035"}
2022/11/13 23:03:15.555253 +0800 INFO logtail/handle.go:429 [Logtail] record block meta row <0:272452-1081-34771-0-0>, false, 1668351398495571808-0, 1668351793501323671-0, f9755cc6-c9c1-4c42-bacd-b6126d3770c1:11951_576_576:59:11759, a39a103f-ec92-406a-bee0-8e03a801c6e7:12309_448_448:0:11541
2022/11/13 23:03:15.555375 +0800 INFO logtail/handle.go:429 [Logtail] record block meta row <0:272452-1081-35767-0-0>, false, 1668351793501323671-0, 0-0, a39a103f-ec92-406a-bee0-8e03a801c6e7:11733_576_576:58:11541, 
2022/11/13 23:03:15.555466 +0800 INFO logtail/handle.go:501 [Logtail] send block meta for "sbtest7"
2022/11/13 23:03:15.555501 +0800 INFO logtail/handle.go:501 [Logtail] send block meta for "sbtest7"
2022/11/13 23:03:15.560666 +0800 INFO mpool/mpool.go:84 MPool global new high watermark
     allocations : 540024982
     frees : 445057676
     go runtime allocations : 0
     alloc bytes : 12780414583712
     free bytes : 11680902713670
     current bytes : 1099511870046
     high water mark : 1099511949816

2022/11/13 23:03:15.560890 +0800 ERROR mpool/mpool.go:526 error: error: out of memory
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Alloc
	/data1/sudong/mo-regression/matrixone/pkg/common/mpool/mpool.go:526
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:74
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:156
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vecbase.go:74
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vector.go:174
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/model.PreparePhyAddrDataWithPool
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/model/preparer.go:36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:139
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:99
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:62
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/reader.go:81
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
	/data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:63
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:55
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73
2022/11/13 23:03:15.561028 +0800 ERROR mpool/mpool.go:526 error: error: out of memory
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Alloc
	/data1/sudong/mo-regression/matrixone/pkg/common/mpool/mpool.go:526
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Realloc
	/data1/sudong/mo-regression/matrixone/pkg/common/mpool/mpool.go:609
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Grow
	/data1/sudong/mo-regression/matrixone/pkg/common/mpool/mpool.go:675
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).extend
	/data1/sudong/mo-regression/matrixone/pkg/container/vector/tools.go:333
github.com/matrixorigin/matrixone/pkg/container/vector.appendOne[...]
	/data1/sudong/mo-regression/matrixone/pkg/container/vector/vector.go:711
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Append
	/data1/sudong/mo-regression/matrixone/pkg/container/vector/vector.go:750
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.Nullable.AppendVector
	/data1/sudong/mo-regression/matrixone/pkg/txn/storage/memorystorage/memtable/nullable.go:52
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PartitionReader).Read
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/partition_reader.go:161
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/reader.go:172
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
	/data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:63
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:55
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73
panic: error: out of memory

goroutine 54760870 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand(0xc3c5229920?, 0x41ea47)
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:76 +0x1d1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append(0xc3c5229920?, {0x0, 0x0, 0x0, 0x0, 0x4, 0xc, 0x0, 0x0, 0x0, ...})
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:156 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append(0x0?, {0x221fa20?, 0xc07b570550?})
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vecbase.go:74 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append(0x1000000000?, {0x221fa20?, 0xc07b570550?})
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/containers/vector.go:174 +0x32
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/model.PreparePhyAddrDataWithPool({0x65, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0}, {0xc1c00d18f0, 0xc, ...}, ...)
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/model/preparer.go:36 +0x163
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc({0x29a0058, 0xc2d0354e70}, 0x8922, 0x40c, {0xc2adf37d60?, 0x18?}, {0xc3892940a0, 0xa, 0x7fac52fed368?}, {0xc31a18e600, ...}, ...)
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:139 +0x957
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner({0x29a0058, 0xc2d0354e70}, 0xc3892a3660, {0xc3892940a0, 0xa, 0xa}, {0xc31a18e600?, 0xc2d32b6900?, 0x0?}, {0xc372890750, ...}, ...)
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:99 +0x11c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead({0x29a0058, 0xc2d0354e70}, 0x3d77b40?, {0xc3892940a0, 0xa, 0xa}, {0xc31a18e600, 0xa, 0xa}, {0xc372890750, ...}, ...)
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:62 +0x27a
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read(0xc33d01b6c0, {0xc3892940a0?, 0xa?, 0xa?}, 0x0?, 0x0?)
	/data1/sudong/mo-regression/matrixone/pkg/vm/engine/disttae/reader.go:81 +0x393
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc1c00d1f28, {0x297a498, 0xc33d01b6c0}, 0xc1c9056780)
	/data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:63 +0x145
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x0?, 0x0?)
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:55 +0xc8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x0?)
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:68 +0x18d

**Comment by LeftHandCold** [comment]
{
	"global": {
		"alloc": 58575806,
		"free": 45751385,
		"goalloc": 0,
		"allocBytes": 1970794382096,
		"freeBytes": 1960181892748,
		"currBytes": 10612489348,
		"highWaterMark": 10721110717
	}
}, {
	"session": {
		"alloc": 1202,
		"free": 1202,
		"goalloc": 0,
		"allocBytes": 422601,
		"freeBytes": 422601,
		"currBytes": 0,
		"highWaterMark": 7744
	}
}, {
	"fallback_proc_mp": {
		"alloc": 15950032,
		"free": 8869611,
		"goalloc": 0,
		"allocBytes": 137470988,
		"freeBytes": 104150420,
		"currBytes": 33320568,
		"highWaterMark": 33320582
	}
}, {
	"zero_fixed_mp_for_test": ""
}, {
	"session": {
		"alloc": 2722987,
		"free": 2297481,
		"goalloc": 0,
		"allocBytes": 85836505705,
		"freeBytes": 84992869237,
		"currBytes": 843636468,
		"highWaterMark": 1061683352
	}
}, {
	"session": {
		"alloc": 2699304,
		"free": 2276781,
		"goalloc": 0,
		"allocBytes": 77319601910,
		"freeBytes": 76499090610,
		"currBytes": 820511300,
		"highWaterMark": 1046200892
	}
}, {
	"session": {
		"alloc": 18953,
		"free": 17970,
		"goalloc": 0,
		"allocBytes": 7103096,
		"freeBytes": 7083572,
		"currBytes": 19524,
		"highWaterMark": 27260
	}
}, {
	"tae_default": {
		"alloc": 4620082,
		"free": 4619922,
		"goalloc": 0,
		"allocBytes": 1137330990965,
		"freeBytes": 1137121493109,
		"currBytes": 209497856,
		"highWaterMark": 536519508
	},{
	"session": {
		"alloc": 2735346,
		"free": 2311650,
		"goalloc": 0,
		"allocBytes": 83594473942,
		"freeBytes": 82739222498,
		"currBytes": 855251444,
		"highWaterMark": 991611820
	}
}, {
	"session": {
		"alloc": 31,
		"free": 31,
		"goalloc": 0,
		"allocBytes": 940,
		"freeBytes": 940,
		"currBytes": 0,
		"highWaterMark": 314
	}
}, {
	"tae_cache": {
		"alloc": 7,
		"free": 0,
		"goalloc": 0,
		"allocBytes": 16760832,
		"freeBytes": 0,
		"currBytes": 16760832,
		"highWaterMark": 16760832
	}
}, {
	"session": {
		"alloc": 2725608,
		"free": 2304328,
		"goalloc": 0,
		"allocBytes": 86902669920,
		"freeBytes": 86072065362,
		"currBytes": 830604558,
		"highWaterMark": 931589228
	}
}, {
	"session": {
		"alloc": 2739481,
		"free": 2312247,
		"goalloc": 0,
		"allocBytes": 78123815781,
		"freeBytes": 77276540909,
		"currBytes": 847274872,
		"highWaterMark": 1087559408
	}
}, {
	"session": {
		"alloc": 2704472,
		"free": 2291595,
		"goalloc": 0,
		"allocBytes": 78947152112,
		"freeBytes": 78117081260,
		"currBytes": 830070852,
		"highWaterMark": 1024205076
	}
}, {
	"session": {
		"alloc": 2759877,
		"free": 2317789,
		"goalloc": 0,
		"allocBytes": 79070615097,
		"freeBytes": 78223961873,
		"currBytes": 846653224,
		"highWaterMark": 1079525972
	}
}, {
	"tae_immutable": {
		"alloc": 15314,
		"free": 15278,
		"goalloc": 0,
		"allocBytes": 4551395136,
		"freeBytes": 4545057280,
		"currBytes": 6337856,
		"highWaterMark": 200451008
	}, {
	"distributed_tae": {
		"alloc": 4518989,
		"free": 3002605,
		"goalloc": 0,
		"allocBytes": 10090337061,
		"freeBytes": 8105703465,
		"currBytes": 1984633596,
		"highWaterMark": 1984636604
	}
}, {
	"tae_log": {
		"alloc": 7,
		"free": 0,
		"goalloc": 0,
		"allocBytes": 5963776,
		"freeBytes": 0,
		"currBytes": 5963776,
		"highWaterMark": 5963776
	}
}, {
	"session": {
		"alloc": 2733495,
		"free": 2311931,
		"goalloc": 0,
		"allocBytes": 81588455358,
		"freeBytes": 80733746634,
		"currBytes": 854708724,
		"highWaterMark": 1073188808
	}
}, {
	"session": {
		"alloc": 2687984,
		"free": 2274992,
		"goalloc": 0,
		"allocBytes": 82519898200,
		"freeBytes": 81724896892,
		"currBytes": 795001308,
		"highWaterMark": 1037462516
	}
}, {
	"session": {
		"alloc": 21,
		"free": 18,
		"goalloc": 0,
		"allocBytes": 5581,
		"freeBytes": 5557,
		"currBytes": 24,
		"highWaterMark": 5424
	}
}, {
	"session": {
		"alloc": 2705705,
		"free": 2289045,
		"goalloc": 0,
		"allocBytes": 80092624669,
		"freeBytes": 79260382103,
		"currBytes": 832242566,
		"highWaterMark": 1055179840
	}
}

**Comment by LeftHandCold** [comment]
The result after running for an hour, I don't know why there are so many session without free

**Comment by LeftHandCold** [comment]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/14086886/201582862-33d06b25-3759-4e1c-b7b7-72bba899152b.png">
a session has 20G without free, and the test environment has 50 sessions.

**Comment by LeftHandCold** [comment]
log :  128:/data1/sudong/mo-regression/matrixone/server.log

**Comment by LeftHandCold** [comment]
[session.log](https://github.com/matrixorigin/matrixone/files/10002596/session.log)
I took a 22G sample to check, the session accounted for a total of 18G, please help @jianwan0214  to take a look

**Comment by daviszhen** [comment]
I is updated today. A new PR will be submitted tomorrow

**Comment by nnsgmsone** [comment]
fixed by #6750

**Comment by daviszhen** [comment]
After the work of  @nnsgmsone and @jianwan0214 is submitted, it is fixed.
