### ISSUE TITLE
[Bug]: load data during, kill mo process, start mo failed.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6889]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Reproducible Steps

commit id: 2f62c7d7c082f91416190e882ae9c7e30cbb8855
128 server:

mo.log path: /data1/tianyahui/matrixone/mo_2.log

1.execute: cd /data/mo-load-data
2.execute: bash load.sh -c cases/table_40000000_100_columns.yml
3.kill mo process
4. execute ./mo-service  -launch ./etc/launch-tae-CN-tae-DN/launch.toml > mo.log 2>&1 &

**Comment by daviszhen** [comment]
I reproduce the boot failure (I am not sure it is same as the description in the case) at the server 128.

I got error:
```
2022/11/24 21:15:45.183029 +0800 INFO logutil/internal.go:36 MO logger init, level=info, log file=
2022/11/24 21:15:45.185495 +0800 INFO trace/trace.go:122 init GlobalBatchProcessor
2022/11/24 21:15:45.185550 +0800 INFO export/batch_processor.go:256 MOCollector Start
2022/11/24 21:15:45.186180 +0800 INFO trace/trace.go:127 init trace span processor
2022/11/24 21:15:45.186396 +0800 INFO trace/trace.go:92 trace with LongQueryTime: 0s
2022/11/24 21:15:45.186902 +0800 INFO metric/metric.go:130 metric with ExportInterval: 15s
2022/11/24 21:15:45.187009 +0800 INFO mo-service/config.go:209 hakeeper client cfg: { [127.0.0.1:32001] 0}
2022/11/24 21:15:45.187071 +0800 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2221 go version: go1.19.1, linux/amd64
2022/11/24 21:15:45.187093 +0800 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2223 dragonboat version: 4.0.0 (Dev)
2022/11/24 21:15:45.187102 +0800 WARN config config/config.go:534 mutual TLS disabled, communication is insecure
2022/11/24 21:15:45.187131 +0800 INFO config config/config.go:656 using default EngineConfig
2022/11/24 21:15:45.187300 +0800 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:349 DeploymentID set to 1
2022/11/24 21:15:45.187353 +0800 ERROR log-service logservice/service.go:107 failed to create log store {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "failed to lock data directory", "errorVerbose": "failed to lock data directory\n(1) attached stack trace\n  -- stack trace:\n  | github.com/lni/dragonboat/v4/internal/server.init\n  | \t/home/pengzhen/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/internal/server/environment.go:62\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6321\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.doInit\n  | \t/usr/local/go/src/runtime/proc.go:6298\n  | runtime.main\n  | \t/usr/local/go/src/runtime/proc.go:233\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1594\nWraps: (2) failed to lock data directory\nError types: (1) *withstack.withStack (2) *errutil.leafError"}
panic: failed to lock data directory

goroutine 1 [running]:
main.startLogService(0xc00342c000, 0xc0001ac000?, {0x2a40ae0, 0xc00342a558})
	/home/pengzhen/matrixone/cmd/mo-service/main.go:218 +0x329
main.startService(0xc00342c000, 0x4?)
	/home/pengzhen/matrixone/cmd/mo-service/main.go:136 +0x155
main.startLogServiceCluster({0xc0032dadc0?, 0x1, 0x219b9a0?}, 0xc003367860?)
	/home/pengzhen/matrixone/cmd/mo-service/launch.go:70 +0xc5
main.startCluster(0x2642ec2?)
	/home/pengzhen/matrixone/cmd/mo-service/launch.go:45 +0x88
main.main()
	/home/pengzhen/matrixone/cmd/mo-service/main.go:81 +0x29c

```

**Comment by volgariver6** [comment]
Did not repro it. Will try some more tests tomorrow. 

Should I kill the mo process with -9 or -15? @tianyahui-python

**Comment by volgariver6** [comment]
Cannot repro. After discussion, assign back to @tianyahui-python , then we do more tests later.

**Comment by tianyahui-python** [comment]
It never came back, downgraded from s0 to s1.

**Comment by tianyahui-python** [comment]
It never came back
