### ISSUE TITLE
[Bug]: sysbench 100 threads test, cn crash 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6998]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):2f62c7d7c082f91416190e882ae9c7e30cbb8855
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sysbench 100 thread test , cn  crash, and cn related log is upload to this issue
![image](https://user-images.githubusercontent.com/113406637/204450124-7f958d78-7b1d-4d83-8a56-73ef2559ba15.png)

log：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x18b2389]

goroutine 1030207 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*Batch).Close(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers/batch.go:162
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc.func2()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:155 +0x29
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc({0x2a180b8, 0xc008315590}, 0xc006831618, {0x0, 0x0, 0x0, 0x0, 0xa6, 0x7c, 0xb4, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:180 +0x5b6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner({0x2a180b8, 0xc008315590}, 0xc006831618, 0x228cd60?, {0xc00589b620?, 0xc02825c360?, 0xe9f436?}, {0xc0088b304c, 0x2, 0x2}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:88 +0xf6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead({0x2a180b8, 0xc008315590}, 0x0?, {0xc00589b620, 0x2, 0x2}, {0xc0088b304c, 0x2, 0x2}, {0xc006f539e0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:51 +0x2ae
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read(0xc0000f9880, {0xc00589b620?, 0x2?, 0x2?}, 0xc0131bbec0?, 0x954980?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/reader.go:82 +0x393
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc006a49f28, {0x29f6040, 0xc0000f9880}, 0xc0075df500)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:63 +0x145
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x0?, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:56 +0xc8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0xc008d63ef0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:74 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:69 +0x18d

### Steps to Reproduce

```Markdown
Using the sysbench tool:git clone https://github.com/matrixorigin/mo-sysbench.git
sysbench  --mysql-host=10.96.3.243 --mysql-port=6001 --mysql-db=sys_db --mysql-user=dump --mysql-password=111 --db-ps-mode=disable oltp_read_only.lua  --tables=10 --table_size=100000 --threads=100 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off --skip_trx=on --range_selects=off --point_selects=1 prepare
sysbench  --mysql-host=10.96.3.243 --mysql-port=6001 --mysql-db=sys_db --mysql-user=dump --mysql-password=111 --db-ps-mode=disable oltp_read_only.lua  --tables=10 --table_size=100000 --threads=100 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off --skip_trx=on --range_selects=off --point_selects=1 run
```

**Comment by heni02** [comment]
[mo_cncrach.log](https://github.com/matrixorigin/matrixone/files/10110229/mo_cncrach.log)

**Comment by heni02** [comment]
confirm,closed
commit id: 2bfec0c2c713d15b518f74f9cd2e2ab0f5076214 image:nightly-2bfec0c2
sysbench 100 no such problem. and also tested thread 128 256 500 can run
![image](https://user-images.githubusercontent.com/113406637/205197207-054032b0-024d-4bc0-8dc5-2293ade98bf7.png)
![image](https://user-images.githubusercontent.com/113406637/205197504-55fc6554-fc28-4aeb-b0dd-2c92c39a81d7.png)
![image](https://user-images.githubusercontent.com/113406637/205197612-24a15374-2b0e-4ba9-b4bd-bbe3d3e5520a.png)
![image](https://user-images.githubusercontent.com/113406637/205197646-a5f8e2b8-6369-4c36-9efd-81a59233d6e7.png)
