### ISSUE TITLE
[Bug]: mo panic after restart and connect-exit for several times

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7218]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):56c9590273867480f531aa0ee4c539d956e09c4e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the error message:

2022/12/15 22:28:34.613460 +0800 INFO frontend/util.go:499 query trace {"connection_id": 1011, "query": "execute __mo_stmt_id_1 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4,@__mo_stmt_var_5,@__mo_stmt_var_6,@__mo_stmt_var_7,@__mo_stmt_var_8,@__mo_stmt_var_9,@__mo_stmt_var_10,@__mo_stmt_var_11,@__mo_stmt_var_12", "vars": "2 , system.statement_info , {} , ETL_merge_task/system.statement_info , 2 , dd1dccb4-4d3c-41f8-b482-5251dc7a41bf , 1 , 1671114514485 , 0 ,  , 1671105600002 , 1671105682494 , 3", "session_info": "connectionId 1011"}
2022/12/15 22:28:34.615266 +0800 INFO frontend/util.go:514 time of Exec.Build : 1.424958ms connectionId 1011
2022/12/15 22:28:34.631493 +0800 INFO frontend/util.go:514 time of Exec.Run : 197.834µs connectionId 1011
2022/12/15 22:28:34.631938 +0800 INFO frontend/util.go:514 time of SendResponse 1.25µs connectionId 1011
2022/12/15 22:28:34.632139 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 1011, "statement": "execute __mo_stmt_id_1 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4,@__mo_stmt_var_5,@__mo_stmt_var_6,@__mo_stmt_var_7,@__mo_stmt_var_8,@__mo_stmt_var_9,@__mo_stmt_var_10,@__mo_stmt_var_11,@__mo_stmt_var_12", "status": "success", "span": {"trace_id": "c1bafe3a-7c84-11ed-b355-ce1bdd7cf1e9", "kind": "statement"}, "session_info": "connectionId 1011"}
2022/12/15 22:28:34.649599 +0800 INFO frontend/util.go:499 query trace {"connection_id": 1011, "query": "deallocate prepare __mo_stmt_id_1", "session_info": "connectionId 1011"}
2022/12/15 22:28:34.649732 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 1011, "statement": "deallocate prepare __mo_stmt_id_1", "status": "success", "span": {"trace_id": "c1c077de-7c84-11ed-b355-ce1bdd7cf1e9", "kind": "statement"}, "session_info": "connectionId 1011"}
2022/12/15 22:28:34.650343 +0800 INFO frontend/util.go:499 query trace {"connection_id": 1011, "query": "COMMIT", "session_info": "connectionId 1011"}
2022/12/15 22:28:34.667288 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 1011, "statement": "commit", "status": "success", "span": {"trace_id": "c1c321d2-7c84-11ed-b355-ce1bdd7cf1e9", "kind": "statement"}, "session_info": "connectionId 1011"}
2022/12/15 22:28:34.667449 +0800 ERROR taskservice/task_service.go:198 error: invalid task, task runner dd1dccb4-4d3c-41f8-b482-5251dc7a41bf, id 3 {"span": {"trace_id": "3dcf7915-db9d-6988-1c50-5c609820cd80", "span_id": "75979172e04e3bc0"}}
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskService).Heartbeat
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/taskservice/task_service.go:198
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).doHeartbeat
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/taskservice/task_runner.go:520
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).heartbeat
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/taskservice/task_runner.go:504
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/common/stopper/stopper.go:259
2022/12/15 22:28:34.667523 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:525 task heartbeat failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "invalid task, task runner dd1dccb4-4d3c-41f8-b482-5251dc7a41bf, id 3"}
panic: runtime error: index out of range [0] with length 0

goroutine 6752 [running]:
github.com/matrixorigin/matrixone/pkg/util/export.(*ContentReader).ReadLine(0x14019c0a8c0?)
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/util/export/merge.go:387 +0x1a0
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).doMergeFiles(0x1401b5779e0, {0x10465ef10, 0x14000169dc0}, {0x1400cf91da0, 0xe}, {0x14012f80000?, 0x2, 0x3e8}, 0x0)
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/util/export/merge.go:299 +0x640
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).Main(0x1401b5779e0, {0x10465ef10, 0x14000169dc0}, {0x3?, 0x0?, 0x105850ba0?})
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/util/export/merge.go:231 +0x358
github.com/matrixorigin/matrixone/pkg/util/export.MergeTaskExecutorFactory.func1({_, _}, {0x3, {{0x14010cf15c0, 0x26}, 0x2, {0x1400dceb0c8, 0x15, 0x15}, {0x0, ...}, ...}, ...})
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/util/export/merge.go:593 +0x438
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).run.func1({0x0?, 0x1022d9b28?})
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/taskservice/task_runner.go:398 +0x398
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/common/stopper/stopper.go:259 +0x6c
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/common/stopper/stopper.go:254 +0x150

### Steps to Reproduce

```Markdown
1. restart mo

2. connect to mo by mysql client

3. exit from mo

4. run 2 and 3 for several times (3 times)
```

**Comment by aressu1985** [comment]
[server.log](https://github.com/matrixorigin/matrixone/files/10237886/server.log)

**Comment by xzxiong** [comment]
some as https://github.com/matrixorigin/matrixone/issues/7040, not repro in my env.

**Comment by xzxiong** [comment]
working on repro

**Comment by xzxiong** [comment]
working on repro

**Comment by xzxiong** [comment]
working on repro

**Comment by xzxiong** [comment]
still try

**Comment by xzxiong** [comment]
still working on repro

**Comment by xzxiong** [comment]
still try repro

**Comment by xzxiong** [comment]
still try repro

**Comment by xzxiong** [comment]
working on

**Comment by aressu1985** [comment]
testing
