### ISSUE TITLE
[Bug]: mo crashed during repeat tpch 0.1 test whit `panic: unknown item type: <nil> <nil>`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7288]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 75140b7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run tpch 0.1 several times, mo will crash. full error log is here:
[mo-service.log.r1.75140b7.zip](https://github.com/matrixorigin/matrixone/files/10279677/mo-service.log.r1.75140b7.zip)

```
2022/12/22 00:41:54.513550 +0800 INFO rpc/handle.go:587 [precommit] handle write end txn: ctx[463D657DF95A4C16BD4269EC5B53B362][1671640913350495452-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

panic: unknown item type: <nil> <nil>

goroutine 1534 [running]:
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memorytable.Tuple.Less({0xc03fae6700, 0x4, 0x230400000000?}, {0xc03e392c00, 0x4, 0xc93234?})
        /data/qsq/matrixone/pkg/txn/storage/memorystorage/memorytable/tuple.go:119 +0x7fa
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.compareIndexEntry[...](0xc05ca336e0, 0xc02e021b00)
        /data/qsq/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:127 +0x54
github.com/tidwall/btree.(*BTreeG[...]).bsearch(0xc09e4c2240?, 0xc0772e2600, 0x4d0000007b090000)
        /root/go/pkg/mod/github.com/tidwall/btree@v1.4.3/generic.go:85 +0x86
github.com/tidwall/btree.(*BTreeG[...]).find(0x0?, 0xc006fdb860?, 0x7f69161cd208?, 0xc05ca336e0?, 0x7f699c792878?)
        /root/go/pkg/mod/github.com/tidwall/btree@v1.4.3/generic.go:100 +0x38
github.com/tidwall/btree.(*BTreeG[...]).delete(0xc09e4c2240, 0x4, 0x0?, 0x41e6ff, 0x2?, 0x0?)
        /root/go/pkg/mod/github.com/tidwall/btree@v1.4.3/generic.go:484 +0x96
github.com/tidwall/btree.(*BTreeG[...]).deleteHint(0xc09e4c2240, 0x7f699c792878, 0x30?)
        /root/go/pkg/mod/github.com/tidwall/btree@v1.4.3/generic.go:461 +0x50
github.com/tidwall/btree.(*BTreeG[...]).DeleteHint(0xc09e4c2240?, 0x1c8443?, 0x4d0000007b090000?)
        /root/go/pkg/mod/github.com/tidwall/btree@v1.4.3/generic.go:454 +0xd3
github.com/tidwall/btree.(*BTreeG[...]).Delete(...)
        /root/go/pkg/mod/github.com/tidwall/btree@v1.4.3/generic.go:444
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Table[...]).FilterVersions.func1()
        /data/qsq/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:610 +0x82c
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Table[...]).update(0xc011f60090, 0xc006fdbd80)
        /data/qsq/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:669 +0xb4
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Table[...]).FilterVersions(0xc006fdbdd8?, 0x478ff9?)
        /data/qsq/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:570 +0x4a
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Partition).GC(0xc024fe64d0?, {0x1732dc8ca74f10a5, 0x0, 0x8323, {}, {0x0, 0x0, 0x0}, 0x0})
        /data/qsq/matrixone/pkg/vm/engine/disttae/partition.go:318 +0x105
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).gc(0xc008a85f10, {0x2a4b030, 0xc0098fde80})
        /data/qsq/matrixone/pkg/vm/engine/disttae/engine.go:447 +0x4bb
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.New
        /data/qsq/matrixone/pkg/vm/engine/disttae/engine.go:66 +0x45e
```

### Steps to Reproduce

```Markdown
1. start mo-service
2. git clone https://github.com/matrixorigin/mo-tpch.git
3. cd mo-tpch
4. run the following script:


#!/bin/bash

for i in $(seq 1 10)
do
    if [ -d "./data/" ];then
        rm -rf ./data/
        sleep 2s
    fi
    ./run.sh -g -s 0.1
    ./run.sh -c -s 0.1
    ./run.sh -l -s 0.1
    ./run.sh -q all -s 0.1
done
```
```


### Additional information

_No response_

**Comment by sukki37** [comment]
Update，new error occurred in `b84dbe7`

```
2022/12/22 15:08:15.233128 +0800 INFO frontend/util.go:514 time of Exec.Build : 13.277224ms connectionId 1029
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d0220d]

goroutine 18307 [running]:
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Version[...]).Visible(0xc02687c0a0?, {{0x17330bd4c91fcdf5, 0x0, 0x8323, {}, {0x0, 0x0, 0x0}, 0x0}, 0x0}, ...)
        /data1/maomao/matrixone/pkg/txn/storage/memorystorage/memtable/physical_row.go:93 +0x4d
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*PhysicalRow[...]).readVersion(0xc022044100, {{0x17330bd4c91fcdf5, 0x0, 0x8323, {}, {0x0, 0x0, 0x0}, 0x0}, 0x0}, ...)
        /data1/maomao/matrixone/pkg/txn/storage/memorystorage/memtable/physical_row.go:66 +0x174
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*PhysicalRow[...]).Read(0xc00942a000?, {{0x17330bd4c91fcdf5, 0x0, 0x8323, {}, {0x0, 0x0, 0x0}, 0x0}, 0x0}, ...)
        /data1/maomao/matrixone/pkg/txn/storage/memorystorage/memtable/physical_row.go:52 +0x47
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*TableIter[...]).First(0xc00a324150)
        /data1/maomao/matrixone/pkg/txn/storage/memorystorage/memtable/table_iter.go:83 +0xd6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PartitionReader).Read(0xc0007aee70, {0x2ac51f0?, 0xc016614240?}, {0xc035170ff0, 0x3, 0x3}, 0x0?, 0xc00a4e1500?)
        /data1/maomao/matrixone/pkg/vm/engine/disttae/partition_reader.go:133 +0x27a
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read(0xc020c92b70, {0x2ac51f0, 0xc016614240}, {0xc035170ff0, 0x3, 0x3}, 0xc0031c8e08?, 0xc0031c8ea8?)
        /data1/maomao/matrixone/pkg/vm/engine/disttae/reader.go:176 +0xd3
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read(0xc020c92b58, {0x2ac51f0, 0xc016614240}, {0xc035170ff0, 0x3, 0x3}, 0xc0031c8f60?, 0x1e39297?)
        /data1/maomao/matrixone/pkg/vm/engine/disttae/reader.go:176 +0xd3
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc005867f28, {0x2aa2620, 0xc020c92b58}, 0xc011e01d40)
        /data1/maomao/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x169
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc0247d77c0?, 0x2ac5228?)
        /data1/maomao/matrixone/pkg/sql/compile/scope.go:56 +0xc8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x3fac720?)
        /data1/maomao/matrixone/pkg/sql/compile/scope.go:74 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /data1/maomao/matrixone/pkg/sql/compile/scope.go:69 +0x18d
```

**Comment by reusee** [comment]
I plan to replace this old mem table implementation with a new one.

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
I believe this is the same issue as #6991 which corrupts random positions in memory.

**Comment by reusee** [comment]
on sick leave.

**Comment by reusee** [comment]
on sick leave.

**Comment by reusee** [comment]
same as #6991

**Comment by reusee** [comment]
No longer reproducible in the main branch, re-assign to @aressu1985

**Comment by aressu1985** [comment]
tracking for 2 more days
