### ISSUE TITLE
[Bug]: dn panic: operation error S3: DeleteObject when running tpch queries on eks 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7686]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): aca93daf2528a20ac54dbc91692df33131279f3e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2023/01/18 07:08:10.791818 +0000","caller":"logtail/handle.go:541","msg":"[logtail] table data [Delete] 272386-%!%mo_increment_columns: [BatchName=data]\n(attr=__mo_rowid)[1]: BLK-324413:Off-1557\n(attr=commit_time)[1]: 1674025690735858801-0\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.810236 +0000","caller":"rpc/handle.go:812","msg":"[precommit] handle write typ: 1, 272386-%!%mo_increment_columns, 272385-mo_task\n txn: ctx[14FA7A09F6DE452DB44585705488D88B][1674025690784418152-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.810961 +0000","caller":"rpc/handle.go:819","msg":"[precommit] handle write end txn: ctx[14FA7A09F6DE452DB44585705488D88B][1674025690784418152-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.811060 +0000","caller":"rpc/handle.go:812","msg":"[precommit] handle write typ: 0, 272386-%!%mo_increment_columns, 272385-mo_task\n txn: ctx[14FA7A09F6DE452DB44585705488D88B][1674025690784418152-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.813363 +0000","caller":"rpc/handle.go:819","msg":"[precommit] handle write end txn: ctx[14FA7A09F6DE452DB44585705488D88B][1674025690784418152-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.824204 +0000","caller":"rpc/handle.go:812","msg":"[precommit] handle write typ: 1, 272387-sys_async_task, 272385-mo_task\n txn: ctx[B585B57AEF3E40E7A1CD0F39173DE290][1674025690773243523-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.824961 +0000","caller":"rpc/handle.go:819","msg":"[precommit] handle write end txn: ctx[B585B57AEF3E40E7A1CD0F39173DE290][1674025690773243523-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.825061 +0000","caller":"rpc/handle.go:812","msg":"[precommit] handle write typ: 0, 272387-sys_async_task, 272385-mo_task\n txn: ctx[B585B57AEF3E40E7A1CD0F39173DE290][1674025690773243523-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.825666 +0000","caller":"rpc/handle.go:819","msg":"[precommit] handle write end txn: ctx[B585B57AEF3E40E7A1CD0F39173DE290][1674025690773243523-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.829531 +0000","caller":"gc/manager.go:93","msg":"processing job=clean-transfer-table, inv=1m0s"}
{"level":"INFO","time":"2023/01/18 07:08:10.829648 +0000","caller":"gc/manager.go:93","msg":"processing job=checkpoint-gc, inv=1m0s"}
{"level":"INFO","time":"2023/01/18 07:08:10.829718 +0000","caller":"checkpoint/info.go:155","msg":"GC 1674013153766096686-0"}
{"level":"INFO","time":"2023/01/18 07:08:10.829753 +0000","caller":"gc/manager.go:93","msg":"processing job=logtail-gc, inv=1m0s"}
{"level":"WARN","time":"2023/01/18 07:08:10.829954 +0000","caller":"logtail/table.go:200","msg":"[logtail] fetch with too small ts","ts":"1674024877414608005-1","minTs":"1674024877429586639-0"}
{"level":"INFO","time":"2023/01/18 07:08:10.863204 +0000","caller":"logtail/handle.go:541","msg":"[logtail] table data [Insert] 272387-sys_async_task: [BatchName=data]\n(attr=__mo_rowid)[1]: BLK-324414:Off-1552\n(attr=commit_time)[1]: 1674025690826063907-0\n(attr=task_id)[1]: 207\n(attr=task_metadata_id)[1]: ETL_merge_task/system.statement_info:9\n(attr=task_metadata_executor)[1]: 2\n(attr=task_metadata_context)[1]: system.statement_info\n(attr=task_metadata_option)[1]: {}\n(attr=task_parent_id)[1]: ETL_merge_task/system.statement_info\n(attr=task_status)[1]: 1\n(attr=task_runner)[1]: 00000000-0000-0000-0000-200000000000\n(attr=task_epoch)[1]: 1\n(attr=last_heartbeat)[1]: 1674025690752\n(attr=result_code)[1]: 0\n(attr=error_msg)[1]: \n(attr=create_at)[1]: 1674014400000\n(attr=end_at)[1]: 0\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.863350 +0000","caller":"logtail/handle.go:541","msg":"[logtail] table data [Delete] 272387-sys_async_task: [BatchName=data]\n(attr=__mo_rowid)[1]: BLK-324414:Off-1539\n(attr=commit_time)[1]: 1674025690826063907-0\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.874859 +0000","caller":"logtail/handle.go:541","msg":"[logtail] table data [Insert] 272386-%!%mo_increment_columns: [BatchName=data]\n(attr=__mo_rowid)[1]: BLK-324413:Off-1559\n(attr=commit_time)[1]: 1674025690815654294-0\n(attr=name)[1]: 272387_task_id\n(attr=offset)[1]: 470\n(attr=step)[1]: 1\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.875051 +0000","caller":"logtail/handle.go:541","msg":"[logtail] table data [Delete] 272386-%!%mo_increment_columns: [BatchName=data]\n(attr=__mo_rowid)[1]: BLK-324413:Off-1558\n(attr=commit_time)[1]: 1674025690815654294-0\n"}
{"level":"INFO","time":"2023/01/18 07:08:10.875139 +0000","caller":"checkpoint/entry.go:198","msg":"GC checkpoint metadata CKP[I][2](1674003848764285712-1->1674003993764676415-0), err <nil>"}
{"level":"WARN","time":"2023/01/18 07:08:10.875300 +0000","caller":"checkpoint/runner.go:326","msg":"gc CKP[I][2](1674003848764285712-1->1674003993764676415-0) failed: operation error S3: DeleteObject, https response error StatusCode: 403, RequestID: 9R7G1NWPFY2H4Y0W, HostID: daqHfSSxHfs4SILNQuRGjlEHz3DIxlNAyX+5GT9n45wC8B7IQ8vaivdGP4BRqYnccMjqQR47BPR4GfqTubw5Pw==, api error AccessDenied: Access Denied"}
panic: operation error S3: DeleteObject, https response error StatusCode: 403, RequestID: 9R7G1NWPFY2H4Y0W, HostID: daqHfSSxHfs4SILNQuRGjlEHz3DIxlNAyX+5GT9n45wC8B7IQ8vaivdGP4BRqYnccMjqQR47BPR4GfqTubw5Pw==, api error AccessDenied: Access Denied

goroutine 33086 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).gcCheckpointEntries(0xc0030b5c80, {0x0, 0x0, 0x0, 0x0, 0x2e, 0x3f, 0x8f, 0x13, 0x18, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:327 +0x3d6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).onGCCheckpointEntries(0x418885?, {0x4a99c0?, 0xc006595b90?, 0xc0005c8ed0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:297 +0x65
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:81 +0x1f1
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:60 +0xea

**Comment by aressu1985** [comment]
it is not problem
