### ISSUE TITLE
[Bug]: worker exits from a panic: interface conversion: interface {} is types.Null, not []uint8 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7713]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Shell
- Version or commit-id (e.g. v0.1.0 or 8b23a93):29f9defeb5d82117d964149d32d9e354b66b3e4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2023/01/26 14:58:44 worker exits from a panic: interface conversion: interface {} is types.Null, not []uint8
2023/01/26 14:58:44.818352 +0800 DEBUG txnimpl/cmdmgr.go:80 ApplyTxnRecord LSN=12359, Size=539
2023/01/26 14:58:44.818443 +0800 DEBUG txnimpl/store.go:625 Txn-05B0924E90464652950B7552846F91A6 PrepareCommit Takes 107.7µs
2023/01/26 14:58:44.818454 +0800 DEBUG log-service v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:377 session read message {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-rpc", "listen-addresses": "[127.0.0.1:32001]", "session-id": 96, "addr": "127.0.0.1:36872", "seqence": 1038}
2023/01/26 14:58:44.818459 +0800 DEBUG txnbase/txnmgr.go:211 [PrePrepare] {"txn": {"id": "12BDB4D88E3D4618A5831DFE7C5740FF", "startTs": "1674716324798667739-0", "state": "Active"}, "duration": "1.907µs"}
2023/01/26 14:58:44.818458 +0800 DEBUG log-service util/log.go:33 txn read {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "txn": "10ac07c2e93a427cb7147fe6cf171778/Active/S:1674716324814362038-0"}
2023/01/26 14:58:44 worker exits from panic: goroutine 428106 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
    /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x25c6720, 0xc045f3da70})
    /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/varchar.Sort({0x2dd46d8, 0xc0111ea000}, {0xc01a7e9ae0, 0x4, 0xc0078df6f8?})
    /data/qsq/matrixone/pkg/vm/engine/tae/mergesort/varchar/func.go:26 +0x5dd
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc01e782a80, 0x4, 0x17?}, 0x3)
    /data/qsq/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:78 +0x665
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc036312bd0)
    /data/qsq/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:118 +0x3df
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc036312bd0)
    /data/qsq/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:138 +0x351
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc02dfa2b60)
    /data/qsq/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x82
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc04a440f00)
    /data/qsq/matrixone/pkg/vm/engine/tae/db/task.go:62 +0x12b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc047356fc0)
    /data/qsq/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x82
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0083809a0, {0x7fd114ebe818, 0xc04a440f00})
    /data/qsq/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:207 +0x36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
    /data/qsq/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x38
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
    /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
    /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

2023/01/26 14:58:44 worker exits from a panic: interface conversion: interface {} is types.Null, not []uint8
2023/01/26 14:58:44.818483 +0800 DEBUG txnbase/txn.go:299 Prepare Commite 12BDB4D88E3D4618A5831DFE7C5740FF
2023/01/26 14:58:44.818497 +0800 DEBUG txnimpl/txndb.go:529 Txn-12BDB4D88E3D4618A5831DFE7C5740FF PrepareCommit Takes 1.517µs
2023/01/26 14:58:44.818495 +0800 DEBUG log-service util/log.go:118 txn send requests {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "requests": "[0: <10ac07c2e93a427cb7147fe6cf171778/Active/S:1674716324814362038-0>/Read/F-0/<O:1000-D:460>/=><2-262146-0-127.0.0.1:22000>]"}
2023/01/26 14:58:44 worker exits from panic: goroutine 428029 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
    /root/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x25c6720, 0xc04cb6d8c0})
    /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/varchar.Sort({0x2dd46d8, 0xc00f073380}, {0xc011401660, 0x8, 0xc027aa76f8?})
    /data/qsq/matrixone/pkg/vm/engine/tae/mergesort/varchar/func.go:26 +0x5dd
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc03032a4c0, 0x4, 0x17?}, 0x3)
    /data/qsq/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:78 +0x665
```

### Steps to Reproduce

```Shell
1. git clone https://github.com/matrixorigin/matrixone.git && cd matrixone
2. go test -c -tags service_test -cover -covermode=count -coverpkg=./pkg/... ./cmd/mo-service/ -o service_test
3. ./service_test -test.coverprofile=bvt_coverage.out  -launch ./etc/launch-tae-multi-CN-tae-DN/launch.toml &>service.log &
4. git clone https://github.com/matrixorigin/mo-tester.git
5. cd mo-tester
6. ./run.sh -n -g -p ../test/distributed/cases 2>&1
7. ps aux|grep 'service_test' | grep -v 'grep' | awk '{print $2}' | xargs kill -s SIGINT
```

**Comment by XuPeng-SH** [comment]
The sort key is not nullable right now. Maybe we can support nullable sort key in next release.

**Comment by sukki37** [comment]
> The sort key is not nullable right now. Maybe we can support nullable sort key in next release.
Another question is, these errors are reported only after the kill signal is received, what's the root cause of the nullable sort key?

**Comment by aptend** [comment]
when compacting block 4602, panic happened. 
```sh
3802077:2023/01/26 14:58:44.818351 +0800 INFO jobs/compactblk.go:131 [Start] {"operation": "[7272]compact", "operand": "[A]BLK[<0:275201-2836-4602-0-0>]"}
```
and 4602 is belong to table `test04`, which is a table with a composite cluster-by key. And the composite key can be null if one of its member values is null.

this bug has nothing to do with `kill` command. I can't repro with `kill`ing

**Comment by aptend** [comment]
@sukki37 this issue can be closed, PTAL
