### ISSUE TITLE
[Bug]: DN panic on restart `panic: interface conversion: interface {} is int32, not []uint8`

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#8089]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6d4bd17
- Hardware parameters: EKS env
```

### Actual Behavior

DN panic after restart for multiple times, and will recover finally. Panic log:

```
panic: interface conversion: interface {} is int32, not []uint8

goroutine 3070 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/compute.CompareBytes({0x23ed2e0?, 0xc0140e1be8?}, {0x23be9c0?, 0xc01410cdf8?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/compute/compare.go:45 +0xb9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/compute.CompareGeneric({0x23ed2e0?, 0xc0140e1be8?}, {0x23be9c0?, 0xc01410cdf8?}, {0x3d, 0x0, 0x0, 0x0, 0x18, 0x32, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/compute/compare.go:94 +0x6a5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/index.(*ZoneMap).Contains(0xc007169e00, {0x23ed2e0?, 0xc0140e1be8})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/index/zonemap.go:155 +0xa6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper.(*ZmReader).Contains(0x14bfdec?, {0x23ed2e0, 0xc0140e1be8})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go:63 +0xc7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper.(*immutableIndex).Dedup(0xc011e80fd0, {0x23ed2e0, 0xc0140e1be8}, 0xc009867d40?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper/immutindex.go:44 +0x32
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper.(*immutableIndex).BatchDedup(0xc011e80fd0, {0x2d0ac28, 0xc014661b00}, 0x195ec70?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper/immutindex.go:71 +0x126
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*persistedNode).BatchDedup(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/pnode.go:88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseBlock).PersistedBatchDedup(0xc014116780, 0xc00d4f9320, {0x0, 0x0, 0x0, 0x0, 0x7c, 0xfd, 0xe1, 0x34, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/base.go:347 +0x86
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*block).BatchDedup(0xc011e39ee8, {0x2d17f60, 0xc00e6a7830}, {0x2d0ac28, 0xc014661b00}, 0x20?, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/blk.go:150 +0x1dd
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Dedup(0xc00cd7fc20, {0x2d0ac28, 0xc014661b00})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:864 +0x238
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).DoBatchDedup(0xc00cd7fc20, {0x2d0ac28, 0xc014661b00})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:970 +0x113
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0xc00cd7fc20, 0xc006feaec0)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:603 +0x6c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0xc005a6f360?, 0xc00e6a7940?, 0xc013502420?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121 +0x4f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0xc014661bc0?, 0x1?, 0x2d0ac28?, 0x2692a40?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:179 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0xc00e6a7910, 0xc013502420?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:162 +0x68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0xc00eecd920, {0x2c93518, 0xc00eecd1d0}, 0xc00b2e8e80)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:61 +0x45e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(0xc005f7c100, {_, _}, {{0xc013cc9b50, 0x10, 0x10}, 0x0, {0x1745745434e1fd7c, 0x0, 0x186, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:880 +0x542
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(0xc005f7c100, {_, _}, {{0xc013cc9b50, 0x10, 0x10}, 0x0, {0x1745745434e1fd7c, 0x0, 0x186, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:142 +0x625
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(0xc0090bab80?, {_, _}, {{0xc013cc9b50, 0x10, 0x10}, 0x0, {0x1745745434e1fd7c, 0x0, 0x186, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:97 +0x75
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc003578480, {0x2c93518, 0xc00eecd1d0}, 0xc005bdec60, 0xc00b1a8e00)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:231 +0xda5
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc0031e6b00?, {0x2c93518, 0xc00eecd1d0}, 0xc005bdec60, 0xc00b1a8e00)
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0xc0031e6ab0, {0x2c93518?, 0xc00eecd1d0?}, {0x2cbb830?, 0xc005bdec60?}, 0x0?, {0x2c70e58, 0xc00be88aa0})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:163 +0x4f0
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0035968c0, {0x2cd9d20, 0xc00a158e00}, {0x2723ee0?, 0xc006feae80}, 0x4)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:227 +0x66c
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc003596960, {0x2cd9d20, 0xc00a158e00})
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5
```

full log:
[dn-log.tgz](https://github.com/matrixorigin/matrixone/files/10780262/dn-log.tgz)

### Expected Behavior

DN should restart without error.

**Comment by aylei** [comment]
@XuPeng-SH PTAL

**Comment by aptend** [comment]
It might be caused by upgrading mo version without deleting old data. Let‘s see if the problem persists after starting the cluster from scratch

**Comment by aylei** [comment]
closing, as data-format compatibility is not guaranteed in dev branch
