### ISSUE TITLE
[Bug]: logservice panic after failover and recovery

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#8239]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-808daa2a
```

### Actual Behavior

Due to underlying node failure, logservice are failovered and the original pod log-0, log-1, log-2 are deleted (with the EBS persisted), the new pods log-4, log-5, log-6 (which is not intended, as tracked in https://github.com/matrixorigin/matrixone-operator/issues/302). The new pods cannot locate HAKeeper and I recover `[log-0, log-1, log-2]` with the original EBS. The recovered pods cannot restart due to the following error:

log-0, log-2
```
panic: inconsistent replicas

goroutine 282 [running]:
github.com/matrixorigin/matrixone/pkg/pb/logservice.(*LogState).updateShards(0xc00016e808, {{0xc004952cc0, 0x24}, {0xc004954ec0, 0x37}, {0xc004954f00, 0x37}, {0xc01cc44340, 0x10}, {0xc0049496c0, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/pb/logservice/logservice.go:150 +0x2b8
```

log-1
```
panic: [00001:20549] recover failed: open /var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/default-log-1/07316764745592933963/snapshot-part-1/snapshot-1-420549/snapshot-000000000004BDF1/snapshot-000000000004BDF1.gbsnap: no such file or directory
(1) attached stack trace
  -- stack trace:
  | github.com/lni/dragonboat/v4.(*node).recover
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/node.go:865
  | [...repeated from below...]
Wraps: (2) [00001:20549] recover failed
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/lni/vfs.defaultFS.Open
  | 	/go/pkg/mod/github.com/matrixorigin/vfs@v0.2.1-0.20220616104132-8852fd867376/vfs.go:158
  | github.com/lni/dragonboat/v4/internal/rsm.NewSnapshotReader
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/internal/rsm/snapshotio.go:279
  | github.com/lni/dragonboat/v4.(*snapshotter).Load
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/snapshotter.go:159
  | github.com/lni/dragonboat/v4/internal/rsm.(*StateMachine).load
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/internal/rsm/statemachine.go:407
  | github.com/lni/dragonboat/v4/internal/rsm.(*StateMachine).doRecover
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/internal/rsm/statemachine.go:391
  | github.com/lni/dragonboat/v4/internal/rsm.(*StateMachine).recover
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/internal/rsm/statemachine.go:363
  | github.com/lni/dragonboat/v4/internal/rsm.(*StateMachine).Recover
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/internal/rsm/statemachine.go:256
  | github.com/lni/dragonboat/v4.(*node).recover
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/node.go:859
  | github.com/lni/dragonboat/v4.(*ssWorker).recover
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/engine.go:291
  | github.com/lni/dragonboat/v4.(*ssWorker).handle
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/engine.go:279
  | github.com/lni/dragonboat/v4.(*ssWorker).workerMain
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/engine.go:265
  | github.com/lni/dragonboat/v4.newSSWorker.func1
  | 	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/engine.go:251
  | github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1
  | 	/go/pkg/mod/github.com/matrixorigin/goutils@v1.3.1-0.20220604063047-388d67b4dbc4/syncutil/stopper.go:79
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1594
Wraps: (4) open /var/lib/matrixone/data/logservice-data/00000000-0000-0000-0000-000000000001/default-log-1/07316764745592933963/snapshot-part-1/snapshot-1-420549/snapshot-000000000004BDF1/snapshot-000000000004BDF1.gbsnap
Wraps: (5) no such file or directory
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *fs.PathError (5) syscall.Errno
```

### Expected Behavior

After recover the original majorities (log-0, log-1, log-2) with the original EBS, logservice should function normally.

### Additional information

full log: 

[log-0.txt](https://github.com/matrixorigin/matrixone/files/10877770/log-0.txt)
[log-1.txt](https://github.com/matrixorigin/matrixone/files/10877771/log-1.txt)
[log-2.txt](https://github.com/matrixorigin/matrixone/files/10877772/log-2.txt)

_No response_

**Comment by aylei** [comment]
cc @volgariver6

**Comment by volgariver6** [comment]
I will handle this issue later.

**Comment by volgariver6** [comment]
not focus on it.

**Comment by volgariver6** [comment]
not focus on it.

**Comment by volgariver6** [comment]
not focus on it.

**Comment by volgariver6** [comment]
has been fixed by https://github.com/matrixorigin/matrixone-operator/pull/314 and https://github.com/matrixorigin/matrixone/pull/8617

**Comment by aressu1985** [comment]
I will test it in HA test

**Comment by aressu1985** [comment]
after lots of pod ,and vm restart, this issue is not happened again.close this
