### ISSUE TITLE
[Bug]: Launch error:panic: proto: wrong wireType = 2 for field Role; I'm not sure this's bug or env problem.

### ISSUE THREAD

**Issue by crzbird** [matrixorigin/matrixone#8522]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- OS type: Mac OS
- Go version: go version go1.19.4 darwin/arm64
```

### Actual Behavior

- Details:
1.Follow the doc,Check out 0.7.0 branch
2.make config & make build
3./mo-service -launch ./etc/quickstart/launch.toml
- Error:
panic: proto: wrong wireType = 2 for field Role

goroutine 222 [running]:
github.com/matrixorigin/matrixone/pkg/hakeeper.(*stateMachine).handleCNHeartbeat(0x14003071c80, {0x14000666301?, 0x1400567c0f0?, 0x1400567c120?})
        /Users/d/GolandProjects/matrixone/pkg/hakeeper/rsm.go:278 +0x1ec
github.com/matrixorigin/matrixone/pkg/hakeeper.(*stateMachine).Update(0x14003071c80, {0x9f, {0x14000666301, 0x5a, 0x5f}, {0x0, {0x0, 0x0, 0x0}}})
        /Users/d/GolandProjects/matrixone/pkg/hakeeper/rsm.go:470 +0xc4

**Comment by crzbird** [comment]
my bad,I launch main branch before,It seems data formats Incompatible!
