### ISSUE TITLE
[Bug]: mo will not exit properly when Ctrl+C 

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#8524]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 08a57f4
- Hardware parameters: intel x86_64
- OS type: linux
- Others:
```

### Actual Behavior

When I type Ctrl+C after running mo, mo will not exit properly
~~~bash
panic: send on closed channel

goroutine 3456 [running]:
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Collect(0xc053146180?, {0x30385d8, 0xc0002683c0}, {0x301a1c0?, 0xc0049b2fc0?})
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/util/export/batch_processor.go:311 +0xb3
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*batchSpanProcessor).OnEnd(0xc0004dc000, {0x3034530?, 0xc0049b2fc0?})
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/util/trace/impl/motrace/batch_span_processor.go:65 +0x11b
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*MOSpan).End(0xc0049b2fc0, {0x0?, 0x0, 0x44f98d0?})
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/util/trace/impl/motrace/mo_trace.go:152 +0x176
github.com/matrixorigin/matrixone/pkg/util/metric.CalculateStorageUsage({0x3038530?, 0xc00b78ce60?}, 0xc00415b128)
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/util/metric/cron_task.go:118 +0x863
github.com/matrixorigin/matrixone/pkg/util/metric.GetMetricStorageUsageExecutor.func1({_, _}, {0x2, {{0xc00b918740, 0xe}, 0x3, {0x4600b60, 0x0, 0x0}, {0x0, ...}, ...}, ...})
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/util/metric/cron_task.go:71 +0x37
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).run.func1({0xc0004effd0?, 0x44db65?})
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/taskservice/task_runner.go:399 +0x5fc
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x8d
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/home/jiajiejie/repos/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0x105
~~~

### Steps to Reproduce

```Markdown
1. cd matrixone && make clean && make build
2. ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
3. run mo-tester for BVT tests
4. Ctrl+C
PS: This behavior is accidental
```

**Comment by xzxiong** [comment]
fixed. ptal @guguducken
