### ISSUE TITLE
[Bug]: Client login failed after Replay

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#8584]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f1598b329799a298bc0fed5868b97809312834c3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Execute sysbench mixed and restart mo-servcie after 20 minutes
![image](https://user-images.githubusercontent.com/14086886/226629668-a78c7dd2-7afb-49ab-8a86-3a5ac02bb342.png)

### Additional information
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1e74a06]

goroutine 1607 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Relation(0xc00c315d20, {0x2de4498, 0xc00563c5a0}, {0xc00b11ff55, 0xa})
        /data1/shenjiangwei/matrixone/pkg/vm/engine/disttae/txn_database.go:125 +0xc46
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation(0x0?, {0xc00b11ff4a?, 0x29398e0?}, {0xc00b11ff55, 0xa})
        /data1/shenjiangwei/matrixone/pkg/frontend/compiler_context.go:187 +0x402
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve(0x0?, {0xc00b11ff4a?, 0x0?}, {0xc00b11ff55, 0xa})
        /data1/shenjiangwei/matrixone/pkg/frontend/compiler_context.go:243 +0x66
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable(0xc00af8fd00, {0x2da5c20?, 0xc00d67c410?}, 0xc00d790000)
        /data1/shenjiangwei/matrixone/pkg/sql/plan/query_builder.go:1755 +0x1262
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable(0xc00af8fd00, {0x2da5600?, 0xc0047fcee0?}, 0xc00d790000)
        /data1/shenjiangwei/matrixone/pkg/sql/plan/query_builder.go:1879 +0x525
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable(0x0?, {0x2da5a00?, 0xc00d67c460?}, 0x0?)
        /data1/shenjiangwei/matrixone/pkg/sql/plan/query_builder.go:1859 +0xff8
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom(0x0?, {0xc00a439cb0?, 0x0?, 0x0?}, 0x1d7bde0?)
        /data1/shenjiangwei/matrixone/pkg/sql/plan/query_builder.go:1641 +0x31
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect(0xc00af8fd00, 0x2e49290?, 0xc00d790000, 0x1)
        /data1/shenjiangwei/matrixone/pkg/sql/plan/query_builder.go:1263 +0xaaa
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder(0x0?, {0x2e49290?, 0xc00d66bb00?}, 0x0?)
        /data1/shenjiangwei/matrixone/pkg/sql/plan/build.go:28 +0x1de
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x2e49290?, 0xc00d66bb00?}, {0x2de5ed8?, 0xc00d67c550?})
        /data1/shenjiangwei/matrixone/pkg/sql/plan/build.go:59 +0xc8
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize(0xc00d8082d0, {0x2de5ed8?, 0xc00d67c550?})
        /data1/shenjiangwei/matrixone/pkg/sql/plan/optimize.go:56 +0x45
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan({0x2de4498, 0xc00b02bda0}, 0xc012790a00, {0x2e49290, 0xc00d66bb00}, {0x2de5ed8?, 0xc00d67c550})
        /data1/shenjiangwei/matrixone/pkg/frontend/mysql_cmd_executor.go:1322 +0x545
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0xc00af8fc80, {0x2de4498, 0xc00b02bda0?}, {0xc?, 0x1?}, 0x2a76728)
        /data1/shenjiangwei/matrixone/pkg/frontend/computation_wrapper.go:197 +0x37c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc00d66ba40, {0x2de4498, 0xc00b02bda0}, {0xc00b11ff10, 0x6b})
        /data1/shenjiangwei/matrixone/pkg/frontend/mysql_cmd_executor.go:2505 +0x29b6
github.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec(0xc00a439c50, {0x2de4498, 0xc00b02bda0}, {0xc00b11ff10, 0x6b})
        /data1/shenjiangwei/matrixone/pkg/frontend/session.go:1334 +0x16c
github.com/matrixorigin/matrixone/pkg/frontend.executeSQLInBackgroundSession({0x2de43f0?, 0xc00af8fa80?}, {0x2de4498, 0xc00b02bda0}, 0x0?, 0x4f52e7?, {0xc00b11ff10, 0x6b}, {0xc00ad1fc70, 0xc004a1a510})
        /data1/shenjiangwei/matrixone/pkg/frontend/session.go:1272 +0x176
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).AuthenticateUser(0xc007c453b0?, {0xc00a7c80ac, 0x4})
        /data1/shenjiangwei/matrixone/pkg/frontend/session.go:1004 +0x41d

**Comment by LeftHandCold** [comment]
Modify to pull mode to successfully login

**Comment by LeftHandCold** [comment]
same as #8303
