### ISSUE TITLE
[Bug]: CN crashed during longrunning test because of `fatal error: concurrent map read and map write`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8810]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 7120770
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

test description can be found in #8799 

log before CN crashed as follows:

```
fatal error: concurrent map read and map write

goroutine 156829 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).getTableMeta(0xc0edfc7340, {0x2e62f98, 0xc1663df350}, 0x1, 0x4280d, 0x1, 0x0?, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn.go:47 +0x256
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).updateMeta(0xc0bdf2c420, {0x2e62f98, 0xc1663df350}, 0x419dff?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table_meta.go:42 +0x2ca
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges(0xc0bdf2c420, {0x2e62f98, 0xc1663df350}, 0xc0bdcc7b80?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:196 +0x14d
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes(0xc17d694dc0, 0xc11d050a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1762 +0x41f
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan(0xa?, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:861 +0x3b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc17d694dc0, {0x2e62f98, 0xc1663df3e0}, 0xc11d050a80, {0xc1663df2c0?, 0x4, 0x6})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:575 +0x352
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc17d694dc0, {0x2e62f98, 0xc1663df3e0}, 0xc11d051180, {0xc1663df2c0?, 0x4, 0x6})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:617 +0x6da
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc17d694dc0, {0x2e62f98, 0xc1663df3e0}, 0xc11d050fc0, {0xc1663df2c0?, 0x4, 0x6})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:593 +0x545
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery(0xc17d694dc0, {0x2e62f98, 0xc1663df3e0}, 0xc1c070a240)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:423 +0x8ee
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope(0x2e62f98?, {0x2e62f98, 0xc1663df3e0}, 0xc0837ac540)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:235 +0x7d0
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile(0xc17d694dc0, {0x2e62f98, 0xc1663df3e0}, 0x2ed60c0?, {0x29fcbe0?, 0xc17d5a4840?}, 0xc1c0ba71d0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:121 +0x185
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0xc003d9a040, {0x2e62f98, 0xc164268f60?}, {0x2e64a48?, 0xc1c0ba71d0?}, 0x2ae9450)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/computation_wrapper.go:297 +0x17aa
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc10d2301e0, {0x2e62f98, 0xc164268510}, {0xc130ff0280, 0x129})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2680 +0x3036
github.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec(0xc022767f70, {0x2e62f98, 0xc178ed7c20}, {0xc130ff0280, 0x129})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1411 +0x1e4
github.com/matrixorigin/matrixone/pkg/frontend.verifyPrivilegeEntryInMultiPrivilegeLevels({0x2e62f98, 0xc178ed7c20}, {0x2e639e0, 0xc022767f70}, 0xc007bba180?, 0x45c7f4?, 0x8?, {0x14, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:5024 +0x22d
github.com/matrixorigin/matrixone/pkg/frontend.determineRoleSetHasPrivilegeSet({0x2e62f98, 0xc178ed7c20}, {0x2e639e0, 0xc022767f70}, 0x6?, 0x203005?, 0xc015298c00)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:5072 +0x337
github.com/matrixorigin/matrixone/pkg/frontend.determineUserHasPrivilegeSet({0x2e62f98, 0xc178ed7c20}, 0x2757000?, 0xc000903ef0?, {0xc007bba5c0?, 0x215b086?})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:5198 +0x2aa
github.com/matrixorigin/matrixone/pkg/frontend.authenticateUserCanExecuteStatementWithObjectTypeAccountAndDatabase({0x2e62f98, 0xc178ed7c20}, 0x2a400ea?, {0x2e640a8?, 0xc02b517600?})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:5567 +0xb1
github.com/matrixorigin/matrixone/pkg/frontend.authenticateUserCanExecuteStatement({0x2e62f98?, 0xc178ed7c20?}, 0xc02b517600?, {0x2e640a8, 0xc02b517600})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2031 +0x14b
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc0ec317200, {0x2e62f98, 0xc178ed79b0}, {0xc02b60d400, 0x138})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2329 +0xf49
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x2e62f98?, {0x2e62f98, 0xc178ed79b0}, 0x2de83d8?, 0xc1e9b58c48)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3255 +0x7f6
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc028e738f0, 0xc1e9b58c48)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:175 +0x3a5
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0ec3170e0?, {0x2eafbc0, 0xc1c18fda00}, {0x24e2ce0?, 0xc0ac38a660}, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:321 +0xaad
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc000f04be0, {0x2eafbc0, 0xc1c18fda00})
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5

goroutine 1 [chan receive, 2 minutes]:
main.waitSignalToStop(0x2e62f28?)
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:116 +0xba
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:109 +0x325

goroutine 22 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0001daf50)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:137 +0x365

goroutine 9 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0001dafc0)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x8b
```

full log is here: [cn0-crash.log](https://github.com/matrixorigin/matrixone/files/11119161/cn0-crash.log)

**Comment by dongdongyang33** [comment]
checking

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/5451e777617e08d138143a60704568488d674888

**Comment by sukki37** [comment]
need time to verify

**Comment by sukki37** [comment]
not repro
