### ISSUE TITLE
[Bug]: UT test TestMergeRangeWithNoConflict fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#8817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![10771680256897_ pic](https://user-images.githubusercontent.com/26563383/229097600-476ac405-bf62-42f3-baac-5a4cbc9e37df.jpg)

https://github.com/matrixorigin/matrixone/actions/runs/4573282200/jobs/8073525814?pr=8793

2023-03-31T09:54:20.7326149Z --- FAIL: TestMergeRangeWithNoConflict (0.10s)
2023-03-31T09:54:20.7326352Z panic: BUG: waiter should be empty. [recovered]
2023-03-31T09:54:20.7326571Z 	panic: BUG: waiter should be empty. [recovered]
2023-03-31T09:54:20.7326771Z 	panic: BUG: waiter should be empty.
2023-03-31T09:54:20.7326785Z 
2023-03-31T09:54:20.7326929Z goroutine 127 [running]:
2023-03-31T09:54:20.7327186Z testing.tRunner.func1.2({0x1395de0, 0x2264eb0})
2023-03-31T09:54:20.7327550Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1396 +0x372
2023-03-31T09:54:20.7327702Z testing.tRunner.func1()
2023-03-31T09:54:20.7327955Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1399 +0x5f0
2023-03-31T09:54:20.7328102Z panic({0x1395de0, 0x2264eb0})
2023-03-31T09:54:20.7328365Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/panic.go:890 +0x262
2023-03-31T09:54:20.7328581Z github.com/lni/goutils/leaktest.AfterTest.func1()
2023-03-31T09:54:20.7329276Z 	/home/runner/go/pkg/mod/github.com/matrixorigin/goutils@v1.3.1-0.20220604063047-388d67b4dbc4/leaktest/leak.go:118 +0x405
2023-03-31T09:54:20.7329560Z panic({0x1395de0, 0x2264eb0})
2023-03-31T09:54:20.7329939Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/panic.go:890 +0x262
2023-03-31T09:54:20.7330246Z github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).reset(0xc00025e280, {0xc00026a24e, 0x2})
2023-03-31T09:54:20.7330636Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/waiter.go:330 +0x1b2
2023-03-31T09:54:20.7330927Z github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).unref(0xc00025e280, {0xc00026a24e, 0x2})
2023-03-31T09:54:20.7331199Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/waiter.go:129 +0x65
2023-03-31T09:54:20.7331551Z github.com/matrixorigin/matrixone/pkg/lockservice.(*mergeContext).commit(0xc0006d9400, {0x6, {0xc00026a24e, 0x2}, 0x1, 0x1, {}, {0x0, 0x0, 0x0}, ...}, ...)
2023-03-31T09:54:20.7331849Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:538 +0x2b3
2023-03-31T09:54:20.7332284Z github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).addRangeLockLocked(0xc0006c4280, 0xc00025e880, 0xc0006c02a0, {0xc0006c902f, 0x1, 0x1}, {0xc0006c903f, 0x1, 0x1}, 0x0)
2023-03-31T09:54:20.7332589Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:380 +0xdf5
2023-03-31T09:54:20.7333000Z github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRangeLockLocked(0xc0006c4280, 0xc0006c02a0, 0x0, 0x0, {0xc0006f1c50, 0x2, 0xc000003600?}, 0x35c0?)
2023-03-31T09:54:20.7333287Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:263 +0x32c
2023-03-31T09:54:20.7333671Z github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock(0xc0006c4280, 0x6?, 0xc0006f1c50?, 0x2?, {0xc0006f1c50, 0x2, 0x2}, {0x1, 0x0, 0x0, ...})
2023-03-31T09:54:20.7333951Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:205 +0x1a6
2023-03-31T09:54:20.7334361Z github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock(0xc0006c4280, {0x226dda0, 0xc0007f6e70}, 0xc0006c02a0, {_, _, _}, {0x1, 0x0, 0x0, ...})
2023-03-31T09:54:20.7334674Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local.go:76 +0x2f0
2023-03-31T09:54:20.7335013Z github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(0xc0002876c0, {_, _}, _, {_, _, _}, {0xc0006e6870, 0x2d, 0x30}, ...)
2023-03-31T09:54:20.7335450Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service.go:83 +0x292
2023-03-31T09:54:20.7335852Z github.com/matrixorigin/matrixone/pkg/lockservice.TestMergeRangeWithNoConflict.func1(0xc0002877f0?, {0xc0000a6188, 0x1, 0xc000303c90?})
2023-03-31T09:54:20.7336165Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local_test.go:382 +0x425
2023-03-31T09:54:20.7336580Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithLevel.func1({0x226e0b0?, 0xc000c130e0}, {0xc000303c20, 0x1, 0x2800?})
2023-03-31T09:54:20.7336873Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:664 +0xb6
2023-03-31T09:54:20.7337261Z github.com/matrixorigin/matrixone/pkg/lockservice.RunLockServicesForTest(0x18?, {0xc000cd4e90, 0x1, 0x0?}, 0xc0006c98a0?, 0xc000cd43b0, 0x0)
2023-03-31T09:54:20.7337562Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/test_helper.go:76 +0x91b
2023-03-31T09:54:20.7338006Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTestsWithLevel({0x2267aa0?, 0xc000287520}, 0xc9?, {0xc000cd4e90, 0x1, 0x1}, 0x16?, 0xc000cd4ea0, 0x17?)
2023-03-31T09:54:20.7338302Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:655 +0x128
2023-03-31T09:54:20.7338586Z github.com/matrixorigin/matrixone/pkg/lockservice.runLockServiceTests(...)
2023-03-31T09:54:20.7338866Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/service_test.go:622
2023-03-31T09:54:20.7339197Z github.com/matrixorigin/matrixone/pkg/lockservice.TestMergeRangeWithNoConflict(0xc000287520?)
2023-03-31T09:54:20.7339512Z 	/home/runner/work/matrixone/matrixone/pkg/lockservice/lock_table_local_test.go:336 +0x8e65
2023-03-31T09:54:20.7339685Z testing.tRunner(0xc000287520, 0x154f220)
2023-03-31T09:54:20.7340089Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1446 +0x217
2023-03-31T09:54:20.7340373Z created by testing.(*T).Run
2023-03-31T09:54:20.7340675Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1493 +0x75e
2023-03-31T09:54:20.7341001Z FAIL	github.com/matrixorigin/matrixone/pkg/lockservice	1.170s
2023-03-31T09:54:20.7341270Z 2023/03/31 09:48:40.222223 +0000 INFO logutil/internal.go:37 MO logger init, level=debug, log file=

**Comment by zhangxu19830126** [comment]
No recurrence even after 5,000 ut run locally. Add  more logging and code level analysis

**Comment by zhangxu19830126** [comment]
close
