### ISSUE TITLE
[Bug]:  DN crashed during longrunning test because of panic

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8842]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

test description can be found at https://github.com/matrixorigin/matrixone/issues/8799

log before DN crashed as follows:
```
{"level":"INFO","time":"2023/04/04 02:17:48.458916 +0000","caller":"rpc/handle.go:102","msg":"HandleCommit end : 0D0663B80D9A498D8FF2DAC30875C1BD\n"}
{"level":"ERROR","time":"2023/04/04 02:17:48.458931 +0000","name":"dn-service","caller":"util/log.go:349","msg":"txn commit with 1 PC failed","uuid":"33376565-3237-3162-3439-323631326537","dn-shard":"2-262148-1-default-dn-0.default-dn-headless.freetier-01.svc:41010","txn":"0d0663b80d9a498d8ff2dac30875c1bd/Active/S:1680574668088477049-0","error":"symlink data.mofscache /var/lib/matrixone/disk-cache/d5d9588e-d240-11ed-9fe9-e27e49450eb5-27466/32-1127: no space left on device","stacktrace":"github.com/matrixorigin/matrixone/pkg/txn/util.LogTxnStart1PCCommitFailed\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/util/log.go:349\ngithub.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:237\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108\ngithub.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:163\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:227\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344"}
panic: only moerr supported

goroutine 2054 [running]:
github.com/matrixorigin/matrixone/pkg/pb/txn.WrapError({0x2c6ec80?, 0xc02757fec0?}, 0x10?)
	/go/src/github.com/matrixorigin/matrixone/pkg/pb/txn/txn.go:258 +0xec
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc005620240, {0x2ca6378, 0xc013d983c0}, 0xc0007ff680, 0xc0538faa80)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:238 +0xe98
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc00083a8c0?, {0x2ca6378, 0xc013d983c0}, 0xc0007ff680, 0xc0538faa80)
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0xc00083a870, {0x2ca6378?, 0xc013d983c0?}, {0x2cce8b8?, 0xc0007ff680?}, 0x0?, {0x2cbb180, 0xc0556c1b00})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:163 +0x4f0
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc000ea0b40, {0x2cf19e0, 0xc010b06100}, {0x2744ea0?, 0xc026e14640}, 0x56)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:227 +0x66c
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc000ea0c80, {0x2cf19e0, 0xc010b06100})
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5

```

the full log is here:
[default-dn-0-crash.log](https://github.com/matrixorigin/matrixone/files/11144042/default-dn-0-crash.log)

**Comment by aylei** [comment]
```
k -n freetier-01 exec -it default-dn-0 -- bash
root@default-dn-0:/# cd /var/lib/
root@default-dn-0:/var/lib# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          50G   14G   37G  27% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/nvme0n1p1   50G   14G   37G  27% /etc/hosts
shm              64M     0   64M   0% /dev/shm
/dev/nvme1n1     30G   12G   18G  39% /var/lib/matrixone
tmpfs            28G   12K   28G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /sys/firmware
root@default-dn-0:/var/lib# du -sh ./matrixone
12G	./matrixone
```

The volume has enough space left

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/b850ca4f2a641a4c29affa65379db63cda477835

**Comment by reusee** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/8866 to be fixed to further long-running tests.

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/pull/8894

**Comment by reusee** [comment]
fixed, waiting for test complete

**Comment by reusee** [comment]
fixed, waiting for test complete

**Comment by reusee** [comment]
fixed, waiting for test complete

**Comment by sukki37** [comment]
testing
