### ISSUE TITLE
[Bug]:  DN crashed repeatedly during longrunning test because of `lz4: invalid source or destination buffer too short`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8866]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):91db3b7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

test description can be found at https://github.com/matrixorigin/matrixone/issues/8799

log before DN crashed as follows:
```
{"level":"INFO","time":"2023/04/06 02:03:26.329472 +0000","caller":"rpc/handle.go:102","msg":"HandleCommit end : 0E68D4BFEDC848ABB658812AA2D2F989\n"}
{"level":"ERROR","time":"2023/04/06 02:03:26.329482 +0000","name":"dn-service","caller":"util/log.go:349","msg":"txn commit with 1 PC failed","uuid":"33376565-3237-3162-3439-323631326537","dn-shard":"2-262148-1-default-dn-0.default-dn-headless.freetier-01.svc:41010","txn":"0e68d4bfedc848abb658812aa2d2f989/Active/S:1680746595396163969-0","error":"lz4: invalid source or destination buffer too short","stacktrace":"github.com/matrixorigin/matrixone/pkg/txn/util.LogTxnStart1PCCommitFailed\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/util/log.go:349\ngithub.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:237\ngithub.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit\n\t/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108\ngithub.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:163\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:227\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344"}
panic: only moerr supported

goroutine 1071 [running]:
github.com/matrixorigin/matrixone/pkg/pb/txn.WrapError({0x2cab3c0?, 0x2c84d20?}, 0x10?)
	/go/src/github.com/matrixorigin/matrixone/pkg/pb/txn/txn.go:258 +0xec
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc0000f67e0, {0x2ce1f18, 0xc0355ad470}, 0xc0007fe600, 0xc0013b6b80)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:238 +0xe98
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc0007bc3b0?, {0x2ce1f18, 0xc0355ad470}, 0xc0007fe600, 0xc0013b6b80)
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0xc0007bc360, {0x2ce1f18?, 0xc0355ad470?}, {0x2d0af18?, 0xc0007fe600?}, 0x45c101?, {0x2cf74e0, 0xc01f3c2840})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:163 +0x4f0
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc000001540, {0x2d2e120, 0xc00eb3a000}, {0x2779980?, 0xc037831e40}, 0x6d)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:227 +0x66c
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc000001a40, {0x2d2e120, 0xc00eb3a000})
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5
```

the full log is here: 
[dn-0405-crash.log](https://github.com/matrixorigin/matrixone/files/11165626/dn-0405-crash.log)

**Comment by aptend** [comment]
repro branch https://github.com/aptend/matrixone/tree/lz4-error

1. git check out the branch
2. start the server locally, `./mo-service -debug-http 127.0.0.1:8181 -launch etc/launch-tae-CN-tae-DN/launch.toml 2>&1`
3. in mo-tpch directory, `./run.sh -c -s 1` & `./run.sh -l -s 1` & `./run.sh -q all -s 1`

**Comment by reusee** [comment]
maybe related to the disk cache

**Comment by reusee** [comment]
fixed, waiting for test complete

**Comment by reusee** [comment]
fixed, waiting for test complete

**Comment by reusee** [comment]
fixed, waiting for test complete

**Comment by sukki37** [comment]
testing
