### ISSUE TITLE
[Bug]: cn panic: runtime error: index out of range [1] with length 1 when run tpch 1g q13 on eks with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8959]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 701b6f1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the error log is :

_id > 10 and task_runner = \"00000000-0000-0000-0000-200000000001\" and task_status = 1 order by task_id limit 3","status":"success","span":{"trace_id":"17cbffd0-d8d6-11ed-b700-023a68cf44a5","kind":"statement"},"session_info":"connectionId 5216|10.0.129.182:41710|{account sys:c3b26af3-bbd4-4632-a9c1-c69f193c18ee:moadmin -- 0:4294967295:0}|5854756f-d8c7-11ed-b700-023a68cf44a5"}
{"level":"INFO","time":"2023/04/12 02:02:40.776975 +0000","name":"cn-service.StatsLog","caller":"mometric/stats_log_writer.go:86","msg":"CN 00000000-0000-0000-0000-200000000001 SHARED stats ","uuid":"00000000-0000-0000-0000-200000000001","FileService Cache Hit Rate":1,"FileService Cache Memory Hit Rate":1,"FileService Cache Disk Hit Rate":"NaN","FileService.S3.List":0,"FileService.S3.Head":0,"FileService.S3.Put":0,"FileService.S3.Get":0,"FileService.S3.Delete":0,"FileService.S3.DeleteMulti":0,"FileService.Cache.Read":6,"FileService.Cache.Hit":6,"FileService.Cache.Memory.Read":6,"FileService.Cache.Memory.Hit":6,"FileService.Cache.Disk.Read":0,"FileService.Cache.Disk.Hit":0,"FileService.Cache.Disk.GetFileContent":0,"FileService.Cache.Disk.SetFileContent":0,"FileService.Cache.Disk.OpenFile":0,"FileService.Cache.Disk.StatFile":0,"FileService.Cache.Disk.Error":0,"FileService.Cache.Disk.Evict":0,"FileService.Cache.Disk.EvictPending":0,"FileService.Cache.Disk.EvictImmediately":0,"FileService.FileWithChecksum.Read":0,"FileService.FileWithChecksum.Write":0,"FileService.FileWithChecksum.UnderlyingRead":0,"FileService.FileWithChecksum.UnderlyingWrite":0,"DistTAE.Logtail.Entries":0,"DistTAE.Logtail.InsertEntries":0,"DistTAE.Logtail.MetadataInsertEntries":0,"DistTAE.Logtail.DeleteEntries":0,"DistTAE.Logtail.MetadataDeleteEntries":0,"DistTAE.Logtail.InsertRows":0,"DistTAE.Logtail.ActiveRows":0,"DistTAE.Logtail.InsertBlocks":0}
{"level":"INFO","time":"2023/04/12 02:02:40.777038 +0000","name":"cn-service.StatsLog","caller":"mometric/stats_log_writer.go:86","msg":"CN 00000000-0000-0000-0000-200000000001 ETL stats ","uuid":"00000000-0000-0000-0000-200000000001","FileService Cache Hit Rate":"NaN","FileService Cache Memory Hit Rate":"NaN","FileService Cache Disk Hit Rate":"NaN","FileService.S3.List":0,"FileService.S3.Head":3,"FileService.S3.Put":3,"FileService.S3.Get":0,"FileService.S3.Delete":0,"FileService.S3.DeleteMulti":0,"FileService.Cache.Read":0,"FileService.Cache.Hit":0,"FileService.Cache.Memory.Read":0,"FileService.Cache.Memory.Hit":0,"FileService.Cache.Disk.Read":0,"FileService.Cache.Disk.Hit":0,"FileService.Cache.Disk.GetFileContent":0,"FileService.Cache.Disk.SetFileContent":0,"FileService.Cache.Disk.OpenFile":0,"FileService.Cache.Disk.StatFile":0,"FileService.Cache.Disk.Error":0,"FileService.Cache.Disk.Evict":0,"FileService.Cache.Disk.EvictPending":0,"FileService.Cache.Disk.EvictImmediately":0,"FileService.FileWithChecksum.Read":0,"FileService.FileWithChecksum.Write":0,"FileService.FileWithChecksum.UnderlyingRead":0,"FileService.FileWithChecksum.UnderlyingWrite":0,"DistTAE.Logtail.Entries":0,"DistTAE.Logtail.InsertEntries":0,"DistTAE.Logtail.MetadataInsertEntries":0,"DistTAE.Logtail.DeleteEntries":0,"DistTAE.Logtail.MetadataDeleteEntries":0,"DistTAE.Logtail.InsertRows":0,"DistTAE.Logtail.ActiveRows":0,"DistTAE.Logtail.InsertBlocks":0}
{"level":"INFO","time":"2023/04/12 02:02:40.777058 +0000","name":"cn-service.StatsLog","caller":"mometric/stats_log_writer.go:86","msg":"CN 00000000-0000-0000-0000-200000000001 LOCAL stats ","uuid":"00000000-0000-0000-0000-200000000001","FileService Cache Hit Rate":"NaN","FileService Cache Memory Hit Rate":"NaN","FileService Cache Disk Hit Rate":"NaN","FileService.S3.List":0,"FileService.S3.Head":0,"FileService.S3.Put":0,"FileService.S3.Get":0,"FileService.S3.Delete":0,"FileService.S3.DeleteMulti":0,"FileService.Cache.Read":0,"FileService.Cache.Hit":0,"FileService.Cache.Memory.Read":0,"FileService.Cache.Memory.Hit":0,"FileService.Cache.Disk.Read":0,"FileService.Cache.Disk.Hit":0,"FileService.Cache.Disk.GetFileContent":0,"FileService.Cache.Disk.SetFileContent":0,"FileService.Cache.Disk.OpenFile":0,"FileService.Cache.Disk.StatFile":0,"FileService.Cache.Disk.Error":0,"FileService.Cache.Disk.Evict":0,"FileService.Cache.Disk.EvictPending":0,"FileService.Cache.Disk.EvictImmediately":0,"FileService.FileWithChecksum.Read":0,"FileService.FileWithChecksum.Write":0,"FileService.FileWithChecksum.UnderlyingRead":0,"FileService.FileWithChecksum.UnderlyingWrite":0,"DistTAE.Logtail.Entries":0,"DistTAE.Logtail.InsertEntries":0,"DistTAE.Logtail.MetadataInsertEntries":0,"DistTAE.Logtail.DeleteEntries":0,"DistTAE.Logtail.MetadataDeleteEntries":0,"DistTAE.Logtail.InsertRows":0,"DistTAE.Logtail.ActiveRows":0,"DistTAE.Logtail.InsertBlocks":0}
panic: runtime error: index out of range [1] with length 1

goroutine 36758084 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).newLeftScope(0xc015ba8600, 0xc38cdc5450, {0xc4eab74680, 0x10, 0x5555555555?})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1669 +0x910
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).JoinRun(0xc38cdc5450, 0xc015ba8600)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:287 +0x2ee
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc38cdc5450, 0xc015ba8600, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:165 +0x6b7
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc38cdc5450?, 0xc015ba8600?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:145 +0x339
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0x3fc4800?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:90 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
[tpch-q13-error.txt](https://github.com/matrixorigin/matrixone/files/11206382/tpch-q13-error.txt)

### Steps to Reproduce

```Markdown
1. run a mo cluster on eks with (2*cn, 1*dn, 3*log)
2. load tpch 1g data 
3. run tpch 1g q13 queries about 10 times 

or 

1. git clone https://github.com/matrixorigin/mo-auto-test.git
2. modify .github/workflows/regression-on-distributed-mode.yml, 
  set JobName.default to tpch_benchmark_test
  set RunTimes to 1
3. make a pr to merge, and the job will automatically run the tpch 1g queries on eks
```

**Comment by aressu1985** [comment]
fixed
