### ISSUE TITLE
[Bug]: panic during sysbench test

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#8960]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4d8f810df
- Hardware parameters: morefine amd
- OS type:manjaro
- Others:
```

### Actual Behavior

panic then crashed after sysbench test for more than 4 hours.

```

➜  matrixone git:(4d8f810df) ✗ ./mo-service -debug-http :8123 -launch etc/launch-tae-CN-tae-DN/launch.toml > log.log
^[fatal error: sync: RUnlock of unlocked RWMutex

goroutine 350746297 [running]:
sync.fatal({0x289b796?, 0x3?})
	/usr/lib/go/src/runtime/panic.go:1031 +0x1e
sync.(*RWMutex).rUnlockSlow(0xc2674fbb30, 0x0?)
	/usr/lib/go/src/sync/rwmutex.go:129 +0x39
sync.(*RWMutex).RUnlock(...)
	/usr/lib/go/src/sync/rwmutex.go:119
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*syncLogTailTimestamp).getTimestamp(0xc0036d97c8)
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:444 +0xd5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*syncLogTailTimestamp).greatEq(0xc1b2e33168?, {0x1754e21c2d9826d3, 0x0, 0x8323, {}, {0x0, 0x0, 0x0}, 0x0})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:464 +0x6e
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).checkTxnTimeIsLegal(0xc0036d97c0, {0x2c98158, 0xc5b1e8f8f0}, {0x1754e21c2d9826d3, 0x0, 0x8323, {}, {0x0, 0x0, 0x0}, ...})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:121 +0x1fc
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).New(0xc0036d9740, {0x2c98158, 0xc5b1e8f8f0}, {0x2cd70a0?, 0xc1fb27f6c0?})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/disttae/engine.go:350 +0x4bb
github.com/matrixorigin/matrixone/pkg/vm/engine.(*EntireEngine).New(0xc023249ba0, {0x2c98158, 0xc5b1e8f8f0}, {0x2cd70a0, 0xc1fb27f6c0})
	/home/pengzhen/Documents/matrixone/pkg/vm/engine/entire_engine.go:33 +0x42
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).NewTxn(0xc377be0fc0)
	/home/pengzhen/Documents/matrixone/pkg/frontend/txn.go:179 +0x210
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).TxnBegin(0x2865023?)
	/home/pengzhen/Documents/matrixone/pkg/frontend/txn.go:508 +0x10e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc377be0f60, {0x2c98158, 0xc5b1e8f590}, {0x2865023, 0x6})
	/home/pengzhen/Documents/matrixone/pkg/frontend/mysql_cmd_executor.go:2374 +0x1075
github.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec(0xc1c91524a0, {0x2c98158, 0xc6fff508a0}, {0x2865023, 0x6})
	/home/pengzhen/Documents/matrixone/pkg/frontend/session.go:1410 +0x1e4
github.com/matrixorigin/matrixone/pkg/frontend.determineUserHasPrivilegeSet({0x2c98158, 0xc6fff508a0}, 0x1?, 0xc000a65d80?, {0xc1b2e34298?, 0x1fea63f?})
	/home/pengzhen/Documents/matrixone/pkg/frontend/authenticate.go:5309 +0x1d7
github.com/matrixorigin/matrixone/pkg/frontend.authenticateUserCanExecuteStatementWithObjectTypeDatabaseAndTable({0x2c98158, 0xc6fff508a0}, 0xc1f716e820?, {0x2c99ce8, 0xc57cf64640}, 0x41a0c7?)
	/home/pengzhen/Documents/matrixone/pkg/frontend/authenticate.go:5747 +0x9b
github.com/matrixorigin/matrixone/pkg/frontend.authenticateCanExecuteStatementAndPlan({0x2c98158, 0xc6fff508a0}, 0xc57cf64640?, {0x2c99ce8, 0xc57cf64640}, 0xb00c1b2e34390?)
	/home/pengzhen/Documents/matrixone/pkg/frontend/mysql_cmd_executor.go:2077 +0x7d
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan({0x2c98158, 0xc6fff508a0}, 0xcaa24e4840, {0x2d077b8, 0xc9de29a770}, {0x2c99ce8?, 0xc57cf64640})
	/home/pengzhen/Documents/matrixone/pkg/frontend/mysql_cmd_executor.go:1427 +0x68d
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0xc28c0f0ec0, {0x2c98158, 0xc6fff508a0?}, {0x2c99ce8?, 0xc57cf64640?}, 0x29484d0)
	/home/pengzhen/Documents/matrixone/pkg/frontend/computation_wrapper.go:197 +0x37c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc6e2070b40, {0x2c98158, 0xc8fcc43470}, {0xc313b6f620, 0x26})
	/home/pengzhen/Documents/matrixone/pkg/frontend/mysql_cmd_executor.go:2709 +0x31f2
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x2c98158?, {0x2c98158, 0xc8fcc43470}, 0x2c31630?, 0xc6ef2d0300)
	/home/pengzhen/Documents/matrixone/pkg/frontend/mysql_cmd_executor.go:3284 +0x7f6
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc9de29a540, 0xc6ef2d0300)
	/home/pengzhen/Documents/matrixone/pkg/frontend/routine.go:175 +0x3a5
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0023e4af0, {0x2ce3520, 0xc22e190700}, {0x237ad20?, 0xca97899180}, 0x0?)
	/home/pengzhen/Documents/matrixone/pkg/frontend/routine_manager.go:309 +0xaa7
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0049a6140, {0x2ce3520, 0xc22e190700})
	/home/pengzhen/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/home/pengzhen/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/home/pengzhen/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5

```

### Expected Behavior

running well

### Steps to Reproduce

```Markdown
1,some changes on commitid 4d8f810df refer to the diff.txt below.
2,sysbench point select.
https://github.com/matrixorigin/mo-load

change cases first:

cases/sysbench/point_select_10_100000/run.yml
duration:660
vuser:1000

start:

./start.sh -m SYSBENCH -n 10 -s 100000
./start.sh -c cases/sysbench/point_select_10_100000 > bench.log
```

### Additional information

[rwmutex.tar.gz](https://github.com/matrixorigin/matrixone/files/11206402/rwmutex.tar.gz)

[diff.txt](https://github.com/matrixorigin/matrixone/files/11206443/diff.txt)

**Comment by m-schen** [comment]
it's a push bug, I will fix it.

**Comment by m-schen** [comment]
doing expression refactor and have no time to trace it.

**Comment by m-schen** [comment]
no time to trace it.

**Comment by m-schen** [comment]
no time to trace it.

**Comment by m-schen** [comment]
重连的初始化直接通过make替换了时间戳，新生成的时间戳没有锁，导致了这个问题。已修复。

**Comment by m-schen** [comment]
已修复。可关闭。

**Comment by daviszhen** [comment]
已修改。
