### ISSUE TITLE
[Question]: How to fix "PANIC dragonboat" when start mo-service?

### ISSUE THREAD

**Issue by terry-xuan-gao** [matrixorigin/matrixone#9167]
### Describe your problem

I'm new to MatrixOne and I'm having trouble launching MatrixOne server from source code.
The source code compiles successfully, but fails when starting the MatrixOne service.
I think the reason relates to `dragonboat`, but I don't know how to solve it.
In addition, when I use docker to pull the official MatrixOne image file and run it, it can be successfully deployed

My local development environment:
- ubuntu 22.04 (microsoft-standard-WSL2)
- go version go1.19.8 linux/amd64
- gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

I know my question may be a bit stupid, but still hope to get some help 🌹

Logs when starting the service:
`./mo-service --daemon --launch ./etc/quickstart/launch.toml &> test.log &`

``` python
2023-04-25 16:12:36.393610 I | mo-service is running in daemon mode, child process is 17444
2023/04/25 16:12:36.434564 +0800 INFO logutil/internal.go:37 MO logger init, level=info, log file=
2023/04/25 16:12:36.453428 +0800 INFO fileservice/local_fs.go:109 fileservice: cache initialized {"fs-name": "SHARED", "capacity": 536870912}
2023/04/25 16:12:36.462173 +0800 INFO motrace/trace.go:129 init GlobalBatchProcessor
2023/04/25 16:12:36.463176 +0800 INFO export/batch_processor.go:260 MOCollector Start
2023/04/25 16:12:36.465924 +0800 INFO motrace/trace.go:134 init trace span processor
2023/04/25 16:12:36.466146 +0800 INFO motrace/trace.go:99 trace with LongQueryTime: 0s
2023/04/25 16:12:36.466484 +0800 INFO mo-service/config.go:210 hakeeper client cfg: { [127.0.0.1:32001] 0 false}
2023/04/25 16:12:36.471411 +0800 INFO metric/metric.go:136 metric with ExportInterval: 15s
2023/04/25 16:12:36.474002 +0800 INFO metric/metric.go:137 metric with UpdateStorageUsageInterval: 15m0s
2023/04/25 16:12:36.472935 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2221 go version: go1.19.8, linux/amd64
2023/04/25 16:12:36.476144 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2223 dragonboat version: 4.0.0 (Dev)
2023/04/25 16:12:36.476382 +0800 WARN config config/config.go:534 mutual TLS disabled, communication is insecure
2023/04/25 16:12:36.476971 +0800 INFO config config/config.go:656 using default EngineConfig
2023/04/25 16:12:36.477219 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:349 DeploymentID set to 1
2023/04/25 16:12:36.509031 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:1759 logdb memory limit: 48 MBytes
2023/04/25 16:12:36.512431 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:358 NodeHost ID: 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf
2023/04/25 16:12:36.512702 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:1806 AddressByNodeHostID: true, use gossip based node registry
2023/04/25 16:12:36.512949 +0800 INFO registry registry/gossip.go:297 gossip probe interval set to 5s
2023/04/25 16:12:36.513192 +0800 INFO registry registry/gossip.go:307 gossip bind address 127.0.0.1 port 32002
2023/04/25 16:12:36.513423 +0800 INFO registry registry/gossip.go:315 gossip advertise address 127.0.0.1 port 32002
2023/04/25 16:12:36.517718 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:366 filesystem error injection mode enabled: false
2023/04/25 16:12:36.518216 +0800 INFO transport transport/transport.go:238 transport type: go-tcp-transport
2023/04/25 16:12:36.518557 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2010 transport type: go-tcp-transport
2023/04/25 16:12:36.518781 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2011 logdb type: Tan
2023/04/25 16:12:36.519015 +0800 INFO dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2012 nodehost address: 127.0.0.1:32000
2023/04/25 16:12:36.519891 +0800 INFO log-service logservice/store.go:151 HAKeeper Timeout Configs {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "process": "system-init", "LogStoreTimeout": 300000000000, "DNStoreTimeout": 10000000000, "CNStoreTimeout": 30000000000}
2023/04/25 16:12:36.521033 +0800 INFO log-service logservice/store.go:171 logservice truncation worker started {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "process": "system-init"}
2023/04/25 16:12:36.526428 +0800 INFO mo-service/main.go:241 bootstrapping hakeeper...
2023/04/25 16:12:36.526393 +0800 INFO log-service logservice/service.go:174 logservice heartbeat worker started {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "process": "system-init"}
2023/04/25 16:12:36.538912 +0800 INFO fileservice/local_fs.go:109 fileservice: cache initialized {"fs-name": "SHARED", "capacity": 536870912}
2023/04/25 16:12:36.540901 +0800 INFO tan tan/open.go:63 /mnt/e/mo_ws/0-7-0/matrixone/mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/LAPTOP-UVCO35A4/00000000000000000001/tandb/node-0-131072 loading an existing tan db
2023/04/25 16:12:36.544049 +0800 INFO hakeeper-client-backend morpc/backend.go:666 start connect to remote {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0"}
2023/04/25 16:12:36.544579 +0800 INFO hakeeper-client-backend morpc/backend.go:670 connect to remote succeed {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0"}
2023/04/25 16:12:36.545056 +0800 INFO hakeeper-client-backend morpc/backend.go:468 read loop started {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0"}
2023/04/25 16:12:36.545094 +0800 INFO hakeeper-client-backend morpc/backend.go:373 write loop started {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0"}
2023/04/25 16:12:36.545232 +0800 INFO rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:343 gc inactive backends task started
2023/04/25 16:12:36.546321 +0800 INFO tan tan/open.go:76 /mnt/e/mo_ws/0-7-0/matrixone/mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/LAPTOP-UVCO35A4/00000000000000000001/tandb/node-0-131072 on disk files [000002.log 000003.log 000004.log 000005.log CURRENT MANIFEST-000001]
2023/04/25 16:12:36.546579 +0800 INFO tan tan/open.go:132 /mnt/e/mo_ws/0-7-0/matrixone/mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/LAPTOP-UVCO35A4/00000000000000000001/tandb/node-0-131072 logFiles to rebuild: map[]
2023/04/25 16:12:36.546783 +0800 INFO tan tan/open.go:133 /mnt/e/mo_ws/0-7-0/matrixone/mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/LAPTOP-UVCO35A4/00000000000000000001/tandb/node-0-131072 indexFiles: []
2023/04/25 16:12:36.548468 +0800 PANIC dragonboat v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2235 operation not supported
github.com/lni/dragonboat/v4.panicNow
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2235
github.com/lni/dragonboat/v4.(*NodeHost).startShard
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:1654
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:508
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/store.go:215
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/service_bootstrap.go:36
main.startLogService.func1
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/main.go:242
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/common/stopper/stopper.go:259
2023/04/25 16:12:36.550314 +0800 INFO logservice/hakeeper_client.go:382 isHAKeeper: false, err: <nil>
2023/04/25 16:12:36.551228 +0800 ERROR hakeeper-client-backend morpc/backend.go:485 read from backend failed {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0", "error": "read tcp4 127.0.0.1:36464->127.0.0.1:32001: use of closed network connection"}
2023/04/25 16:12:36.551540 +0800 ERROR hakeeper-client-backend morpc/backend.go:490 read loop stopped {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0"}
2023/04/25 16:12:36.556679 +0800 ERROR hakeeper-client-backend v2@v2.0.3-0.20221212132037-abf2d4c05484/session.go:496 close conneciton failed {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0", "session-id": 0, "error": "close tcp4 127.0.0.1:36464->127.0.0.1:32001: use of closed network connection"}
2023/04/25 16:12:36.558678 +0800 INFO hakeeper-client-backend morpc/backend.go:377 write loop stopped {"remote": "127.0.0.1:32001", "backend-id": "c796eb47-ce88-446c-bc80-3606d94974f0"}
2023/04/25 16:12:36.562467 +0800 ERROR rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:349 gc inactive backends task stopped
2023/04/25 16:12:36.568221 +0800 ERROR logservice/hakeeper_client.go:394 error: cannot locate ha keeper
github.com/matrixorigin/matrixone/pkg/logservice.connectToHAKeeper
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/hakeeper_client.go:394
github.com/matrixorigin/matrixone/pkg/logservice.newHAKeeperClient
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/hakeeper_client.go:314
github.com/matrixorigin/matrixone/pkg/logservice.newManagedHAKeeperClient
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/hakeeper_client.go:111
github.com/matrixorigin/matrixone/pkg/logservice.NewCNHAKeeperClient
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/hakeeper_client.go:84
main.waitHAKeeperReady
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/launch.go:136
main.waitClusterCondition
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/launch.go:197
main.startDNService
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/main.go:198
main.startService
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/main.go:146
main.startDNServiceCluster
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/launch.go:89
main.startCluster
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/launch.go:48
main.main
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/main.go:87
runtime.main
	/usr/local/go/src/runtime/proc.go:250
2023/04/25 16:12:36.568545 +0800 INFO mo-service/launch.go:139 hakeeper not ready, retry
panic: operation not supported

goroutine 228 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0030a0a80, {0x0, 0x0, 0x0})
	/home/gx/go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc0001482d0, 0x4, {0x287fd3e?, 0xc00320a1c0?}, {0xc002ff43b0?, 0xc002fe6500?, 0xc00574f0d0?}, {0x0, 0x0, 0x0})
	/home/gx/go/pkg/mod/go.uber.org/zap@v1.21.0/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/home/gx/go/pkg/mod/go.uber.org/zap@v1.21.0/sugar.go:159
github.com/matrixorigin/matrixone/pkg/logutil.DragonboatAdaptLogger.Panicf(...)
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logutil/dragonboat.go:65
github.com/lni/dragonboat/v4/logger.(*dragonboatLogger).Panicf(0xc0000c2280?, {0x287fd3e, 0x3}, {0xc002ff43b0, 0x1, 0x1})
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/logger/logger.go:132 +0x57
github.com/lni/dragonboat/v4.panicNow(...)
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:2235
github.com/lni/dragonboat/v4.(*NodeHost).startShard(0xc0031d2700, 0xc0005d2360, 0x0, 0x41ee79?, {0x20000, 0x0, 0x1, 0x1, 0xa, 0x1, ...}, ...)
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:1654 +0xe13
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica(0x0?, 0x259b100?, 0x24?, 0x2b?, {0x20000, 0x0, 0x1, 0x1, 0xa, 0x1, ...})
	/home/gx/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221226075848-d266f8c2420c/nodehost.go:508 +0xe5
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica(0xc0056fc000, 0x20000, 0x0?, 0x0?)
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/store.go:215 +0xc7
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper(_, {_, _}, {{0x0, 0x0}, 0x1, {0xc00013e990, 0x24}, 0x0, {0x0, ...}, ...})
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/logservice/service_bootstrap.go:36 +0x92
main.startLogService.func1({0x2ca6678, 0xc00548a270})
	/mnt/e/mo_ws/0-7-0/matrixone/cmd/mo-service/main.go:242 +0x11c
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/mnt/e/mo_ws/0-7-0/matrixone/pkg/common/stopper/stopper.go:254 +0x12c

```

**Comment by triump2020** [comment]
Try to upgrade the dragonboat module.  @terry-xuan-gao

**Comment by volgariver6** [comment]
Please try it in a real virtual machine, but not microsoft-standard-WSL2. Thank you.

**Comment by volgariver6** [comment]
@terry-xuan-gao Any updates?

**Comment by volgariver6** [comment]
OK, thank you. @terry-xuan-gao
