### ISSUE TITLE
[Bug]: lots of unexpected error Duplicate entry '15202' for key 'hist_id' when runing tpcc benchmark test on eks with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9222]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4d4150a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When runing tpcc test (1warehouse 1 terminals),there are lots of unexpected errors of : 
2023-04-30 03:24:07 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, **ErrorMessage : Duplicate entry '15175' for key 'hist_id'
2023-04-30 03:24:07 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15176' for key 'hist_id'
2023-04-30 03:24:07 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15177' for key 'hist_id'
2023-04-30 03:24:07 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15178' for key 'hist_id'**
2023-04-30 03:24:07 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15179' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15180' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15181' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15182' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15183' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15184' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15185' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15186' for key 'hist_id'
2023-04-30 03:24:08 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:09 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15188' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15189' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15190' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15191' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15192' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15193' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:294 - [EXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:09 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15196' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15197' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15198' for key 'hist_id'
2023-04-30 03:24:09 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15199' for key 'hist_id'
2023-04-30 03:24:10 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15200' for key 'hist_id'
2023-04-30 03:24:10 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:10 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:10 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:10 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:10 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15202' for key 'hist_id'
**2023-04-30 03:24:10 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15203' for key 'hist_id'**
2023-04-30 03:24:10 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:10 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15204' for key 'hist_id'
2023-04-30 03:24:11 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:11 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
**2023-04-30 03:24:11 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15205' for key 'hist_id'**
2023-04-30 03:24:11 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:11 FATAL jTPCCTerminal:325 - [EXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-04-30 03:24:11 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '15207' for key 'hist_id'
2023-04-30 03:24:11 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict

but the column hist_id of table  bmsql_history is type of auto_increment, it should never duplicated

create table bmsql_history (
  hist_id  integer auto_increment,
  h_c_id   integer,
  h_c_d_id integer,
  h_c_w_id integer,
  h_d_id   integer,
  h_w_id   integer,
  h_date   timestamp,
  h_amount decimal(6,2),
  h_data   varchar(24),
  primary key (hist_id)
);

And the dn was painc by 'panic: logic error interval [14,20], start 26, end 26'

{"level":"INFO","time":"2023/04/30 03:30:44.925589 +0000","caller":"rpc/handle.go:753","msg":"[precommit] handle write end txn: ctx[BCD3995CEC534470A054B5D2ED34123F][1682825444758535473-1->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/04/30 03:30:44.925616 +0000","caller":"rpc/handle.go:746","msg":"[precommit] handle write typ: 0, 272387-sys_async_task, 272385-mo_task\n txn: ctx[BCD3995CEC534470A054B5D2ED34123F][1682825444758535473-1->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/04/30 03:30:45.038578 +0000","caller":"rpc/handle.go:753","msg":"[precommit] handle write end txn: ctx[BCD3995CEC534470A054B5D2ED34123F][1682825444758535473-1->9223372036854775807-4294967295][Active]: <nil>\n"}
{"level":"INFO","time":"2023/04/30 03:30:45.042646 +0000","caller":"rpc/handle.go:103","msg":"HandleCommit end : BCD3995CEC534470A054B5D2ED34123F, 179.605537ms\n"}
{"level":"INFO","time":"2023/04/30 03:30:45.042647 +0000","name":"dn-service.logtail-push-service","caller":"service/session.go:334","msg":"table not subscribed, filter out","uuid":"00000000-0000-0000-0000-100000000000","server-id":"f981d98b-6ccc-462e-a5c4-e47f5ec8bd37","stream-id":1,"id":"db_id:272385 tb_id:272388 ","checkpoint":""}
{"level":"INFO","time":"2023/04/30 03:30:45.042681 +0000","name":"dn-service.logtail-push-service","caller":"service/session.go:334","msg":"table not subscribed, filter out","uuid":"00000000-0000-0000-0000-100000000000","server-id":"f981d98b-6ccc-462e-a5c4-e47f5ec8bd37","stream-id":1,"id":"db_id:272385 tb_id:272388 ","checkpoint":""}
{"level":"WARN","time":"2023/04/30 03:30:48.722097 +0000","caller":"logtail/table.go:200","msg":"[logtail] fetch with too small ts","ts":"1682824537494054944-1","minTs":"1682824542232726457-0"}
panic: logic error interval [14,20], start 26, end 26

goroutine 1188 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*CheckpointData).UpdateBlkMeta(0xc01df09c70, 0xc07247b6b0?, 0x17, 0x17, 0x1a, 0x1a)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/utils.go:421 +0x388
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*BaseCollector).VisitBlk(0xc07247b800, 0xc062316800)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/utils.go:846 +0x2cb1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*LoopProcessor).OnBlock(0x24beb40?, 0xc072620540?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog/processor.go:67 +0x25
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*TableEntry).RecurLoop(0xc02fb03c08?, {0x2dbd640, 0xc07248c1e0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog/table.go:354 +0x1f0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*DBEntry).RecurLoop(0xc000a18c68?, {0x2dbd640, 0xc07248c1e0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog/database.go:497 +0xfa
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).RecurLoop(0x38a4e82000000001?, {0x2dbd640, 0xc07248c1e0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog/catalog.go:1092 +0xfa
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.IncrementalCheckpointDataFactory.func1(0x38a4e82000000001?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/utils.go:128 +0xa7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).doIncrementalCheckpoint(0xc0007eb800, 0xc06fa8e000)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:456 +0xb5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).onIncrementalCheckpointEntries(0xc0007eb800, {0x4a4b60?, 0xc003860890?, 0xc00059eed0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:363 +0x8e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:81 +0x1f1
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:60 +0xea

the cn and dd log log:
[tpcc_duplicated.tar.gz](https://github.com/matrixorigin/matrixone/files/11360530/tpcc_duplicated.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo cluster on eks with 2cn
2. run a tester pod in the same ns
3. git clone https://github.com/matrixorigin/mo-tpcc.git in tester
4. git clone https://github.com/matrixorigin/mo-load-data.git in tester
3. cd mo-load-data, ./load.sh -h xxxx -c cases/00_from_s3/tpcc_1 -m -r -g
4. cd mo-tpcc, ./runBenchmark.sh props.mo
```

**Comment by jiangxinmeng1** [comment]
d15e37b556e能复现
15128有重复
 
![image](https://user-images.githubusercontent.com/51114574/236164612-c6df0afe-8978-43e0-a179-4b9c58e4fbcf.png)

dn之前已经收到过15128了，在mo-load-data, ./load.sh跑完，跑mo-tpcc, ./runBenchmark.sh之前
 
![image](https://user-images.githubusercontent.com/51114574/236164657-83030a85-a38c-4071-90d4-da6aa81a9c72.png)

在跑mo-tpcc, ./runBenchmark.sh的时候又收到了一次
 
![image](https://user-images.githubusercontent.com/51114574/236164724-453310a1-73ea-4a60-b58e-bf1955ad2677.png)

加日志打印了每次拿到的offset
 
![image](https://user-images.githubusercontent.com/51114574/236164777-5174a220-2eae-4dc7-a12e-65429ba8ca46.png)

好像offset有问题，load完30000行，但是offset从15127开始了，导致重新插入了15128
 
![image](https://user-images.githubusercontent.com/51114574/236164837-f9d5a1d8-ddc5-4516-9858-cebfdece7f3c.png)

**Comment by zhangxu19830126** [comment]
继续修复bvt

**Comment by zhangxu19830126** [comment]
@aressu1985 test

**Comment by aressu1985** [comment]
this pr has been reverted, can not test now

**Comment by aressu1985** [comment]
testing

**Comment by zhangxu19830126** [comment]
自增列重写的 pr，在合并在远宁的分支。等远宁的分支合并后，测试

**Comment by aressu1985** [comment]
After decision, we accept this in mo 0.8

**Comment by aressu1985** [comment]
tracking by another issue
