### ISSUE TITLE
[Bug]: instance crashed when using DBeaver

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#9240]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

 connectionId 605|192.168.32.1:51286|{account sys:root:moadmin -- 0:0:0}|c7722495-ea46-11ed-911d-000c29c1acc5
2023/05/04 02:43:46.365504 -0400 INFO frontend/util.go:415 time of Exec.Run : 136.303µs connectionId 605|192.168.32.1:51286|{account sys:root:moadmin -- 0:0:0}|c7722495-ea46-11ed-911d-000c29c1acc5
2023/05/04 02:43:46.365640 -0400 INFO frontend/util.go:400 query trace status {"connection_id": 605, "statement": "SELECT @@session.transaction_read_only", "status": "success", "span": {"trace_id": "04deee9b-ea47-11ed-911d-000c29c1acc5", "kind": "statement"}, "session_info": "connectionId 605|192.168.32.1:51286|{account sys:root:moadmin -- 0:0:0}|c7722495-ea46-11ed-911d-000c29c1acc5"}
2023/05/04 02:43:46.366255 -0400 INFO frontend/util.go:400 query trace {"connection_id": 605, "query": "/* ApplicationName=DBeaver 23.0.2 - Metadata */ ALTER TABLE tpch.lineitem ADD L_LINENUMBER BIGINT NOT NULL", "session_info": "connectionId 605|192.168.32.1:51286|{account sys:root:moadmin -- 0:0:0}|c7722495-ea46-11ed-911d-000c29c1acc5"}
2023/05/04 02:43:46.366459 -0400 INFO frontend/session.go:437 session uuid: c7722495-ea46-11ed-911d-000c29c1acc5 -> background session uuid: 04df2797-ea47-11ed-911d-000c29c1acc5
2023/05/04 02:43:46.368846 -0400 INFO frontend/util.go:400 query trace status {"connection_id": 4294967295, "statement": "begin", "status": "success", "span": {"trace_id": "04df2ab8-ea47-11ed-911d-000c29c1acc5", "kind": "statement"}, "session_info": ""}
2023/05/04 02:43:46.369944 -0400 INFO compile/compile.go:2039 cn generateNodes, tbl 272400 ranges is 2
2023/05/04 02:43:46.370049 -0400 INFO compile/compile.go:2039 cn generateNodes, tbl 1 ranges is 1
2023/05/04 02:43:46.370141 -0400 INFO frontend/util.go:415 time of Exec.Build : 1.09019ms 
2023/05/04 02:43:46.370567 -0400 INFO frontend/util.go:415 time of Exec.Run : 360.072µs 
2023/05/04 02:43:46.370670 -0400 INFO frontend/util.go:400 query trace status {"connection_id": 4294967295, "statement": "select rp.privilege_id,rp.with_grant_option\n\t\t\t\tfrom mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n\t\t\t\twhere d.dat_id = rp.obj_id\n\t\t\t\t\tand rp.obj_type = \"database\"\n\t\t\t\t\tand rp.role_id = 0\n\t\t\t\t\tand rp.privilege_id = 26\n\t\t\t\t\tand rp.privilege_level = \"d\"\n\t\t\t\t\tand d.datname = \"tpch\"", "status": "success", "span": {"trace_id": "04df8b9b-ea47-11ed-911d-000c29c1acc5", "kind": "statement"}, "session_info": ""}
2023/05/04 02:43:46.371088 -0400 INFO compile/compile.go:2039 cn generateNodes, tbl 272400 ranges is 2
2023/05/04 02:43:46.371174 -0400 INFO frontend/util.go:415 time of Exec.Build : 345.193µs 
2023/05/04 02:43:46.371376 -0400 INFO frontend/util.go:415 time of Exec.Run : 148.407µs 
2023/05/04 02:43:46.371435 -0400 INFO frontend/util.go:400 query trace status {"connection_id": 4294967295, "statement": "select rp.privilege_id,rp.with_grant_option\n\t\t\t\tfrom mo_catalog.mo_role_privs rp\n\t\t\t\twhere rp.obj_id = 0\n\t\t\t\t\tand rp.obj_type = \"database\"\n\t\t\t\t\tand rp.role_id = 0\n\t\t\t\t\tand rp.privilege_id = 26\n\t\t\t\t\tand rp.privilege_level = \"*\"", "status": "success", "span": {"trace_id": "04dfd1ac-ea47-11ed-911d-000c29c1acc5", "kind": "statement"}, "session_info": ""}
2023/05/04 02:43:46.371505 -0400 INFO frontend/util.go:400 query trace status {"connection_id": 4294967295, "statement": "commit", "status": "success", "span": {"trace_id": "04dfebb9-ea47-11ed-911d-000c29c1acc5", "kind": "statement"}, "session_info": ""}
2023/05/04 02:43:46.372637 -0400 INFO frontend/util.go:415 time of Exec.Build : 1.111176ms connectionId 605|192.168.32.1:51286|{account sys:root:moadmin -- 0:0:0}|c7722495-ea46-11ed-911d-000c29c1acc5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1fb01c8]

goroutine 6222 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).AlterTable(0xc0080f96c0, 0xc00aa10600)
	/data/matrixone/pkg/sql/compile/ddl.go:211 +0x668
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc00aa10600, 0xc0080f96c0)
	/data/matrixone/pkg/sql/compile/compile.go:211 +0x8a5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run.func1(0xc00aa10300?)
	/data/matrixone/pkg/sql/compile/compile.go:259 +0x35
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/data/matrixone/pkg/sql/compile/compile.go:258 +0x69
```

### Actual Behavior

When using DBeaver to migrate data from Oracle to MO, instance crashed with the given error log

**Comment by daviszhen** [comment]
alter table 好像还未实现完成。
