### ISSUE TITLE
[Bug]: `inconsistent mutex state` panic when load ssb-10g data.

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#9509]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- 
main branch f9088ea25dc066aeaa19b0aa5531c351e47f5b3d

- Hardware parameters:
I use my own machine (MacBook m1), and can repro 100%.
I'm not sure if x86 can repro it 100%.

- OS type:
- 
- Others:
```

### Actual Behavior

panic stack:

```
fatal error: sync: Unlock of unlocked RWMutex
fatal error: sync: inconsistent mutex state
fatal error: sync: unlock of unlocked mutex

goroutine 4287 [running]:
sync.fatal({0x1028847c0?, 0x0?})
 /usr/local/go/src/runtime/panic.go:1031 +0x20
sync.(*RWMutex).Unlock(0x14004c267e0)
 /usr/local/go/src/sync/rwmutex.go:209 +0x78
github.com/matrixorigin/matrixone/pkg/incrservice.(*columnCache).applyAutoValues(0x14004c267e0, {0x10325cf18, 0x14004e7bb30}, 0x42844, 0x1fd2, 0x0, 0x14005cf1a00, 0x14005cf19c0)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/incrservice/column_cache.go:250 +0xe8
github.com/matrixorigin/matrixone/pkg/incrservice.insertAutoValues[...]({0x10325cf18, 0x14004e7bb30}, 0x42844, 0x140036246e0, 0x1fd2, 0xffffffffffffffff, 0x14004c267e0, 0x14005cf1b00)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/incrservice/column_cache.go:460 +0x2f0
github.com/matrixorigin/matrixone/pkg/incrservice.(*columnCache).insertAutoValues(0x0?, {0x10325cf18?, 0x14004e7bb30?}, 0x1fd1?, 0x1c00?, 0x42844?)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/incrservice/column_cache.go:189 +0x234
github.com/matrixorigin/matrixone/pkg/incrservice.(*tableCache).insertAutoValues(0x140047e68c0, {0x10325cf18, 0x14004e7bb30}, 0x8?, 0x14005ffd880)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/incrservice/table_cache.go:75 +0xe8
github.com/matrixorigin/matrixone/pkg/incrservice.(*service).InsertValues(0x14005ffd880?, {0x10325cf18, 0x14004e7bb30}, 0x1400561cd80?, 0x1045ecf58?)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/incrservice/service.go:175 +0x64
github.com/matrixorigin/matrixone/pkg/sql/colexec/preinsert.genAutoIncrCol(0x14003faaa00?, 0x14003faaa00, 0x140068f5710?)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/colexec/preinsert/preinsert.go:86 +0x48
github.com/matrixorigin/matrixone/pkg/sql/colexec/preinsert.Call(0x2?, 0x14003faaa00, {0x102e297c0?, 0x14008959160}, 0xa0?, 0xc5?)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/colexec/preinsert/preinsert.go:59 +0x130
github.com/matrixorigin/matrixone/pkg/vm.Run({0x14000882780?, 0x6, 0x140045cfe98?}, 0x14003faaa00)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61 +0xf8
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun(0x14005cf1f30, 0x14003a25000, 0x14003faaa00)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:123 +0x14c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x1400bd70820, 0x1400b596000?)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:71 +0xe8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x140048b9860?)
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:93 +0x28
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
 /Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:93 +0x19c
```

### Expected Behavior

no error happens and load succeed.

### Steps to Reproduce

```Markdown
1. use mo-ssb to generate ssb-10g data
`./run.sh -g -s 10`

2. create table and load data
`./run.sh -c -s 10`
`./run.sh -l -s 10`
```

**Comment by m-schen** [comment]
可以作为一个查increse cache bug的线索。

**Comment by m-schen** [comment]
我重新生成了一份数据后就不会panic了。不过这个地方应该是有什么可能导致重复解锁的bug存在的。

**Comment by zhangxu19830126** [comment]
fixed in yuanning's plan refactor branch
