### ISSUE TITLE
[Bug]: Proxy crashes due to error "panic: impossible"

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9786]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):701b6f16
- Hardware parameters:
- OS type:
- Others:

root@HOST-10-206-134-17:~/mo# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@HOST-10-206-134-17:~/mo# uname -a
Linux HOST-10-206-134-17 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
```

### Actual Behavior

1. create an mo cluster via `kubectl apply -f mo.yaml`
2. all other comopnents are running normally, expect for proxy, which crashes all the time due to error 
```bash
root@HOST-10-206-134-17:~/mo# k logs -nmo-hn mo-proxy-h4zkx
/mo-service -cfg /tmp/tmp.zY4X3a0oVF 
{"level":"INFO","time":"2023/06/01 04:26:52.576084 +0000","caller":"logutil/internal.go:37","msg":"MO logger init, level=, log file="}
panic: impossible

goroutine 1 [running]:
main.(*Config).mustGetServiceUUID(0xc0005e5400)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/config.go:364 +0xa5
main.newRuntime(0xc000131d50?, 0x55c58a?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/setup.go:83 +0x97
main.setupProcessLevelRuntime.func1()
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/setup.go:52 +0x52
sync.(*Once).doSlow(0x3?, 0x4?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
main.setupProcessLevelRuntime(0xc0005e5400?, 0xc000bff500?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/setup.go:50 +0x65
main.startService({0x2cd73c8, 0xc00011a000}, 0x2758880?, 0xc0005e5400?, 0x23bd760?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:138 +0x7d
main.main()
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:107 +0x310
```
3. mo.yaml is as below, and the only configuration for proxy is to set replicas to 2
```bash
root@HOST-10-206-134-17:~/mo# cat ./mo-701b6f16.yaml 
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
  namespace: mo-hn
spec:
  proxy:
    replicas: 2
  cnGroups:
  - cnLabels:
    - key: operation
      values:
      - write1
      - write2
    config: |2

      [cn]
      turn-on-push-model = true

      [cn.Engine]
      type = "distributed-tae"

      [log]
      format = "json"
      level = "debug"
      max-size = 512
    name: tp
    nodeSelector:
      matrixone/tp: "true"
    replicas: 1
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 500Mi
    serviceType: ClusterIP
    sharedStorageCache: {}
  - cnLabels:
    - key: operation
      values:
      - read1
      - read2
    config: |2

      [cn]
      turn-on-push-model = true

      [cn.Engine]
      type = "distributed-tae"

      [log]
      format = "json"
      level = "debug"
      max-size = 512
    name: ap
    nodeSelector:
      matrixone/ap: "true"
    replicas: 1
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 500Mi
    serviceType: ClusterIP
    sharedStorageCache: {}
  dn:
    config: |2

      [dn]

      [dn.Ckp]
      flush-interval = "60s"
      global-interval = "100000s"
      incremental-interval = "60s"
      min-count = 100
      scan-interval = "5s"

      [dn.Txn]

      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"

      [log]
      format = "json"
      level = "error"
      max-size = 512
    nodeSelector:
      matrixone/dn: "true"
    replicas: 1
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 500Mi
    serviceArgs:
    - -debug-http=:6060
    sharedStorageCache:
      memoryCacheSize: 250Mi
  imagePullPolicy: IfNotPresent
  imageRepository: matrixorigin/matrixone
  logService:
    config: |2

      [log]
      format = "json"
      level = "error"
      max-size = 512
    initialConfig:
      dnShards: 1
      logShardReplicas: 3
      logShards: 1
    nodeSelector:
      matrixone/lg: "true"
    pvcRetentionPolicy: Retain
    replicas: 3
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 500Mi
    serviceArgs:
    - -debug-http=:6060
    sharedStorage:
      s3:
        endpoint: http://minio.minio-mo
        path: mo-test
        s3RetentionPolicy: Retain
        secretRef:
          name: minio
        type: minio
    storeFailureTimeout: 10m0s
    volume:
      size: 4608Mi

  version: nightly-701b6f16
```

### Expected Behavior

proxy should be running normally 

### Steps to Reproduce

```Markdown
See above
```

### Additional information

<img width="1264" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/05934f18-9660-4307-9d93-dea194c858de">

<img width="421" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/c687c463-b4f7-4af0-9dfa-ebd934ab499f">

**Comment by aronchanisme** [comment]
@volgariver6  As per discussed, this is a known issue which has been fixed on April 13th. Issue's gone after upgrading mo to `0cbe8014`. Thanks a lot for your help. Closing this thread now.
<img width="1120" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/ee47e4c6-600d-4405-84a7-d8d39930383b">
