### ISSUE TITLE
[Bug]: some connection lost during tpcc test on eks with muti-cn for query timeout 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9867]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): f1a218d
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

during tpcc test on eks with muti-cn, such as daily regresison or merger trigger regression, there are many error of conneciton lost.

<img width="1390" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/173660eb-3f8f-41a8-8cab-a5940bc21dee">

mo log is in s3 path: s3://mo-ares/etl/etl_20230605215403/

### Expected Behavior

each txn of tpcc should complete in 30s

**Comment by aressu1985** [comment]
pls assign to @LeftHandCold

**Comment by volgariver6** [comment]
@LeftHandCold please check this one.

**Comment by LeftHandCold** [comment]
<img width="1791" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/f2e41bdb-cfd4-4869-830d-9978ec57d8c4">
Some statements in the transaction took more than 30s to execute, so the error of connection lost will be reported.

**Comment by LeftHandCold** [comment]
The statement that exceeds 30s is because the reading of s3 takes too long, which may trigger the flow limit.

**Comment by LeftHandCold** [comment]
<img width="1915" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/9345e501-071e-47b6-9906-6090f24d4dfa">

**Comment by LeftHandCold** [comment]
<img width="1840" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/1576ffee-ec79-46fb-815a-27acfbdaeb73">

**Comment by reusee** [comment]
Excessive S3 requests may occur in the failing version (f1a218d), causing retries and long response times.
The S3 issue has been fixed in https://github.com/matrixorigin/matrixone/commit/b209696954ac22e9c447db8cc103b0285964a9ac and https://github.com/matrixorigin/matrixone/commit/3cdceab82e2d5e7b5aaa005ea8fe308fb2731a53

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
looking into the excessive s3 requests issue

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
still trying to reproduce
not reproduced on my local machine yet. A new machine with more memory is on the way. will try with higher TPCC terminals.

**Comment by reusee** [comment]
A possible fix committed https://github.com/matrixorigin/matrixone/commit/895f4c48fbd380c4defa07225b6f1b54abd94abe

**Comment by reusee** [comment]
Seems recent nightly regression on EKS / TPCC tests is done without error. Although failed on the last result check.
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5257773331/jobs/9503227747
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5251266797/jobs/9488127493

@aressu1985 Please confirm whether the hung issue due to S3 still occurs.

**Comment by reusee** [comment]
No hang was observed today.

**Comment by reusee** [comment]
Not reproducible on the main branch.
nightly regression on EKS done without error: 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5304546499/jobs/9601515659
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5298998397/jobs/9592254430

**Comment by reusee** [comment]
found this error when loading 100 warehouses
```
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 30,021 milliseconds ago.  The last packet sent successfully to
 the server was 30,021 milliseconds ago.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813)
        at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:765)
        at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 30,021 milliseconds ago.  The last packet sent successfully to
 the server was 30,021 milliseconds ago.
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.ja
va:67)                                                                                                                          at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:562)
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:732)
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:671)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:986)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:921)
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1154)
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:801)
        ... 3 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:273)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:299)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:556)
        ... 9 more
Worker 001: ERROR: Communications link failure
```

Seems different from the reported one.

**Comment by domingozhang** [comment]
@aptend could you please take a look at this issue

**Comment by reusee** [comment]
Got a repro
mo version: db6f124803a8ddf805cac037001f1779c3cb3c0e
mo-tpcc configs: 30 warehouses, 500 terminals, run mins 100
mo-tpcc output: ```

2023-06-20 12:14:02 ERROR jTPCCConnection:321 - The connection has been closed. Usage: 161MB / 1008MB
2023-06-20 12:14:02 ERROR jTPCCConnection:326 - The connection has not been valid.
2023-06-20 12:14:02 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][CONNECTION] The connection has not been valid, caused by:
 Communications link failure

The last packet successfully received from the server was 30,008 milliseconds ago.  The last packet sent successfully to the server was 30,008 milliseconds ago.
2023-06-20 12:14:02 ERROR jTPCCConnection:321 - The connection has been closed. Usage: 167MB / 1008MB
2023-06-20 12:14:02 ERROR jTPCCConnection:326 - The connection has not been valid.
2023-06-20 12:14:02 ERROR jTPCCConnection:321 - The connection has been closed.
2023-06-20 12:14:02 ERROR jTPCCConnection:326 - The connection has not been valid.
2023-06-20 12:14:02 ERROR jTPCCConnection:321 - The connection has been closed.
2023-06-20 12:14:02 ERROR jTPCCConnection:326 - The connection has not been valid.
2023-06-20 12:14:02 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][CONNECTION] The connection has not been valid, caused by:
 Communications link failure

The last packet successfully received from the server was 30,028 milliseconds ago.  The last packet sent successfully to the server was 30,028 milliseconds ago.
2023-06-20 12:14:02 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][CONNECTION] The connection has not been valid, caused by:
 Communications link failure

The last packet successfully received from the server was 30,025 milliseconds ago.  The last packet sent successfully to the server was 30,025 milliseconds ago.
Term-00, Running Average tpmTOTAL: 2207.63    Current tpmTOTAL: 25692    Memory Usage: 12023-06-20 12:14:02 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][CONNECTION] The connection has not been valid, caused by:
 Communications link failure

```

mo-service log:  
[log.txt](https://github.com/matrixorigin/matrixone/files/11795878/log.txt)

**Comment by reusee** [comment]
This line looks suspicious, just before the failure. line 16173 in https://github.com/matrixorigin/matrixone/files/11795878/log.txt
```
{"level":"ERROR","time":"2023/06/20 12:13:39.578121 +0800","name":"log-service","caller":"logservice/truncation.go:134","msg":"request export snapshot failed","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"timeout","errorVerbose":"timeout\n(1) attached stack trace\n  -- stack trace:\n  | github.com/lni/dragonboat/v4.init\n  | \t/home/reus/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/request.go:75\n  | runtime.doInit1\n  | \t/home/reus/gotip/src/runtime/proc.go:6739\n  | runtime.doInit\n  | \t/home/reus/gotip/src/runtime/proc.go:6706\n  | runtime.main\n  | \t/home/reus/gotip/src/runtime/proc.go:249\n  | runtime.goexit\n  | \t/home/reus/gotip/src/runtime/asm_amd64.s:1650\nWraps: (2) timeout\nError types: (1) *withstack.withStack (2) *errutil.leafError"}
```

**Comment by reusee** [comment]
Discussed with @volgariver6, and confirmed it's a log-service issue. 
When the system pressure is high, writing to log-service may timeout.

**Comment by reusee** [comment]
May be related: https://github.com/matrixorigin/matrixone/issues/9883
Also a log-service stability issue under high pressure.

**Comment by reusee** [comment]
repro step:

install mino if not installed

run run.sh to start mo (extract files from run.tgz below)

run mo-tpcc warehouse 10, terminals 100

[run.tgz](https://github.com/matrixorigin/matrixone/files/11812018/run.tgz)

**Comment by reusee** [comment]
Another repro
a same log-service error occurred.
but tpcc errors are different, I don't know what was happening.
logs:
[tpcc.log](https://github.com/matrixorigin/matrixone/files/11815573/tpcc.log)
[mo.log](https://github.com/matrixorigin/matrixone/files/11815575/mo.log)

wait for @volgariver6 to look into it.

**Comment by reusee** [comment]
not working today

**Comment by reusee** [comment]
not workday

**Comment by reusee** [comment]
same "request export snapshot failed" today

[tpcc.log](https://github.com/matrixorigin/matrixone/files/11858988/tpcc.log)

[mo.log](https://github.com/matrixorigin/matrixone/files/11858989/mo.log)

**Comment by reusee** [comment]
re-assigning to @volgariver6

**Comment by volgariver6** [comment]
在导数据的过程中，发生问题，监控了磁盘IO，MO 的read IO能达到2G/s 多，IO利用率也达到了100%：

iotop的输出：
```
19:01:37 Current DISK READ:       2.70 G/s | Current DISK WRITE:     981.75 K/s
```

iostat的输出：
```
06/25/23 19:01:36
Device            r/s     rMB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wMB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dMB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
sda           22733.00   1208.69     0.00   0.00    0.20    54.44   54.00      0.25     9.00  14.29    0.30     4.67    0.00      0.00     0.00   0.00    0.00     0.00    2.00    0.50    4.45 100.00
```

可以看出，在 `19:01:36` 的时候，磁盘IO util 达到了 100%，读数据每秒 2.7G

**Comment by volgariver6** [comment]
使用 bcc 工具 opensnoop 抓了一下，在 IO util 达到100%的时候，打开的文件都是 fileservice 的cache文件：

```
193.986962000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00005/full-data.mofscache
193.987913000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00003/full-data.mofscache
193.988531000 47707  mo-service         -1   2 mo-data/file-service-cache/c496cf22-1358-11ee-87ca-5254002a4bc3_00005/full-data.mofscache
193.989740000 47707  mo-service         -1   2 mo-data/file-service-cache/c496cf22-1358-11ee-87ca-5254002a4bc3_00003/full-data.mofscache
194.008080000 47707  mo-service         -1   2 mo-data/file-service-cache/c496cf22-1358-11ee-87ca-5254002a4bc3_00005/full-data.mofscache
194.009301000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00005/full-data.mofscache
194.866982000 47707  mo-service         -1   2 mo-data/file-service-cache/cb0cced6-1358-11ee-87ca-5254002a4bc3_00003/full-data.mofscache
195.061965000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00005/full-data.mofscache
195.062375000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00003/full-data.mofscache
195.081817000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00005/full-data.mofscache
195.084337000 47707  mo-service         -1   2 mo-data/file-service-cache/c496ce4e-1358-11ee-87ca-5254002a4bc3_00003/full-data.mofscache
```

**Comment by reusee** [comment]
A bpftrace script to monitor I/O
```
#!/usr/bin/env bpftrace

tracepoint:syscalls:sys_enter_open* 
/comm == "mo-service"/ 
{
  @open = count();
}

tracepoint:syscalls:sys_enter_close* 
/comm == "mo-service"/ 
{
  @close = count();
}

tracepoint:syscalls:sys_enter_unlink* 
/comm == "mo-service"/ 
{
  @unlink = count();
}

tracepoint:syscalls:sys_exit_read* 
/comm == "mo-service"/ 
{
  @read = sum(args->ret);
}

tracepoint:syscalls:sys_exit_write* 
/comm == "mo-service"/ 
{
  @write = sum(args->ret);
}

interval:s:1 {
  time("\n%H:%M:%S\n");

  print(@open);
  print(@close);
  print(@read);
  print(@write);
  print(@unlink);

  clear(@open);
  clear(@close);
  clear(@read);
  clear(@write);
  clear(@unlink);
}


```

**Comment by reusee** [comment]
An updated script to monitor I/O burst

```
#!/usr/bin/env bpftrace

kprobe:vfs_*
/comm == "mo-service"/ 
{
  @vfs[func] = count();
}

kprobe:vfs_read
/comm == "mo-service"/ 
{
  @readbytes += arg2;
}

kprobe:vfs_write
/comm == "mo-service"/ 
{
  @writebytes += arg2;
}

BEGIN {
  @print_threshold = 300 << 20
}

interval:s:1 {

  $rs = (int64)@readbytes;
  $ws = (int64)@writebytes;
  if ($rs > @print_threshold || $ws > @print_threshold) {
    time("\n%H:%M:%S\n");
    print(@vfs);
    printf("read bytes: %d\n", $rs);
    printf("write bytes: %d\n", $ws);
  }

  clear(@vfs);
  @readbytes = 0;
  @writebytes = 0;
}


```

**Comment by reusee** [comment]
A script for monitoring mo-service I/O burst 
https://github.com/reusee/bt-tools/blob/master/io-burst.bt

**Comment by volgariver6** [comment]
今天动哥那个环境没有复现，IO突增的原因还没找到。

**Comment by reusee** [comment]
found a strange I/O pattern when link failure occurred
[iolog.txt](https://github.com/matrixorigin/matrixone/files/11898232/iolog.txt)

At line 8153 of the above log file, time 00:40:33, there was a large number of small-sized reads, causing small-sized disk cache writes. Those under-100-sized reads/writes never occurred previously.
This was the I/O burst which caused the high latency of log service writes and lead to link failure.

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
same as https://github.com/matrixorigin/matrixone/issues/9883#issuecomment-1618225001

**Comment by volgariver6** [comment]
still in vestigation

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
最近standalone测试都没有复现，先降级s0，一边观察一边分析

**Comment by volgariver6** [comment]
set to holding because no progress recently.
